// C1 · O encanamento (U3 · Infraestrutura Digital), ensinado do zero.
// Fonte: fontes/exploracao/U3.txt. O texto extraído não traz o conteúdo dos cartões clicáveis (definições de banda e
// latência, camadas OSI e TCP/IP, listas de vantagens e riscos da nuvem). Onde isso acontece, o jogo ensina o conteúdo
// padrão da área e marca com o selo "além do material".
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, ficha, gen, mcq, multi, texto } from '../ajuda';
import { CARDS_EXP } from './cards';

export const C1: Regiao = {
  id: 'c1', mundo: 'exp', nome: 'O encanamento', unidades: 'U3', pronto: true,
  tese: 'O digital tem corpo físico, com limites de energia, distância e tempo.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'c1-conexao', titulo: 'Aula 1 · Banda não é velocidade', tipo: 'licao', min: 10, resumo: 'Do zero: o que é conectividade, os tipos de conexão e a diferença entre largura de banda e latência.',
      steps: [
        texto('**Por que começar por aqui.** A plataforma entrega a disciplina na ordem U1, U2, U3… Para entender, a ordem boa é outra: de baixo para cima. Primeiro o **encanamento** por onde os dados passam (esta região, a U3); depois os sistemas das empresas; depois a inteligência artificial; por fim, a sociedade em volta.\n\n**O problema.** A transmissão do culto ao vivo trava. O plano de internet da igreja é de "500 mega". Alguém diz: "impossível travar com 500 mega!". Será?\n\nPara responder, é preciso separar duas coisas que o dia a dia mistura numa palavra só, "velocidade".'),
        texto('**Conectividade** é a capacidade de dispositivos e sistemas trocarem dados entre si. O curso chama de "infraestrutura invisível": você só nota quando falha.\n\nImagine os dados como água num cano. O cano tem duas medidas independentes:\n\n**Largura de banda**: a **grossura** do cano. Quanto dado passa **por segundo**. Mede-se em **Mbps**, megabits por segundo. É o número do seu plano.\n\n**Latência**: o **comprimento** do cano. Quanto tempo um dado leva para **chegar** ao destino (e a resposta voltar). Mede-se em **ms**, milissegundos (milésimos de segundo).\n\nUm cano grosso e comprido despeja muita água, mas a primeira gota demora. Um cano fino e curto responde na hora, mas passa pouco.', 'alem', 'No texto extraído da U3, as definições de largura de banda e latência estão em cartões clicáveis cujo conteúdo não veio. A unidade só afirma que os dois são "determinantes para a qualidade do acesso". As definições acima são as usuais.'),
        ex(cheque('c1-k01', 'c1.conectividade', 'Numa videochamada, você fala e a pessoa responde dois segundos depois, mas a imagem está nítida. O problema é de:', ['latência: os dados demoram para chegar', 'largura de banda: passa pouco dado', 'nenhum dos dois'], 0, 'Imagem nítida quer dizer que passa dado suficiente (banda ok). O atraso na resposta é latência.')),
        { t: 'toy', toy: 'cano', modo: 'livre', intro: 'Mexa na banda (a grossura) e na latência (o comprimento) e veja, embaixo, quais usos funcionam. Use os botões "E se…?". Por enquanto ignore a "janela TCP"; ela entra daqui a pouco.' },
        texto('**Cada uso sofre com uma coisa diferente.**\n\n- **Download, streaming de filme**: sofrem com pouca **banda**. Um atraso de um segundo no começo ninguém nota.\n- **Videochamada, jogo online, cirurgia remota**: sofrem com **latência**. Usam pouca banda, mas não toleram atraso.\n\nPor isso a transmissão do culto pode travar com 500 mega: se o caminho até o servidor é longo ou congestionado, a banda sobra e o tempo de resposta estraga tudo.\n\n**Uma pegadinha de unidade.** Banda é em mega**bits** (Mb); arquivo é em mega**bytes** (MB). **1 byte = 8 bits.** Um plano de 100 Mbps baixa 12,5 MB por segundo, não 100.'),
        gen('c1.vazao', 2),
        texto('**Os três tipos de conexão (é do curso).**\n\n**Cabeada**: usa meio físico, cabo de cobre ou **fibra óptica**. A fibra leva os dados como luz; o curso destaca: "altas velocidades, baixa latência e maior estabilidade".\n\n**Sem fio (Wi-Fi)**: usa ondas de rádio entre o aparelho e um ponto de acesso. Dá mobilidade dentro de um espaço. A qualidade cai com **interferência, distância e número de usuários** ao mesmo tempo.\n\n**Móvel (4G, 5G)**: usa a rede das operadoras de celular. Leva a internet para a rua.\n\nNenhuma é "a melhor": cada uma troca estabilidade por mobilidade.\n\nA **qualidade do acesso**, diz o curso, é a combinação de quatro coisas: largura de banda, latência, **estabilidade** da conexão e **confiabilidade** da infraestrutura.'),
        ex(cheque('c1-k02', 'c1.conectividade', 'Segundo o curso, o que pode piorar a qualidade de uma conexão Wi-Fi?', ['Interferências, distância e número de usuários conectados ao mesmo tempo', 'O uso de fibra óptica no prédio', 'A cor do roteador'], 0, 'É a frase da unidade sobre conexões sem fio.')),
        texto('**Por que isso é assunto de negócio, e não só de técnico.** O curso insiste num ponto que vai aparecer em toda prova desta disciplina: **tecnologia é meio, não fim**.\n\nCitando Rogers (2017): "as tecnologias digitais transformam a forma como as empresas criam valor, conectando clientes, dados e operações em redes cada vez mais integradas".\n\nE a unidade conclui: investir em qualidade de acesso "não é apenas uma decisão técnica, mas uma estratégia essencial". Sem conectividade boa, a transformação digital "torna-se limitada, aprofundando desigualdades".\n\n**Guarde o padrão**: nas questões, a alternativa que trata a tecnologia como **estratégia** (ligada a pessoas, decisão, valor) costuma ganhar da que a trata como aparelho.'),
        ex(mcq('c1-q4', 'c1.conectividade', 'U3 · Avaliando · Quiz 04', 'Questão do curso. A relação entre infraestrutura digital e conectividade pode ser observada quando:', ['Sistemas dependem de redes estáveis para funcionar adequadamente', 'A automação ocorre sem necessidade de troca de dados', 'A segurança da informação é ignorada', 'Os dispositivos funcionam sempre isolados uns dos outros'], 0, 'Sistemas precisam de rede estável. Na plataforma há também a alternativa "Dispositivos digitais acessam serviços em nuvem", que é igualmente verdadeira.', { selo: 'confira', seloNota: 'Na plataforma, as alternativas A ("Sistemas dependem de redes estáveis") e C ("Dispositivos digitais acessam serviços em nuvem") são as duas corretas pelo conteúdo, e a questão aparece com marcação de escolha única. Aqui troquei a C por uma alternativa errada para a questão ter uma só resposta. Confira na plataforma se ela aceita mais de uma.' })),
        ficha({
          titulo: 'Conectividade: a ficha',
          porque: 'Tudo que é digital depende de dados chegando de um lugar a outro. Se o cano é ruim, o serviço mais sofisticado do mundo não funciona.',
          ideia: 'Banda é quanto passa por segundo (grossura). Latência é quanto demora para chegar (comprimento). São independentes.',
          regra: '$$1 \\text{ byte} = 8 \\text{ bits} \\qquad \\text{tempo de download} = \\frac{\\text{tamanho em megabits}}{\\text{vazão em Mbps}}$$',
          exemplo: 'Arquivo de 100 MB num link de 40 Mbps: 800 megabits ÷ 40 = 20 s.',
          armadilha: 'Chamar banda de "velocidade". E confundir megabit (Mb) com megabyte (MB).',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'c1-redes', titulo: 'Aula 2 · Como os dados acham o caminho', tipo: 'licao', min: 11, resumo: 'Redes, LAN/MAN/WAN, modem, switch e roteador, protocolos e a ideia de camadas (OSI e TCP/IP).',
      steps: [
        texto('**O problema.** Você manda uma foto para um amigo em Portugal. Ela sai do seu celular, passa pelo Wi-Fi, pelo aparelho da operadora, por cabos sob o oceano, e aparece no celular dele em um segundo. Ninguém "ligou" os dois aparelhos diretamente. Como a foto achou o caminho?\n\n**Rede de computadores** é um conjunto de dispositivos interligados para **compartilhar dados e recursos**. Tem três ingredientes, e a atividade de completar lacunas do curso pede exatamente eles: **hardware** (os aparelhos e cabos), **software** e **protocolos** de comunicação (as regras).'),
        texto('**Tamanhos de rede.** A classificação é pela **abrangência geográfica**:\n\n- **LAN** (rede local): uma casa, um escritório, um prédio.\n- **MAN** (rede metropolitana): uma cidade. Os campi de uma universidade, as câmeras de uma prefeitura.\n- **WAN** (rede de longa distância): entre cidades, países, continentes. A internet é a maior WAN.\n\nO curso cita também **topologias**, que são o formato das ligações: em **estrela** (todos ligados a um ponto central) ou em **barramento** (todos pendurados num mesmo cabo).'),
        gen('c1.rede', 1),
        texto('**Os três aparelhos.** O curso destaca roteadores, switches e modems. Cada um resolve um problema diferente:\n\n- **Modem**: liga a sua rede à **operadora**. Converte o sinal que vem da rua (fibra, cabo) em sinal que a sua rede entende.\n- **Switch**: liga os dispositivos **dentro** da mesma rede local e entrega cada dado só para o destinatário certo.\n- **Roteador**: liga **redes diferentes** e decide por qual caminho o dado segue. É quem conecta a sua LAN à internet.\n\nNa sua casa, a caixinha da operadora costuma ser os três num aparelho só, mais o ponto de acesso Wi-Fi. Por isso os nomes se confundem.', 'alem', 'As funções de cada dispositivo estão num infográfico cujo texto não veio na extração. O curso só afirma que eles são "responsáveis pela interconexão e pelo controle do tráfego de dados".'),
        ex(cheque('c1-k03', 'c1.redes', 'Qual aparelho decide por qual caminho um dado segue entre redes diferentes?', ['Roteador', 'Switch', 'Modem'], 0, 'Roteador: liga redes e escolhe a rota. O switch só distribui dentro da rede local; o modem só fala com a operadora.')),
        texto('**Protocolos: as regras da conversa.** Para dois aparelhos de fabricantes diferentes se entenderem, precisam seguir as **mesmas regras**. Um conjunto de regras de comunicação é um **protocolo**.\n\nOs três nomes que o curso cobra:\n\n- **TCP/IP**: a base da internet. "Estrutura a comunicação entre dispositivos".\n- **HTTP**: o protocolo das páginas web.\n- **HTTPS**: o HTTP com **criptografia**. O cadeado do navegador. O S é de "seguro".\n\nO que o TCP/IP faz com a sua foto, nas palavras do curso: os dados são "**fragmentados, transmitidos, verificados e reconstruídos** corretamente no destino". A foto é picada em **pacotes**, cada pacote pode ir por um caminho, e no destino tudo é conferido e remontado. Se um pacote se perde, é pedido de novo.\n\nSem essa padronização, diz a unidade, a internet não operaria "de forma global e interoperável".'),
        texto('**Por que a janela limita a vazão.** Lembra da "janela TCP" do brinquedo? Agora dá para entender.\n\nComo o TCP **confere** se os dados chegaram, o emissor manda um tanto e **espera a confirmação** antes de mandar mais. Esse tanto é a **janela**.\n\nSe a janela é de 64 KiB e a confirmação leva 200 ms para voltar, a conta é:\n\n- bits por janela: $64 \\times 1024 \\times 8 = 524.288$ bits;\n- uma janela a cada 0,2 s: $524.288 \\div 0{,}2 \\approx 2{,}6$ milhões de bits por segundo.\n\n**2,6 Mbps**, mesmo que o link seja de 1000. O gargalo não é a grossura do cano: é o tempo de espera, isto é, a **latência**. É a prova, com número, de que banda e latência são coisas diferentes.', 'alem', 'O material não faz essa conta. Ela entra porque explica o porquê de "latência importa", que a unidade só afirma. Conferido por código.'),
        { t: 'toy', toy: 'cano', modo: 'desafio', intro: 'Três desafios. No segundo, confira a conta que acabou de ver.', desafios: ['cn-video', 'cn-janela', 'cn-download'] },
        texto('**Camadas: dividir para conquistar.** Fazer a foto atravessar o mundo envolve problemas muito diferentes: sinal elétrico no cabo, endereço do destino, conferência dos pacotes, formato da imagem. Para não virar bagunça, a comunicação é organizada em **camadas**: cada uma resolve um problema e conversa só com as vizinhas.\n\nHá dois **modelos de referência**:\n\n- **Modelo OSI**: 7 camadas. É o modelo teórico, usado para ensinar e para localizar problemas. De baixo para cima: física, enlace, rede, transporte, sessão, apresentação, aplicação.\n- **Modelo TCP/IP**: 4 camadas. É o que a internet usa na prática: acesso à rede, internet, transporte, aplicação.\n\nO que o curso cobra é o **para quê**: os modelos padronizam a comunicação e "permitem que diferentes tecnologias e fabricantes operem de forma **interoperável**"; a organização em camadas "facilita o desenvolvimento, a manutenção e a segurança".', 'alem', 'Os nomes das camadas estão em cartões clicáveis que não vieram na extração. O texto visível só dá a finalidade dos modelos.'),
        ex(mcq('c1-q1', 'c1.redes', 'U3 · Avaliando · Quizz 01', 'Qual elemento da infraestrutura digital é diretamente responsável por permitir a comunicação entre dispositivos e sistemas em uma rede?', ['Dispositivos de armazenamento', 'Conectividade e redes de computadores', 'Sistemas operacionais', 'Interfaces de usuário'], 1, 'Comunicação entre dispositivos é o papel da conectividade e das redes.')),
        ficha({
          titulo: 'Redes: a ficha',
          porque: 'Nenhum sistema funciona sozinho: ERP, nuvem, IA, tudo depende de dados circulando entre máquinas.',
          ideia: 'Rede = dispositivos interligados por hardware, software e protocolos. Os dados viajam em pacotes; cada camada cuida de um problema.',
          regra: '$$\\text{LAN} \\subset \\text{MAN} \\subset \\text{WAN} \\qquad \\text{OSI: 7 camadas} \\qquad \\text{TCP/IP: 4 camadas}$$',
          exemplo: 'Modem fala com a operadora; switch distribui na rede local; roteador liga redes e escolhe o caminho. HTTPS = HTTP com criptografia.',
          armadilha: 'Trocar switch por roteador. E achar que OSI e TCP/IP são protocolos: são modelos de referência.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'c1-nuvem', titulo: 'Aula 3 · A nuvem é o computador de outra pessoa', tipo: 'licao', min: 11, resumo: 'O que é computação em nuvem, IaaS, PaaS e SaaS pela divisão de responsabilidades, escalabilidade, vantagens e riscos.',
      steps: [
        texto('**O problema.** A igreja quer um sistema de cadastro de membros. Caminho antigo: comprar um servidor, pôr numa sala com ar-condicionado, instalar sistema, fazer backup, chamar técnico quando quebra. Caminho novo: "põe na nuvem".\n\nMas o que é a nuvem? Não é mágica nem é o céu: são **computadores de outra empresa**, em prédios enormes chamados **data centers**, que você usa **pela internet** e paga conforme usa.\n\nA definição que o curso adota: um modelo que possibilita o **acesso sob demanda** a **recursos computacionais** (servidores, armazenamento, redes, softwares) **pela internet**, sem instalação local nem gerenciamento direto da infraestrutura física. Os recursos são **compartilhados** e **escaláveis**, e você **paga apenas pelo que usa**.'),
        ex(mcq('c1-r-erl', 'c1.nuvem', 'U3 · Estudo guiado (Erl e Monroy)', 'Questão do curso. Qual alternativa melhor define a Computação em Nuvem?', [
          'Uso exclusivo de servidores locais para armazenamento e processamento de dados.',
          'Modelo que permite acesso sob demanda a recursos computacionais compartilhados, como servidores, armazenamento e aplicações.',
          'Tecnologia voltada apenas para grandes empresas, devido ao alto custo de implementação.',
          'Sistema que elimina completamente a necessidade de segurança da informação.',
        ], 1, 'Sob demanda, compartilhado, pela internet.', { heuristica: 'As três erradas têm absolutos: "exclusivo", "apenas", "elimina completamente". Nesta disciplina, absoluto quase sempre denuncia o distrator.' })),
        texto('**Quem cuida do quê.** Um sistema rodando é uma **pilha** de coisas, uma em cima da outra. De baixo para cima:\n\n1. o prédio e a rede do data center;\n2. os servidores e o armazenamento;\n3. a virtualização (o que permite fatiar uma máquina física em várias virtuais);\n4. o sistema operacional;\n5. o ambiente de execução;\n6. os dados;\n7. a aplicação.\n\nNo caminho antigo, a empresa cuida das sete. Na nuvem, o **provedor** assume uma parte, **de baixo para cima**. A pergunta "quantas camadas ele assume?" é o que diferencia os três modelos de serviço. Mexa na pilha antes de ver os nomes.'),
        { t: 'toy', toy: 'pilha', modo: 'livre', intro: 'Toque nas camadas para passá-las para o provedor ou devolvê-las para você. Tente deixar com o provedor só as três de baixo e depois vá subindo. Veja o nome que aparece.' },
        texto('**Os três modelos (é do curso).**\n\n**IaaS**, Infraestrutura como Serviço. O provedor entrega "infraestrutura básica": servidores virtuais, redes, armazenamento. Você fica com "maior controle sobre **sistemas operacionais e aplicações**"; o provedor é "responsável pela **infraestrutura física**". Para quem quer flexibilidade sem ter data center.\n\n**PaaS**, Plataforma como Serviço. O provedor entrega "plataformas prontas para o **desenvolvimento, teste e implantação** de aplicações": ele gerencia a infraestrutura **e os ambientes de execução**. O desenvolvedor só escreve o programa.\n\n**SaaS**, Software como Serviço. O provedor entrega "**softwares prontos para uso**", acessados pelo navegador ou aplicativo: e-mail, armazenamento de arquivos, sistemas de gestão, ferramentas colaborativas.\n\nUma comparação: **IaaS** é alugar a cozinha vazia; **PaaS** é alugar a cozinha montada e levar só a receita; **SaaS** é pedir a pizza.'),
        { t: 'toy', toy: 'pilha', modo: 'desafio', intro: 'Monte cada modelo a partir do zero.', desafios: ['pn-iaas', 'pn-paas', 'pn-saas'] },
        gen('c1.modelo', 2),
        texto('**Escalabilidade.** A definição do curso, que cai em prova: a capacidade de "**aumentar ou reduzir rapidamente** a capacidade de processamento e armazenamento **conforme a demanda**, sem a necessidade de grandes investimentos em infraestrutura física".\n\nPense numa loja na Black Friday: num dia, dez vezes mais visitas. Com servidor próprio, ou você compra máquina para o pico (e ela fica ociosa o resto do ano), ou o site cai. Na nuvem, você aumenta por um dia e paga por um dia.\n\n**Vantagens**: menor custo inicial, pagar pelo uso, escalabilidade, acesso de qualquer lugar, continuidade (backup e recuperação).\n\n**Riscos** (o curso manda olhar com atenção): **dependência do provedor** (difícil sair depois), **segurança e privacidade** dos dados em mãos de terceiros, **conformidade** com leis de proteção de dados, e dependência de **internet**. Por isso a unidade pede "análise de contratos, níveis de serviço e conformidade".', 'alem', 'As listas de vantagens e de riscos estão em cartões clicáveis que não vieram. Os itens acima juntam o que o texto visível menciona (custo, escalabilidade, dependência de provedores externos, contratos, níveis de serviço, conformidade) com o conteúdo usual do tema.'),
        ex(cheque('c1-k04', 'c1.nuvem', 'Uma empresa migrou tudo para um único provedor de nuvem e, dois anos depois, descobre que trocar de fornecedor custaria uma fortuna. Qual risco se concretizou?', ['Dependência do provedor', 'Falta de escalabilidade', 'Latência alta'], 0, 'É o risco de ficar preso a um fornecedor. Por isso o curso fala em analisar contratos e níveis de serviço antes.')),
        texto('**Fechando com o padrão da disciplina.** Segundo Morais (2020), citado na unidade: "a inovação digital permite às empresas ganharem eficiência, flexibilidade e competitividade, **desde que a tecnologia seja utilizada de forma estratégica**".\n\nRepare na condição: "desde que". A nuvem não resolve nada sozinha. No estudo de caso que fecha esta região (a Tecnovia), cada setor contratou nuvem por conta própria, sem estratégia, e o resultado foi **mais** custo e **mais** bagunça.'),
        ficha({
          titulo: 'Nuvem: a ficha',
          porque: 'Quase toda empresa hoje decide o que fica em casa e o que vai para a nuvem. A decisão é sobre quem assume qual responsabilidade.',
          ideia: 'Recursos computacionais de terceiros, sob demanda, pela internet, pagos pelo uso. Os modelos diferem em quantas camadas o provedor assume.',
          regra: '$$\\text{IaaS: infraestrutura} \\qquad \\text{PaaS: + plataforma} \\qquad \\text{SaaS: software pronto}$$',
          exemplo: 'Máquina virtual alugada: IaaS. Ambiente para subir o código: PaaS. E-mail no navegador: SaaS.',
          armadilha: 'Achar que na nuvem a segurança "é problema do provedor". Seus dados e seus acessos continuam sendo responsabilidade sua.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'c1-seguranca', titulo: 'Aula 4 · Aparelhos, segurança e o limite físico', tipo: 'licao', min: 10, resumo: 'Dispositivos e sistemas operacionais, a tríade da segurança e por que data centers esbarram em energia e calor.',
      steps: [
        texto('**A ponta visível.** Rede e nuvem são invisíveis. O que a gente vê são os **dispositivos**: o curso os chama de "camada visível e interativa da infraestrutura digital", os pontos de acesso a tudo.\n\nQuatro famílias:\n\n- **Computadores** (desktops, notebooks): mais poder de processamento e armazenamento; para programação, análise de dados, design.\n- **Smartphones** e **tablets**: mobilidade.\n- **IoT**, a **Internet das Coisas**: sensores, relógios, eletrodomésticos, máquinas de fábrica, todos ligados à internet, coletando e trocando dados em tempo real. Leva o digital "para além dos ambientes tradicionais": cidades, indústria, saúde.\n\nTodo dispositivo tem um **sistema operacional**: o programa que gerencia o hardware, controla os recursos e faz a ponte entre o usuário e a máquina. Em computadores: Windows, macOS, Linux. Em celulares: Android e iOS. Em IoT: sistemas "mais leves e especializados", voltados a economizar energia.'),
        ex(cheque('c1-k05', 'c1.dispositivos', 'Qual é a função do sistema operacional, segundo o curso?', ['Gerenciar o hardware, controlar os recursos e fazer a interface entre o usuário e o dispositivo', 'Fornecer o sinal de internet', 'Guardar os arquivos na nuvem'], 0, 'É a definição da unidade. Sinal de internet é com a rede; nuvem é serviço.')),
        texto('**Mais aparelhos, mais portas.** A integração entre dispositivos (começar no celular, continuar no notebook) é feita por nuvem, redes sem fio, **APIs** (as "tomadas" pelas quais um sistema conversa com outro) e login unificado.\n\nO preço disso, nas palavras do curso: a integração "**amplia a superfície de ataques** cibernéticos". Cada aparelho ligado é uma porta a mais para vigiar.\n\n**A tríade.** O objetivo da segurança da informação tem três partes, e é questão certa de prova:\n\n- **Confidencialidade**: só vê quem pode ver.\n- **Integridade**: ninguém altera sem autorização; o dado é confiável.\n- **Disponibilidade**: a informação está lá quando é preciso.'),
        gen('c1.triade', 1),
        ex(mcq('c1-q2', 'c1.seguranca', 'U3 · Avaliando · Quizz 02', 'A segurança da informação na infraestrutura digital tem como principal objetivo:', ['Aumentar a velocidade da conexão com a internet', 'Garantir a confidencialidade, integridade e disponibilidade das informações', 'Automatizar processos manuais', 'Reduzir o uso de dispositivos digitais'], 1, 'A tríade: confidencialidade, integridade e disponibilidade.')),
        texto('**As ferramentas.** O curso lista, em dois grupos:\n\n**Medidas**: **autenticação** de usuários (provar quem você é), **controle de acesso** (o que cada um pode fazer), **criptografia** (embaralhar o dado para que só o destinatário leia) e **monitoramento** do tráfego.\n\n**Equipamentos e práticas**: **firewall** (o porteiro: filtra o que entra e sai da rede), **sistemas de detecção de intrusões** e **políticas de segurança**.\n\nE o fator humano: "a conscientização dos usuários", com senhas fortes e sistemas atualizados. A maior parte dos incidentes começa numa pessoa, não numa máquina.\n\nAkabane (2018), citado na unidade: "a gestão estratégica das tecnologias cognitivas exige atenção especial à segurança da informação, pois **o valor dos dados depende diretamente de sua proteção e confiabilidade**". De novo o padrão: segurança "não é apenas uma questão técnica, mas também estratégica".'),
        texto('**O limite físico: energia e calor.** A unidade abre com uma notícia da Forbes: a inteligência artificial está pressionando os **data centers**.\n\nPor quê? A nuvem parece não ter peso, mas cada cálculo é feito por um chip, e chip gasta **eletricidade** e vira **calor**. Um data center é um galpão com dezenas de milhares de computadores ligados 24 horas. Dois limites aparecem:\n\n- **Energia**: a rede elétrica da região precisa aguentar. Treinar e rodar modelos de IA consome muito mais que servir páginas.\n- **Calor**: toda essa energia vira calor, que precisa ser retirado. O resfriamento gasta mais energia, e muitas vezes água.\n\nO curso resume como uma **tensão** entre o desenvolvimento tecnológico acelerado, "que exige cada vez mais energia e recursos físicos", e a capacidade das redes elétricas, dos sistemas de resfriamento e das regras, sem comprometer "a qualidade de vida das comunidades, a sustentabilidade ambiental e a segurança do fornecimento elétrico".\n\nÉ a tese desta região: **o digital tem corpo**.'),
        ex(cheque('c1-k06', 'c1.dispositivos', 'Segundo o disparador da U3, por que a expansão da IA é um desafio para a infraestrutura digital?', ['Porque aumenta a demanda por poder computacional, energia e resfriamento além do que os data centers tradicionais previam', 'Porque a IA dispensa o uso de data centers', 'Porque a IA reduz o consumo de energia das redes'], 0, 'Mais cálculo = mais energia e mais calor. Os desafios são técnicos, ambientais e sociais.')),
        texto('**As pessoas no meio disso.** A unidade fecha com Martha Gabriel (2021), numa frase que vale decorar para a A3:\n\n> "Não são as tecnologias que substituem os profissionais, mas os profissionais que sabem usar tecnologia substituem os que não sabem."\n\nO ponto do curso: dispositivos e sistemas "só geram valor quando utilizados de forma consciente e estratégica". O profissional precisa de habilidades **técnicas, cognitivas e comportamentais**, e de atualização contínua.'),
        ficha({
          titulo: 'Dispositivos, segurança e limites: a ficha',
          porque: 'Infraestrutura não é só cabo: é o aparelho na mão do usuário, a proteção do dado e a conta de luz do data center.',
          ideia: 'Dispositivos são a camada visível; o sistema operacional gerencia cada um. Segurança protege três coisas. E tudo isso consome energia e gera calor.',
          regra: '$$\\text{segurança} = \\text{confidencialidade} + \\text{integridade} + \\text{disponibilidade}$$',
          exemplo: 'Site fora do ar: disponibilidade. Dado adulterado: integridade. Senha vazada: confidencialidade.',
          armadilha: 'Tratar segurança como assunto só do técnico. O curso diz: é estratégica e depende do comportamento dos usuários.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB
    {
      id: 'c1-lab', titulo: 'Laboratório · Cano e pilha', tipo: 'lab', min: 7, resumo: 'Os dois brinquedos à vontade e um caso para decidir.',
      steps: [
        { t: 'toy', toy: 'cano', modo: 'livre', intro: 'Bancada livre. Um teste: deixe a latência em 600 ms (satélite) e veja quais usos sobrevivem mesmo com banda de 1000 Mbps.' },
        { t: 'toy', toy: 'pilha', modo: 'livre', intro: 'Use os botões para pular entre os modelos e leia a frase de cada um. Depois tente montar uma divisão "com buraco" e veja o aviso.' },
        gen('c1.modelo', 1),
        gen('c1.triade', 1),
        ex(mcq('c1-l1', 'c1.nuvem', undefined, 'A igreja quer um sistema de cadastro de membros e não tem ninguém de TI. Qual modelo faz mais sentido, e por quê?', ['SaaS: um software pronto, em que o provedor cuida de tudo e a igreja só usa', 'IaaS: a igreja aluga máquinas virtuais e instala e mantém tudo', 'Servidor próprio numa sala da igreja', 'PaaS: a igreja programa o próprio sistema na plataforma'], 0, 'Sem equipe técnica, quanto mais camadas com o provedor, melhor. O preço é menos controle e mais dependência, o que pede cuidado com contrato e com os dados dos membros (dados pessoais: assunto da última região).', { fixo: true })),
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'c1-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'A U3 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**Conectividade**: base "invisível" dos serviços digitais. Conexões **cabeadas** (cobre, fibra: alta velocidade, baixa latência, estabilidade), **sem fio** (Wi-Fi: mobilidade; sofre com interferência, distância e número de usuários) e **móveis** (4G, 5G). **Banda** = quanto passa por segundo; **latência** = quanto demora para chegar. Qualidade do acesso = banda + latência + estabilidade + confiabilidade.\n\n**Redes**: hardware, software e protocolos. **LAN, MAN, WAN** por abrangência. Topologias (estrela, barramento). **Modem, switch, roteador**. **TCP/IP** (base da internet), **HTTP** e **HTTPS** (seguro). Modelos de referência **OSI** (7 camadas) e **TCP/IP** (4): padronização e interoperabilidade.'),
        texto('**Nuvem**: acesso sob demanda a recursos compartilhados, pela internet, pagando pelo uso. **IaaS** (infraestrutura; você controla sistema operacional e aplicações), **PaaS** (plataforma pronta para desenvolver), **SaaS** (software pronto). **Escalabilidade**: aumentar ou reduzir conforme a demanda. Riscos: dependência do provedor, segurança, conformidade; analisar contratos e níveis de serviço.\n\n**Dispositivos**: computadores, smartphones, tablets, IoT; sistemas operacionais (Windows, macOS, Linux, Android, iOS). Integração amplia a superfície de ataque.\n\n**Segurança**: **confidencialidade, integridade, disponibilidade**. Autenticação, controle de acesso, criptografia, monitoramento, firewall, detecção de intrusão, políticas e conscientização.\n\n**Limite físico**: data centers, energia e calor, pressionados pela IA.\n\n**Autores**: Rogers (2017), Akabane (2018), Morais (2020), Gabriel (2021).'),
        ex(mcq('c1-q5', 'c1.redes', 'U3 · Avaliando · Quiz 05', 'Assinale a resposta correta sobre os elementos da infraestrutura digital:', ['Redes de computadores: permite a troca de dados entre sistemas e usuários', 'Segurança da informação: executa tarefas de forma automática com mínima intervenção humana', 'Automação: possibilita o acesso e a interação com tecnologias do cotidiano', 'Dispositivos digitais: protege dados contra acessos não autorizados e falhas'], 0, 'As outras três estão com as definições trocadas entre si: "executa tarefas de forma automática" é automação; "possibilita o acesso e a interação" é dispositivo; "protege dados" é segurança.')),
        { t: 'feynman', prompt: 'Explique para alguém da igreja, sem termos técnicos: por que a transmissão ao vivo pode travar mesmo com um plano de internet caro?' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'c1-questoes', titulo: 'Questões da U3', tipo: 'questoes', min: 8, resumo: 'As questões da plataforma que faltavam e algumas de fixação sobre o texto da unidade.',
      steps: [
        texto('A U3 tem só seis questões na plataforma; cinco delas já apareceram nas aulas. A primeira abaixo é a que faltava. As demais **não são da plataforma**: escrevi a partir do texto da unidade, no estilo das provas, para você treinar o padrão das alternativas.'),
        ex(multi('c1-q3', 'c1.dispositivos', 'U3 · Avaliando · Quiz 03', 'Quais alternativas representam componentes da infraestrutura digital que contribuem para a automação de processos no cotidiano? (Marque todas as corretas.)', ['Sensores e dispositivos IoT', 'Serviços de computação em nuvem', 'Cabos de energia elétrica', 'Softwares de controle e monitoramento', 'Protocolos de segurança da informação'], [0, 1, 3], 'Sensores coletam, a nuvem processa e os softwares de controle agem: esses três automatizam. Cabo de energia não é infraestrutura digital.', { selo: 'confira', seloNota: 'O gabarito oficial não está no material. "Protocolos de segurança" (alternativa E) protegem a automação, mas não a realizam; por isso deixei de fora. Confira na plataforma se ela conta a E como correta.' })),
        ex(mcq('c1-x1', 'c1.nuvem', undefined, 'O que diferencia IaaS, PaaS e SaaS, segundo o curso?', ['O nível de controle e de responsabilidade do usuário', 'O país em que fica o data center', 'A velocidade da conexão contratada', 'O tamanho da empresa que contrata'], 0, 'A unidade diz: os modelos "se diferenciam pelo nível de controle e responsabilidade do usuário".')),
        ex(mcq('c1-x2', 'c1.nuvem', undefined, 'Qual alternativa descreve corretamente a escalabilidade na computação em nuvem?', ['Permite aumentar ou reduzir rapidamente a capacidade de processamento e armazenamento conforme a demanda, sem grandes investimentos em infraestrutura física.', 'Garante que o sistema nunca fique fora do ar.', 'Elimina totalmente os custos de tecnologia da empresa.', 'Exige a compra antecipada de servidores para os momentos de pico.'], 0, 'É a frase da unidade.', { heuristica: '"Garante", "nunca", "elimina totalmente": absolutos. A correta é a mais longa e qualificada.' })),
        ex(mcq('c1-x3', 'c1.conectividade', undefined, 'Segundo Rogers (2017), citado na U3, a conectividade é:', ['Um fator estratégico que integra pessoas, dados e sistemas, e não apenas um recurso técnico', 'Um recurso exclusivamente técnico, de responsabilidade da equipe de TI', 'Dispensável para empresas com bons produtos', 'Importante apenas para empresas de tecnologia'], 0, 'O destaque da unidade: "a conectividade não é apenas um recurso técnico, mas um fator estratégico".', { heuristica: 'Tecnologia como meio (estratégia, pessoas, valor) vence tecnologia como fim. E "exclusivamente", "apenas" denunciam as erradas.' })),
        ex(mcq('c1-x4', 'c1.redes', undefined, 'Para que servem os modelos de referência OSI e TCP/IP?', ['Padronizar a comunicação em camadas, permitindo que tecnologias e fabricantes diferentes operem de forma interoperável', 'Aumentar a largura de banda da conexão', 'Substituir os roteadores e switches', 'Armazenar dados na nuvem'], 0, 'Padronização e interoperabilidade; a divisão em camadas facilita desenvolvimento, manutenção e segurança.')),
        ex(mcq('c1-x5', 'c1.seguranca', undefined, 'Qual conjunto reúne apenas medidas de segurança em redes citadas na U3?', ['Autenticação de usuários, controle de acesso, criptografia e monitoramento do tráfego', 'Fibra óptica, Wi-Fi e 5G', 'IaaS, PaaS e SaaS', 'LAN, MAN e WAN'], 0, 'As outras são tipos de conexão, modelos de nuvem e tipos de rede.')),
        ex(mcq('c1-x6', 'c1.dispositivos', undefined, 'O que são os dispositivos de Internet das Coisas (IoT), segundo o curso?', ['Sensores, atuadores, vestíveis e outros objetos físicos conectados à internet, que coletam e trocam dados em tempo real', 'Computadores de mesa com alto poder de processamento', 'Programas que gerenciam o hardware', 'Cabos que ligam os continentes'], 0, 'Objetos físicos ligados à internet. A IoT "amplia a infraestrutura digital para além dos ambientes tradicionais de computação".')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'c1-chefe', titulo: 'Chefão: o caso Tecnovia', tipo: 'chefe', min: 12, resumo: 'O estudo de caso da U3: uma empresa de logística com rede instável, aparelhos velhos e nuvem sem estratégia.',
      steps: [
        texto('**O caso (estudo de caso da U3).** A **Tecnovia Serviços Logísticos** é uma empresa de médio porte, de transporte e armazenagem, com filiais em três estados. Ela se digitalizou: ERP, aplicativo para motoristas, nuvem. E os problemas apareceram:\n\n1. **Rede instável nos horários de pico**, travando o acesso simultâneo aos sistemas.\n2. Matriz e filiais ligadas por **provedores diferentes**, com desempenho desigual e difícil integração.\n3. **Aparelhos heterogêneos e desatualizados**: incompatibilidade com softwares novos e risco de segurança.\n4. **Nuvem sem estratégia**: alguns setores contrataram nuvem pública por conta própria, outros mantêm servidores locais. Resultado: ambiente híbrido mal integrado, **mais custo, dados redundantes, falhas de backup**.\n\nA pergunta do curso: quais são os principais desafios e que medidas adotar?'),
        ex(mcq('c1-b1', 'c1.conectividade', 'U3 · Estudo de caso: Tecnovia', 'A rede trava justamente nos horários de pico, quando muita gente acessa ao mesmo tempo. Qual é o diagnóstico mais provável?', ['Falta de largura de banda (ou de capacidade da rede) para o número de acessos simultâneos', 'Latência alta causada pela distância até o satélite', 'Excesso de escalabilidade', 'Falta de criptografia'], 0, 'O problema aparece com o volume: é capacidade. Latência por distância apareceria o dia todo.', { fixo: true })),
        ex(mcq('c1-b2', 'c1.redes', 'U3 · Estudo de caso: Tecnovia', 'Matriz e filiais ficam em três estados. Que tipo de rede as interliga?', ['WAN', 'LAN', 'MAN', 'Nenhuma: cada filial tem sua própria internet'], 0, 'Entre estados: rede de longa distância. Dentro de cada prédio há uma LAN.', { fixo: true })),
        ex(mcq('c1-b3', 'c1.seguranca', 'U3 · Estudo de caso: Tecnovia', 'Os aparelhos desatualizados "aumentam os riscos de segurança". Um ataque que tira o ERP do ar no meio da operação fere principalmente qual pilar?', ['Disponibilidade', 'Confidencialidade', 'Integridade', 'Escalabilidade'], 0, 'O sistema ficou indisponível. (Escalabilidade nem é pilar de segurança.)', { fixo: true })),
        ex(mcq('c1-b4', 'c1.nuvem', 'U3 · Estudo de caso: Tecnovia', 'Cada setor contratou a sua nuvem sem falar com os outros. Que consequência o caso descreve?', ['Aumento de custos operacionais, redundância de dados e falhas nos processos de backup', 'Redução de custos, pois cada setor negocia o próprio contrato', 'Mais segurança, por não depender de um único provedor', 'Maior integração entre os setores'], 0, 'É a frase do caso. Nuvem sem estratégia vira silo na nuvem, que é o assunto da próxima região.', { fixo: true })),
        { t: 'toy', toy: 'pilha', modo: 'livre', intro: 'Pense na Tecnovia: uma empresa de logística, sem vocação para manter servidores. Monte a divisão de responsabilidades que você recomendaria para o ERP dela e leia as consequências.' },
        ex(mcq('c1-b5', 'c1.nuvem', undefined, 'Qual recomendação está mais alinhada com o que a unidade ensina?', [
          'Definir uma estratégia única de nuvem alinhada aos objetivos do negócio, padronizar conectividade e dispositivos, e adotar políticas de segurança e de backup.',
          'Comprar os aparelhos mais modernos do mercado para todos os funcionários.',
          'Deixar cada setor continuar escolhendo as próprias ferramentas, para ganhar agilidade.',
          'Voltar tudo para servidores locais, eliminando completamente os riscos da nuvem.',
        ], 0, 'A diretoria do caso quer "alinhar a tecnologia às demandas do negócio". Estratégia primeiro; aparelho depois.', { fixo: true, heuristica: 'A correta é a mais longa e fala de estratégia e negócio. As erradas são soluções só técnicas ou trazem "eliminando completamente".' })),
        {
          t: 'escrita', fonte: 'U3 · Estudo de caso (o curso pede de 1000 a 2000 caracteres)',
          prompt: 'É a atividade da unidade: quais são os principais desafios da infraestrutura digital enfrentados pela Tecnovia e que medidas podem ser adotadas para superá-los?',
          modelo: 'A Tecnovia enfrenta quatro desafios de infraestrutura digital, que têm a mesma raiz: a tecnologia foi adotada sem uma estratégia que a integrasse. O primeiro é de conectividade: a rede fica instável nos horários de pico, o que indica largura de banda e capacidade insuficientes para o acesso simultâneo. O segundo é de integração entre unidades: matriz e filiais dependem de provedores distintos, com desempenho desigual. O terceiro é o parque de dispositivos heterogêneo e desatualizado, que gera incompatibilidades e amplia a superfície de ataque. O quarto é o uso de computação em nuvem sem coordenação, com setores em nuvem pública e outros em servidores locais, o que resulta em custos maiores, dados redundantes e falhas de backup. Como medidas, a empresa deve dimensionar a rede para o pico e padronizar a conectividade entre as unidades com níveis de serviço contratados; padronizar e atualizar os dispositivos e seus sistemas operacionais; definir uma estratégia única de nuvem, escolhendo o modelo de serviço conforme a necessidade e analisando contratos e conformidade; e adotar políticas de segurança que garantam confidencialidade, integridade e disponibilidade, com controle de acesso, criptografia, backup e conscientização dos usuários. Como lembra Morais (2020), a tecnologia traz eficiência e competitividade desde que seja utilizada de forma estratégica: o que falta à Tecnovia não é tecnologia, é alinhamento entre ela e o negócio.',
          rubrica: ['Listei os quatro problemas do caso (rede, provedores, dispositivos, nuvem)', 'Dei o diagnóstico de cada um com o conceito certo (banda, integração, superfície de ataque, falta de estratégia)', 'Propus uma medida para cada problema', 'Citei a tríade da segurança', 'Liguei tudo à ideia de tecnologia como estratégia, não como fim', 'Usei um autor da unidade (Morais, Rogers, Akabane ou Gabriel)'],
        },
        { t: 'feynman', prompt: 'O que a Tecnovia tinha de sobra, e o que faltava? Responda em duas frases.' },
      ],
    },
  ],
  cards: [...CARDS_EXP.filter((c) => c.regiao === 'c1'), ...cards('exp', 'c1', [
    ['Megabit × megabyte', '1 byte = 8 bits. Banda é em megabits por segundo (Mbps); arquivo é em megabytes (MB). 100 Mbps baixam 12,5 MB por segundo.'],
    ['Os três tipos de conexão', 'Cabeada (cobre, fibra: rápida e estável), sem fio (Wi-Fi: mobilidade, sofre com interferência e distância) e móvel (4G, 5G).'],
    ['TCP/IP, HTTP e HTTPS', 'TCP/IP estrutura a comunicação na internet. HTTP transfere páginas web. HTTPS é o HTTP com criptografia.'],
    ['Para que servem os modelos OSI e TCP/IP?', 'Padronizar a comunicação em camadas, para que tecnologias e fabricantes diferentes sejam interoperáveis. OSI tem 7 camadas; TCP/IP, 4.'],
    ['Riscos da computação em nuvem', 'Dependência do provedor, segurança e privacidade dos dados, conformidade com leis. Analisar contratos e níveis de serviço.'],
    ['Por que a IA pressiona os data centers?', 'Exige muito mais poder computacional: mais energia elétrica e mais calor para resfriar. O digital tem limites físicos.'],
    ['Citação de Gabriel (2021) sobre profissionais', '"Não são as tecnologias que substituem os profissionais, mas os profissionais que sabem usar tecnologia substituem os que não sabem."'],
    ['Heurística de prova: os absolutos', 'Alternativa com "totalmente", "exclusivamente", "apenas", "elimina", "garante", "dispensa" tende a ser distrator.'],
  ], 7)],
};
