// C2 · O sistema nervoso da empresa (U4 · Sistemas de Informação Empresariais + U2 · Transformação Digital), do zero.
// Fontes: fontes/exploracao/U4.txt e U2.txt.
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, ficha, gen, mcq, texto } from '../ajuda';
import { CARDS_EXP } from './cards';

export const C2: Regiao = {
  id: 'c2', mundo: 'exp', nome: 'O sistema nervoso da empresa', unidades: 'U4 + U2', pronto: true,
  tese: 'O inimigo é o silo; digitalizar não é transformar.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'c2-silos', titulo: 'Aula 1 · O silo', tipo: 'licao', min: 10, resumo: 'Do zero: o que é um sistema de informação, o que é um silo e por que ele aparece mesmo quando todo mundo trabalha direito.',
      steps: [
        texto('**O problema (é o disparador da U4).** Duas empresas do mesmo ramo, as duas usando tecnologia.\n\nNa primeira, vendas tem uma planilha, o estoque tem outra e o financeiro tem um sisteminha próprio. O vendedor promete entrega para amanhã de um produto que acabou ontem. O financeiro cobra um valor diferente do que o vendedor combinou.\n\nNa segunda, os sistemas são integrados: uma venda aparece na hora no estoque e no financeiro.\n\n"Ambas utilizam tecnologia. No entanto, os resultados são significativamente distintos. O que explica essa diferença?"\n\nAntes da resposta, veja acontecer.'),
        { t: 'toy', toy: 'silos', modo: 'desafio', intro: 'Três setores, um produto. Cada caixa mostra o que AQUELE setor acha que é verdade. Faça os dois primeiros desafios.', desafios: ['si-diverge', 'si-atraso'] },
        texto('**O nome do problema: silo.** Um **silo informacional** (ou silo operacional) é uma barreira que **isola as informações** dentro de um departamento. Cada setor tem os seus dados, no seu sistema ou na sua planilha, e os outros não enxergam.\n\nO que você viu no brinquedo é o ponto principal: **ninguém errou**. O vendedor vendeu olhando o número que ele tinha. O número é que estava velho. Silo não é problema de gente descuidada; é problema de **estrutura**.\n\nPor que os silos aparecem? Porque cada setor **otimiza para si**: escolhe a ferramenta que resolve o problema **dele**, do jeito mais rápido. A planilha do estoque é ótima para o estoque. O custo aparece só quando a informação precisa **atravessar** de um setor para o outro.'),
        texto('**As consequências (lista do curso, cai em prova).** A falta de integração pode causar:\n\n- **retrabalho** (digitar a mesma coisa em dois lugares, repassar planilha);\n- **divergência de dados** (cada setor com um número);\n- **atrasos** nos processos;\n- **falhas na comunicação** entre setores;\n- **aumento de custos** operacionais;\n- **decisões baseadas em informações desatualizadas ou incompletas**.\n\nNo estudo de caso da unidade, isso aparece como: atrasos na entrega, erros no controle de estoque, divergência entre dados financeiros e comerciais.'),
        ex(mcq('c2-q5', 'c2.silos', 'U4 · Avaliando', 'Questão do curso. A falta de integração entre sistemas pode resultar em:', ['Maior alinhamento estratégico.', 'Informações consistentes e sincronizadas.', 'Retrabalho e decisões baseadas em dados desatualizados.', 'Automação eficiente dos processos.'], 2, 'Retrabalho e dado velho: os dois sintomas clássicos do silo.')),
        texto('**Sistema de informação.** O remédio para o silo é o **sistema de informação empresarial**: um conjunto organizado de pessoas, processos, dados e tecnologia que **coleta, processa, armazena e distribui** informação para apoiar o trabalho e as decisões.\n\nO curso chama esses sistemas de "**espinha dorsal** da gestão organizacional". Quando são **integrados**, os setores compartilham os mesmos dados e a empresa ganha uma **visão holística** (do todo).\n\nA frase-chave da unidade: com a integração, a informação passa a ser tratada como um **ativo organizacional**, isto é, um bem valioso, como máquinas e dinheiro.\n\nE o padrão de sempre: a integração "deixa de ser apenas um aspecto técnico e passa a assumir um **papel estratégico**".'),
        { t: 'toy', toy: 'silos', modo: 'desafio', intro: 'Agora ligue a integração e repita as operações.', desafios: ['si-integra'] },
        texto('**Por que integrar é difícil, se é tão bom?** Porque exige duas coisas que custam:\n\n- um **padrão comum**: todos precisam chamar a mesma coisa pelo mesmo nome e registrar do mesmo jeito (o "cliente" do financeiro tem de ser o mesmo "cliente" de vendas);\n- **mudar o jeito de trabalhar**: o curso avisa que implantar um sistema integrado "implica a revisão dos fluxos de trabalho e das rotinas" e exige "alinhamento entre **tecnologia, processos e pessoas**".\n\nPor isso tanta empresa convive com silos: derrubar um silo mexe com hábitos e com poder, não só com software.', 'alem', 'A explicação de por que os silos surgem (cada setor otimiza para si) e de por que integrar é custoso não está escrita assim no material; ele só descreve as consequências. A parte sobre tecnologia, processos e pessoas é citação da U4.'),
        ex(mcq('c2-q1', 'c2.silos', 'U4 · Integração e tomada de decisão · Quiz', 'A integração dos sistemas de informação contribui para a tomada de decisão organizacional porque:', ['Elimina completamente os riscos e incertezas do processo decisório.', 'Permite substituir gestores por sistemas automatizados.', 'Transforma dados integrados em informação estratégica e conhecimento organizacional.', 'Restringe o uso das informações apenas aos setores técnicos.'], 2, 'É a ideia de Akabane (2018) na unidade: integrar sistemas, dados e processos "transforma informações dispersas em conhecimento organizacional".', { heuristica: '"Elimina completamente", "substituir gestores", "apenas": absolutos. A correta trata a tecnologia como meio para decidir melhor.' })),
        ficha({
          titulo: 'Silo e integração: a ficha',
          porque: 'Quase todo problema "de tecnologia" numa empresa é, no fundo, um problema de informação que não atravessa de um setor para o outro.',
          ideia: 'Silo: cada setor com seus dados isolados. Integração: uma base compartilhada, em que cada fato é registrado uma vez e todos enxergam.',
          regra: '$$\\text{silo} \\Rightarrow \\text{retrabalho, divergência, atraso, custo, decisão com dado velho}$$',
          exemplo: 'O vendedor vende um produto que o estoque não tem mais: ele decidiu certo com a informação errada.',
          armadilha: 'Achar que silo é culpa de pessoas. É estrutura. E achar que integrar é só instalar software: mexe em processos e pessoas.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'c2-erpcrm', titulo: 'Aula 2 · ERP, CRM e o caminho do dado', tipo: 'licao', min: 11, resumo: 'Os dois grandes sistemas das empresas, as três etapas do fluxo de dados e onde os dados ficam guardados.',
      steps: [
        texto('**Dois sistemas, duas direções.** Para integrar a empresa, existem dois tipos de sistema, que olham para lados opostos.\n\n**ERP** (*Enterprise Resource Planning*, planejamento dos recursos da empresa). Olha para **dentro**. É uma plataforma integrada que centraliza os **processos internos**: **finanças, produção, logística, recursos humanos e compras**. Tudo numa **única base de dados**, o que elimina redundância e dá confiabilidade.\n\n**CRM** (*Customer Relationship Management*, gestão do relacionamento com o cliente). Olha para **fora**. Reúne o que se sabe sobre os clientes: **vendas, marketing, atendimento e suporte**. Serve para personalizar o atendimento e fidelizar.\n\nNa igreja: um "ERP" cuidaria de tesouraria, patrimônio e escalas; um "CRM" cuidaria do cadastro de membros e visitantes e do acompanhamento de cada um.'),
        gen('c2.erpcrm', 2),
        texto('**Juntos: visão sistêmica.** Separados, ERP e CRM seriam dois silos grandes. O ganho está em **ligar os dois**: o curso diz que, integrados, eles conectam "informações internas de operação com dados externos relacionados ao mercado e aos clientes", dando uma "visão abrangente do negócio".\n\nExemplo: o CRM registra que os clientes estão pedindo muito um produto; o ERP, ao ver isso, aumenta a compra de matéria-prima. Ou o contrário: o ERP sabe que o estoque acabou; o CRM impede o vendedor de prometer.'),
        ex(mcq('c2-q3', 'c2.erpcrm', 'U4 · Avaliando', 'Questão do curso. A principal vantagem da integração entre ERP e CRM é:', ['A substituição completa do trabalho humano.', 'A centralização e compartilhamento de dados entre setores.', 'A eliminação da necessidade de planejamento estratégico.', 'O aumento da burocracia interna.'], 1, 'Centralizar e compartilhar: o contrário do silo.', { heuristica: '"Substituição completa", "eliminação da necessidade": absolutos.' })),
        texto('**O caminho do dado: três etapas.** O curso descreve o **fluxo de dados** dentro da empresa como um percurso em três etapas:\n\n1. **Entrada**: o dado é gerado ou **coletado** (uma venda digitada, um sensor, um formulário).\n2. **Processamento**: o dado é organizado, calculado, cruzado com outros. É aqui que dado vira **informação**.\n3. **Armazenamento**: fica guardado em bancos de dados, para ser recuperado depois "de forma rápida, segura e confiável".\n\nO aviso da unidade: "falhas na coleta, no processamento ou no armazenamento impactam diretamente a qualidade da informação". É a velha regra: **entra lixo, sai lixo**. Um dado digitado errado na entrada contamina todas as decisões lá na frente.\n\nRepare nas duas palavras que voltaram da região anterior: **integridade** e **disponibilidade** dos dados são, diz o curso, "fatores críticos" aqui.'),
        ex(cheque('c2-k01', 'c2.fluxo', 'Um atendente digita o CPF de um cliente com um número trocado. Em qual etapa do fluxo de dados está a falha?', ['Entrada', 'Processamento', 'Armazenamento'], 0, 'O erro nasceu na coleta. O sistema vai processar e guardar direitinho um dado errado.')),
        texto('**Dado, informação, conhecimento.** A unidade pergunta: "qual a diferença entre organizar dados e transformá-los em informação estratégica?".\n\n- **Dado**: o registro cru. "37 unidades."\n- **Informação**: o dado com contexto. "O estoque do produto X caiu para 37 unidades, e vende 20 por dia."\n- **Conhecimento**: o que se faz com isso. "Precisamos comprar hoje, ou faltará depois de amanhã."\n\nDecidir com base nisso, em vez de no palpite, é o que o curso chama de decisão **baseada em dados** (*data-driven*). E quando os dados estão atualizados **em tempo real**, a decisão fica mais rápida.'),
        ex(mcq('c2-q4', 'c2.fluxo', 'U4 · Avaliando', 'Quando os dados são atualizados em tempo real, a organização tende a:', ['Tomar decisões mais rápidas e fundamentadas.', 'Ignorar relatórios gerenciais.', 'Trabalhar com informações duplicadas.', 'Reduzir a comunicação entre setores.'], 0, 'Dado atual = decisão mais rápida e com fundamento.')),
        texto('**Onde os dados moram.** O vídeo da unidade apresenta três tipos de "depósito":\n\n- **Data Warehouse** ("armazém de dados"): guarda dados **estruturados**, já limpos e organizados em tabelas, prontos para relatórios. É a biblioteca: tudo catalogado.\n- **Data Lake** ("lago de dados"): guarda dados **brutos**, de qualquer formato (textos, imagens, registros), para organizar depois. É o galpão: cabe tudo, mas achar dá trabalho.\n- **Data Lakehouse**: o **híbrido**, que tenta juntar a flexibilidade do lago com a organização do armazém.\n\nServem para análises históricas, relatórios gerenciais e apoio à decisão.', 'alem', 'O texto da U4 só cita os três nomes e remete a um vídeo. As definições acima são as usuais.'),
        ficha({
          titulo: 'ERP, CRM e fluxo de dados: a ficha',
          porque: 'São os sistemas que você vai encontrar em qualquer empresa, e o vocabulário de qualquer reunião sobre "integração".',
          ideia: 'ERP organiza a empresa por dentro; CRM organiza a relação com o cliente. Integrados, dão visão do todo. O dado entra, é processado e é armazenado.',
          regra: '$$\\text{entrada} \\to \\text{processamento} \\to \\text{armazenamento} \\qquad \\text{dado} \\to \\text{informação} \\to \\text{conhecimento}$$',
          exemplo: 'ERP: finanças, produção, logística, RH, compras. CRM: vendas, marketing, atendimento, suporte.',
          armadilha: 'Trocar os dois. Macete: o C de CRM é de Cliente.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'c2-transformacao', titulo: 'Aula 3 · Digitalizar não é transformar', tipo: 'licao', min: 11, resumo: 'A distinção mais cobrada da disciplina, os três pilares e o caso Empresa A × Empresa B.',
      steps: [
        texto('**O problema (é o disparador da U2).** Duas empresas do mesmo setor.\n\nA **Empresa A** comprou computadores modernos, implantou um ERP, escaneou os documentos e abriu perfil nas redes sociais. Mas as decisões continuam saindo "da experiência dos gestores", os processos seguem pouco integrados e os dados "raramente são analisados".\n\nA **Empresa B** nasceu digital: processos automatizados, sistemas integrados (ERP, CRM e análise), decisões por dados em tempo real, cliente no centro. E discute privacidade, impacto da automação e ética.\n\nAs duas usam tecnologia. Só uma é "transformada digitalmente". Qual, e por quê?'),
        ex(cheque('c2-k02', 'c2.transformacao', 'Qual das duas empresas passou por transformação digital?', ['A Empresa B: mudou o jeito de decidir e de funcionar, não só as ferramentas', 'A Empresa A: foi a que mais comprou tecnologia', 'As duas, pois ambas usam ERP'], 0, 'A Empresa A tem as ferramentas, mas funciona como antes. É o caso clássico de digitalização sem transformação.')),
        texto('**Os dois conceitos.**\n\n**Digitalização**: converter o **analógico em digital**. O papel vira PDF; a planilha de papel vira planilha no computador. O processo é o mesmo, só mudou o suporte.\n\n**Transformação digital**: um **processo estratégico** que usa tecnologias digitais para mudar a fundo o **modelo de negócio**, a **cultura organizacional**, os **processos** e a **forma de tomar decisões** e de **criar valor**. Vai "muito além da simples adoção de ferramentas".\n\nA relação entre os dois, na formulação da questão final da unidade: a digitalização é uma **etapa inicial** de modernização; a transformação digital envolve **mudanças estruturais**.\n\nUma comparação: escanear a partitura é digitalização. Compor de outro jeito porque agora dá para gravar, editar e ouvir o resultado na hora é transformação.'),
        gen('c2.digtrans', 2),
        texto('**Os três pilares (U2).**\n\n1. **Integração de tecnologias emergentes**: adoção "consciente e integrada" de nuvem, inteligência artificial, internet das coisas, big data, plataformas digitais.\n2. **Reengenharia de processos**: revisão **crítica** dos processos, para eliminar etapas redundantes, automatizar fluxos e redesenhar práticas.\n3. **Foco na experiência do cliente e cultura de inovação e agilidade**: o cliente no centro das decisões, usando dados e *feedback* para melhorar.\n\nRepare: só o primeiro pilar é "tecnologia". Os outros dois são **processo** e **cultura**. A Empresa A parou no primeiro, e ainda pela metade (adotou, mas não integrou).\n\nE o curso acrescenta: a transformação "não ocorre de forma pontual", é "um processo **contínuo** de aprendizagem e adaptação". A tecnologia é um **catalisador** de mudanças que envolvem "pessoas, cultura e modelos de gestão".'),
        ex(cheque('c2-k03', 'c2.transformacao', 'Qual dos três pilares fala de rever criticamente os processos, eliminando etapas redundantes?', ['Reengenharia de processos', 'Integração de tecnologias emergentes', 'Foco na experiência do cliente'], 0, 'Reengenharia = redesenhar o processo, não só informatizar o que já existia.')),
        texto('**Toda empresa que usa tecnologia é digital?** Não. A resposta do curso é uma lista do que diferencia a organização transformada da apenas digitalizada:\n\n- a **integração** dos sistemas;\n- o **uso estratégico dos dados**;\n- a **orientação ao cliente**;\n- a **mudança cultural**.\n\nE a transformação digital **não é só técnica**: envolve impactos **éticos, sociais e profissionais**, como proteção de dados, automação do trabalho, inclusão digital e novas competências. (Isso volta na última aula desta região.)'),
        ex(mcq('c2-q7', 'c2.transformacao', 'U2 · Avaliando · Questão 1', 'Assinale a alternativa que melhor representa a relação entre digitalização e transformação digital.', [
          'A digitalização e a transformação digital possuem o mesmo significado, pois ambas se referem à adoção de tecnologias digitais para melhorar a eficiência operacional das organizações.',
          'A transformação digital caracteriza-se pela incorporação pontual de tecnologias digitais, sem necessidade de alterações nos modelos de negócio, na cultura organizacional ou nos processos de decisão.',
          'A digitalização é uma etapa inicial de modernização tecnológica, enquanto a transformação digital envolve mudanças estruturais nos modelos de negócio, nos processos, na cultura organizacional e na forma de criação de valor, apoiadas pelo uso estratégico de tecnologias emergentes.',
          'A transformação digital ocorre de forma isolada, restrita às áreas de tecnologia da informação, sem impactos relevantes nas relações de trabalho, na ética ou na sociedade.',
        ], 2, 'Etapa inicial × mudança estrutural.', { selo: 'confira', seloNota: 'Na plataforma, a alternativa B aparece corrompida, com dois textos colados um por cima do outro ("A digitalização representa uma muA transformação digital caracteriza-se…"). Aqui usei a parte legível. A correta é a C, e ela está limpa.', heuristica: 'Alternativa corrompida: ignore o lixo e procure a cláusula limpa. E a correta é, de novo, a mais longa e qualificada.' })),
        ex(mcq('c2-q8', 'c2.transformacao', 'U2 · Avaliando · Questão 2', 'Qual é a principal diferença entre digitalização e transformação digital?', ['A digitalização elimina o uso de tecnologias digitais', 'A digitalização converte processos analógicos em digitais, enquanto a transformação digital muda a estratégia, os processos e o modelo de negócio', 'A transformação digital se limita ao uso de softwares.', 'Ambos os conceitos possuem o mesmo significado.'], 1, 'Converter × transformar.', { selo: 'confira', seloNota: 'Na plataforma, a alternativa correta aparece cortada no meio ("…enquanto a"). Completei com o sentido que a unidade ensina.' })),
        ficha({
          titulo: 'Digitalização × transformação digital: a ficha',
          porque: 'É a distinção que abre a A3 e que aparece em quase toda prova da disciplina.',
          ideia: 'Digitalizar troca o suporte (papel por tela). Transformar muda o modelo de negócio, os processos, a cultura e o jeito de decidir.',
          regra: '$$\\text{três pilares: tecnologias integradas} + \\text{reengenharia de processos} + \\text{cliente e cultura de inovação}$$',
          exemplo: 'Empresa A: tem ERP e decide "no olho" (digitalizada). Empresa B: decide por dados, cliente no centro, discute ética (transformada).',
          armadilha: 'Medir transformação pelo quanto se gastou em tecnologia. O que conta é o que mudou no funcionamento.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'c2-rogers', titulo: 'Aula 4 · Rogers, tecnologias emergentes e gente', tipo: 'licao', min: 11, resumo: 'Os cinco domínios de Rogers, as tecnologias que reestruturam setores, o low-code e as implicações éticas, sociais e profissionais.',
      steps: [
        texto('**O autor central: David Rogers.** O livro dele, *Transformação digital: repensando o seu negócio para a era digital* (2017), é a referência mais citada da disciplina. A tese cabe numa frase, e é a citação número um para a A3:\n\n> "A transformação digital não é sobre tecnologia, mas sobre estratégia."\n\nRogers organiza a transformação em **cinco domínios**, cinco áreas em que as regras do jogo mudaram:\n\n1. **Clientes**: deixaram de ser massa passiva e viraram redes que se influenciam.\n2. **Competição**: a disputa passa por plataformas; rival e parceiro se misturam.\n3. **Dados**: viram um ativo estratégico, gerado o tempo todo.\n4. **Inovação**: feita por experimentos rápidos e baratos.\n5. **Valor**: o que a empresa entrega precisa ser repensado continuamente.\n\nPara decorar: **C-C-D-I-V**: clientes, competição, dados, inovação, valor.', 'alem', 'A U2 lista os cinco domínios pelo nome e manda ler o capítulo 1 de Rogers. A descrição de uma linha de cada domínio vem do livro, não do texto da unidade.'),
        gen('c2.rogers', 1),
        ex(mcq('c2-q6', 'c2.rogers', 'U2 · Pilares e conceitos · Quiz', 'De acordo com os cinco domínios de Rogers (2017), uma organização pode ser considerada efetivamente transformada digitalmente quando:', [
          'Implanta tecnologias digitais para automatizar processos existentes, mantendo seu modelo de negócio tradicional.',
          'Digitaliza documentos e amplia sua presença em plataformas digitais.',
          'Utiliza tecnologias digitais para promover mudanças estratégicas em seus modelos de negócio, orientando decisões por dados e colocando o cliente no centro da estratégia.',
          'Adota sistemas corporativos avançados, independentemente de mudanças culturais e organizacionais.',
        ], 2, 'Mudança estratégica no modelo de negócio + dados + cliente no centro.', { selo: 'confira', seloNota: 'Na plataforma, a alternativa B vem corrompida: o texto da alternativa correta foi colado no meio dela ("Digitaliza doUtiliza tecnologias digitais…cumentos"). A alternativa C é a correta e está limpa. Aqui reconstruí a B como "Digitaliza documentos e amplia sua presença em plataformas digitais".' })),
        texto('**As tecnologias emergentes.** O curso lista as que estão reestruturando setores tradicionais (indústria, saúde, finanças, comércio):\n\n- **Inteligência artificial (IA)**: sistemas que aprendem com dados e analisam grandes volumes para apoiar decisões.\n- **Internet das Coisas (IoT)**: objetos físicos conectados à internet.\n- **Big data**: conjuntos de dados grandes e variados demais para as ferramentas comuns.\n- **Computação em nuvem**: a região anterior.\n- **Blockchain**: um registro compartilhado e encadeado, em que é muito difícil adulterar o que já foi gravado.\n\nQuando elas se juntam na fábrica, o nome é **Indústria 4.0**: máquinas com sensores (IoT) mandam dados para a nuvem, a IA analisa, e a produção se ajusta sozinha.\n\nO lado bom: eficiência, automação, personalização, novos modelos de negócio. O lado difícil: requalificação profissional, impacto no emprego, privacidade e segurança.'),
        ex(mcq('c2-q9', 'c2.tecnologias', 'U2 · Avaliando · Questão 4', 'A Internet das Coisas (IoT) se caracteriza principalmente por:', ['Substituir o trabalho humano', 'Conectar dispositivos físicos à internet', 'Criar ambientes virtuais imersivos', 'Eliminar a necessidade de dados'], 1, 'Objetos físicos conectados. "Ambientes virtuais imersivos" é realidade virtual.')),
        ex(mcq('c2-q10', 'c2.tecnologias', 'U2 · Avaliando · Questão 3', 'Qual tecnologia emergente permite a análise de grandes volumes de dados para apoiar decisões estratégicas?', ['Internet das Coisas', 'Inteligência Artificial', 'Realidade aumentada', 'Impressão 3D'], 1, 'Das quatro, é a IA que analisa. A IoT coleta os dados; não os analisa.', { selo: 'confira', seloNota: '"Grandes volumes de dados" é a definição de big data, que não está entre as alternativas. Entre as quatro oferecidas, a que analisa dados é a Inteligência Artificial. O gabarito oficial não está no material.' })),
        texto('**Low-code: automação para quem não programa.** Voltando à U4. Muita tarefa de escritório é repetitiva: copiar um dado de um sistema para outro, avisar alguém quando um pedido chega.\n\n**Automação de fluxo de trabalho** é fazer o sistema executar essas tarefas sozinho. E as ferramentas de **baixo código** (*low-code*) permitem montar essas automações **de forma visual**, arrastando blocos prontos, "sem a necessidade de programação complexa".\n\nExemplos do curso: envio automático de notificações, atualização de registros, consolidação de informações, acompanhamento de solicitações.\n\nO efeito: a tecnologia "deixa de ser restrita a especialistas em programação" e passa a apoiar diretamente as áreas administrativas. E libera as pessoas "para atividades estratégicas".'),
        ex(mcq('c2-q2', 'c2.lowcode', 'U4 · Avaliando', 'A automação por ferramentas low-code contribui principalmente para:', ['Aumentar a dependência exclusiva da equipe de TI.', 'Reduzir erros operacionais em tarefas repetitivas.', 'Substituir completamente os sistemas ERP.', 'Diminuir o volume de dados disponíveis.'], 1, 'Menos erro humano em tarefa repetitiva. O low-code REDUZ a dependência de TI, e complementa o ERP, não o substitui.')),
        texto('**As pessoas: ética, sociedade e profissão.** A U2 dedica um tópico inteiro a isso, e a A3 também.\n\n**Desafios éticos**: privacidade e proteção de dados pessoais, segurança da informação, **transparência algorítmica** e **vieses** em sistemas automatizados. O uso pouco transparente "pode gerar discriminações, violações de direitos, exclusão social e perda de confiança".\n\n**Desafios sociais**: desigualdade de acesso, **exclusão digital**, mudanças no mercado de trabalho.\n\n**Desafios profissionais**: habilidades multidisciplinares, pensamento crítico, adaptabilidade e **ética digital**.\n\nA frase do curso: a ética "não deve ser entendida como um elemento externo ou complementar à tecnologia, mas como **parte integrante**" de conceber, implementar e gerir as soluções.\n\nSobre emprego, a posição do material é sempre a mesma: a automação **redefine funções**; não elimina as pessoas. Martha Gabriel: a tecnologia redefine o trabalho "sem eliminar a centralidade do fator humano".'),
        ex(mcq('c2-q11', 'c2.etica', 'U2 · Avaliando · Questão 5', 'A automação de processos impacta o mercado de trabalho principalmente porque:', ['Elimina todas as profissões', 'Substitui apenas atividades criativas', 'Reduz tarefas repetitivas e redefine funções', 'Impede o surgimento de novas carreiras'], 2, 'Redefine, não elimina. É a tese que a A3 espera no fechamento.', { heuristica: '"Todas", "apenas", "impede": absolutos.' })),
        ex(mcq('c2-q12', 'c2.etica', 'U2 · Implicações éticas · Quiz', 'De acordo com Martha Gabriel (2021), uma atuação profissional adequada no contexto da transformação digital exige que o profissional:', ['Priorize exclusivamente o domínio de ferramentas tecnológicas emergentes.', 'Substitua o pensamento humano por decisões totalmente automatizadas.', 'Desenvolva competências técnicas e humanas, adotando uma postura ética, crítica e adaptável.', 'Evite o uso de tecnologias digitais para reduzir riscos éticos.'], 2, 'Técnica + humana + ética. Nem tecnologia sozinha, nem fuga da tecnologia.')),
        ficha({
          titulo: 'Rogers, tecnologias e gente: a ficha',
          porque: 'É o repertório de autores e conceitos que as questões e a A3 esperam ver citado.',
          ideia: 'Transformação digital é estratégia (Rogers). As tecnologias emergentes são o meio. Quem decide se dá certo são processos, cultura e pessoas.',
          regra: '$$\\text{Rogers: clientes, competição, dados, inovação, valor}$$',
          exemplo: 'IoT conecta objetos; IA analisa os dados; low-code automatiza tarefas repetitivas sem programador.',
          armadilha: 'Dizer que a automação "elimina" o trabalho humano. A posição do curso é: redefine funções.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB
    {
      id: 'c2-lab', titulo: 'Laboratório · Empresa com silos', tipo: 'lab', min: 7, resumo: 'O brinquedo à vontade e um diagnóstico para treinar o olho.',
      steps: [
        { t: 'toy', toy: 'silos', modo: 'livre', intro: 'Bancada livre. Um experimento: em modo silo, faça três vendas e um recebimento e use "Repassar planilha". Conte quantas operações depois os números voltam a divergir. Depois integre e repita.' },
        gen('c2.digtrans', 1),
        gen('c2.erpcrm', 1),
        ex(mcq('c2-l1', 'c2.transformacao', undefined, 'Uma clínica trocou as fichas de papel por um sistema, mas cada médico usa o sistema do seu jeito, ninguém analisa os dados e a recepção ainda liga para confirmar tudo. Diagnóstico?', ['Digitalização sem transformação: mudou o suporte, não os processos nem a forma de decidir', 'Transformação digital completa', 'Silo eliminado, pois há um sistema único', 'Falta de largura de banda'], 0, 'É a Empresa A. Ter o sistema não basta: faltam reengenharia de processos e uso dos dados.', { fixo: true })),
        ex(mcq('c2-l2', 'c2.silos', undefined, 'A mesma clínica tem um sistema para agendamento e outro, separado, para cobrança, e os dois não conversam. Que consequência é a mais provável?', ['Paciente atendido que não é cobrado, ou cobrado por consulta desmarcada: divergência entre os dois sistemas', 'Aumento da largura de banda', 'Melhora automática da experiência do paciente', 'Redução do retrabalho'], 0, 'Dois sistemas que não se falam são dois silos, mesmo sendo digitais.', { fixo: true })),
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'c2-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'A U4 e a U2 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**U4.** Sistemas de informação são a "espinha dorsal" da gestão. **Silo**: informação isolada por setor; causa retrabalho, divergência, atraso, falha de comunicação, custo e decisão com dado desatualizado. **Integração** trata a informação como **ativo** e é estratégica, não só técnica.\n\n**ERP** (para dentro: finanças, produção, logística, RH, compras; base única) e **CRM** (para fora: vendas, marketing, atendimento, suporte). Juntos: visão sistêmica.\n\n**Fluxo de dados**: entrada → processamento → armazenamento. Depósitos: Data Warehouse, Data Lake, Lakehouse.\n\n**Low-code**: automação visual de tarefas repetitivas, acessível a não programadores; reduz erros e libera pessoas para o estratégico.'),
        texto('**U2.** **Digitalização** (analógico → digital; etapa inicial) × **transformação digital** (mudança estrutural em modelo de negócio, processos, cultura, decisão e criação de valor).\n\n**Três pilares**: integração de tecnologias emergentes; reengenharia de processos; foco no cliente com cultura de inovação e agilidade.\n\n**Rogers (2017)**: cinco domínios (clientes, competição, dados, inovação, valor). "A transformação digital não é sobre tecnologia, mas sobre estratégia."\n\n**Tecnologias emergentes**: IA, IoT, big data, nuvem, blockchain; Indústria 4.0.\n\n**Empresa A × Empresa B**: usar tecnologia não é ser digital.\n\n**Implicações**: éticas (privacidade, transparência algorítmica, viés), sociais (exclusão digital, trabalho) e profissionais (competências técnicas e humanas, ética). A automação **redefine** funções.'),
        ex(mcq('c2-q13', 'c2.silos', 'U4 · Avaliando · Questão 1', 'Qual alternativa melhor explica como a integração de ERP e CRM e a automação low-code contribuem para a eficiência e a decisão baseada em dados?', [
          'A integração de sistemas concentra apenas informações financeiras, enquanto a automação substitui totalmente o trabalho humano nas organizações.',
          'Sistemas ERP e CRM operam de forma independente, sendo a automação utilizada apenas para acelerar tarefas técnicas de TI.',
          'A integração entre ERP e CRM possibilita a centralização e a confiabilidade dos dados, enquanto a automação de processos reduz atividades manuais, melhora o fluxo de informações e apoia decisões mais ágeis e baseadas em dados.',
          'A automação de processos elimina a necessidade de integração entre sistemas, pois cada setor passa a operar de forma autônoma.',
        ], 2, 'Integração dá confiabilidade; automação reduz o manual; os dois juntos aceleram a decisão.', { selo: 'confira', seloNota: 'Na plataforma, a alternativa D aparece com dois textos misturados ("A automação de Ferramentas low-code são restritas a desenvolvedores…processos elimina a necessidade de integração…"). Aqui usei uma das duas frases. A correta é a C, que está limpa.' })),
        { t: 'feynman', prompt: 'Sem olhar: explique a diferença entre digitalização e transformação digital com um exemplo da sua igreja ou do seu trabalho.' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'c2-questoes', titulo: 'Questões da U4 e da U2', tipo: 'questoes', min: 8, resumo: 'A questão da plataforma que faltava e outras de fixação, no estilo da prova.',
      steps: [
        texto('Quase todas as questões da plataforma destas duas unidades já apareceram dentro das aulas. A primeira abaixo é a que faltava. As outras **não são da plataforma**: escrevi a partir do texto das unidades para você treinar as heurísticas.\n\n**As quatro heurísticas da casa** (use depois de responder pelo conteúdo, para conferir):\n\n1. Alternativa com **absoluto** (totalmente, exclusivamente, apenas, elimina, substitui, garante) tende a ser distrator.\n2. A correta costuma ser a **mais longa e qualificada**.\n3. Tecnologia como **meio** (estratégia, cultura, pessoas, decisão) vence tecnologia como fim.\n4. Alternativa **corrompida**: ignore o lixo e leia a cláusula limpa.'),
        ex(mcq('c2-q14', 'c2.erpcrm', 'U4 · ERP e CRM · Quiz', 'Podemos considerar que a evolução dos sistemas de informação empresariais tende a:', ['Manter os sistemas isolados para aumentar a segurança das informações.', 'Reduzir a importância dos dados na tomada de decisão organizacional.', 'Ampliar a integração, a automação e o uso de tecnologias como inteligência artificial.', 'Eliminar a necessidade de alinhamento entre tecnologia e estratégia organizacional.'], 2, 'Mais integração, mais automação, mais IA: é o resumo do capítulo de Morais (2020) que a unidade indica.')),
        ex(mcq('c2-x1', 'c2.erpcrm', undefined, 'Qual é a diferença de foco entre ERP e CRM?', ['O ERP centraliza os processos internos (finanças, produção, logística, RH, compras); o CRM gerencia o relacionamento com o cliente (vendas, marketing, atendimento, suporte)', 'O ERP cuida apenas de clientes; o CRM, apenas de estoque', 'Os dois fazem exatamente a mesma coisa', 'O ERP é para empresas pequenas e o CRM para grandes'], 0, 'Dentro × fora.')),
        ex(mcq('c2-x2', 'c2.fluxo', undefined, 'Quais são as três etapas do fluxo de dados descritas na U4?', ['Entrada, processamento e armazenamento', 'Compra, venda e entrega', 'Hardware, software e protocolo', 'IaaS, PaaS e SaaS'], 0, 'Coleta, tratamento e guarda. Falha em qualquer uma compromete a decisão.')),
        ex(mcq('c2-x3', 'c2.transformacao', undefined, 'Segundo a U2, o que diferencia uma organização apenas digitalizada de uma verdadeiramente transformada?', ['A integração dos sistemas, o uso estratégico dos dados, a orientação ao cliente e a mudança cultural', 'A quantidade de computadores comprados', 'A presença em redes sociais', 'O uso exclusivo de sistemas em nuvem'], 0, 'É a lista do cartão "Toda empresa que usa tecnologia pode ser considerada digital?".', { heuristica: 'A correta junta sistema, dado, cliente e cultura: tecnologia como meio. "Exclusivo" denuncia a última.' })),
        ex(mcq('c2-x4', 'c2.transformacao', undefined, 'Qual alternativa lista os três pilares da transformação digital da U2?', ['Integração de tecnologias emergentes; reengenharia de processos; foco na experiência do cliente com cultura de inovação e agilidade', 'Hardware, software e redes', 'Entrada, processamento e armazenamento', 'Confidencialidade, integridade e disponibilidade'], 0, 'As outras são trios de outros assuntos: componentes de rede, fluxo de dados, tríade de segurança. Atenção para não trocar.')),
        ex(mcq('c2-x5', 'c2.etica', undefined, 'Para a U2, qual é o lugar da ética na transformação digital?', ['É parte integrante da concepção, implementação e gestão das soluções digitais, e não um elemento externo ou complementar', 'É um tema à parte, que só interessa ao setor jurídico', 'É dispensável quando a tecnologia é eficiente', 'Só se aplica a empresas que usam inteligência artificial'], 0, 'A frase da unidade: a ética "não deve ser entendida como um elemento externo ou complementar à tecnologia".')),
        ex(mcq('c2-x6', 'c2.lowcode', undefined, 'O que as ferramentas low-code mudam no acesso à automação?', ['Permitem que usuários com conhecimento técnico básico modelem fluxos de trabalho de forma visual, com componentes prontos', 'Exigem que todo funcionário aprenda a programar', 'Tornam a automação exclusiva da equipe de TI', 'Dispensam a existência de sistemas como ERP e CRM'], 0, 'Modelagem visual com blocos prontos: a tecnologia deixa de ser restrita a programadores.')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'c2-chefe', titulo: 'Chefão: a indústria tradicional', tipo: 'chefe', min: 12, resumo: 'Os estudos de caso da U4 e da U2 num só: uma indústria com silos que quer se transformar.',
      steps: [
        texto('**O caso (estudos de caso da U4 e da U2).** Você foi contratado como consultor por uma **indústria tradicional** do setor manufatureiro. O retrato:\n\n- vendas, estoque e financeiro usam **sistemas e planilhas isoladas**;\n- há atrasos na entrega, erros de estoque e divergência entre dados financeiros e comerciais;\n- as decisões saem "majoritariamente da experiência dos gestores";\n- a relação com o cliente **acaba depois da venda**.\n\nA empresa quer aumentar a eficiência, decidir melhor e melhorar a experiência do cliente.'),
        ex(mcq('c2-b1', 'c2.silos', 'U4 · Estudo de caso: sistemas integrados', 'Primeiro, o diagnóstico. O que explica atrasos, erros de estoque e números que não batem?', ['Silos informacionais: cada setor trabalha com dados isolados e desatualizados', 'Falta de computadores modernos', 'Excesso de integração entre os setores', 'Clientes exigentes demais'], 0, 'É a fragmentação dos dados: "compromete a eficiência organizacional e a qualidade da tomada de decisão".', { fixo: true })),
        ex(mcq('c2-b2', 'c2.erpcrm', 'U4 · Estudo de caso: sistemas integrados', 'A relação com o cliente acaba depois da venda. Que sistema ataca esse ponto, e qual ataca a bagunça entre estoque e financeiro?', ['CRM para o relacionamento com o cliente; ERP para integrar estoque, financeiro e demais processos internos', 'ERP para o relacionamento com o cliente; CRM para estoque e financeiro', 'Um Data Lake resolve os dois', 'Nenhum sistema: basta treinar os vendedores'], 0, 'CRM olha para fora; ERP olha para dentro. E os dois precisam conversar.', { fixo: true })),
        { t: 'toy', toy: 'silos', modo: 'livre', intro: 'Mostre o antes e o depois: faça algumas operações em silo, veja os contadores, e então integre.' },
        ex(mcq('c2-b3', 'c2.transformacao', 'U2 · Estudo de caso: indústria tradicional', 'A diretoria propõe: "vamos comprar um ERP e pronto, estaremos transformados". O que você responde?', ['Implantar o sistema é digitalização; transformação exige rever processos, decidir com dados e pôr o cliente no centro', 'Correto: ERP é sinônimo de transformação digital', 'Melhor não comprar nada, para evitar riscos', 'Basta abrir um perfil nas redes sociais'], 0, 'É a Empresa A do disparador: tem ERP e decide "no olho". Falta o resto dos pilares.', { fixo: true })),
        ex(mcq('c2-b4', 'c2.tecnologias', 'U2 · Estudo de caso: indústria tradicional', 'Que tecnologias emergentes fazem sentido para otimizar a produção e a gestão da informação dessa indústria?', ['IoT (sensores nas máquinas), computação em nuvem, big data e IA para analisar os dados e apoiar decisões', 'Apenas redes sociais', 'Impressoras mais rápidas', 'Nenhuma: tecnologia emergente só serve para empresas nativas digitais'], 0, 'É o quadro da Indústria 4.0: sensores coletam, a nuvem guarda e processa, a IA analisa.', { fixo: true })),
        ex(mcq('c2-b5', 'c2.etica', 'U2 · Estudo de caso: indústria tradicional', 'Que desafios éticos e sociais o consultor precisa pôr na mesa?', ['Requalificação dos trabalhadores cujas funções serão redefinidas, proteção dos dados coletados e transparência no uso de automação', 'Nenhum: tecnologia é neutra', 'Apenas o custo dos equipamentos', 'A demissão de todos os funcionários, pois a automação os substitui totalmente'], 0, 'Trabalhadores, dados e automação: são os três eixos que o enunciado do caso pede.', { fixo: true })),
        {
          t: 'escrita', fonte: 'U2 · Estudo de caso (o curso pede de 1000 a 2000 caracteres) e treino para a A3',
          prompt: 'Responda como consultor: (1) que tecnologias adotar; (2) que desafios éticos e sociais surgem para trabalhadores, dados e automação; (3) como a integração de sistemas ajuda a decidir melhor.',
          modelo: 'A indústria descrita está no estágio de digitalização parcial: usa tecnologia, mas mantém processos pouco integrados e decide pela experiência dos gestores. Para se transformar, o ponto de partida não é a ferramenta, e sim a estratégia; como afirma Rogers (2017), a transformação digital não é sobre tecnologia, mas sobre estratégia. No plano tecnológico, recomendo um ERP para unificar vendas, estoque e financeiro numa base única, um CRM para manter a relação com o cliente depois da venda, sensores de IoT nas máquinas, computação em nuvem para armazenar e processar os dados e ferramentas de análise e inteligência artificial para apoiar as decisões. No plano ético e social, três cuidados são necessários: a automação redefine funções e exige requalificação dos trabalhadores, que precisam ser incluídos no processo; os dados coletados de clientes e funcionários devem ser protegidos e usados com finalidade clara; e as decisões automatizadas precisam de transparência e supervisão humana. Por fim, a integração entre os sistemas elimina os silos: cada informação é registrada uma vez e fica disponível em tempo real para todos os setores, o que reduz retrabalho e divergências e permite decisões mais rápidas e baseadas em evidências. A empresa deixa de apenas digitalizar o que já fazia e passa a rever processos, colocar o cliente no centro e criar valor de outra forma, que é o que caracteriza a transformação digital.',
          rubrica: ['Abri pela distinção digitalização × transformação digital', 'Citei tecnologias e disse para que serve cada uma', 'Tratei dos três eixos éticos e sociais: trabalhadores, dados, automação', 'Expliquei como a integração elimina silos e melhora a decisão', 'Usei pelo menos um autor (Rogers, Gabriel, Akabane ou Morais)', 'Fechei mostrando que a mudança é de processo e cultura, não só de ferramenta'],
        },
        { t: 'feynman', prompt: 'Em uma frase: por que a Empresa A, com ERP e tudo, não é uma empresa transformada digitalmente?' },
      ],
    },
  ],
  cards: [...CARDS_EXP.filter((c) => c.regiao === 'c2'), ...cards('exp', 'c2', [
    ['Por que os silos surgem?', 'Cada setor escolhe a ferramenta que resolve o problema dele. O custo só aparece quando a informação precisa atravessar para outro setor.'],
    ['Dado, informação e conhecimento', 'Dado: registro cru. Informação: dado com contexto. Conhecimento: o que se decide com isso.'],
    ['O que é low-code?', 'Ferramentas de baixo código: automações montadas de forma visual, com blocos prontos, acessíveis a quem não programa. Reduzem erros em tarefas repetitivas.'],
    ['Empresa A × Empresa B (U2)', 'A: comprou tecnologia, mas decide pela experiência e não integra nem analisa dados (só digitalizou). B: processos integrados, decisão por dados, cliente no centro, discute ética (transformada).'],
    ['Tecnologias emergentes citadas na U2', 'Inteligência artificial, internet das coisas (IoT), big data, computação em nuvem e blockchain. Juntas na fábrica: Indústria 4.0.'],
    ['A automação e o emprego, segundo o curso', 'Reduz tarefas repetitivas e redefine funções; não elimina o fator humano. Exige requalificação.'],
    ['As quatro heurísticas de prova', 'Absolutos são distratores; a correta é a mais longa e qualificada; tecnologia como meio vence tecnologia como fim; em alternativa corrompida, leia a cláusula limpa.'],
  ], 9)],
};
