// C3 · A máquina que aprende (U5 · Inteligência Artificial e Automação + U6 · No-Code e IA Generativa), do zero.
// Fontes: fontes/exploracao/U5.txt e U6.txt.
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, ficha, gen, mcq, multi, texto } from '../ajuda';
import { CARDS_EXP } from './cards';

export const C3: Regiao = {
  id: 'c3', mundo: 'exp', nome: 'A máquina que aprende', unidades: 'U5 + U6', pronto: true,
  tese: 'Automação obedece, IA infere; o que vale agora é saber pedir.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'c3-autoia', titulo: 'Aula 1 · Obedecer ou aprender', tipo: 'licao', min: 11, resumo: 'Do zero: o que é IA, e a diferença entre automação, IA e sistema inteligente.',
      steps: [
        texto('**O problema.** A caixa de e-mail da igreja recebe vinte mensagens de golpe por dia. Você quer um filtro. Há dois jeitos de construir.\n\n**Jeito 1**: você escreve a regra. "Se a mensagem tem a palavra *grátis* ou *clique*, é spam."\n\n**Jeito 2**: você não escreve regra nenhuma. Mostra ao programa uma pilha de mensagens já separadas ("estas são golpe, estas são boas") e deixa ele descobrir sozinho o que as diferencia.\n\nO primeiro é **automação**. O segundo é **inteligência artificial**. Experimente os dois antes de eu dar as definições.'),
        { t: 'toy', toy: 'spam', modo: 'desafio', intro: 'Um filtro de spam, feito dos dois jeitos. Faça os dois primeiros desafios.', desafios: ['sp-regra', 'sp-modelo'] },
        texto('**As definições do curso.**\n\n**Automação**: "execução automática de tarefas repetitivas com base em **regras predefinidas**". Sistemas automatizados tradicionais "**não aprendem nem se adaptam**; eles apenas seguem instruções programadas".\n\n**Inteligência Artificial (IA)**: a área da computação que desenvolve sistemas capazes de executar tarefas que normalmente **exigiriam inteligência humana**: reconhecer padrões, tomar decisões, resolver problemas, entender linguagem, **aprender a partir de dados**. Envolve a capacidade de "**aprender, inferir e tomar decisões** com base em dados".\n\nA frase que resume a diferença: "enquanto a automação **executa processos**, a IA **analisa contextos** e pode modificar seu comportamento ao longo do tempo".\n\n(*Inferir* é tirar uma conclusão a partir de pistas, sem que ela tenha sido dita. O filtro inferiu que "clique" é suspeito.)'),
        ex(mcq('c3-q1', 'c3.fundamentos', 'U5 · Avaliando · Quizz 01', 'Questão do curso. A inteligência artificial (IA) pode ser definida, de forma introdutória, como:', ['Um conjunto de máquinas que substituem totalmente o trabalho humano', 'Sistemas computacionais capazes de executar tarefas que normalmente exigiriam inteligência humana', 'Programas que funcionam apenas com regras fixas e sem dados', 'Tecnologias usadas exclusivamente em robôs industriais'], 1, 'É a definição da unidade. "Regras fixas e sem dados" descreve a automação tradicional.', { heuristica: '"Totalmente", "apenas", "exclusivamente": os três distratores têm absoluto.' })),
        texto('**O terceiro nome: sistema inteligente.** O curso distingue ainda os **sistemas inteligentes**: uma **combinação** de automação, IA e integração com **sensores, dados e redes**. Eles **percebem o ambiente**, processam e **agem** de forma autônoma ou semiautônoma.\n\nExemplos do curso: controle de tráfego, casas inteligentes, plataformas de gestão baseadas em dados.\n\nUma escada:\n\n- **Automação**: faz sempre o mesmo. (O portão que abre quando você aperta o botão.)\n- **IA**: aprende com dados e decide. (O programa que reconhece a placa do carro.)\n- **Sistema inteligente**: sente, aprende e age. (O portão que reconhece o seu carro chegando e abre sozinho.)\n\nUm caso que confunde: o **RPA** (*Robotic Process Automation*, automação de processos robóticos). Tem "robô" no nome, mas é **automação**: um software que imita cliques e digitação humana para preencher formulários e copiar dados entre sistemas. O curso avisa: "diferentemente de soluções complexas de inteligência artificial, o RPA automatiza **processos estruturados**".'),
        gen('c3.autoia', 2),
        texto('**Regra é transparente; modelo é opaco.** Volte ao filtro. Quando a **regra** barra uma mensagem, qualquer pessoa lê a regra e sabe por quê. Dá para conferir, contestar, corrigir. Diz-se que é **auditável**.\n\nQuando o **modelo aprendido** barra uma mensagem, a explicação é uma conta com pesos que ele mesmo ajustou. No brinquedo eram 6 pesos; num sistema real são milhões. Ninguém consegue ler aquilo e dizer "foi por isso".\n\nA troca é esta: a regra é **explicável e rígida**; o modelo é **flexível e opaco**. Essa opacidade vai ser o centro da discussão ética na última região.', 'alem', 'A U5 define os três conceitos, mas não faz o contraste "auditável × opaco". Ele entra porque é o que liga esta unidade à governança algorítmica da U8.'),
        texto('**Três tipos de IA.** O curso classifica a IA "de acordo com seu nível de complexidade e autonomia":\n\n- **IA estreita** (ou fraca): faz **uma** tarefa específica, às vezes melhor que gente. Reconhecer rostos, traduzir, recomendar filmes. **Toda IA que existe hoje é estreita.**\n- **IA geral**: teria inteligência comparável à humana em qualquer tarefa. **Ainda não existe**; é hipótese e objeto de pesquisa.\n- **IA aplicada**: a IA usada para resolver problemas concretos de um setor (saúde, finanças, indústria).\n\nA lição do curso: "a IA não é uma tecnologia única ou homogênea, mas um conjunto de abordagens e aplicações".', 'alem', 'No texto extraído, os três tipos aparecem só pelo nome (os cartões clicáveis não vieram). As descrições são as usuais; "IA aplicada" não é uma categoria padrão fora deste curso, então confira na plataforma como ele a define.'),
        ex(cheque('c3-k01', 'c3.fundamentos', 'Um programa que joga xadrez melhor que qualquer humano, mas não sabe fazer mais nada, é um exemplo de:', ['IA estreita', 'IA geral', 'Automação sem aprendizado'], 0, 'Excelente numa tarefa só: estreita. A geral faria qualquer tarefa intelectual.')),
        texto('**E o padrão da disciplina, de novo.** A U5 repete a citação de Rogers (2017): "a transformação digital não é sobre tecnologia, mas sobre estratégia". E conclui que a IA "não substitui apenas tarefas humanas, mas **redefine funções**", e que seu impacto "depende da forma como é integrada aos processos, às pessoas e às decisões estratégicas".'),
        ex(mcq('c3-q5', 'c3.fundamentos', 'U5 · Avaliando · Quizz 05', 'Assinale a alternativa correta sobre os elementos da Inteligência Artificial:', ['Inteligência Artificial: área da computação que desenvolve sistemas capazes de simular inteligência humana', 'Aprendizado de Máquina: execução automática de tarefas e processos', 'Automação: informações utilizadas para treinar e alimentar sistemas inteligentes', 'Dados: técnica que permite que sistemas aprendam padrões a partir de exemplos'], 0, 'As outras três estão com as definições trocadas em roda: "execução automática de tarefas" é automação; "informações para treinar" são dados; "técnica que aprende padrões" é aprendizado de máquina.')),
        ficha({
          titulo: 'Automação × IA: a ficha',
          porque: 'É a distinção que decide o que se pode esperar de um sistema: se ele só repete, ou se muda com os dados (e portanto pode errar de jeitos novos).',
          ideia: 'Automação obedece a regras fixas. IA aprende com dados e infere. Sistema inteligente junta as duas com sensores e age.',
          regra: '$$\\text{automação: regra} \\to \\text{ação} \\qquad \\text{IA: dados} \\to \\text{modelo} \\to \\text{decisão}$$',
          exemplo: 'RPA preenchendo formulário: automação. Recomendação de filmes: IA. Controle de tráfego com sensores: sistema inteligente.',
          armadilha: 'Chamar de IA tudo que é automático. RPA tem "robô" no nome e não aprende nada.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'c3-aprendizado', titulo: 'Aula 2 · Como uma máquina aprende', tipo: 'licao', min: 12, resumo: 'Aprender = diminuir o erro sobre exemplos. Os três tipos de aprendizado, os algoritmos que o curso cita e por que o dado é o combustível.',
      steps: [
        texto('**O problema.** "A máquina aprende" soa misterioso. O que acontece de verdade lá dentro?\n\nPegue um caso: prever quanta energia um servidor gasta conforme as horas de uso. Você tem oito medições. Quer uma fórmula que acerte as próximas.\n\nA fórmula mais simples é uma reta: **energia = a × horas + b**. Faltam dois números, $a$ e $b$. "Aprender" vai ser **achar esses dois números**. Tente você primeiro.'),
        { t: 'toy', toy: 'treinador', modo: 'desafio', intro: 'Os pontos são as medições. A reta azul é o modelo. Os traços vermelhos são os erros. No primeiro desafio, você faz o papel do algoritmo; no segundo, a máquina faz.', desafios: ['tr-mao', 'tr-auto'] },
        texto('**O que você acabou de ver é aprendizado de máquina.** Sem mistério:\n\n1. Existe um **modelo**: uma fórmula com números ajustáveis (os **parâmetros**; aqui, $a$ e $b$).\n2. Existem **dados de exemplo**: casos em que a resposta certa é conhecida.\n3. Existe uma medida de **erro**: o quanto o modelo erra nesses exemplos.\n4. **Treinar** é mexer nos parâmetros, pouco a pouco, na direção que **diminui o erro**.\n\nNada além disso. O modelo não "entende" o que é energia. Ele ajusta números. Um modelo de linguagem moderno faz o mesmo com bilhões de parâmetros em vez de dois.\n\nA definição do curso diz isso com outras palavras: no aprendizado de máquina (*machine learning*), os sistemas "aprendem a partir de dados e aprimoram seu desempenho **sem a necessidade de programação explícita** para cada tarefa".', 'alem', 'A formulação "aprender = minimizar o erro sobre exemplos" não está no material, que só dá a definição geral. Entra porque é o mecanismo por trás da definição.'),
        ex(mcq('c3-q2', 'c3.aprendizado', 'U5 · Avaliando · Quizz 02', 'O aprendizado de máquina (machine learning) se diferencia da programação tradicional porque:', ['Não utiliza dados para funcionamento', 'Depende apenas de comandos manuais do usuário', 'Aprende padrões a partir de dados para melhorar seu desempenho', 'Elimina a necessidade de algoritmos'], 2, 'Na programação tradicional, alguém escreve a regra. No aprendizado de máquina, a regra sai dos dados.')),
        texto('**Três jeitos de aprender.** O que muda é o tipo de exemplo que a máquina recebe.\n\n**Supervisionado**: os exemplos vêm **com a resposta certa** (o **rótulo**). "Esta mensagem é spam", "este imóvel custou tanto". A máquina aprende a ligar a entrada à resposta. Foi o caso da reta e do filtro.\n\n**Não supervisionado**: os exemplos vêm **sem resposta**. A máquina procura sozinha **estrutura** nos dados: grupos de clientes parecidos, padrões que ninguém pediu.\n\n**Por reforço**: não há exemplos prontos. A máquina **age**, recebe **recompensa ou punição** e ajusta o comportamento. É como se treina um programa para jogar ou um robô para andar.'),
        gen('c3.tipo', 2),
        texto('**Os algoritmos que o curso cita.** Você não precisa saber fazer nenhum; precisa saber **em qual gaveta** cada um fica.\n\n**Supervisionado**\n- **Regressão linear**: prevê um **número** (a reta que você treinou).\n- **Regressão logística**: prevê uma **classe** (sim ou não; apesar do nome, classifica).\n- **Árvore de decisão**: uma sequência de perguntas ("renda acima de X? tem dívida?") até chegar à resposta.\n- **k-NN** (*k* vizinhos mais próximos): decide olhando os $k$ exemplos mais parecidos.\n\nO curso destaca que esses quatro são usados pela "**interpretabilidade**": dá para entender por que decidiram.\n\n**Não supervisionado**\n- **k-means**: **agrupa** os dados em $k$ grupos.\n- **PCA** (análise de componentes principais): **reduz a dimensionalidade**, isto é, resume muitas colunas em poucas.\n\n**Por reforço**\n- **Q-learning** e métodos baseados em políticas.\n\nAcima de todos estão as **redes neurais profundas**, mais poderosas e bem menos interpretáveis.'),
        ex(cheque('c3-k02', 'c3.aprendizado', 'Em qual tipo de aprendizado ficam o k-means e o PCA?', ['Não supervisionado', 'Supervisionado', 'Por reforço'], 0, 'Os dois trabalham com dados sem rótulo: um agrupa, o outro resume.')),
        texto('**Dado é combustível.** O curso usa essa imagem: os dados são o "**combustível**" dos sistemas inteligentes. E três qualidades decidem tudo: "a **qualidade**, a **quantidade** e a **diversidade** dos dados influenciam diretamente o desempenho dos modelos".\n\nO outro lado: "dados incompletos, **enviesados** ou mal estruturados podem comprometer os resultados".\n\nVeja o que um único dado ruim faz.'),
        { t: 'toy', toy: 'treinador', modo: 'desafio', intro: 'Um dado estranho entra no conjunto. Treine e observe a reta.', desafios: ['tr-estranho'] },
        texto('**Preditiva e generativa.** A unidade fecha distinguindo dois usos:\n\n- **IA preditiva**: analisa dados para **prever** resultados. Exemplo do curso: estimar o risco de evasão escolar.\n- **IA generativa**: **cria conteúdo novo**: textos, imagens, código. É o assunto das duas próximas aulas.\n\nAkabane (2018), citado na unidade: "as tecnologias cognitivas ampliam a capacidade das organizações de aprender com dados e transformar informação em vantagem competitiva".'),
        ficha({
          titulo: 'Aprendizado de máquina: a ficha',
          porque: 'Recomendação, crédito, diagnóstico, tradução: tudo isso é um modelo que ajustou números sobre exemplos. Saber disso tira o mistério e mostra onde pode dar errado.',
          ideia: 'Um modelo com parâmetros, dados de exemplo e uma medida de erro. Treinar é ajustar os parâmetros para o erro cair.',
          regra: '$$\\text{supervisionado: com rótulo} \\qquad \\text{não supervisionado: sem rótulo} \\qquad \\text{reforço: recompensa}$$',
          exemplo: 'Supervisionado: regressão linear e logística, árvore de decisão, k-NN. Não supervisionado: k-means, PCA. Reforço: Q-learning.',
          armadilha: 'Achar que o modelo "entende". Ele minimiza erro. Se o dado é torto, ele aprende o torto com capricho.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'c3-generativa', titulo: 'Aula 3 · A máquina que escreve', tipo: 'licao', min: 11, resumo: 'IA generativa por dentro: prever o próximo pedaço, de novo e de novo. E por que o prompt muda tudo.',
      steps: [
        texto('**O problema.** Você digita uma pergunta e um programa responde com três parágrafos bem escritos. De onde sai esse texto? Ele não está guardado em lugar nenhum; foi **gerado** ali, na hora.\n\nA **IA generativa**, diz o curso, são "sistemas capazes de **criar conteúdos originais**, como textos, imagens, áudio e código, a partir de dados e **padrões aprendidos**". Exemplos: **GPT** (texto) e **DALL·E** (imagem).\n\nA sigla GPT quer dizer *Generative Pre-trained Transformer*: gerador, pré-treinado, com uma arquitetura chamada *transformer*.\n\nComo um modelo "gera"? A resposta é mais simples do que parece. Brinque com um modelo minúsculo antes.'),
        { t: 'toy', toy: 'gerador', modo: 'desafio', intro: 'Este modelo foi treinado com seis frases curtas. Ele só sabe uma coisa: depois de cada palavra, quais costumam vir. Escreva com ele.', desafios: ['ge-frase'] },
        texto('**O mecanismo: prever o próximo pedaço.** O que você fez é o que um GPT faz:\n\n1. Olha o texto que existe até agora.\n2. Calcula, para cada palavra possível, a **chance** de ela ser a próxima.\n3. Escolhe uma.\n4. Acrescenta ao texto e **volta ao passo 1**.\n\nUm modelo que gera assim, usando a própria saída como entrada do passo seguinte, chama-se **autorregressivo**.\n\nOu seja: a IA generativa é uma **IA preditiva** rodando em círculo. Ela prevê o próximo pedaço, muitas vezes seguidas.\n\nA diferença do brinquedo para o de verdade é de **tamanho**: o seu olha só a última palavra e viu seis frases; um GPT olha milhares de palavras para trás e foi treinado com uma fatia enorme da internet. O princípio é o mesmo.', 'alem', 'A U6 diz apenas que a IA generativa cria conteúdo "a partir de dados e padrões aprendidos". O mecanismo (prever o próximo pedaço, repetidamente) não está no material; entra porque explica as três consequências que vêm a seguir.'),
        texto('**Três consequências desse mecanismo.**\n\n**1. Ele não confere fatos.** O modelo escolhe o **provável**, não o **verdadeiro**. Um texto fluente e errado sai com a mesma naturalidade de um texto certo. Daí a regra do curso: "**sempre revise e valide** as respostas".\n\n**2. Ele só sabe o que estava nos dados.** Troque o texto de treino e muda tudo o que ele consegue dizer. Vieses dos dados reaparecem no texto.\n\n**3. O começo condiciona o resto.** Cada palavra que você escreve antes muda as chances do que vem depois. Esse "começo" tem nome: **prompt**.'),
        { t: 'toy', toy: 'gerador', modo: 'desafio', intro: 'Veja as consequências 2 e 3 acontecendo, e depois o que dá errado quando o modelo sempre escolhe a mais provável.', desafios: ['ge-prompt', 'ge-repete'] },
        texto('**Prompt: condicionar a previsão.** O **prompt** é o texto que você entrega ao modelo: a pergunta, o pedido, o contexto. Como o modelo continua o texto a partir dali, um prompt vago dá uma continuação genérica; um prompt rico em contexto puxa uma continuação específica.\n\nÉ por isso que o curso afirma: "a qualidade da resposta de uma IA generativa depende mais da **forma como você pergunta** do que apenas da tecnologia utilizada".\n\nE por isso a diferença para o software tradicional: lá, "comandos são rígidos e estruturados"; aqui, o modelo responde "de acordo com a **forma, o contexto e a intenção** expressa no prompt".\n\nO usuário vira, na expressão do curso, um "**orquestrador**" da inteligência artificial.'),
        ex(cheque('c3-k03', 'c3.generativa', 'Por que um modelo de linguagem pode dar uma resposta bem escrita e errada?', ['Porque ele gera o texto mais provável, e não tem um passo de conferir se é verdade', 'Porque ele consulta um banco de dados de respostas e às vezes pega a errada', 'Porque ele foi programado com regras fixas'], 0, 'Prever o provável não é o mesmo que conferir o verdadeiro. Não há banco de respostas nem regra escrita por gente.')),
        ex(mcq('c3-q6', 'c3.generativa', 'U6 · IA generativa · Quiz (Schmidt, Huttenlocher e Kissinger)', 'Podemos considerar que a trajetória da inteligência artificial demonstra que:', ['A IA permaneceu restrita a cálculos matemáticos simples, sem avanços na criação de conteúdos', 'A IA evoluiu de fundamentos teóricos para sistemas capazes de gerar conteúdos e apoiar atividades cognitivas humanas.', 'A IA substitui integralmente a inteligência humana em qualquer tarefa.', 'A IA não possui aplicações práticas no cotidiano profissional atual.'], 1, 'De Turing aos modelos generativos: evolução, com a IA apoiando (não substituindo) a atividade humana.', { heuristica: '"Integralmente", "qualquer tarefa", "não possui": absolutos. A correta fala em APOIAR.' })),
        texto('**Os riscos que o curso lista.** O crescimento da IA generativa levanta "desafios éticos e de segurança da informação":\n\n- **autoria** de conteúdo e **direitos autorais** (de quem é o texto gerado? e os textos usados no treino?);\n- **uso indevido de dados**;\n- **disseminação de desinformação**;\n- **reprodução de vieses** algorítmicos.\n\nA frase para guardar: compreender a IA generativa "não significa apenas saber utilizá-la, mas também reconhecer seus **limites, riscos e impactos**".'),
        ex(mcq('c3-q7', 'c3.generativa', 'U6 · Avaliando', 'O uso ético da IA generativa envolve principalmente:', ['Aceitar todas as respostas automaticamente.', 'Revisar, validar e reconhecer limitações dos modelos.', 'Copiar conteúdos sem citar fonte.', 'Automatizar qualquer decisão sem supervisão.'], 1, 'Revisão humana, validação e consciência dos limites.')),
        ficha({
          titulo: 'IA generativa: a ficha',
          porque: 'É a tecnologia que mais mudou o trabalho de escritório nos últimos anos. Saber o mecanismo evita os dois erros: confiar demais e desprezar.',
          ideia: 'Um modelo que prevê o próximo pedaço de texto e repete isso. O prompt é o começo que condiciona a continuação.',
          regra: '$$\\text{texto até agora} \\to \\text{chances da próxima palavra} \\to \\text{escolhe} \\to \\text{repete}$$',
          exemplo: 'GPT gera texto; DALL·E gera imagem. Riscos: autoria, direitos autorais, desinformação, vieses.',
          armadilha: 'Tratar a resposta como consulta a uma fonte. É uma previsão: revise e valide sempre.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'c3-prompt', titulo: 'Aula 4 · Saber pedir, e montar sem código', tipo: 'licao', min: 11, resumo: 'Engenharia de prompt, ferramentas no-code e a automação no dia a dia e nas empresas.',
      steps: [
        texto('**Engenharia de prompt.** Se o prompt condiciona a resposta, escrever bons prompts vira uma habilidade. O curso a chama de **engenharia de prompt**: "a elaboração cuidadosa de comandos e instruções para interagir com modelos de IA generativa".\n\n**As três partes de um bom prompt** (questão certa de prova):\n\n- **Contexto**: quem está pedindo, em que situação, para qual público.\n- **Objetivo**: para que serve o resultado.\n- **Instrução clara**: o que fazer e em que formato entregar.\n\nCompare:\n\n"*Escreva sobre o ensaio.*"\n\n"*Sou líder de louvor de uma igreja pequena, com músicos iniciantes* (contexto). *Quero que o ensaio de quinta renda mais* (objetivo). *Monte um roteiro de 60 minutos, em tópicos, com o tempo de cada parte* (instrução)."'),
        gen('c3.prompt', 2),
        ex(mcq('c3-q8', 'c3.prompt', 'U6 · Avaliando', 'Questão do curso. Um prompt bem estruturado deve conter principalmente:', ['Apenas palavras-chave soltas.', 'Contexto, objetivo e instrução clara.', 'Códigos de programação.', 'Somente perguntas fechadas.'], 1, 'As três partes.')),
        texto('**As quatro técnicas (lista do curso).**\n\n1. **Formulação clara e objetiva**: sem ambiguidade.\n2. **Uso de exemplos** para guiar: mostrar um modelo do que você quer ajuda o sistema a entender o **formato** esperado.\n3. **Iteração e refinamento progressivo**: "o primeiro prompt raramente é o melhor". Ajuste com base na resposta anterior.\n4. **Validação e ajuste** das respostas: conferir antes de usar.\n\nRepare que a quarta não é sobre escrever: é sobre **não confiar cegamente**. O curso pergunta: "Você confia cegamente na resposta da IA? Sempre revise e valide as respostas antes de utilizá-las em atividades acadêmicas ou profissionais."'),
        ex(cheque('c3-k04', 'c3.prompt', 'A resposta veio no formato errado. Segundo as técnicas do curso, qual é o próximo passo?', ['Refinar o prompt (por exemplo, incluindo um exemplo do formato) e pedir de novo', 'Desistir: a ferramenta não serve', 'Usar a resposta assim mesmo'], 0, 'Iteração e refinamento; e exemplos ajudam justamente com formato.')),
        texto('**No-code: construir sem programar.** A outra metade da U6. **Ferramentas no-code** são plataformas que permitem criar aplicações, sites e automações "**sem a necessidade de escrever código manualmente**", por interfaces visuais de **arrastar e soltar** (*drag-and-drop*).\n\nA palavra que o curso usa, e que é a resposta da questão: elas **democratizam** o desenvolvimento. Deixa de ser exclusividade de programadores; setores administrativos, educacionais e comerciais "passam a construir suas próprias soluções".\n\nDois exemplos nomeados:\n\n- **Webflow**: construir **sites** responsivos por edição visual.\n- **Zapier**: **integrar aplicativos** e criar automações entre plataformas ("quando chegar uma resposta no formulário, mande um e-mail").\n\nBenefícios: prototipagem rápida, menor custo, autonomia, cultura de experimentação.\n\n**No-code × low-code**: no *low-code* (da U4) ainda há um pouco de código; no *no-code*, nenhum.'),
        ex(mcq('c3-q9', 'c3.nocode', 'U6 · Avaliando', 'O principal impacto das ferramentas no-code na transformação digital é:', ['Eliminar totalmente a área de tecnologia da informação.', 'Democratizar o desenvolvimento de soluções digitais.', 'Substituir modelos de inteligência artificial.', 'Tornar desnecessário o uso de dados.'], 1, 'Democratizar: mais gente consegue criar.')),
        ex(mcq('c3-q10', 'c3.nocode', 'U6 · Avaliando', 'Quando uma empresa utiliza Zapier para conectar formulários e envio automático de e-mails, ela está aplicando:', ['Programação tradicional em linguagem Python.', 'Automação de processos por integração no-code.', 'Criação de banco de dados relacional.', 'Engenharia de hardware.'], 1, 'Zapier liga aplicativos sem código. Repare: isso é AUTOMAÇÃO (gatilho e ação fixos), não IA.')),
        texto('**Juntando as duas coisas.** As plataformas no-code se ligam a modelos de IA por **APIs** e conectores (as "tomadas" entre sistemas). Dá para montar, sem programar:\n\n- um **chatbot** que gera respostas em linguagem natural, em vez de só repetir respostas prontas;\n- **relatórios** escritos automaticamente a partir de uma planilha;\n- **posts** para redes sociais.\n\nO fluxo do estudo de caso da U6: o usuário informa parâmetros (tema, público-alvo, estilo) → o sistema envia a um modelo de IA → recebe o conteúdo → mostra o resultado.\n\nE a exigência que o curso repete: "**revisão humana** dos conteúdos gerados, proteção de dados e transparência no uso da inteligência artificial".'),
        ex(mcq('c3-q11', 'c3.nocode', 'U6 · Avaliando', 'A combinação entre no-code e IA generativa permite principalmente:', ['Criar soluções digitais inteligentes sem programação tradicional.', 'Substituir totalmente profissionais humanos.', 'Eliminar a necessidade de design de interfaces.', 'Impedir personalização de sistemas.'], 0, 'Soluções inteligentes ao alcance de quem não programa.')),
        ficha({
          titulo: 'Prompt e no-code: a ficha',
          porque: 'São as duas habilidades práticas que a disciplina quer que você leve: pedir bem a uma IA e montar uma automação sem depender de programador.',
          ideia: 'Prompt bom tem contexto, objetivo e instrução. No-code monta soluções com blocos visuais. Os dois juntos põem IA dentro de fluxos de trabalho.',
          regra: '$$\\text{prompt} = \\text{contexto} + \\text{objetivo} + \\text{instrução clara}$$',
          exemplo: 'Webflow faz sites; Zapier integra aplicativos. Técnicas: clareza, exemplos, iteração, validação.',
          armadilha: 'Achar que no-code elimina a área de TI, ou que dá para dispensar a revisão humana.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB
    {
      id: 'c3-lab', titulo: 'Laboratório · Três máquinas e as pessoas', tipo: 'lab', min: 10, resumo: 'Os três brinquedos à vontade, o viés nascendo dos dados e o que a automação faz com o trabalho.',
      steps: [
        { t: 'toy', toy: 'spam', modo: 'desafio', intro: 'Volte ao filtro. Agora você vai ensinar errado de propósito.', desafios: ['sp-vies'] },
        texto('**De onde vem o viés algorítmico.** Você acabou de fabricar um. O curso explica assim: "como os sistemas de IA aprendem a partir de **dados históricos**, eles podem **reproduzir e até amplificar** preconceitos sociais existentes, como discriminações de gênero, raça ou classe social. Isso ocorre quando os dados utilizados para treinamento refletem **desigualdades estruturais** da sociedade."\n\nOnde isso pesa: **concessão de crédito, seleção de candidatos a emprego, definição de políticas públicas**.\n\nAs **três contramedidas** que o curso lista: **transparência**, **auditoria de algoritmos** e **diversidade nas equipes** que criam os sistemas.\n\nE a frase que tira a culpa da máquina: a reflexão ética "envolve **escolhas humanas** sobre quais problemas resolver, quais dados utilizar e quais valores orientarão o uso da tecnologia".'),
        ex(mcq('c3-r-etica', 'c3.etica', 'U5 · Estudo guiado (artigo sobre ética na IA)', 'Qual item representa uma preocupação ética central no uso e desenvolvimento de sistemas de IA?', [
          'A inteligência artificial deve substituir totalmente todas as funções humanas, pois isso é inevitável e não representa riscos sociais.',
          'A ética na IA exige princípios como benefício humano, responsabilidade jurídica e transparência, de modo a evitar que sistemas autônomos causem prejuízos ou discriminação.',
          'A ética não faz parte do campo da IA, pois ela é apenas um campo técnico de engenharia e matemática.',
          'Os únicos desafios da IA são tecnológicos, como capacidade de processamento e velocidade de cálculo, sem relação com valores sociais ou morais.',
        ], 1, 'Benefício humano, responsabilidade e transparência.', { heuristica: '"Totalmente todas", "apenas", "os únicos": absolutos. A correta é a mais longa e fala de pessoas.' })),
        texto('**A automação no cotidiano e nas empresas (U5).** Quatro frentes:\n\n- **Cotidiano**: **assistentes virtuais** (voz no celular, alto-falantes) e **sistemas de recomendação** (streaming, redes sociais, lojas).\n- **Administrativa**: notas fiscais, controle financeiro, estoque, folha de pagamento. Aqui entra o **RPA**.\n- **Atendimento**: **chatbots** e assistentes corporativos, que fazem o atendimento inicial e respondem perguntas frequentes.\n- **Industrial**: robôs, sensores, **Indústria 4.0**, monitoramento em tempo real e **manutenção preditiva** (consertar antes de quebrar).\n\n**E o trabalho?** A posição do curso é firme: "a automação **não elimina o papel humano, mas o transforma**". Tarefas repetitivas são automatizadas; cresce a demanda por quem analisa dados, decide e interage com sistemas inteligentes. Competências valorizadas: **pensamento crítico, criatividade, adaptabilidade e aprendizado contínuo**.\n\nMartha Gabriel (2021): "o futuro do trabalho não é sobre humanos **versus** máquinas, mas sobre humanos **com** máquinas".'),
        ex(multi('c3-q3', 'c3.automacao', 'U5 · Avaliando · Quizz 03', 'Quais situações do cotidiano representam aplicações de IA e automação? (Marque todas as corretas.)', ['Sistemas de recomendação em plataformas de streaming', 'Assistentes virtuais por voz em smartphones', 'Planilhas preenchidas manualmente sem uso de algoritmos', 'Filtros automáticos de e-mails contra spam', 'Chatbots para atendimento ao cliente'], [0, 1, 3, 4], 'Todas menos a planilha preenchida à mão: ali não há nem automação nem IA.')),
        ex(multi('c3-q4', 'c3.automacao', 'U5 · Avaliando · Quizz 04', 'A automação de processos com uso de IA pode trazer quais benefícios para organizações e usuários? (Marque todas as corretas.)', ['Aumento de eficiência e redução de tarefas repetitivas', 'Eliminação total da necessidade de supervisão humana', 'Apoio à tomada de decisão baseada em dados', 'Padronização e maior rapidez na execução de processos'], [0, 2, 3], 'Eficiência, apoio à decisão e padronização. "Eliminação total da supervisão humana" é o distrator: o curso exige supervisão e revisão humana.', { heuristica: '"Eliminação total": absoluto.' })),
        { t: 'toy', toy: 'treinador', modo: 'livre', intro: 'Bancada livre do treinador. Tente uma reta bem errada e aperte "100 passos": ela sempre volta para perto do mesmo lugar, porque é ali que o erro é menor.' },
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'c3-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'A U5 e a U6 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**U5.** **IA**: sistemas que executam tarefas que exigiriam inteligência humana; aprendem, inferem e decidem com dados. **Automação**: tarefas repetitivas por regras predefinidas; não aprende. **Sistema inteligente**: automação + IA + sensores, dados e redes; percebe e age. **RPA**: software que simula ações humanas em processos estruturados (é automação). Tipos de IA: **estreita, geral, aplicada**.\n\n**Aprendizado de máquina**: aprende com dados sem programação explícita. **Supervisionado** (regressão linear e logística, árvore de decisão, k-NN), **não supervisionado** (k-means, PCA), **por reforço** (Q-learning). Dados são o **combustível**: qualidade, quantidade, diversidade.\n\n**Automação**: assistentes virtuais, recomendação, administrativa, chatbots, industrial (Indústria 4.0, manutenção preditiva).\n\n**Impactos**: o trabalho é transformado, não eliminado; aprendizado contínuo; **viés algorítmico** (crédito, recrutamento, políticas públicas), contramedidas: transparência, auditoria, diversidade; privacidade; inclusão digital.'),
        texto('**U6.** **No-code**: criar soluções sem escrever código, por arrastar e soltar; **democratiza** o desenvolvimento. **Webflow** (sites), **Zapier** (integração e automação entre aplicativos).\n\n**IA generativa**: cria textos, imagens, áudio e código a partir de padrões aprendidos (**GPT**, **DALL·E**). **Preditiva** prevê; **generativa** cria. Riscos: autoria, direitos autorais, uso indevido de dados, desinformação, vieses.\n\n**Engenharia de prompt**: formulação clara; exemplos; iteração e refinamento; validação. Prompt = **contexto + objetivo + instrução clara**. O usuário é o "orquestrador".\n\n**Integração** no-code + IA por APIs: chatbots, relatórios, conteúdo. Sempre com **revisão humana**.\n\n**Citações**: Rogers (2017), "não é sobre tecnologia, mas sobre estratégia"; Gabriel (2021), "humanos com máquinas"; Akabane (2018), tecnologias cognitivas transformam dados em conhecimento.'),
        ex(mcq('c3-q12', 'c3.nocode', 'U6 · Estudo de caso · Quiz (Akabane)', 'As tecnologias cognitivas contribuem para as organizações principalmente porque:', ['Substituem completamente o trabalho humano nos processos organizacionais.', 'Permitem transformar dados e interações em conhecimento aplicado à gestão e à tomada de decisão.', 'Eliminam a necessidade de integração entre sistemas de informação.', 'Tornam desnecessário o uso de estratégias digitais nas empresas.'], 1, 'Dados e interações virando conhecimento para decidir.', { heuristica: '"Completamente", "eliminam", "desnecessário": três absolutos, três distratores.' })),
        { t: 'feynman', prompt: 'Sem olhar: explique para alguém da igreja a diferença entre um programa que segue regras e um que aprende com exemplos. Use o filtro de spam.' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'c3-questoes', titulo: 'Questões da U5 e da U6', tipo: 'questoes', min: 8, resumo: 'Questões de fixação no estilo da prova, sobre os pontos que as questões oficiais não cobrem.',
      steps: [
        texto('Todas as questões da plataforma destas duas unidades já apareceram dentro das aulas e do laboratório. As questões abaixo **não são da plataforma**: escrevi a partir do texto das unidades, no formato das provas, para cobrir o que faltava.'),
        ex(mcq('c3-x1', 'c3.fundamentos', undefined, 'O que é RPA, segundo a U5?', ['Softwares que simulam ações humanas em sistemas digitais para automatizar processos estruturados, como preencher formulários e extrair dados', 'Um tipo avançado de inteligência artificial que aprende sozinho', 'Um robô industrial com braços mecânicos', 'Uma técnica de aprendizado por reforço'], 0, 'RPA automatiza processo estruturado. O curso frisa: "diferentemente de soluções complexas de inteligência artificial".')),
        ex(mcq('c3-x2', 'c3.aprendizado', undefined, 'Qual alternativa associa corretamente algoritmo e tipo de aprendizado?', ['k-means: não supervisionado; árvore de decisão: supervisionado; Q-learning: por reforço', 'k-means: supervisionado; regressão linear: por reforço; PCA: supervisionado', 'Q-learning: não supervisionado; k-NN: por reforço; PCA: supervisionado', 'Regressão logística: não supervisionado; k-means: por reforço; árvore de decisão: não supervisionado'], 0, 'Supervisionado: regressões, árvore, k-NN. Não supervisionado: k-means, PCA. Reforço: Q-learning.')),
        ex(mcq('c3-x3', 'c3.aprendizado', undefined, 'Por que o curso chama os dados de "combustível" dos sistemas inteligentes?', ['Porque a qualidade, a quantidade e a diversidade dos dados influenciam diretamente o desempenho dos modelos', 'Porque os dados fornecem a energia elétrica dos servidores', 'Porque dados nunca contêm erros', 'Porque quanto menos dados, melhor o modelo'], 0, 'Dado incompleto, enviesado ou mal estruturado compromete o resultado.')),
        ex(mcq('c3-x4', 'c3.etica', undefined, 'Segundo a U5, por que sistemas de IA podem reproduzir preconceitos?', ['Porque aprendem a partir de dados históricos, que podem refletir desigualdades estruturais da sociedade', 'Porque os programadores sempre inserem preconceitos de propósito', 'Porque computadores têm opiniões próprias', 'Porque a IA só funciona com regras fixas'], 0, 'O viés vem dos dados de treinamento. As contramedidas: transparência, auditoria e diversidade nas equipes.')),
        ex(mcq('c3-x5', 'c3.automacao', undefined, 'Qual é a posição da U5 sobre o impacto da automação no trabalho?', ['A automação não elimina o papel humano, mas o transforma, valorizando pensamento crítico, criatividade, adaptabilidade e aprendizado contínuo', 'A automação elimina todas as profissões em poucos anos', 'A automação não tem nenhum efeito sobre o mercado de trabalho', 'A automação só afeta trabalhos criativos'], 0, 'Transforma, não elimina. É a tese que a A3 espera.', { heuristica: '"Todas", "nenhum", "só": absolutos.' })),
        ex(mcq('c3-x6', 'c3.generativa', undefined, 'Qual é a diferença entre IA preditiva e IA generativa?', ['A preditiva analisa dados para prever resultados; a generativa cria conteúdos novos, como textos e imagens', 'A preditiva cria imagens; a generativa prevê o clima', 'São dois nomes para a mesma coisa', 'A preditiva usa dados; a generativa não usa'], 0, 'Exemplo do curso de preditiva: estimar risco de evasão escolar.')),
        ex(mcq('c3-x7', 'c3.prompt', undefined, 'Qual conjunto reúne as quatro técnicas de engenharia de prompt da U6?', ['Formulação clara e objetiva; uso de exemplos; iteração e refinamento; validação e ajuste das respostas', 'Entrada, processamento, armazenamento e saída', 'Contexto, objetivo, instrução e código', 'IaaS, PaaS, SaaS e no-code'], 0, 'Cuidado com a terceira: contexto, objetivo e instrução são as PARTES do prompt, não as técnicas (e "código" não faz parte).')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'c3-chefe', titulo: 'Chefão: a Comercial Alpha', tipo: 'chefe', min: 12, resumo: 'O estudo de caso da U5: uma varejista com muitos dados e decisões manuais, que quer usar aprendizado de máquina.',
      steps: [
        texto('**O caso (estudo de caso da U5).** A **Comercial Alpha** é uma varejista de médio porte, com lojas físicas e venda online. Ela coleta muitos dados (clientes, vendas, estoque, canais digitais), mas decide com "análises manuais e relatórios estáticos".\n\nQuatro dores:\n\n1. **previsão de demanda imprecisa**;\n2. **excesso ou falta** de produtos em estoque;\n3. dificuldade de **personalizar ofertas**;\n4. descoberta **tardia** de clientes abandonando o carrinho.\n\nA direção quer usar aprendizado de máquina para prever vendas, recomendar produtos e atender por chatbot. As preocupações: **qualidade dos dados**, **integração** com os sistemas existentes e **capacitação** dos funcionários. E quer fazer isso "de forma prática, **gradual e estratégica**", sem comprometer "a ética, a transparência e a segurança".'),
        ex(mcq('c3-b1', 'c3.aprendizado', 'U5 · Estudo de caso: Comercial Alpha', 'Prever quantas unidades serão vendidas no próximo mês, a partir do histórico de vendas, é um problema de qual tipo de aprendizado?', ['Supervisionado: há exemplos passados com a resposta conhecida (quanto vendeu)', 'Não supervisionado: não há nenhuma resposta conhecida', 'Por reforço: o sistema ganha pontos por vender', 'Nenhum: é automação por regra fixa'], 0, 'O histórico traz a entrada (mês, promoções, estação) e a resposta (vendas). Prever um número é regressão.', { fixo: true })),
        ex(mcq('c3-b2', 'c3.aprendizado', 'U5 · Estudo de caso: Comercial Alpha', 'A empresa quer descobrir perfis de clientes para personalizar ofertas, sem saber de antemão quais perfis existem. Que técnica do curso serve?', ['k-means, que agrupa clientes parecidos (não supervisionado)', 'Regressão linear, que prevê um número', 'Q-learning, que aprende por recompensa', 'RPA, que preenche formulários'], 0, 'Agrupar sem rótulos: aprendizado não supervisionado.', { fixo: true })),
        ex(mcq('c3-b3', 'c3.automacao', 'U5 · Estudo de caso: Comercial Alpha', 'O chatbot vai responder dúvidas frequentes dos clientes. Em que frente da automação isso se encaixa, segundo a U5?', ['Robôs de atendimento, que automatizam o atendimento inicial e melhoram a experiência do cliente', 'Automação industrial', 'Manutenção preditiva', 'Redução de dimensionalidade'], 0, 'Chatbots e assistentes virtuais corporativos.', { fixo: true })),
        { t: 'toy', toy: 'treinador', modo: 'livre', intro: 'Imagine que os pontos são as vendas da Alpha. Ligue o "dado estranho" (uma venda registrada errada) e treine. É a preocupação número um do caso: qualidade dos dados.' },
        ex(mcq('c3-b4', 'c3.aprendizado', 'U5 · Estudo de caso: Comercial Alpha', 'Por que a "qualidade dos dados" aparece como preocupação antes de qualquer modelo?', ['Porque o modelo aprende exatamente o que os dados mostram: dados incompletos ou enviesados produzem previsões erradas', 'Porque modelos de aprendizado de máquina não usam dados', 'Porque dados ruins deixam os servidores mais lentos', 'Porque a lei proíbe o uso de dados em modelos'], 0, 'Dado é o combustível. Lixo entra, lixo sai, e o modelo não avisa.', { fixo: true })),
        ex(mcq('c3-b5', 'c3.etica', 'U5 · Estudo de caso: Comercial Alpha', 'O modelo de recomendação passa a oferecer crédito parcelado só para clientes de certos bairros, porque assim era no histórico. O que está acontecendo, e o que fazer?', ['Viés algorítmico herdado dos dados históricos; a resposta é transparência, auditoria do algoritmo e diversidade na equipe', 'Nada de errado: o modelo é neutro, pois é matemático', 'Um erro de hardware; basta trocar o servidor', 'Falta de largura de banda'], 0, 'O modelo reproduz (e pode amplificar) a desigualdade que estava nos dados. As três contramedidas são as do curso.', { fixo: true })),
        ex(mcq('c3-b6', 'c3.prompt', 'U6 · Estudo de caso: conteúdo para redes sociais', 'A Alpha também quer gerar posts com IA generativa, numa ferramenta no-code. Qual prompt segue a estrutura que o curso ensina?', ['"Somos uma loja de roupas de bairro (contexto). Queremos divulgar a promoção de inverno (objetivo). Escreva três legendas curtas, em tom informal, com uma chamada para a loja online (instrução)."', '"Post."', '"Escreva algo bom sobre a loja."', '"Promoção, inverno, roupas, barato, compre."'], 0, 'Contexto, objetivo e instrução clara. As outras são vagas ou só palavras-chave soltas.', { fixo: true })),
        {
          t: 'escrita', fonte: 'U5 · Estudo de caso (resposta esperada) e treino para a A3',
          prompt: 'É a atividade da unidade: como a Comercial Alpha pode aplicar o aprendizado de máquina em suas atividades cotidianas para melhorar a tomada de decisão e a eficiência operacional?',
          modelo: 'A Comercial Alpha tem o insumo principal do aprendizado de máquina, que são os dados, mas ainda decide por análises manuais. A aplicação deve ser gradual e ligada a problemas concretos do negócio. Primeiro, um modelo de aprendizado supervisionado, treinado com o histórico de vendas, pode prever a demanda de cada produto; com essa previsão, a reposição de estoque deixa de oscilar entre excesso e falta. Segundo, técnicas não supervisionadas de agrupamento podem identificar perfis de clientes, permitindo ofertas personalizadas, e um sistema de recomendação pode sugerir produtos conforme o histórico de cada um. Terceiro, um modelo pode sinalizar cedo o comportamento de abandono no e-commerce, e chatbots podem automatizar o atendimento inicial. Três condições precisam ser cuidadas. A qualidade dos dados vem antes de tudo, porque o modelo aprende exatamente o que os dados mostram: dados incompletos ou enviesados geram previsões erradas. Os modelos precisam estar integrados aos sistemas existentes, para não criar novos silos. E os funcionários devem ser capacitados para interpretar os resultados, pois a decisão continua sendo humana. Do ponto de vista ético, a empresa deve garantir transparência no uso dos dados dos clientes, auditar os modelos para detectar vieses e manter supervisão humana nas decisões sensíveis. Como afirma Gabriel (2021), o futuro do trabalho não é sobre humanos versus máquinas, mas sobre humanos com máquinas: o aprendizado de máquina amplia a capacidade de decisão da equipe, sem substituí-la.',
          rubrica: ['Liguei cada dor do caso a uma aplicação (demanda, estoque, personalização, abandono, atendimento)', 'Usei os termos certos (supervisionado, agrupamento, recomendação, chatbot)', 'Tratei a qualidade dos dados como condição', 'Falei de integração com os sistemas e de capacitação das pessoas', 'Incluí ética: transparência, auditoria de viés, supervisão humana', 'Fechei com a ideia de que a IA apoia a decisão humana (e citei um autor)'],
        },
        { t: 'feynman', prompt: 'Em duas frases: o que a Comercial Alpha precisa ter ANTES de qualquer modelo de IA funcionar bem?' },
      ],
    },
  ],
  cards: [...CARDS_EXP.filter((c) => c.regiao === 'c3'), ...cards('exp', 'c3', [
    ['O que é "treinar" um modelo?', 'Ajustar os parâmetros do modelo, pouco a pouco, para diminuir o erro sobre os dados de exemplo.'],
    ['Como a IA generativa produz um texto?', 'Prevê o próximo pedaço mais provável, acrescenta ao texto e repete. Por isso pode escrever bem e errar o fato.'],
    ['O que é um prompt e por que ele importa?', 'O texto que você entrega ao modelo. Ele condiciona a continuação: contexto diferente, resposta diferente.'],
    ['O que é no-code e qual o seu principal impacto?', 'Criar soluções digitais sem escrever código, por arrastar e soltar. Democratiza o desenvolvimento.'],
    ['Regra escrita × modelo aprendido', 'A regra é explícita e auditável, mas rígida. O modelo é flexível, mas opaco: é difícil dizer por que decidiu.'],
    ['Riscos da IA generativa (U6)', 'Autoria e direitos autorais, uso indevido de dados, desinformação e reprodução de vieses. Sempre revisar e validar.'],
    ['Onde o viés algorítmico pesa mais, segundo a U5?', 'Concessão de crédito, seleção de candidatos a emprego e definição de políticas públicas.'],
  ], 12)],
};
