// C4 · O mundo em volta (U1 · Tecnologias Digitais no Cotidiano + U7 · Ecossistemas de Inovação Digital + U8 · Ética e Segurança Digital), do zero.
// Fontes: fontes/exploracao/U1.txt, U7.txt e U8.txt.
// O PDF das unidades não traz gabarito: as respostas das questões da plataforma foram tiradas do próprio texto da unidade.
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, ficha, gen, mcq, multi, texto } from '../ajuda';
import { CARDS_EXP } from './cards';

export const C4: Regiao = {
  id: 'c4', mundo: 'exp', nome: 'O mundo em volta', unidades: 'U1 + U7 + U8', pronto: true,
  tese: 'Onde a tecnologia encosta em gente.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'c4-redes', titulo: 'Aula 1 · Quem escolhe o que você vê', tipo: 'licao', min: 11, resumo: 'Redes sociais do zero: relações, identidade digital, produção de conteúdo e a opinião pública passando por um algoritmo.',
      steps: [
        texto('**O problema.** Você abre uma rede social de manhã. Existem milhares de posts novos de gente que você segue. Você vai ler uns dez. **Quem escolheu esses dez?**\n\nNão foi você, e não foi ninguém em particular. Foi um **critério de ordenação**: uma regra que decide o que sobe e o que afunda. Antes de qualquer definição, mexa nesse critério.'),
        { t: 'toy', toy: 'feed', modo: 'desafio', intro: 'Oito posts, sempre os mesmos. Só a ordem muda. Faça o primeiro desafio.', desafios: ['fd-engaja'] },
        texto('**O que você viu tem nome.** A unidade lista, entre as transformações nas relações humanas, a "**mediação por algoritmos**". *Mediar* é ficar no meio: entre você e os seus amigos existe um sistema que escolhe o que passa.\n\n(*Algoritmo* é uma sequência de passos para resolver um problema. Aqui o problema é "em que ordem mostrar os posts".)\n\nE isso pesa na **opinião pública**, que é o conjunto do que as pessoas de uma sociedade pensam sobre os assuntos comuns. O curso diz que as redes "moldam debates sociais e políticos", e que a velocidade e o alcance podem "**intensificar polarizações, disseminar desinformação ou reforçar vieses**".\n\nNão é só um lado: a influência "reflete tanto o **poder de mobilização coletiva** quanto os **riscos de manipulação informacional**". A defesa que o curso propõe é **senso crítico** e **literacia digital** (saber ler o ambiente digital: de onde veio, quem ganha com isso, se é fato ou opinião).', 'alem', 'A U1 cita a mediação por algoritmos e seus efeitos, mas não explica o mecanismo (ordenar por engajamento). O brinquedo mostra o mecanismo; os números dele são inventados.'),
        ex(multi('c4-q5', 'c4.redes', 'U1 · Avaliando · Questão 5', 'Questão do curso. A influência das redes sociais na opinião pública pode ocorrer quando: (Marque todas as corretas.)', ['Informações se disseminam rapidamente entre os usuários', 'Algoritmos priorizam determinados conteúdos', 'Não há interação entre usuários', 'Opiniões são formadas a partir de conteúdos compartilhados e comentados'], [0, 1, 3], 'Velocidade, priorização por algoritmo e opiniões formadas pelo que circula. Sem interação não há influência: é o distrator.')),
        texto('**De onde veio tudo isso.** Antes das redes, conversar com alguém longe exigia telefonema ou carta. Hoje as relações acontecem em ambientes com "conexão em tempo real" e "atualização contínua". A unidade diz que isso "**redefiniu o conceito de proximidade**": dá para manter laço com quem mora longe.\n\nO preço, segundo a própria unidade: uso excessivo, "busca constante por **validação**" e relações que ficam **superficiais** quando só existem na tela.\n\nA frase que o curso marca como importante, e que serve de tese para qualquer texto: mais do que julgar as redes como boas ou más, importa "**como elas são utilizadas**". O vínculo depende "da **intencionalidade**, do cuidado e da consciência no uso".\n\n**No trabalho**, as redes servem para **networking** (formar rede de contatos), carreira e visibilidade. O LinkedIn foi feito para isso; as outras também são usadas assim.'),
        ex(mcq('c4-q2', 'c4.redes', 'U1 · Avaliando · Questão 2', 'Qual é um dos principais papéis das redes sociais na construção de relações profissionais?', ['Substituir completamente o contato presencial', 'Facilitar a criação de redes de contato e oportunidades profissionais', 'Eliminar hierarquias no ambiente de trabalho', 'Garantir anonimato total aos usuários'], 1, 'Networking e oportunidades.', { heuristica: '"Completamente", "eliminar", "total": três absolutos, três distratores.' })),
        texto('**Identidade digital.** Procure o seu nome num buscador. O que aparece é a sua **identidade digital**: "a representação de um indivíduo ou organização no ambiente online".\n\nEla é feita de **perfis, interações, conteúdos compartilhados e reputação percebida**. "Cada postagem, comentário ou foto contribui para moldar essa identidade."\n\nDois detalhes que a prova gosta:\n\n- Ela **não é só o cadastro**. Nome, e-mail e data de nascimento são dados; a identidade é o que você **faz** lá.\n- Ela não é "apenas uma extensão virtual da identidade física": é uma "**narrativa pública** que pode ser gerida estrategicamente". O infográfico da unidade fala em "curadoria da imagem", "**rastros digitais**" e no equilíbrio entre "autenticidade e performance social".'),
        ex(mcq('c4-q3', 'c4.redes', 'U1 · Avaliando · Questão 3', 'A identidade digital de um indivíduo nas redes sociais é formada principalmente por:', ['Apenas dados pessoais cadastrados nas plataformas', 'Conteúdos publicados, interações realizadas e comportamento online', 'Informações fornecidas por terceiros sem consentimento', 'Elementos técnicos das plataformas digitais'], 1, 'O que você publica, com quem interage e como se comporta.', { heuristica: '"Apenas" na primeira alternativa já a derruba.' })),
        texto('**Produzir e colaborar.** Antes, falar para muita gente era privilégio de jornal, rádio e TV. Agora "qualquer pessoa pode produzir, compartilhar e amplificar mensagens". O curso chama isso de acesso à audiência **democratizado**, e de **cultura de visibilidade**.\n\nO problema que vem junto: "qualidade da informação", "veracidade dos conteúdos" e o "impacto psicológico do consumo constante".\n\nE as redes viraram lugar de **colaboração**: grupos, comunidades de prática, projetos coletivos e movimentos sociais coordenam ações e "**cocriam** soluções", sem depender de estarem no mesmo lugar.'),
        ex(multi('c4-q4', 'c4.redes', 'U1 · Avaliando · Questão 4', 'Quais práticas contribuem para uma produção de conteúdo responsável e colaborativa nas redes sociais? (Marque todas as corretas.)', ['Verificar a veracidade das informações antes de compartilhar', 'Incentivar o diálogo respeitoso e a troca de ideias', 'Publicar conteúdos ofensivos para aumentar engajamento', 'Reconhecer e citar fontes utilizadas', 'Estimular a colaboração entre usuários'], [0, 1, 3, 4], 'Todas menos a do conteúdo ofensivo. Repare que ela descreve justamente o que o feed por engajamento premia.')),
        ficha({
          titulo: 'Redes sociais: a ficha',
          porque: 'Boa parte do que as pessoas sabem do mundo hoje chega por um feed. Entender quem ordena o feed é entender de onde vem a opinião.',
          ideia: 'Redes são espaços de relação, de identidade, de produção de conteúdo e de colaboração, mediados por algoritmos que decidem o que ganha visibilidade.',
          regra: '$$\\text{identidade digital} = \\text{conteúdos} + \\text{interações} + \\text{comportamento online}$$',
          exemplo: 'Networking no LinkedIn; um boato que alcança milhares em minutos; um grupo que organiza um mutirão pelo aplicativo.',
          armadilha: 'Tratar a rede como boa ou má em si. A posição do curso é que depende de como é usada; e absolutos ("substituir completamente", "anonimato total") são distratores.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'c4-cidade', titulo: 'Aula 2 · O celular, a loja e a cidade', tipo: 'licao', min: 12, resumo: 'Aplicativos como tecnologias cognitivas, comércio eletrônico, Internet das Coisas, trabalho remoto e o profissional do futuro.',
      steps: [
        texto('**O problema.** Conte quantas coisas você resolveu pelo celular esta semana: pagar, pedir comida, ver o caminho, marcar consulta, estudar. Há dez anos, cada uma era um lugar diferente para ir.\n\nA unidade diz que os aplicativos "deixaram de ser ferramentas acessórias e passaram a ocupar um **papel central**". As cinco áreas que ela cita (decore a lista, cai): **serviços financeiros, saúde, educação, transporte e produtividade**.'),
        texto('**Tecnologias cognitivas.** A palavra nova desta aula. *Cognitivo* vem de *cognição*: o ato de conhecer, pensar, decidir.\n\nUm aplicativo de mapa não só mostra a rua: ele compara rotas, prevê trânsito e **recomenda** uma. Ele faz uma parte do **pensar** por você. O curso, citando **Akabane (2018)**, chama isso de **tecnologia cognitiva**: sistemas que "processam informações, aprendem com dados e auxiliam na tomada de decisões".\n\nA citação direta para guardar: "as tecnologias cognitivas **ampliam a capacidade humana de análise, aprendizado e decisão**, tornando-se elementos estratégicos para indivíduos e organizações" (AKABANE, 2018).\n\nRepare no verbo: **ampliam**. Não substituem. Os aplicativos de produtividade são descritos como "**extensões da capacidade cognitiva humana**".\n\nOs desafios que a unidade lista para os aplicativos: **dependência tecnológica**, **gestão da privacidade** e necessidade de **competências digitais**.'),
        ex(cheque('c4-k01', 'c4.apps', 'Segundo Akabane (2018), o que as tecnologias cognitivas fazem com a capacidade humana de análise e decisão?', ['Ampliam', 'Substituem por completo', 'Tornam desnecessária'], 0, 'Ampliam. É a mesma linha de toda a disciplina: a tecnologia apoia, a pessoa decide.')),
        texto('**Comércio eletrônico.** *E-commerce* é comprar e vender por plataformas digitais. A unidade diz que ele passou "de uma alternativa ao comércio tradicional para um **eixo central da economia digital**".\n\nAs cinco peças que o curso manda analisar:\n\n1. **Consumo digital**: o consumidor fica mais ativo. Compara preços, lê avaliações, fala direto com a marca. Rompem-se "barreiras geográficas e temporais": compra-se a qualquer hora, de qualquer lugar.\n2. **Meios de pagamento** digitais e a segurança das transações.\n3. **Logística**: a entrega vira parte estratégica da satisfação.\n4. **Experiência do usuário (UX)**: facilidade de uso, clareza, rapidez, atendimento. "Pequenas falhas na experiência podem resultar na perda de consumidores." A UX "deixa de ser um aspecto técnico e passa a ser um **elemento estratégico**".\n5. **Mercado de trabalho**: surgem profissões (dados, marketing digital, logística, atendimento online) e funções do comércio físico são "transformadas ou reduzidas", exigindo **requalificação**.\n\nO autor citado aqui é **Morais**: a transformação digital "coloca o **cliente no centro** das decisões estratégicas".'),
        texto('**Internet das Coisas (IoT).** Até aqui, quem estava na internet eram pessoas com seus aparelhos. Na **IoT** (*Internet of Things*), quem se conecta são **objetos**: sensores, semáforos, máquinas, medidores, cada um enviando e recebendo dados.\n\nDefinição do curso: "por meio da conexão de sensores, dispositivos e sistemas inteligentes, a IoT permite o **monitoramento e a automação de processos em tempo real**".\n\nNuma cidade, isso dá a **cidade inteligente**: dados usados "para otimizar o trânsito, o consumo de energia, a segurança e os serviços públicos".\n\nNo trabalho: acompanhar a produção à distância e fazer **manutenção preditiva** (o sensor avisa que a máquina vai falhar antes de ela falhar).'),
        ex(mcq('c4-r-iot', 'c4.mobilidade', 'U1 · Tópico 4 · questão sobre IoT e cidades inteligentes', 'A partir do conceito de Internet das Coisas (IoT) aplicado às cidades inteligentes, qual alternativa melhor representa o principal objetivo dessa integração tecnológica?', ['Automatizar exclusivamente os sistemas industriais, sem impacto direto na vida urbana.', 'Substituir totalmente a atuação humana na gestão das cidades por sistemas digitais autônomos.', 'Conectar dispositivos, serviços e infraestruturas urbanas para otimizar recursos, mobilidade e serviços públicos.', 'Garantir apenas maior velocidade de conexão à internet para os moradores das cidades.'], 2, 'Conectar para otimizar.', { heuristica: '"Exclusivamente", "totalmente", "apenas": os três distratores têm absoluto.' })),
        texto('**Trabalho remoto e o futuro do trabalho.** Com tecnologias móveis, nuvem e plataformas colaborativas, o trabalho deixou de depender de um lugar fixo. O curso chama isso de **mobilidade digital**, e a conexão permanente de **ubiquidade da conectividade** (*ubíquo* = que está em todo lugar).\n\n**Ganhos**: menos deslocamento, mais autonomia, conciliar vida pessoal e profissional.\n\n**Custos**, em três frentes que a unidade lista:\n\n- **Gestão de equipes**: sem supervisão presencial, é preciso coordenar de outro jeito.\n- **Engajamento e saúde mental**: isolamento, sobrecarga, dificuldade de desconectar.\n- **Processos e liderança**: liderança baseada em "**confiança, autonomia e resultado**".\n\nSoma-se a isso a **sobrecarga informacional** e a "diluição das fronteiras entre vida pessoal e profissional".\n\n**Martha Gabriel (2021)**, citação direta: "o profissional do futuro será aquele capaz de **aprender continuamente, adaptar-se às mudanças e colaborar com tecnologias inteligentes**".\n\nE **Schmidt, Huttenlocher e Kissinger (2023)**: "a inteligência artificial não é apenas mais uma ferramenta, mas uma tecnologia que **redefine a relação entre humanos, conhecimento e poder**".'),
        gen('c4.cotidiano', 2),
        texto('**Quem fica de fora.** A unidade fecha com os desafios sociais: **desigualdade de acesso**, **exclusão digital**, **precarização** de algumas formas de trabalho, e os debates sobre **privacidade, vigilância e uso de dados pessoais**.\n\nA frase do curso: o impacto da IA "será desigual se não houver **políticas públicas** e estratégias institucionais voltadas à **inclusão**".'),
        ex(multi('c4-q1', 'c4.mobilidade', 'U1 · Avaliando · Questão 1', 'Questão do curso. Quais cuidados éticos e de segurança devem ser observados no uso das tecnologias digitais? (Marque todas as corretas.)', ['Proteção de dados e privacidade', 'Segurança da informação', 'Transparência e responsabilidade', 'Inclusão digital e acessibilidade'], [0, 1, 2, 3], 'As quatro são cuidados que a unidade defende, e nenhuma é um distrator.', { selo: 'confira', seloNota: 'No PDF, esta questão aparece com bolinhas de alternativa única, mas as quatro opções estão corretas segundo o texto da unidade. Aqui ela foi tratada como "marque todas". Confira na plataforma como ela é corrigida.' })),
        ex(mcq('c4-q6', 'c4.redes', 'U1 · Avaliando · Questão 6', 'Assinale a alternativa correta sobre Tecnologias Digitais no Cotidiano:', ['Relações pessoais e profissionais: conjunto de interações e conexões estabelecidas entre usuários', 'Identidade digital: criação e compartilhamento de textos, imagens e vídeos', 'Produção de conteúdo: trabalho coletivo e troca de conhecimentos entre usuários', 'Colaboração nas redes sociais: forma como o indivíduo se apresenta e é percebido no ambiente digital'], 0, 'As outras três estão com as definições trocadas em roda: "criação e compartilhamento" é produção de conteúdo; "trabalho coletivo" é colaboração; "como o indivíduo se apresenta" é identidade digital.', { heuristica: 'Questão de "definições trocadas": ache a única em que nome e descrição combinam. Este formato se repete em quase toda unidade.' })),
        ficha({
          titulo: 'Tecnologia no cotidiano: a ficha',
          porque: 'É a unidade que dá o vocabulário para descrever qualquer cenário da A3: aplicativo, e-commerce, IoT, trabalho remoto, inclusão.',
          ideia: 'Aplicativos e sensores passaram a mediar decisões do dia a dia. Eles ampliam a capacidade das pessoas, mudam o trabalho e deixam gente de fora se não houver inclusão.',
          regra: '$$\\text{tecnologia cognitiva: amplia } (\\text{análise} + \\text{aprendizado} + \\text{decisão})$$',
          exemplo: 'Akabane (2018): tecnologias cognitivas. Gabriel (2021): o profissional do futuro aprende continuamente. IoT: conectar para otimizar recursos, mobilidade e serviços públicos.',
          armadilha: 'Alternativas dizendo que a tecnologia "substitui totalmente" o humano ou resolve "apenas" uma coisa.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'c4-ecossistema', titulo: 'Aula 3 · Ninguém inova sozinho', tipo: 'licao', min: 10, resumo: 'O que é um ecossistema de inovação, quem são os atores e o que cada um traz, e a cultura que segura tudo.',
      steps: [
        texto('**O problema.** Uma pessoa tem uma boa ideia de aplicativo na sua cidade. O que falta para a ideia virar empresa?\n\nFalta **gente que saiba programar** (alguém formou essas pessoas). Falta **dinheiro** para os primeiros meses. Falta **regra clara** para abrir a empresa e internet que funcione. Falta **quem já errou antes** para aconselhar. Faltam **clientes grandes** dispostos a testar.\n\nNenhuma dessas coisas depende de quem teve a ideia. A inovação precisa de um **ambiente**.'),
        texto('**Ecossistema de inovação.** A palavra vem da biologia: numa floresta, árvore, fungo, inseto e chuva dependem uns dos outros. Tire um e os outros sofrem.\n\nDefinição do curso: "o conjunto de **atores, instituições, recursos e relações** que, em um determinado contexto, favorecem a **criação e a difusão de inovações**". A metáfora enfatiza a **interdependência**: "o sucesso de uma inovação depende da saúde e do equilíbrio do sistema como um todo".\n\nO contraste que a unidade faz: o modelo antigo era centrado "em grandes empresas ou laboratórios **isolados**"; o ecossistema valoriza "**abertura, colaboração e compartilhamento** de conhecimento". A tecnologia digital é o "**elemento integrador**".\n\nEle existe em várias escalas: de um polo tecnológico local a redes globais.'),
        ex(mcq('c4-q7', 'c4.ecossistema', 'U7 · Avaliando · Questão 1', 'Questão do curso. Um ecossistema de inovação digital pode ser definido como:', ['Um conjunto isolado de empresas de tecnologia', 'Um ambiente colaborativo que integra startups, empresas, universidades, governo e sociedade', 'Apenas espaços físicos de coworking', 'Um mercado exclusivamente voltado para comércio eletrônico'], 1, 'Colaboração entre atores diferentes. "Isolado" é o oposto exato da ideia.', { heuristica: '"Isolado", "apenas", "exclusivamente": os distratores negam a colaboração.' })),
        texto('**Os atores e o que cada um traz.** A lista que a unidade repete: **startups, empresas consolidadas, universidades, governo e investidores** (em alguns trechos entram também a **sociedade civil** e os **usuários**).\n\n- **Startups**: criam **soluções inovadoras e novos modelos de negócio**.\n- **Universidades e instituições de pesquisa**: **formam profissionais qualificados e produzem conhecimento**.\n- **Governo**: **políticas públicas e incentivo** à inovação.\n- **Investidores**: o capital para a ideia sobreviver até dar retorno.\n- **Empresas consolidadas**: mercado, experiência e **inovação aberta** (buscar inovação fora de casa, em parceria com startups).\n- **Hubs tecnológicos**: **integram** os atores, oferecem infraestrutura e apoiam o empreendedorismo.', 'confira', 'No texto extraído, os quatro cartões de atores (startups, universidades, governo, investidores) vieram só com o título. As contribuições acima são as que a própria unidade usa na questão "Quizz 05" e no estudo de caso; a de investidores e a de empresas consolidadas foram completadas a partir do restante do texto. Confira os cartões na plataforma.'),
        gen('c4.ator', 2),
        ex(mcq('c4-q11', 'c4.ecossistema', 'U7 · Avaliando · Quizz 05', 'Analise a alternativa correta sobre os atores do ecossistema e as suas contribuições:', ['Startups: criação de soluções inovadoras e novos modelos de negócio', 'Universidades: formulação de políticas públicas e incentivo à inovação', 'Governo: integração de atores, infraestrutura e apoio ao empreendedorismo', 'Hubs tecnológicos: formação de profissionais qualificados e produção de conhecimento'], 0, 'De novo as definições em roda: políticas públicas são do governo; integrar atores é do hub; formar profissionais é da universidade.')),
        texto('**Cultura de inovação.** Atores juntos não bastam: é preciso um jeito de pensar. A unidade o descreve assim: valorização "da **criatividade, da experimentação e do aprendizado contínuo**".\n\nA frase mais citável: "o **erro é compreendido como parte do processo de aprendizado**, e não como fracasso definitivo".\n\nE a diversidade conta: "a diversidade de perspectivas estimula soluções mais criativas e eficazes".\n\n**Rogers**, outra vez. A citação que atravessa a disciplina reaparece aqui: "a transformação digital **não é sobre tecnologia, mas sobre estratégia**" (ROGERS, 2017). E, segundo ele, a mudança desloca o foco "de ativos físicos para **redes, plataformas e capacidades digitais**".'),
        ex(mcq('c4-r-morais', 'c4.ecossistema', 'U7 · Estudo guiado (Morais, p. 28 a 45)', 'Qual alternativa melhor expressa o conceito de Transformação Digital?', ['A simples digitalização de documentos e adoção de computadores nos setores administrativos.', 'A substituição completa de funcionários por tecnologias automatizadas para reduzir custos operacionais.', 'A incorporação estratégica de tecnologias digitais para redefinir modelos de negócio, processos e a proposta de valor ao cliente.', 'A criação de um setor exclusivo de TI responsável por todas as decisões tecnológicas da empresa.'], 2, 'É a mesma distinção da camada C2: digitalizar documentos não é transformar. Transformar é redefinir modelo de negócio, processos e valor.', { heuristica: '"Simples", "completa", "exclusivo", "todas": os três distratores se entregam.' })),
        texto('**O que trava um ecossistema.** A unidade lista: **desigualdades regionais**, **falta de acesso a financiamento**, **carência de infraestrutura digital** e **barreiras regulatórias**. E um alerta: a concentração da inovação em poucos polos "pode **aprofundar desigualdades** socioeconômicas".\n\nA saída proposta: "políticas inclusivas e estratégias colaborativas".'),
        ficha({
          titulo: 'Ecossistema de inovação: a ficha',
          porque: 'Explica por que algumas regiões geram empresas novas e outras não, mesmo havendo gente com boas ideias nas duas.',
          ideia: 'Inovação é resultado da interação entre atores que dependem uns dos outros, sustentada por uma cultura que aceita experimentar e errar.',
          regra: '$$\\text{startups} + \\text{universidades} + \\text{governo} + \\text{investidores} + \\text{empresas} \\;\\to\\; \\text{inovação}$$',
          exemplo: 'Polo Digital Nova Esperança: prefeitura, universidades, empresas e incubadoras criando empregos numa cidade que perdia os jovens.',
          armadilha: 'Trocar as contribuições: política pública é do governo, conhecimento é da universidade, integração é do hub.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'c4-startups', titulo: 'Aula 4 · Da ideia à escala', tipo: 'licao', min: 12, resumo: 'O que é uma startup, os quatro estágios, o MVP, os ambientes de apoio e por que negócio digital escala.',
      steps: [
        texto('**O problema.** Uma padaria nova e um aplicativo novo são, os dois, empresas pequenas. Só o segundo costuma ser chamado de **startup**. Por quê?\n\nA diferença não é o tamanho nem a tecnologia. A padaria **já sabe** como ganha dinheiro: faz pão, vende pão. O aplicativo ainda **não sabe** se alguém vai querer, quanto pagaria, nem como cobrar. Ele está **procurando** um modelo de negócio.\n\nDefinição da unidade: startups são "organizações criadas para desenvolver produtos ou serviços inovadores em ambientes caracterizados por **elevada incerteza**". Elas não nascem com modelo de negócio definido, "mas com **hipóteses** que precisam ser testadas, validadas e ajustadas".\n\n(*Hipótese* é um palpite que ainda precisa de prova. *Modelo de negócio* é o jeito como a empresa cria valor e ganha dinheiro com isso.)'),
        ex(mcq('c4-r-reis', 'c4.startups', 'U7 · Estudo guiado (Reis, Startups, p. 8 a 18)', 'Questão do curso. Qual alternativa melhor define o conceito de startup?', ['Uma empresa tradicional de pequeno porte com atuação local e modelo de negócio consolidado.', 'Uma organização criada para operar em condições de extrema certeza e estabilidade de mercado.', 'Uma organização temporária em busca de um modelo de negócio inovador, escalável e repetível.', 'Uma empresa voltada exclusivamente ao desenvolvimento de aplicativos tecnológicos.'], 2, '"Temporária" porque, quando acha o modelo, deixa de ser startup e vira empresa. "Escalável": cresce sem o custo crescer junto. "Repetível": dá para vender de novo e de novo do mesmo jeito.')),
        texto('**Os quatro estágios.** O ciclo de vida que a unidade descreve:\n\n1. **Ideação**: surge a ideia, a partir de um **problema real**. Foco em pesquisa, público-alvo e **proposta de valor**.\n2. **Validação**: cria-se o **MVP** e testa-se com **usuários reais**. O objetivo é saber se a solução atende e se há "disposição para utilizá-la ou pagá-la".\n3. **Tração**: crescimento da base de clientes, aumento da receita, consolidação do modelo.\n4. **Escala**: expansão, "muitas vezes em nível nacional ou internacional", com tecnologia e automação.\n\n**MVP** (*Minimum Viable Product*, Produto Mínimo Viável) é a versão mais simples do produto que já permite aprender algo com clientes de verdade. O método por trás chama-se **lean startup** (startup enxuta): "experimentação contínua, **aprendizado validado** e adaptação rápida ao mercado".'),
        gen('c4.estagio', 2),
        { t: 'toy', toy: 'escala', modo: 'desafio', intro: 'Uma loja de bairro e um aplicativo, lado a lado. Aumente os clientes e observe o custo de cada cliente.', desafios: ['es-vira', 'es-milhao', 'es-mvp'] },
        texto('**Escalabilidade.** O que você viu é a definição do curso: "os negócios digitais podem **crescer rapidamente sem aumento proporcional de custos**". No resumo final da unidade: modelos "capazes de crescer com **custos marginais reduzidos**" (*custo marginal* é o custo de atender **um cliente a mais**).\n\nO que torna isso possível: infraestrutura em nuvem, automação de processos e modelos de negócio **replicáveis**.\n\nO preço, que a unidade faz questão de registrar: crescer rápido "exige **governança** adequada, **segurança da informação**, conformidade regulatória e gestão eficiente de dados".\n\n**Plataformas e economia de dados.** Uma **plataforma digital** é uma infraestrutura que põe dois ou mais lados para interagir (motorista e passageiro, loja e cliente), "reduzindo custos de transação". De passagem, ela coleta dados de todo mundo. Daí a **economia de dados**: "a informação se torna um **ativo estratégico**".', 'alem', 'Os números do brinquedo são inventados. A U7 afirma a escalabilidade e os custos marginais reduzidos, mas não traz conta nenhuma.'),
        ex(mcq('c4-q8', 'c4.startups', 'U7 · Avaliando · Questão 2', 'Qual é o principal papel das startups em um ecossistema de inovação digital?', ['Reproduzir modelos de negócio tradicionais', 'Reduzir a concorrência no mercado', 'Desenvolver soluções inovadoras e escaláveis', 'Substituir empresas consolidadas'], 2, 'Inovadoras e escaláveis: as duas palavras da definição.')),
        texto('**Onde as startups crescem.** Os ambientes de apoio:\n\n- **Incubadoras**: para startups em **estágio inicial**. Ajudam a transformar ideia em negócio viável, com suporte técnico, capacitação gerencial, mentorias, orientação jurídica e, às vezes, espaço físico.\n- **Parques tecnológicos**: reúnem empresas, startups, universidades e centros de pesquisa num mesmo ambiente, para **transferência de conhecimento** e inovação de alto valor.\n- **Hubs de inovação**: "espaços mais **flexíveis e abertos**", que conectam empreendedores, investidores, corporações e instituições públicas. Estimulam **cocriação** e **inovação aberta**.\n- **Aceleradoras**: aparecem no título do tópico e na questão abaixo.', 'confira', 'O texto extraído da U7 não traz o parágrafo que define as aceleradoras. Fora do curso, o uso comum é: programas curtos e intensivos para startups que já têm produto e querem crescer rápido, geralmente com investimento. Confira na plataforma.'),
        ex(multi('c4-q9', 'c4.startups', 'U7 · Avaliando · Questão 3', 'Quais elementos são característicos de hubs tecnológicos dentro de ecossistemas de inovação digital? (Marque todas as corretas.)', ['Incubadoras e aceleradoras de startups', 'Parcerias com universidades e centros de pesquisa', 'Ambientes colaborativos e redes de mentoria', 'Isolamento entre empresas para evitar concorrência', 'Acesso a investimentos e capital de risco'], [0, 1, 2, 4], 'Tudo que conecta. O "isolamento" contradiz a própria ideia de hub.')),
        texto('**O que o ecossistema devolve à região.** Os impactos socioeconômicos que a unidade lista:\n\n- **Desenvolvimento econômico**: produtividade, novos mercados, **diversificação** da economia.\n- **Geração de empregos** qualificados, em perfis multidisciplinares.\n- **Novas formas de trabalho**: remoto, por projetos, empreendedorismo digital.\n- **Inclusão social**, com uma ressalva firme: "a inclusão **não ocorre de forma automática**". Depende de infraestrutura, educação e políticas públicas.\n- **Transformação regional**: revitalizar regiões e **reter talentos**, reduzindo a migração para os grandes centros.\n\nE o lado ruim: o avanço pode "ampliar desigualdades, **concentrar renda e poder** econômico".'),
        ex(multi('c4-q10', 'c4.impactos', 'U7 · Avaliando · Questão 4', 'Os impactos socioeconômicos positivos de ecossistemas de inovação digital incluem: (Marque todas as corretas.)', ['Geração de empregos qualificados', 'Estímulo ao empreendedorismo local', 'Redução do acesso à tecnologia', 'Desenvolvimento econômico regional', 'Inovação em serviços digitais'], [0, 1, 3, 4], 'Reduzir o acesso à tecnologia não é impacto positivo, nem é o que acontece.')),
        ficha({
          titulo: 'Startups e escala: a ficha',
          porque: 'É o vocabulário de quem trabalha com tecnologia: MVP, validação, tração, escala. E explica por que negócios digitais crescem tão depressa.',
          ideia: 'Uma startup é uma busca: testa hipóteses até achar um modelo de negócio que possa ser repetido e ampliado sem o custo crescer junto.',
          regra: '$$\\text{ideação} \\to \\text{validação (MVP)} \\to \\text{tração} \\to \\text{escala}$$',
          exemplo: 'Incubadora apoia o começo; parque tecnológico transfere conhecimento; hub conecta todo mundo.',
          armadilha: 'Achar que startup é "empresa pequena de tecnologia". A definição é: organização temporária em busca de um modelo inovador, escalável e repetível.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 5
    {
      id: 'c4-etica', titulo: 'Aula 5 · O algoritmo não é neutro', tipo: 'licao', min: 11, resumo: 'Por que "é matemática, logo é imparcial" está errado, os três dilemas éticos da U8 e os quatro pilares da governança.',
      steps: [
        texto('**O problema.** Um banco decide quem recebe empréstimo. Antes, um gerente decidia, e todo mundo sabia que gerente tem preferências. O banco troca o gerente por um sistema que dá uma **nota** a cada pessoa e aprova quem passa de um **corte**.\n\nA propaganda diz: "agora a decisão é **imparcial**, porque é feita por matemática".\n\nSerá? Você vai regular esse sistema.'),
        { t: 'toy', toy: 'vies', modo: 'desafio', intro: 'Dois bairros, oito pessoas em cada. Você controla a nota de corte. Faça os dois primeiros desafios.', desafios: ['vi-mesma', 'vi-paridade'] },
        texto('**Por que a neutralidade é um equívoco.** A frase central da U8:\n\n"Embora os algoritmos operem a partir de modelos estatísticos e lógicos, suas decisões são condicionadas pelos **dados de entrada**, pelos **critérios de otimização** definidos e pelas **finalidades institucionais** para as quais são concebidos. Dessa forma, a suposta neutralidade tecnológica **revela-se um equívoco**."\n\nTrês portas por onde entram valores humanos. Você passou pelas três:\n\n1. **Dados de entrada.** A nota do bairro B era menor porque o histórico era pior. O sistema herdou o passado.\n2. **Critérios de otimização.** O que o sistema tenta acertar? Evitar calote a qualquer custo, ou não recusar quem pagaria? São objetivos diferentes, e alguém escolhe.\n3. **Finalidades.** Para que a instituição quer o sistema: lucrar mais, emprestar para mais gente, cortar funcionários?\n\nNenhuma das três é decisão da máquina.\n\nA U7 traz a mesma ideia na voz de **Martha Gabriel (2021, p. 39)**: "**a tecnologia não é neutra: ela reflete valores humanos e amplifica tanto nossos acertos quanto nossos erros**".'),
        { t: 'toy', toy: 'vies', modo: 'desafio', intro: 'Agora tente ser justo dos dois jeitos ao mesmo tempo.', desafios: ['vi-impossivel'] },
        texto('**O que esse impossível ensina.** Quando duas ideias razoáveis de justiça não cabem juntas, **escolher entre elas é uma decisão ética**, e não técnica. Se ninguém a toma de forma consciente, ela é tomada por omissão, por quem programou.', 'alem', 'A U8 afirma que o algoritmo não é neutro, mas não mostra este conflito entre "mesma regra" e "mesmo resultado". Ele entra porque é o exemplo mais simples de que configurar um sistema é escolher valores.'),
        texto('**Os três dilemas éticos da U8.** A unidade destaca:\n\n1. **Vieses discriminatórios**: algoritmos "podem reproduzir preconceitos existentes nos dados", com decisões injustas que atingem **grupos vulneráveis**.\n2. **Privacidade dos dados**: a coleta para alimentar a IA levanta a questão do **consentimento informado** (a pessoa sabe e concorda?).\n3. **Desinformação**: informações falsas ou manipuladas, agora potencializadas por sistemas que geram conteúdo.\n\nOnde o risco é maior, segundo a unidade: **recrutamento, avaliação de desempenho, concessão de crédito e análise de riscos**. E o perigo específico: a "**dependência excessiva de decisões automatizadas, sem supervisão humana**", que leva a "injustiças sistemáticas" e à "dificuldade de **atribuição de responsabilidades**".\n\nOutros três riscos nomeados: **concentração de poder informacional**, **opacidade dos algoritmos** e **assimetria informacional** (um lado sabe muito sobre o outro, e o outro não sabe nada).'),
        ex(mcq('c4-q12', 'c4.etica', 'U8 · Quiz diagnóstico · Questão 1', 'Questão do curso. No contexto da ética e da segurança digital, qual é o principal desafio associado ao uso atual de algoritmos e inteligência artificial?', ['A completa autonomia dos sistemas, que dispensam qualquer supervisão humana.', 'A neutralidade dos algoritmos, que operam sem influência de valores sociais.', 'A necessidade de alinhar inovação tecnológica, responsabilidade ética e supervisão humana diante do uso crescente de decisões automatizadas.', 'A eliminação dos riscos sociais e legais por meio do avanço técnico da inteligência artificial.'], 2, 'Alinhar inovação, ética e supervisão humana. Cuidado com a segunda alternativa: ela afirma que os algoritmos SÃO neutros, o contrário do que a unidade ensina.', { heuristica: '"Completa", "qualquer", "eliminação": absolutos. E a alternativa da neutralidade é a pegadinha conceitual da unidade.' })),
        texto('**Governança: como se cobra um algoritmo.** *Governança* é o conjunto de regras e controles sobre como algo é dirigido. A U8 lista quatro práticas como "**exigências fundamentais**":\n\n- **Transparência**: saber que há um sistema decidindo, e com base em quê.\n- **Auditabilidade**: alguém de fora consegue examinar o sistema e seus resultados.\n- **Explicabilidade**: dá para explicar por que **esta** decisão saiu assim.\n- **Responsabilização**: há alguém que responde quando dá errado.\n\nE a exigência que amarra tudo: "**governança, regulação e supervisão humana contínua**".\n\nPor fim, a unidade pede uma visão **interdisciplinar**: conhecimentos "técnicos, jurídicos, organizacionais e éticos". Ética digital não é assunto só de programador.', 'alem', 'A U8 dá os quatro nomes sem defini-los um a um. As descrições curtas são as de uso corrente.'),
        ex(cheque('c4-k02', 'c4.etica', 'Segundo a U8, as decisões de um algoritmo são condicionadas por três coisas. Quais?', ['Dados de entrada, critérios de otimização e finalidades institucionais', 'Hardware, software e rede', 'Entrada, processamento e saída'], 0, 'As três portas por onde entram valores humanos.')),
        ficha({
          titulo: 'Ética e algoritmos: a ficha',
          porque: 'Decisões sobre crédito, emprego e serviços públicos já passam por sistemas automáticos. Saber onde os valores entram é saber onde cobrar.',
          ideia: 'Um algoritmo faz contas, mas os dados, o objetivo e a finalidade foram escolhidos por pessoas. Por isso ele não é neutro e precisa de governança e supervisão humana.',
          regra: '$$\\text{governança} = \\text{transparência} + \\text{auditabilidade} + \\text{explicabilidade} + \\text{responsabilização}$$',
          exemplo: 'Um modelo de crédito treinado com histórico desigual dá nota menor a um bairro inteiro.',
          armadilha: 'A alternativa "os algoritmos são neutros, pois operam sem influência de valores". Em toda questão desta unidade, ela é o erro.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 6
    {
      id: 'c4-lgpd', titulo: 'Aula 6 · Dado pessoal tem dono', tipo: 'licao', min: 11, resumo: 'A LGPD pelos seus princípios, cidadania digital, e como se previnem as ameaças digitais.',
      steps: [
        texto('**O problema.** A farmácia pede o seu CPF "para dar o desconto". O aplicativo de lanterna pede acesso aos seus contatos. O cadastro da promoção pergunta a sua renda.\n\nTrês perguntas que quase ninguém faz: **para que** querem isso? **Precisam** mesmo disso? O que **mais** vão fazer com isso?\n\nNo Brasil, essas perguntas têm resposta em uma lei de 2018.'),
        texto('**A LGPD.** A **Lei Geral de Proteção de Dados** é a **Lei nº 13.709/2018**. Ela "estabelece normas para o **tratamento de dados pessoais**, garantindo direitos fundamentais de **liberdade e privacidade**".\n\n(*Dado pessoal* é qualquer informação que identifica uma pessoa ou permite identificá-la. *Tratamento* é tudo o que se faz com o dado: coletar, guardar, usar, compartilhar, apagar.)\n\nO que a lei tenta equilibrar, nas palavras da unidade: "o **potencial econômico** e tecnológico da informação com a preservação dos **direitos fundamentais** dos indivíduos".\n\nQuem fiscaliza: a **ANPD** (Autoridade Nacional de Proteção de Dados), "órgão regulador brasileiro responsável pela aplicação da LGPD".\n\nA unidade cita **seis princípios**, em duas listas: **finalidade, necessidade, adequação, transparência, segurança e responsabilização**. Monte um cadastro e veja cada um acender.'),
        { t: 'toy', toy: 'lgpd', modo: 'desafio', intro: 'O cadastro do ministério de louvor. Ele existe para avisar a escala da semana. Faça os dois primeiros desafios.', desafios: ['lg-minimo', 'lg-desvio'] },
        texto('**Os seis princípios, um por um.**\n\n- **Finalidade**: o dado é coletado para um **propósito específico, legítimo e informado**. "Pode ser útil um dia" não vale.\n- **Adequação**: o que se faz com o dado é **compatível** com a finalidade informada.\n- **Necessidade**: coleta-se **o mínimo** para aquela finalidade. A unidade usa também a palavra **minimização**.\n- **Transparência**: a pessoa recebe informação **clara** sobre o que é feito.\n- **Segurança**: medidas **técnicas e administrativas** para proteger os dados.\n- **Responsabilização**: quem trata os dados precisa **demonstrar** que cumpre a lei e responder por isso.\n\nO que isso muda nas empresas, segundo a U8: rever práticas "historicamente baseadas na **coleta indiscriminada** de informações", e projetar sistemas com a proteção de dados "**desde as etapas iniciais** de desenvolvimento", com **controle de acesso, rastreabilidade e minimização de coleta**.\n\nE o argumento de negócio, com **Rogers (2017)**: a **confiança** vira "elemento estruturante" e demonstrar responsabilidade com dados é "**diferencial competitivo**".', 'alem', 'A U8 nomeia os princípios, mas não define cada um. As definições acima seguem o artigo 6º da LGPD. A unidade também NÃO trata de três assuntos que costumam cair quando se fala da lei: as bases legais do tratamento (artigo 7º, como consentimento e obrigação legal), os direitos do titular (acessar, corrigir, apagar) e as sanções. Se a prova pedir, não está no material.'),
        gen('c4.lgpd', 2),
        texto('**Cidadania digital.** A lei cuida do lado das organizações. O outro lado é seu. **Cidadania digital** é "o exercício consciente dos **direitos e deveres** no uso das tecnologias, respeitando a ética, a privacidade e a segurança de todos os usuários".\n\nA unidade insiste que proteger dados não é "responsabilidade exclusiva das organizações": é "um **processo coletivo**". Na prática: conhecer os próprios direitos, cuidar do que compartilha, **respeitar a privacidade de terceiros** (a foto do outro, o número do outro), reconhecer riscos e "**questionar práticas abusivas**".'),
        texto('**Ameaças e prevenção.** A parte de segurança da U8 é curta e direta. A prevenção exige "a implementação **combinada** de soluções **técnicas** e ações **educativas**".\n\n**Técnicas** (três, decore):\n\n- **Autenticação em múltiplos fatores** (MFA): além da senha, um segundo comprovante, como um código no celular. Se a senha vazar, ainda falta o segundo fator.\n- **Gestão adequada de senhas**: fortes, diferentes para cada serviço, guardadas direito.\n- **Atualização contínua de sistemas**: cada atualização fecha falhas conhecidas.\n\nJuntas, elas "reduzem significativamente a **superfície de ataque**" (o conjunto de pontos por onde alguém pode tentar entrar).\n\n**Educativa**: **programas de conscientização**, para que as pessoas "reconheçam tentativas de **fraude**". A maior parte dos golpes não quebra nenhum sistema: convence alguém a entregar a senha.\n\nA síntese da unidade: a segurança é "um **processo contínuo**, integrado à cultura organizacional", em que "**tecnologia, comportamento humano e responsabilidade institucional** atuam de forma articulada".'),
        ex(mcq('c4-q14', 'c4.lgpd', 'U8 · Quiz diagnóstico · Questão 3', 'Questão do curso. Ao considerarmos a ciência dos dados no contexto organizacional, é correto afirmar que:', ['Os dados possuem apenas função operacional e não interferem em decisões estratégicas.', 'A ciência dos dados está restrita a especialistas técnicos e não impacta a ética digital.', 'Os dados constituem um ativo estratégico, exigindo gestão responsável, segura e alinhada aos objetivos organizacionais.', 'A segurança da informação é um aspecto secundário no uso estratégico dos dados.'], 2, 'Dado é ativo estratégico, e por isso mesmo pede gestão responsável e segura.', { heuristica: '"Apenas", "restrita", "secundário": cada distrator diminui a importância de alguma coisa. A correta soma.' })),
        ex(cheque('c4-k03', 'c4.ameacas', 'A senha de um funcionário vazou, mas o invasor não conseguiu entrar porque o sistema pediu um código enviado ao celular. Que medida funcionou?', ['Autenticação em múltiplos fatores', 'Atualização de sistemas', 'Minimização de coleta'], 0, 'O segundo fator segurou. Sozinha, a senha não basta.')),
        ficha({
          titulo: 'LGPD e segurança: a ficha',
          porque: 'Todo sistema que você vier a construir vai guardar dado de alguém. A lei e as boas práticas dizem o que pode e como proteger.',
          ideia: 'O dado pessoal continua sendo da pessoa. Quem o trata precisa de um propósito, do mínimo necessário, de clareza, de proteção e de alguém que responda.',
          regra: '$$\\text{LGPD (Lei 13.709/2018)}: \\text{finalidade, adequação, necessidade, transparência, segurança, responsabilização}$$',
          exemplo: 'Prevenção: múltiplos fatores, gestão de senhas, atualização de sistemas e conscientização.',
          armadilha: 'Achar que segurança é só comprar tecnologia, ou que proteção de dados é só problema da empresa. A unidade diz: é processo contínuo e coletivo.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB
    {
      id: 'c4-lab', titulo: 'Laboratório · Quatro máquinas e a cidade', tipo: 'lab', min: 11, resumo: 'Os quatro brinquedos de novo, com os desafios que faltaram, e o estudo de caso da U1 para treinar a escrita.',
      steps: [
        { t: 'toy', toy: 'feed', modo: 'desafio', intro: 'De volta ao feed. Agora o modo personalizado.', desafios: ['fd-bolha'] },
        texto('**Do feed à ética.** O que você montou é o que a U8 descreve: sistemas de recomendação e de personalização "exercem influência significativa sobre comportamentos individuais" e, sem regulação ou monitoramento, "podem **limitar a pluralidade informacional, reforçar estereótipos e comprometer a autonomia dos usuários**".\n\nRepare que a U1 e a U8 falam da mesma coisa em pontas opostas do curso: lá como "mediação por algoritmos", aqui como dilema ético.'),
        ex(mcq('c4-q13', 'c4.etica', 'U8 · Quiz diagnóstico · Questão 2', 'Um dos principais desafios éticos do uso atual da inteligência artificial está relacionado:', ['À completa autonomia dos sistemas inteligentes, que já substituíram o julgamento humano.', 'À neutralidade dos algoritmos, que operam sem influência de valores humanos.', 'À necessidade de alinhar inovação tecnológica, responsabilidade ética e supervisão humana diante do uso crescente de decisões automatizadas.', 'À eliminação dos riscos sociais por meio do avanço técnico dos sistemas de IA.'], 2, 'É quase a mesma questão do início da unidade, com outras palavras. A resposta é a mesma: alinhar inovação, ética e supervisão humana.')),
        { t: 'toy', toy: 'lgpd', modo: 'desafio', intro: 'Um cadastro que começou errado em tudo. Conserte.', desafios: ['lg-conforme'] },
        texto('**O estudo de caso da U1: Cidade Viva.** Um município de porte médio investiu em tecnologia: **aplicativo para agendar consultas** na rede pública, **transporte com pagamento eletrônico**, **plataformas de participação cidadã** e **redes sociais institucionais**.\n\n**O que melhorou**: menos filas, deslocamentos e espera; serviços pelo celular; pequenos comerciantes vendendo pelas redes e alcançando mais clientes.\n\n**O que apareceu de problema**: parte da população sem internet ou sem saber usar (**exclusão digital**); preocupação com **privacidade dos dados**; **dependência excessiva** de tecnologia; e **informações falsas** nas redes, afetando a confiança nas instituições.'),
        {
          t: 'escrita', fonte: 'U1 · Estudo de caso: Cidade Viva (treino para a A1 e a A3)',
          prompt: 'É a atividade da unidade: de que forma as tecnologias digitais influenciam positivamente e negativamente o cotidiano das pessoas, e quais estratégias podem ser adotadas para potencializar seus benefícios?',
          modelo: 'As tecnologias digitais influenciam o cotidiano de duas formas opostas, como mostra o caso da Cidade Viva. Do lado positivo, os aplicativos de agendamento de consultas, o transporte com pagamento eletrônico e as plataformas de participação cidadã reduziram filas, deslocamentos e tempo de espera, ampliando o acesso a serviços. No comércio local, as redes sociais e as plataformas digitais permitiram que pequenos empreendedores divulgassem produtos e alcançassem novos clientes. Como afirma Akabane (2018), as tecnologias cognitivas ampliam a capacidade humana de análise, aprendizado e decisão. Do lado negativo, a digitalização revelou quatro problemas. O primeiro é a exclusão digital: quem não tem internet ou não sabe usar as ferramentas fica sem o serviço que antes era presencial. O segundo é a privacidade, pois os sistemas passam a concentrar dados de saúde e de deslocamento dos moradores. O terceiro é a dependência excessiva da tecnologia. O quarto é a desinformação nas redes sociais, que afeta a convivência e a confiança nas instituições. Para potencializar os benefícios, proponho quatro estratégias. Primeira, inclusão digital: pontos de acesso gratuito, capacitação da população e manutenção de canais presenciais para quem precisa. Segunda, proteção de dados conforme a LGPD, coletando apenas o necessário e informando a finalidade. Terceira, educação para o senso crítico e a literacia digital, para que os cidadãos reconheçam conteúdos falsos. Quarta, comunicação institucional transparente nas redes oficiais. Em síntese, a tecnologia não melhora nem piora a cidade por si mesma: o resultado depende de como é implantada, o que confirma a ideia de Rogers (2017) de que a transformação digital não é sobre tecnologia, mas sobre estratégia.',
          rubrica: ['Mostrei os dois lados (positivo e negativo) com exemplos do caso', 'Citei a exclusão digital e propus algo concreto para ela', 'Tratei de privacidade e liguei à LGPD', 'Tratei de desinformação e de senso crítico (literacia digital)', 'Listei estratégias numeradas, e não só problemas', 'Fechei com uma tese e citei um autor do curso'],
        },
        { t: 'toy', toy: 'vies', modo: 'livre', intro: 'Bancada livre do laboratório de viés. Experimente: com o cadeado aberto, qual par de cortes aprova todos os bons pagadores dos dois bairros com o menor número de maus pagadores?' },
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'c4-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 5, resumo: 'A U1, a U7 e a U8 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**U1 · Tecnologias no cotidiano.** **Redes sociais**: relações pessoais e profissionais (networking), **identidade digital** (conteúdos, interações e comportamento; narrativa pública), produção de conteúdo (acesso democratizado; veracidade), colaboração (cocriação) e **opinião pública** (mobilização × desinformação e polarização; mediação por algoritmos; senso crítico e literacia digital). **Aplicativos**: finanças, saúde, educação, transporte, produtividade; são **tecnologias cognitivas** (Akabane, 2018), que ampliam análise, aprendizado e decisão. **E-commerce**: consumo digital, pagamentos, logística, **experiência do usuário** (estratégica), mercado de trabalho (requalificação); Morais: cliente no centro. **IoT**: sensores conectados; cidades inteligentes; manutenção preditiva. **Trabalho remoto**: gestão de equipes, saúde mental, liderança por confiança. Gabriel (2021): aprender continuamente. Desafios: exclusão digital, privacidade, vigilância.'),
        texto('**U7 · Ecossistemas de inovação.** **Ecossistema**: atores, instituições, recursos e relações que favorecem criar e difundir inovações; interdependência; colaboração no lugar do isolamento. **Atores**: startups (soluções e modelos de negócio), universidades (profissionais e conhecimento), governo (políticas e incentivos), investidores (capital), empresas consolidadas (inovação aberta), hubs (integração). **Cultura de inovação**: experimentação; erro como aprendizado. **Startup**: organização temporária em busca de um modelo de negócio inovador, escalável e repetível. **Estágios**: ideação → validação (MVP) → tração → escala. **Lean startup**: aprendizado validado. **Ambientes**: incubadoras (início), aceleradoras, parques tecnológicos (transferência de conhecimento), hubs (abertos, cocriação). **Escalabilidade**: crescer sem aumento proporcional de custos. **Plataformas** e **economia de dados**. **Impactos**: empregos, novas formas de trabalho, inclusão (não automática), transformação regional; riscos de concentração e desigualdade.\n\n**U8 · Ética e segurança.** **Dilemas**: vieses discriminatórios, privacidade, desinformação. **Neutralidade é um equívoco**: dados de entrada, critérios de otimização, finalidades. **Governança**: transparência, auditabilidade, explicabilidade, responsabilização; supervisão humana contínua. **LGPD** (Lei 13.709/2018): finalidade, adequação, necessidade, transparência, segurança, responsabilização; **ANPD**. **Cidadania digital**: direitos e deveres; processo coletivo. **Prevenção**: múltiplos fatores, senhas, atualização, conscientização; segurança como processo contínuo.\n\n**Citações**: Rogers (2017), "não é sobre tecnologia, mas sobre estratégia"; Gabriel (2021, p. 39), "a tecnologia não é neutra…"; Akabane (2018), tecnologias cognitivas; Schmidt, Huttenlocher e Kissinger (2023), a IA "redefine a relação entre humanos, conhecimento e poder".'),
        { t: 'feynman', prompt: 'Sem olhar: explique para alguém da igreja por que um sistema que "só faz conta" pode ser injusto. Use o exemplo dos dois bairros.' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'c4-questoes', titulo: 'Questões da U1, da U7 e da U8', tipo: 'questoes', min: 9, resumo: 'Questões de fixação no estilo da prova, sobre os pontos que as questões oficiais não cobrem.',
      steps: [
        texto('As 17 questões da plataforma destas três unidades já apareceram dentro das aulas e do laboratório. As questões abaixo **não são da plataforma**: escrevi a partir do texto das unidades, no formato das provas, para cobrir o que faltava.'),
        ex(mcq('c4-x1', 'c4.apps', undefined, 'Segundo a U1, o que são tecnologias cognitivas, no sentido de Akabane (2018)?', ['Sistemas que processam informações, aprendem com dados e auxiliam na tomada de decisões, ampliando a capacidade humana', 'Máquinas que pensam sozinhas e dispensam as pessoas', 'Qualquer aparelho ligado à internet', 'Redes sociais usadas para estudar'], 0, 'Ampliam análise, aprendizado e decisão.')),
        ex(mcq('c4-x2', 'c4.apps', undefined, 'Por que a U1 afirma que a experiência do usuário "deixa de ser um aspecto técnico e passa a ser um elemento estratégico"?', ['Porque, num ambiente muito competitivo, pequenas falhas de uso fazem a empresa perder consumidores, e uma boa experiência gera fidelização e vantagem competitiva', 'Porque a experiência do usuário é decidida pelo setor jurídico', 'Porque sites bonitos dispensam logística', 'Porque o consumidor digital não compara preços'], 0, 'UX gera valor, fidelização e vantagem competitiva (Morais).')),
        ex(mcq('c4-x3', 'c4.mobilidade', undefined, 'Qual alternativa reúne desafios do trabalho remoto citados na U1?', ['Gestão de equipes sem supervisão presencial, risco de isolamento e sobrecarga, e necessidade de liderança baseada em confiança e resultado', 'Aumento do tempo de deslocamento e perda de autonomia', 'Fim da necessidade de comunicação entre a equipe', 'Impossibilidade de usar sistemas em nuvem'], 0, 'Gestão de equipes; engajamento e saúde mental; processos e liderança.')),
        ex(mcq('c4-x4', 'c4.startups', undefined, 'O que é um MVP e em qual estágio da startup ele aparece?', ['Produto Mínimo Viável: a versão mais simples que permite testar a solução com usuários reais; aparece na validação', 'Modelo de Vendas Progressivo: aparece na escala', 'Um tipo de investidor: aparece na tração', 'O plano de negócios completo: aparece na ideação'], 0, 'Validação = MVP + teste com usuários reais.')),
        ex(mcq('c4-x5', 'c4.startups', undefined, 'O que significa dizer que um negócio digital é escalável?', ['Que ele pode crescer rapidamente sem aumento proporcional dos custos', 'Que ele tem muitos funcionários', 'Que ele vende apenas para grandes empresas', 'Que ele não precisa de infraestrutura tecnológica'], 0, 'Custos marginais reduzidos: atender mais um cliente custa quase nada.')),
        ex(mcq('c4-x6', 'c4.impactos', undefined, 'Sobre inclusão social nos ecossistemas de inovação, a U7 afirma que:', ['A inclusão não ocorre de forma automática: exige acesso à infraestrutura digital, educação de qualidade e políticas públicas', 'A tecnologia inclui todas as pessoas automaticamente', 'A inclusão é responsabilidade exclusiva das startups', 'Ecossistemas de inovação sempre reduzem desigualdades'], 0, 'A unidade também alerta que a concentração de inovação em poucos polos pode aprofundar desigualdades.', { heuristica: '"Automaticamente", "exclusiva", "sempre": absolutos.' })),
        ex(mcq('c4-x7', 'c4.etica', undefined, 'Quais são as quatro práticas de governança de dados e algoritmos que a U8 chama de "exigências fundamentais"?', ['Transparência, auditabilidade, explicabilidade e responsabilização', 'Confidencialidade, integridade, disponibilidade e autenticidade', 'Ideação, validação, tração e escala', 'Finalidade, necessidade, adequação e consentimento'], 0, 'Cuidado com as outras listas: a segunda é da segurança da informação (U3), a terceira são os estágios da startup, a quarta mistura princípios da LGPD.')),
        ex(mcq('c4-x8', 'c4.lgpd', undefined, 'Um aplicativo de lanterna pede acesso à lista de contatos do usuário. Que princípio da LGPD isso contraria mais diretamente?', ['Necessidade: coleta de dados além do mínimo exigido pela finalidade', 'Segurança: falta de senha', 'Responsabilização: falta de um encarregado', 'Nenhum: o usuário aceitou os termos'], 0, 'Acender a tela não exige saber quem são os seus contatos.')),
        ex(mcq('c4-x9', 'c4.ameacas', undefined, 'Segundo a U8, como se previnem as ameaças digitais?', ['Com a combinação de soluções técnicas (múltiplos fatores, gestão de senhas, atualização de sistemas) e ações educativas de conscientização', 'Apenas com a compra de equipamentos mais modernos', 'Proibindo o uso da internet pelos funcionários', 'Deixando a segurança a cargo exclusivo do setor de TI'], 0, 'Técnica e educação juntas; segurança é processo contínuo e parte da cultura.', { heuristica: '"Apenas", "exclusivo": absolutos.' })),
        ex(mcq('c4-x10', 'c4.lgpd', undefined, 'O que é cidadania digital, segundo a U8?', ['O exercício consciente dos direitos e deveres no uso das tecnologias, respeitando a ética, a privacidade e a segurança de todos os usuários', 'O documento de identidade em formato digital', 'O direito de publicar qualquer coisa sem consequência', 'A obrigação de as empresas protegerem dados, sem participação dos usuários'], 0, 'Direitos e deveres; um processo coletivo, que não é só das organizações.')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'c4-chefe', titulo: 'Chefão final: a Rede Bem Viver', tipo: 'chefe', min: 12, resumo: 'Um cenário organizacional que usa as oito unidades de uma vez, no molde do que a A3 pede.',
      steps: [
        texto('**Por que este chefão é diferente.** A U8 descreve a **A3**: analisar "um **cenário organizacional** caracterizado pelo uso intensivo de tecnologias digitais", com integração de sistemas, grandes volumes de dados, automação e IA apoiando decisões, e os impactos disso em ética e segurança.\n\nO cenário verdadeiro da A3 será dado na plataforma. O que está abaixo é **um cenário de treino, inventado por mim** com esses mesmos ingredientes, para você praticar a costura das oito unidades.\n\n**O cenário.** A **Rede Bem Viver** tem cinco clínicas populares na Grande São Paulo. Cada clínica tem a **sua planilha** de pacientes. A rede **escaneou os prontuários** de papel e anuncia que "fez a transformação digital". Há um **aplicativo de agendamento**, que pede nome, telefone, CPF, renda e localização. Um **modelo de IA**, treinado com o histórico de atendimentos, decide a **prioridade** de cada paciente na fila. Um **chatbot generativo** responde dúvidas de saúde. No mês passado, a senha compartilhada da recepção vazou e a **lista de pacientes com diagnósticos** apareceu na internet.'),
        ex(mcq('c4-b1', 'c4.integracao', 'Cenário de treino · liga com a U4', 'Cinco clínicas, cinco planilhas que não conversam. Que nome o curso dá a esse problema, e qual é a saída?', ['Silos de informação; a saída é integrar os sistemas (por exemplo, com um ERP), para todos verem o mesmo dado', 'Latência; a saída é contratar mais banda', 'Viés algorítmico; a saída é trocar o modelo', 'Escalabilidade; a saída é abrir mais clínicas'], 0, 'Silos: cada setor com a sua versão da verdade. É a U4.', { fixo: true })),
        ex(mcq('c4-b2', 'c4.integracao', 'Cenário de treino · liga com a U2', 'A rede escaneou os prontuários e diz que fez a transformação digital. Está certa?', ['Não: isso é digitalização. Transformação digital redefine processos, modelo de negócio e valor entregue; como diz Rogers, não é sobre tecnologia, mas sobre estratégia', 'Sim: transformação digital é passar o papel para o computador', 'Sim, desde que os arquivos estejam em PDF', 'Não, porque faltou comprar computadores mais novos'], 0, 'Mudou o suporte, e o jeito de trabalhar continuou igual.', { fixo: true })),
        ex(mcq('c4-b3', 'c4.integracao', 'Cenário de treino · liga com a U3', 'A lista de pacientes com diagnósticos apareceu na internet. Qual pilar da segurança da informação foi ferido primeiro?', ['Confidencialidade: informação vista por quem não devia', 'Disponibilidade: o sistema ficou fora do ar', 'Integridade: os dados foram alterados', 'Escalabilidade: o sistema não cresceu'], 0, 'A tríade da U3. Aqui, alguém VIU o que não podia.', { fixo: true })),
        ex(mcq('c4-b4', 'c4.integracao', 'Cenário de treino · liga com a U8', 'A senha da recepção era uma só, compartilhada por todos, e nunca tinha sido trocada. Que conjunto de medidas a U8 recomenda?', ['Autenticação em múltiplos fatores, gestão adequada de senhas, atualização dos sistemas e conscientização das pessoas', 'Trocar o aplicativo por outro mais bonito', 'Aumentar a largura de banda', 'Coletar mais dados dos pacientes'], 0, 'Soluções técnicas e ações educativas, combinadas.', { fixo: true })),
        { t: 'toy', toy: 'lgpd', modo: 'livre', intro: 'Use o cadastro como rascunho: o aplicativo da rede pede nome, telefone, CPF, renda e localização para marcar uma consulta. O que sobra?' },
        ex(mcq('c4-b5', 'c4.integracao', 'Cenário de treino · liga com a U8', 'O aplicativo de agendamento pede renda e localização em tempo real. Que princípios da LGPD estão em jogo?', ['Necessidade (coletar só o mínimo para agendar) e finalidade (dizer para que cada dado serve)', 'Nenhum, pois dado de saúde não é dado pessoal', 'Apenas segurança', 'Escalabilidade e tração'], 0, 'Para marcar consulta não é preciso renda nem localização contínua.', { fixo: true })),
        ex(mcq('c4-b6', 'c4.integracao', 'Cenário de treino · liga com a U5 e a U8', 'O modelo de prioridade passou a pôr no fim da fila os pacientes de dois bairros, porque no histórico eles faltavam mais às consultas. O que está acontecendo?', ['Viés herdado dos dados de entrada; a resposta é governança: transparência, auditabilidade, explicabilidade, responsabilização e supervisão humana', 'Nada: o modelo é matemático, logo é neutro', 'Um problema de latência da rede', 'Falta de um MVP'], 0, 'O histórico tinha uma desigualdade (falta de transporte, por exemplo) e o modelo a transformou em regra.', { fixo: true })),
        ex(mcq('c4-b7', 'c4.integracao', 'Cenário de treino · liga com a U6', 'O chatbot generativo responde dúvidas de saúde sem revisão de ninguém. Qual é o risco, pelo que a U6 ensina?', ['O modelo gera o texto mais provável, e não confere se é verdadeiro: pode dar uma resposta fluente e errada. É preciso revisão humana e validação', 'Nenhum: a IA generativa consulta um banco de respostas médicas', 'O único risco é a resposta demorar', 'O risco é o chatbot aprender a programar'], 0, 'Revisar e validar sempre; em saúde, com mais razão.', { fixo: true })),
        {
          t: 'escrita', fonte: 'Cenário de treino, no molde da A3 descrita na U8',
          prompt: 'Analise a Rede Bem Viver seguindo os quatro pontos que a A3 pede: (1) o papel dos sistemas de informação e da infraestrutura; (2) o uso estratégico de dados, automação e IA; (3) os desafios de privacidade, proteção de dados e segurança; (4) a importância de práticas éticas e responsáveis.',
          modelo: 'A Rede Bem Viver usa muita tecnologia, mas de forma desarticulada, e os seus problemas mostram que tecnologia sem estratégia e sem governança gera risco. Quanto aos sistemas de informação e à infraestrutura, cada clínica mantém uma planilha própria, o que configura silos de informação: não há visão única do paciente, e o mesmo dado existe em versões diferentes. Escanear prontuários foi digitalização, e não transformação digital, pois os processos continuaram os mesmos. A integração dos dados em um sistema único, sustentado por infraestrutura em nuvem com controle de acesso, é a base para qualquer avanço. Quanto ao uso estratégico de dados, automação e IA, a rede já possui o insumo, que são os dados, e um modelo que define prioridades de atendimento. Esse uso pode melhorar a fila, desde que os dados tenham qualidade e que a decisão final permaneça com profissionais de saúde. O chatbot generativo pode orientar sobre horários e preparo de exames, mas não deve responder questões clínicas sem revisão, pois gera o texto mais provável, e não o verificado. Quanto à privacidade e à segurança, o vazamento da lista de pacientes feriu a confidencialidade e decorreu de uma senha compartilhada. As medidas são autenticação em múltiplos fatores, gestão de senhas, atualização dos sistemas e conscientização da equipe. O aplicativo coleta renda e localização sem necessidade, contrariando os princípios da necessidade e da finalidade da LGPD (Lei 13.709/2018). Quanto à ética, o modelo de prioridade prejudica pacientes de dois bairros porque aprendeu com um histórico desigual. Como afirma Gabriel (2021), a tecnologia não é neutra: ela reflete valores humanos e amplifica acertos e erros. A rede precisa de transparência, auditabilidade, explicabilidade e responsabilização, com supervisão humana contínua. Em síntese, como defende Rogers (2017), a transformação digital não é sobre tecnologia, mas sobre estratégia: a Rede Bem Viver só terá ganhos reais quando integrar seus sistemas, proteger os dados e submeter suas decisões automatizadas ao controle de pessoas.',
          rubrica: ['Segui os quatro pontos, um parágrafo ou bloco para cada', 'Usei termos de pelo menos cinco unidades (silos, digitalização × transformação, tríade, viés, LGPD, prompt/IA generativa…)', 'Liguei cada problema do cenário a um conceito e a uma medida', 'Citei a LGPD com pelo menos dois princípios', 'Afirmei que o algoritmo não é neutro e pedi governança e supervisão humana', 'Citei Rogers e Gabriel (ou outro autor do curso) e fechei com uma tese'],
        },
        texto('**Roteiro para a A3 de verdade.** A A3 vale **40 pontos**, vai de **05/nov a 02/dez** e **não tem recuperação**. O texto é **seu**: o jogo só organiza. Quando o cenário real sair, use este esqueleto.\n\n**1. Abertura (3 ou 4 linhas).** Diga qual é a organização, o que ela faz com tecnologia e qual é a sua tese. Uma tese que sempre serve: *a tecnologia só gera valor quando vem com estratégia, integração e responsabilidade*.\n\n**2. Sistemas e infraestrutura.** Procure no cenário: há sistemas isolados ou integrados? Onde ficam os dados (nuvem, servidor próprio)? Termos: silos, ERP e CRM, fluxo de dados, IaaS/PaaS/SaaS, tríade da segurança.\n\n**3. Dados, automação e IA.** Procure: quem decide, a pessoa ou o sistema? O sistema segue regra ou aprende? De onde vêm os dados de treino? Termos: automação × IA, aprendizado supervisionado, qualidade dos dados, IA generativa e revisão humana, digitalização × transformação.\n\n**4. Privacidade e segurança.** Procure: que dados pessoais são coletados? São necessários? Houve ou pode haver vazamento? Termos: LGPD (Lei 13.709/2018) e seus princípios, ANPD, múltiplos fatores, senhas, atualização, conscientização.\n\n**5. Ética.** Procure: quem pode ser prejudicado por uma decisão automática? Dá para explicar a decisão? Quem responde? Termos: viés, neutralidade como equívoco, transparência, auditabilidade, explicabilidade, responsabilização, supervisão humana, inclusão digital.\n\n**6. Fecho.** Volte à tese e proponha dois ou três passos concretos.\n\n**Citações prontas** (escolha duas): Rogers (2017), "a transformação digital não é sobre tecnologia, mas sobre estratégia". Gabriel (2021, p. 39), "a tecnologia não é neutra: ela reflete valores humanos e amplifica tanto nossos acertos quanto nossos erros". Gabriel (2021), "o futuro do trabalho não é sobre humanos versus máquinas, mas sobre humanos com máquinas". Akabane (2018), as tecnologias cognitivas "ampliam a capacidade humana de análise, aprendizado e decisão".'),
        { t: 'feynman', prompt: 'Em três frases: qual é a ideia que atravessa as oito unidades de Exploração Digital? (Dica: releia as citações de Rogers e de Gabriel.)' },
      ],
    },
  ],
  cards: [...CARDS_EXP.filter((c) => c.regiao === 'c4'), ...cards('exp', 'c4', [
    ['O que são tecnologias cognitivas (Akabane, 2018)?', 'Sistemas que processam informações, aprendem com dados e apoiam decisões. Ampliam a capacidade humana de análise, aprendizado e decisão.'],
    ['O que é um ecossistema de inovação?', 'O conjunto de atores, instituições, recursos e relações que favorecem a criação e a difusão de inovações. A palavra-chave é interdependência.'],
    ['O que é um MVP?', 'Produto Mínimo Viável: a versão mais simples do produto que já permite testar a ideia com usuários reais. Marca o estágio de validação.'],
    ['O que é escalabilidade?', 'Crescer rapidamente sem aumento proporcional dos custos (custos marginais reduzidos).'],
    ['Incubadora, parque tecnológico e hub', 'Incubadora: apoio a startups em estágio inicial. Parque: reúne empresas, universidades e pesquisa para transferir conhecimento. Hub: espaço aberto que conecta os atores e estimula a cocriação.'],
    ['Os três dilemas éticos da U8', 'Vieses discriminatórios, privacidade dos dados e disseminação de desinformação.'],
    ['Como a U8 manda prevenir ameaças digitais?', 'Técnica + educação: autenticação em múltiplos fatores, gestão de senhas, atualização de sistemas e programas de conscientização.'],
    ['O que é cidadania digital?', 'O exercício consciente de direitos e deveres no uso das tecnologias, respeitando ética, privacidade e segurança de todos. É um processo coletivo.'],
    ['Os quatro pontos que a A3 pede', 'Sistemas de informação e infraestrutura; uso estratégico de dados, automação e IA; privacidade, proteção de dados e segurança; práticas éticas e responsáveis.'],
    ['Citação de Gabriel (2021) sobre o profissional do futuro', '"Aquele capaz de aprender continuamente, adaptar-se às mudanças e colaborar com tecnologias inteligentes."'],
  ], 10)],
};
