// Simulados de Exploração Digital: A1 (dissertativa) e A2 (objetiva).
// O formato exato das provas não está no material. A2: questões REAIS da plataforma (as mesmas das camadas, com a fonte), misturadas.
// A1: questões escritas para o jogo, uma por camada, com resposta-modelo e rubrica; tudo o que as respostas afirmam está nas aulas.
import type { Ex, Phase, Regiao, Step } from '../../engine/types';
import { texto } from '../ajuda';
import { C1 } from './c1';
import { C2 } from './c2';
import { C3 } from './c3';
import { C4 } from './c4';

const todas: Ex[] = [C1, C2, C3, C4].flatMap((r) => r.fases.flatMap((f) => f.steps.flatMap((s) => (s.t === 'ex' ? [s.ex] : []))));
/** Copia uma questão real de uma camada para o simulado, com outro id (para o progresso das duas não se misturar). */
const copia = (prefixo: string, ids: string[]): Step[] => ids.map((id, i) => {
  const e = todas.find((x) => x.id === id);
  if (!e) throw new Error('simulado: não achei a questão ' + id);
  return { t: 'ex', ex: { ...e, id: `${prefixo}-${i + 1}`, selo: undefined, seloNota: undefined } as Ex };
});

export const IDS_A2_EXP: Record<'a' | 'b', string[]> = {
  a: ['c1-q1', 'c1-q2', 'c1-r-erl', 'c2-q1', 'c2-q3', 'c2-q7', 'c2-q9', 'c3-q1', 'c3-q2', 'c3-q8', 'c3-q3', 'c4-q2', 'c4-q5', 'c4-q7', 'c4-r-reis', 'c4-q12'],
  b: ['c1-q3', 'c1-q4', 'c1-q5', 'c2-q5', 'c2-q6', 'c2-q8', 'c2-q11', 'c3-q5', 'c3-q7', 'c3-q9', 'c3-q4', 'c4-q3', 'c4-r-iot', 'c4-q11', 'c4-q9', 'c4-q13'],
};

const escrita = (fonte: string, prompt: string, modelo: string, rubrica: string[]): Step => ({ t: 'escrita', fonte, prompt, modelo, rubrica });

const A1: Phase = {
  id: 'cs-a1', titulo: 'Simulado A1 · dissertativa', tipo: 'chefe', min: 40, resumo: 'Quatro questões para escrever, uma por camada da disciplina, com resposta-modelo e lista de conferência.',
  steps: [
    texto('**Como usar este simulado.** A A1 (02 a 11/nov) é **dissertativa**. O material não mostra uma A1 de exemplo, então estas quatro questões são **minhas**, no molde das atividades de "estudo de caso" das unidades, uma por camada do Mundo 2.\n\nPara cada uma: (1) responda de verdade, em 10 a 15 linhas; (2) abra a resposta-modelo; (3) marque na lista o que a sua resposta tem. O modelo não é "a" resposta certa: é uma resposta que cumpre os seis itens.\n\n**A receita que serve para as quatro**: definir os termos com as palavras do curso, aplicar ao caso, mostrar o outro lado (risco ou limite), fechar com uma tese e um autor.'),
    escrita('Simulado A1 · Questão 1 (infraestrutura, U3)',
      'Um escritório de contabilidade com 12 funcionários guarda tudo num servidor próprio, numa sala sem controle de acesso, e quer "ir para a nuvem". (a) Explique o que é computação em nuvem e diferencie IaaS, PaaS e SaaS. (b) Indique qual modelo faz mais sentido para o escritório e por quê. (c) Usando os três pilares da segurança da informação, aponte os riscos da situação atual.',
      'Computação em nuvem é o uso de recursos de computação, como servidores, armazenamento e programas, pela internet, sob demanda, em vez de mantê-los em equipamentos próprios. Os três modelos de serviço se diferenciam por quanto o provedor assume. No IaaS, o provedor entrega a infraestrutura (máquinas virtuais, rede e armazenamento) e a empresa ainda cuida do sistema operacional e das aplicações. No PaaS, o provedor entrega também a plataforma para desenvolver e implantar aplicações, e a empresa cuida apenas do seu código e dos seus dados. No SaaS, o software chega pronto e a empresa só o utiliza. Para um escritório de contabilidade sem equipe de tecnologia, o SaaS é o mais indicado: sistemas de gestão, e-mail e armazenamento de documentos por assinatura dispensam a manutenção de servidores e de sistemas operacionais. Quanto à segurança, a situação atual fere os três pilares. A confidencialidade está em risco porque o servidor fica em sala sem controle de acesso, e os dados fiscais dos clientes podem ser vistos por quem não deveria. A integridade está em risco porque não há controle sobre quem altera os arquivos. A disponibilidade está em risco porque uma única máquina concentra tudo: se ela falhar, o escritório para. A nuvem não elimina esses riscos sozinha: continuam necessários o controle de acesso, as cópias de segurança e a conscientização dos funcionários. Em síntese, a migração só vale a pena se vier acompanhada de uma política de segurança, pois a tecnologia é meio e não fim.',
      ['Defini computação em nuvem', 'Diferenciei IaaS, PaaS e SaaS pelo que o provedor assume', 'Escolhi um modelo e justifiquei pelo perfil do escritório', 'Usei os três pilares: confidencialidade, integridade e disponibilidade', 'Disse que a nuvem não resolve a segurança sozinha', 'Fechei com uma tese']),
    escrita('Simulado A1 · Questão 2 (sistemas e transformação digital, U4 e U2)',
      'Uma rede de três lojas de roupas controla vendas num sistema, estoque em planilhas e clientes num caderno. A dona comprou tablets para os vendedores e afirma que "a empresa já passou pela transformação digital". (a) Que problema os três controles separados criam? (b) Que sistemas o curso indica para resolvê-lo? (c) A afirmação da dona está correta? Use Rogers.',
      'Os três controles separados formam silos de informação: cada setor guarda os seus dados sem compartilhar com os outros. A consequência é que não existe uma visão única do negócio. O vendedor pode vender uma peça que o estoque já não tem, o mesmo cliente aparece com dados diferentes em cada lugar, e as decisões são tomadas com informação parcial e atrasada, além do retrabalho de copiar dados à mão. O curso indica a integração dos sistemas. O ERP centraliza os processos internos, como finanças, estoque, compras e logística, em uma base única. O CRM reúne o relacionamento com o cliente: histórico de compras, atendimento e marketing. Integrados, os dois permitem que uma venda atualize o estoque e o histórico do cliente ao mesmo tempo. A afirmação da dona não está correta. Comprar tablets é adotar equipamento, e passar o caderno para uma planilha seria digitalização, isto é, mudar o suporte da informação. Transformação digital é redefinir processos, modelo de negócio e a forma de criar valor para o cliente. Rogers (2017) afirma que a transformação digital não é sobre tecnologia, mas sobre estratégia, e a organiza em cinco domínios: clientes, competição, dados, inovação e valor. A rede só estaria se transformando se, por exemplo, passasse a tratar os dados de compra como ativo para decidir o que comprar e para personalizar ofertas. Em síntese, a loja tem tecnologia, mas ainda não tem integração nem estratégia digital.',
      ['Nomeei o problema: silos de informação, com pelo menos duas consequências', 'Expliquei ERP (processos internos) e CRM (relacionamento com o cliente)', 'Diferenciei digitalização de transformação digital', 'Citei Rogers: "não é sobre tecnologia, mas sobre estratégia"', 'Citei os cinco domínios (ou pelo menos três deles)', 'Dei um exemplo do que seria transformação de verdade nessa loja']),
    escrita('Simulado A1 · Questão 3 (IA e automação, U5 e U6)',
      'Uma escola quer usar tecnologia em duas frentes: enviar automaticamente um e-mail aos pais quando o aluno falta, e prever quais alunos correm risco de abandonar o curso. (a) Qual das duas é automação e qual é inteligência artificial? Justifique com as definições do curso. (b) Que tipo de aprendizado de máquina serve para a previsão, e de que ele depende? (c) Que risco ético existe e como reduzi-lo?',
      'O envio do e-mail é automação: a execução automática de uma tarefa repetitiva com base em uma regra predefinida (se faltou, envia). O sistema não aprende nem se adapta; apenas segue a instrução programada. A previsão de abandono é inteligência artificial, pois o sistema aprende a partir de dados, infere e apoia uma decisão; trata-se de IA preditiva, e o curso usa exatamente o exemplo de estimar o risco de evasão escolar. Para a previsão serve o aprendizado supervisionado: o modelo é treinado com exemplos de anos anteriores em que a resposta é conhecida, ou seja, alunos que abandonaram e alunos que concluíram. Treinar é ajustar o modelo para diminuir o erro sobre esses exemplos. Por isso ele depende da qualidade, da quantidade e da diversidade dos dados, que o curso chama de combustível dos sistemas inteligentes: dados incompletos ou enviesados comprometem o resultado. O risco ético é o viés algorítmico. Se, no histórico, alunos de certo bairro ou de certa renda abandonaram mais, o modelo pode marcar como "de risco" todos os alunos desse grupo e a escola pode passar a tratá-los como casos perdidos, reproduzindo e ampliando a desigualdade. Para reduzir o risco, o curso indica transparência, auditoria dos algoritmos e diversidade nas equipes, além de supervisão humana: a previsão deve servir para oferecer apoio ao aluno, e a decisão continua sendo de pessoas. Como afirma Gabriel (2021), o futuro do trabalho não é sobre humanos versus máquinas, mas sobre humanos com máquinas.',
      ['Classifiquei as duas frentes e justifiquei (regra predefinida × aprender com dados)', 'Indiquei aprendizado supervisionado e expliquei por que há rótulo', 'Falei da dependência dos dados (qualidade, quantidade, diversidade)', 'Nomeei o risco: viés algorítmico herdado do histórico', 'Propus medidas: transparência, auditoria, diversidade, supervisão humana', 'Citei um autor e fechei dizendo que a decisão é humana']),
    escrita('Simulado A1 · Questão 4 (ética, dados e inovação, U1, U7 e U8)',
      'Uma startup criou um aplicativo de entregas que usa um algoritmo para distribuir as corridas entre os entregadores e coleta a localização deles 24 horas por dia. O fundador diz: "o algoritmo é neutro, é só matemática". (a) Essa afirmação se sustenta? Use a U8. (b) Que princípios da LGPD a coleta de localização pode ferir? (c) Que práticas de governança a empresa deveria adotar, considerando que quer escalar?',
      'A afirmação não se sustenta. A U8 afirma que a suposta neutralidade tecnológica é um equívoco, porque as decisões de um algoritmo são condicionadas pelos dados de entrada, pelos critérios de otimização definidos e pelas finalidades institucionais para as quais ele foi concebido. No aplicativo, alguém escolheu o que o sistema deve otimizar, por exemplo o menor tempo de entrega ou o menor custo, e essa escolha decide quais entregadores recebem mais corridas. Se o histórico favoreceu quem trabalha em certas regiões ou horários, o sistema repetirá esse padrão. Como afirma Gabriel (2021), a tecnologia não é neutra: ela reflete valores humanos e amplifica tanto nossos acertos quanto nossos erros. Quanto à LGPD (Lei 13.709/2018), a coleta de localização 24 horas por dia pode ferir o princípio da necessidade, pois a finalidade de distribuir corridas só exige a localização durante o trabalho, e o da finalidade, se o dado for usado para outros propósitos. Também exige transparência, isto é, o entregador deve saber o que é coletado e para quê, e segurança, pois o vazamento de dados de localização expõe a rotina das pessoas. Quanto à governança, a empresa deveria adotar as quatro práticas que a U8 lista: transparência sobre os critérios de distribuição, auditabilidade do algoritmo, explicabilidade das decisões que afetam cada entregador e responsabilização, com alguém que responda pelos erros, além de supervisão humana contínua. Isso é ainda mais importante porque a startup quer escalar: a U7 lembra que o crescimento acelerado exige governança, segurança da informação e conformidade regulatória. Em síntese, inovar e escalar não dispensam responsabilidade; a confiança é parte do valor do negócio.',
      ['Neguei a neutralidade usando as três fontes: dados de entrada, critérios de otimização, finalidades', 'Apliquei ao caso (o que o algoritmo otimiza e quem é afetado)', 'Citei a LGPD com necessidade e finalidade (e pelo menos mais um princípio)', 'Listei transparência, auditabilidade, explicabilidade e responsabilização', 'Liguei a escala à necessidade de governança (U7)', 'Citei Gabriel (ou outro autor) e fechei com uma tese']),
    { t: 'feynman', prompt: 'Qual das quatro questões foi a mais difícil para você? Escreva o que travou. (Isso vai para o diário e diz para qual camada voltar.)' },
  ],
};

const A2 = (letra: 'a' | 'b'): Phase => ({
  id: `cs-a2${letra}`, titulo: `Simulado A2 · objetiva (versão ${letra.toUpperCase()})`, tipo: 'questoes', min: 20, resumo: '16 questões reais da plataforma, das oito unidades, misturadas. Sem aula no meio: é só você e a questão.',
  steps: [
    texto(`**Como usar.** A A2 (12 a 18/nov) é **objetiva**. Este simulado junta 16 questões **reais da plataforma**, das oito unidades de Exploração Digital. Você já viu cada uma dentro das camadas; aqui elas vêm misturadas.\n\nFaça de uma vez, sem consultar. Reserve uns 20 minutos. Use as três heurísticas que treinamos: (1) desconfie de absolutos ("totalmente", "apenas", "exclusivamente"); (2) nas questões de "definições trocadas", ache a única em que nome e descrição combinam; (3) a correta costuma falar de pessoas, estratégia e responsabilidade.${letra === 'b' ? '\n\nEsta é a versão B: questões diferentes da versão A.' : ''}`),
    ...copia(`cs-a2${letra}`, IDS_A2_EXP[letra]),
    { t: 'feynman', prompt: 'Em qual unidade você mais errou neste simulado? O que vai rever?' },
  ],
});

export const SIMULADOS_EXP: Regiao = {
  id: 'cs', mundo: 'exp', nome: 'Simulados A1 e A2', unidades: 'U1 a U8', pronto: true, simulado: true,
  tese: 'O ensaio geral de Exploração Digital: uma prova dissertativa e duas objetivas.',
  fases: [A2('a'), A1, A2('b')],
  cards: [],
};
