// M1 · Conjuntos e funções (U1), ensinado do zero.
// Fontes: fontes/matematica/U1.txt e PDFs da Unidade 1. O texto aqui é uma reformulação: parte de situações
// concretas, constrói a ideia, e só depois dá nome e símbolo. O que o curso cobra está todo aqui.
import type { Regiao } from '../../engine/types';
import { cards, cheque, conj, ex, ficha, gen, mcq, num, texto } from '../ajuda';

export const M1: Regiao = {
  id: 'm1', mundo: 'mat', nome: 'Conjuntos e funções', unidades: 'U1', pronto: true,
  tese: 'Conjuntos dizem o que pode entrar; funções dizem o que sai. É a base de banco de dados, filtros e tipos.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'm1-oque', titulo: 'Aula 1 · O que é um conjunto', tipo: 'licao', min: 9, resumo: 'Do zero: o que é, como se escreve, pertencer, estar contido, vazio e universo.',
      steps: [
        texto('**Comece por um problema.** Você cuida da lista de transmissão do ministério de louvor. Alguém te passa os nomes assim:\n\n`Ana, Bruno, Ana, Caio, Bruno, Davi`\n\nQuantas pessoas vão receber a mensagem?'),
        ex(cheque('m1-k01', 'm1.conjuntos', 'Quantas pessoas diferentes há nessa lista?', ['6', '4', '2'], 1, 'Ana e Bruno aparecem duas vezes, mas cada um é uma pessoa só. São 4: Ana, Bruno, Caio e Davi.')),
        texto('Você acabou de fazer, de cabeça, a operação mais básica desta matéria: olhou para uma lista e ficou só com **quem está nela**, sem ligar para repetição nem para a ordem.\n\nA matemática dá um nome para "um grupo de coisas em que só interessa quem está dentro": **conjunto**.\n\nCada coisa de dentro se chama **elemento**. Elemento pode ser qualquer coisa: pessoas, números, produtos, arquivos, até outros conjuntos.'),
        texto('**Como se escreve.** Usa-se chaves, com os elementos separados por vírgula, e uma letra maiúscula para dar nome ao conjunto:\n\n$$L = \\{\\text{Ana}, \\text{Bruno}, \\text{Caio}, \\text{Davi}\\}$$\n\nDuas regras saem direto da ideia de "só interessa quem está dentro":\n\n- **Não existe repetição.** $\\{\\text{Ana}, \\text{Ana}, \\text{Bruno}\\}$ é o mesmo que $\\{\\text{Ana}, \\text{Bruno}\\}$.\n- **Não existe ordem.** $\\{1, 2, 3\\}$ é o mesmo que $\\{3, 1, 2\\}$.'),
        ex(cheque('m1-l1', 'm1.conjuntos', 'Os conjuntos $\\{1, 2, 3\\}$ e $\\{3, 1, 2, 2\\}$ são:', ['o mesmo conjunto', 'diferentes, porque a ordem mudou', 'diferentes, porque um tem 4 elementos'], 0, 'Os dois têm exatamente os elementos 1, 2 e 3. Ordem e repetição não contam. Em Python, `set([3, 1, 2, 2])` dá `{1, 2, 3}`.')),
        texto('**Pertencer.** A pergunta que mais se faz a um conjunto é: "fulano está aí dentro?". Existe um símbolo para ela:\n\n- $\\text{Ana} \\in L$ lê-se "Ana **pertence** a L" (Ana está no conjunto).\n- $\\text{Edu} \\notin L$ lê-se "Edu **não pertence** a L".\n\nO símbolo $\\in$ é um "e" estilizado, de "elemento". Ele sempre liga **um elemento** a **um conjunto**.\n\nPara um conjunto estar "bem definido", essa pergunta precisa ter resposta clara para qualquer coisa: ou pertence, ou não pertence. "As pessoas legais da igreja" não é um conjunto; "as pessoas na escala de domingo" é.'),
        ex(cheque('m1-k02', 'm1.conjuntos', 'Seja $P = \\{2, 4, 6, 8\\}$. Qual frase está certa?', ['$4 \\in P$ e $5 \\notin P$', '$5 \\in P$', '$4 \\notin P$'], 0, '4 é um dos elementos listados; 5 não é.')),
        texto('**E quando o conjunto é grande demais para listar?** Ninguém escreve todos os números pares, um por um. Aí se descreve o conjunto por uma **propriedade**, a regra para entrar:\n\n$$P = \\{x \\mid x \\text{ é inteiro e } x \\text{ é divisível por 2}\\}$$\n\nLê-se: "P é o conjunto dos x **tais que** x é inteiro e divisível por 2". A barra $\\mid$ quer dizer "tal que".\n\nÉ exatamente o que um filtro faz num sistema: `clientes onde cidade = Guarulhos` descreve um conjunto por uma propriedade, sem listar ninguém.'),
        texto('**Um conjunto dentro do outro.** A escala de domingo é $D = \\{\\text{Ana}, \\text{Caio}\\}$. Todo mundo que está em D também está na lista geral L. Quando isso acontece, dizemos que D **está contido** em L, ou que D é **subconjunto** de L:\n\n$$D \\subseteq L$$\n\nCuidado com a diferença, que é a pegadinha clássica:\n\n- $\\in$ liga um **elemento** a um conjunto: $\\text{Ana} \\in L$.\n- $\\subseteq$ liga um **conjunto** a outro conjunto: $\\{\\text{Ana}\\} \\subseteq L$.\n\nDois conjuntos são **iguais** quando cada um está contido no outro, ou seja, têm exatamente os mesmos elementos.'),
        ex(cheque('m1-k03', 'm1.conjuntos', 'A = {1, 2, 3, 4, 5} e B = {2, 4}. O que é verdade?', ['B ⊆ A, porque todo elemento de B também está em A', 'A ⊆ B, porque A é maior', 'B ∈ A'], 0, 'Para B ⊆ A, basta conferir cada elemento de B: o 2 está em A, o 4 está em A. O contrário não vale: o 1 está em A e não está em B.')),
        texto('**Dois conjuntos especiais.**\n\nO **conjunto vazio**, escrito $\\emptyset$ ou $\\{\\}$, não tem elemento nenhum. Parece inútil, mas aparece o tempo todo: é o resultado de uma busca que não achou nada. E ele é subconjunto de qualquer conjunto (não há nenhum elemento dele que fique de fora).\n\nO **conjunto universo**, escrito $U$, é "tudo que está em jogo" naquele problema: todos os membros da igreja, todos os produtos da loja. Ele importa porque a pergunta "quem **não** está na escala?" só tem resposta se você souber de onde está tirando as pessoas.\n\nPor fim, uma notação que vai aparecer muito: $|A|$ é a **quantidade de elementos** de A. Se $L$ tem Ana, Bruno, Caio e Davi, então $|L| = 4$.'),
        ex(cheque('m1-k04', 'm1.conjuntos', 'Uma consulta no sistema procura "clientes de Guarulhos com mais de 150 anos" e não acha ninguém. O resultado é:', ['o conjunto vazio, ∅', 'um erro: isso não é um conjunto', 'o conjunto universo'], 0, 'Um conjunto sem elementos continua sendo um conjunto. $|\\emptyset| = 0$.')),
        ficha({
          titulo: 'Conjunto: a ficha',
          porque: 'Todo sistema guarda coleções: clientes, produtos, permissões. Conjunto é a forma exata de falar de uma coleção sem se preocupar com ordem ou repetição. Uma tabela de banco de dados é um conjunto de linhas.',
          ideia: 'Coleção bem definida de elementos distintos. Só importa quem pertence.',
          regra: '$$a \\in A \\;\\text{(pertence)} \\qquad B \\subseteq A \\;\\text{(está contido)} \\qquad \\emptyset \\;\\text{(vazio)} \\qquad |A| \\;\\text{(quantos)}$$',
          exemplo: 'A = {1, 2, 3, 4, 5}, B = {2, 4}: então $2 \\in B$, $B \\subseteq A$, $|A| = 5$. Por propriedade: $\\{x \\mid x \\text{ é par}\\}$.',
          armadilha: '$\\in$ é para elemento; $\\subseteq$ é para conjunto. E o vazio é subconjunto de todo conjunto.',
        }),
        ex(mcq('m1-q6', 'm1.conjuntos', 'U1 · Complemento da teoria', 'Agora uma questão do curso. Qual é a definição correta de conjunto?', [
          'Uma coleção bem definida de elementos distintos, em que se pode determinar claramente se um elemento pertence ou não a ela.',
          'Qualquer lista aleatória de elementos, mesmo com repetições e elementos indefinidos.',
          'Algo exclusivo para números inteiros, que não pode conter outros tipos de elementos.',
          'Uma sequência ordenada de elementos que permite elementos repetidos.',
        ], 0, 'Bem definida (dá para decidir quem pertence), elementos distintos, sem ordem. Você já sabia isso tudo.', { heuristica: 'As erradas usam "qualquer", "exclusivo", "aleatória": palavras absolutas ou que contradizem a definição.' })),
        { t: 'feynman', prompt: 'Com suas palavras e um exemplo seu: o que é um conjunto, e qual a diferença entre "pertence" e "está contido"?' },
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'm1-conj', titulo: 'Aula 2 · Juntar, cruzar e tirar', tipo: 'licao', min: 10, resumo: 'As quatro operações, uma de cada vez, a partir de duas listas de clientes.',
      steps: [
        texto('**O problema.** Uma empresa vende dois produtos. As listas de clientes são:\n\n- **X** = {C1, C2, C3, C4, C5, C6}\n- **Y** = {C4, C5, C7, C8}\n\nO marketing faz três pedidos: (1) quem usa os dois, para oferecer um combo; (2) quem usa só o X, para apresentar o Y; (3) uma lista única de todo mundo, sem mandar mensagem em dobro.\n\nCada pedido é uma **operação** entre conjuntos. Vamos uma por vez.'),
        texto('**1. Interseção: quem está nos dois.**\n\nPercorra a lista X e, para cada cliente, pergunte: "ele também está em Y?". C1 não. C2 não. C3 não. **C4 sim. C5 sim.** C6 não.\n\nO resultado é $\\{C4, C5\\}$. Esse conjunto se chama **interseção** de X e Y:\n\n$$X \\cap Y = \\{C4, C5\\}$$\n\nA palavra que resume a interseção é **E**: o elemento está em X **e** está em Y.'),
        texto('**2. União: quem está em pelo menos um.**\n\nAgora junte as duas listas e apague as repetições: C1, C2, C3, C4, C5, C6, e de Y só entram os que ainda não apareceram: C7 e C8.\n\n$$X \\cup Y = \\{C1, C2, C3, C4, C5, C6, C7, C8\\}$$\n\nA palavra da **união** é **OU**: está em X **ou** está em Y (ou nos dois). Repare que C4 e C5 entram uma vez só: conjunto não tem repetição.\n\nPara não confundir os símbolos: $\\cup$ parece um copo, onde você **junta** tudo. $\\cap$ é o copo virado: só fica o que estava preso nos dois.'),
        ex(cheque('m1-k05', 'm1.operacoes', 'A = {1, 2, 3} e B = {3, 4}. Quanto é $A \\cap B$?', ['{3}', '{1, 2, 3, 4}', '{1, 2}'], 0, 'Só o 3 aparece nas duas. {1, 2, 3, 4} seria a união.')),
        texto('**3. Diferença: quem está num e não está no outro.**\n\n"Quem usa só o X" = pegue a lista X e **risque** quem também está em Y. Saem C4 e C5:\n\n$$X - Y = \\{C1, C2, C3, C6\\}$$\n\nO curso também escreve $X \\setminus Y$; é a mesma coisa. A frase da **diferença** é **E NÃO**: está em X **e não** está em Y.\n\nAgora o detalhe que derruba muita gente. Faça ao contrário, $Y - X$: pegue Y e risque quem está em X. Sobram $\\{C7, C8\\}$. É outro conjunto. Na diferença, **a ordem importa**.'),
        ex(cheque('m1-k06', 'm1.operacoes', 'A = {1, 2, 3, 4} e B = {3, 4, 5, 6}. Quanto é $B - A$?', ['{5, 6}', '{1, 2}', '{3, 4}'], 0, 'Pegue B = {3, 4, 5, 6} e risque o que também está em A (3 e 4). Sobram 5 e 6. {1, 2} é A − B.')),
        texto('**4. Complemento: quem ficou de fora.**\n\nSuponha que a empresa tem 10 clientes ao todo: $U = \\{C1, \\dots, C10\\}$. Quem **não** usa o produto X?\n\n$$X\' = \\{C7, C8, C9, C10\\}$$\n\nO **complemento** de X (escreve-se $X\'$, $X^c$ ou $\\overline{X}$) é tudo que está no universo e não está em X. A palavra dele é **NÃO**.\n\nPor isso o universo é obrigatório aqui: sem saber quem são "todos", não dá para dizer quem ficou de fora. No fundo, $X\' = U - X$.'),
        { t: 'toy', toy: 'venn', modo: 'livre', intro: 'O desenho abaixo é um **diagrama de Venn**: cada círculo é um conjunto, e a parte em que os círculos se cruzam é a interseção. Cada bolinha é um elemento.\n\nArraste as bolinhas e veja os conjuntos mudarem. Toque numa região vazia para ver o nome dela. Tente: (1) deixar a interseção vazia; (2) pôr todo mundo de B dentro de A.' },
        texto('**Resumo das quatro perguntas.** Para qualquer elemento, cada operação faz uma pergunta diferente:\n\n- $A \\cup B$: está em **pelo menos um**? (OU)\n- $A \\cap B$: está **nos dois**? (E)\n- $A - B$: está em A **e não** em B?\n- $A\'$: está **fora** de A?\n\nEssas quatro palavras (OU, E, E NÃO, NÃO) vão voltar na lógica, na álgebra booleana e na probabilidade. É a mesma ideia com roupas diferentes.\n\nAgora é com você: três exercícios com números novos a cada vez.'),
        gen('m1.ops', 3),
        texto('**Onde isso aparece no código.** O curso usa Python, que tem um tipo chamado `set` (conjunto). Os operadores são:\n\n- `x | y` união\n- `x & y` interseção\n- `x - y` diferença\n\nEm SQL (banco de dados), as mesmas operações se chamam `UNION`, `INTERSECT` e `EXCEPT`. Você não precisa programar agora; precisa reconhecer que é a mesma coisa.'),
        ex(mcq('m1-q3', 'm1.operacoes', 'U1 · Avaliando · Questão 3', 'Em Python, qual operação identifica os clientes que usam **pelo menos um** dos produtos X e Y, sem repetição?', ['clientes_produto_x | clientes_produto_y', 'clientes_produto_x & clientes_produto_y', 'clientes_produto_x - clientes_produto_y', 'clientes_produto_y - clientes_produto_x', 'clientes_produto_x + clientes_produto_y'], 0, '"Pelo menos um" é união: em Python, `|`. O `&` é interseção, o `-` é diferença, e `+` nem existe para `set` (dá erro).')),
        ex(mcq('m1-r-ops', 'm1.operacoes', 'U1 · Operações da álgebra de conjuntos', 'Dado U = {computadores, impressoras, modems, teclados, mouses}, A = {impressoras, modems} (promoção) e B = {computadores, modems, teclados} (estoque), qual afirmativa está correta?', [
          'A ∪ B contém todos os produtos que estão em promoção e em estoque simultaneamente.',
          'A ∩ B é o conjunto dos produtos que estão em promoção, mas não em estoque.',
          'A \\ B representa os produtos em promoção que não estão em estoque.',
          'O complemento de B em relação a U é o conjunto {computadores, modems, teclados}.',
          'A ∪ B representa os produtos que estão exclusivamente em estoque, excluindo os produtos em promoção.',
        ], 2, 'A \\ B = em A e não em B = {impressoras}. As outras trocam as definições: "simultaneamente" é interseção; "mas não" é diferença; o complemento de B é {impressoras, mouses}.')),
        ficha({
          titulo: 'As quatro operações: a ficha',
          porque: 'Toda vez que você filtra uma lista ("clientes ativos E de SP, menos os bloqueados"), está fazendo operação de conjuntos. Um `WHERE` de SQL é isso.',
          ideia: 'União = pelo menos um. Interseção = os dois. Diferença = num e não no outro. Complemento = fora, dentro do universo.',
          regra: '$$\\begin{aligned} A \\cup B &\\to \\text{OU} & A \\cap B &\\to \\text{E} \\\\ A - B &\\to \\text{E NÃO} & A\' &\\to \\text{NÃO} \\end{aligned}$$',
          exemplo: 'A = {impressoras, modems}, B = {computadores, modems, teclados}: A ∪ B tem 4 produtos; A ∩ B = {modems}; A − B = {impressoras}.',
          armadilha: 'A − B ≠ B − A. E o complemento depende de qual é o universo.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB VENN
    {
      id: 'm1-venn', titulo: 'Laboratório · Ler e pintar um Venn', tipo: 'lab', min: 9, resumo: 'As 8 regiões de três círculos, expressões com parênteses, e a questão do curso que não tem resposta.',
      steps: [
        texto('**Três círculos, oito regiões.** Com três conjuntos A, B e C, o desenho se divide em pedaços. Para cada círculo, um ponto pode estar **dentro ou fora**: são 2 opções para A, 2 para B, 2 para C. No total, $2 \\times 2 \\times 2 = 8$ regiões (7 dentro de algum círculo e 1 fora de todos).\n\nCada região tem um "endereço" exato. Por exemplo, "dentro de A, fora de B, fora de C" se escreve:\n\n$$A \\cap B\' \\cap C\'$$\n\nQualquer expressão de conjuntos, por mais complicada, é só um **punhado dessas regiões**. Ler uma expressão é descobrir quais regiões ela pega.'),
        texto('**Como ler uma expressão com parênteses.** Igual a uma conta: primeiro o que está dentro dos parênteses.\n\nExemplo: $(B \\cap C) - A$.\n\n- Primeiro $B \\cap C$: a "lente" onde B e C se cruzam. Ela tem dois pedaços: um dentro de A e outro fora.\n- Depois $- A$: tire o que está em A.\n\nSobra **um** pedaço só: o que está em B e em C, mas não em A.\n\nNo laboratório abaixo você vai pintar regiões. Verde quer dizer certo, vermelho quer dizer que pintou a mais, amarelo que faltou.'),
        { t: 'toy', toy: 'venn', modo: 'desafio', intro: 'Cinco desafios de pintar. O primeiro tem só dois círculos, para aquecer. Leia cada expressão de dentro dos parênteses para fora.', desafios: ['v-pin-4', 'v-pin-1', 'v-pin-2', 'v-pin-3', 'v-pin-6'] },
        gen('m1.venn', 3),
        ex(mcq('m1-r-u8a', 'm1.venn', 'U8 · quiz diagnóstico', 'A = ficção científica, B = premiados, C = publicados nos últimos 5 anos. O cupom vai para livros premiados **E** recentes, mas que **NÃO** sejam ficção científica. Qual expressão?', ['(B ∪ C) − A', '(B ∩ C) − A', 'B ∩ (C ∪ A)', '(B ∩ C) ∩ A', '(B − A) ∪ (C − A)'], 1, 'Troque cada palavra pelo símbolo: "premiados E recentes" = B ∩ C; "mas não ficção" = − A. Fica (B ∩ C) − A.')),
        texto('**Uma questão do curso com defeito.** A U1 tem uma atividade que pede a expressão dos clientes que compraram **apenas** eletrônicos (A), sem alimentos (B) nem vestuário (C). Você pintou essa região há pouco: é "A, tirando tudo que está em B ou em C".\n\nVeja as alternativas que o curso oferece e decida.'),
        ex(mcq('m1-r-venn', 'm1.venn', 'U1 · atividade do diagrama de Venn', 'A = clientes de eletrônicos, B = de alimentos, C = de vestuário. Qual expressão representa os clientes que compraram **apenas** eletrônicos, sem alimentos nem vestuário?', ['(B ∪ C)', '(A ∪ B) − C', 'A ∩ B ∩ C', '(A ∪ C)', '(A ∩ B) − C', 'Nenhuma das cinco: a expressão certa é A − (B ∪ C)'], 5,
          'O próprio texto da unidade diz: "A − (B ∪ C): clientes que compraram apenas produtos eletrônicos". Nenhuma das cinco alternativas do curso é essa região. Se cair igual, escreva A − (B ∪ C), que é o mesmo que A ∩ B\' ∩ C\'.',
          { selo: 'erro', seloNota: 'As alternativas A a E são as do curso. Conferi as oito regiões por código: nenhuma delas é igual a A − (B ∪ C). A sexta alternativa foi acrescentada pelo jogo.', fixo: true })),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'm1-ie', titulo: 'Aula 3 · Contar sem contar duas vezes', tipo: 'licao', min: 11, resumo: 'Inclusão-exclusão construída no desenho. O exemplo resolvido vai sumindo até você fazer sozinho.',
      steps: [
        texto('**O problema.** No ministério de louvor, 5 pessoas tocam violão e 4 tocam teclado. O líder quer comprar uma camiseta para cada músico. Quantas camisetas?\n\nA tentação é responder 9. Antes de eu explicar, arrume você mesmo no desenho e veja quanto dá.'),
        { t: 'toy', toy: 'venn', modo: 'desafio', intro: 'A = toca violão, B = toca teclado. Sabe-se que **2 pessoas tocam os dois**. Dê seu palpite e depois arraste as bolinhas até cumprir o que se pede (as que sobrarem ficam fora dos círculos).', desafios: ['v-arr-2'] },
        texto('Deu **7**, não 9. O que aconteceu?\n\nAs duas pessoas que tocam os dois instrumentos estão na contagem do violão **e** na contagem do teclado. Somar 5 + 4 conta essas duas pessoas **duas vezes**. Para consertar, tira-se uma das vezes:\n\n$$5 + 4 - 2 = 7$$\n\nIsso vale para quaisquer dois conjuntos, e tem um nome pomposo, **princípio da inclusão-exclusão** (inclui os dois grupos, exclui a repetição):\n\n$$|A \\cup B| = |A| + |B| - |A \\cap B|$$\n\nLeia assim: "quantos estão em pelo menos um = quantos em A + quantos em B − quantos foram contados em dobro".'),
        ex(cheque('m1-k07', 'm1.inclusao-exclusao', 'Se ninguém tocasse os dois instrumentos ($|A \\cap B| = 0$), quantas camisetas seriam?', ['9', '7', '5'], 0, 'Sem ninguém em comum não há contagem em dobro: 5 + 4 − 0 = 9. A soma simples só funciona quando os grupos não se cruzam.')),
        gen('m1.ie2', 3),
        texto('**Com três conjuntos.** Entrou a bateria: agora há A (violão), B (teclado) e C (bateria). A lógica é a mesma, mas tem uma surpresa.\n\nPense em **uma pessoa que toca os três**. Quantas vezes ela é contada em cada etapa?\n\n- Somando $|A| + |B| + |C|$: contada **3** vezes.\n- Tirando as três interseções duplas ($A \\cap B$, $A \\cap C$, $B \\cap C$): ela está nas três, então é tirada **3** vezes. Ficou em **0**.\n- Ela sumiu da conta! Por isso a interseção tripla **volta** uma vez: **+1**.\n\n$$\\begin{aligned} |A \\cup B \\cup C| = {} & |A| + |B| + |C| \\\\ & - |A \\cap B| - |A \\cap C| - |B \\cap C| \\\\ & + |A \\cap B \\cap C| \\end{aligned}$$'),
        texto('**O método que nunca falha: de dentro para fora.** Em vez de decorar a fórmula, preencha o desenho começando pelo meio:\n\n- **1º** o miolo (quem está nos três).\n- **2º** os três pedaços "em dois, mas não no terceiro". Atenção: quando o enunciado diz "8 estão em A e B", esse 8 **inclui** o miolo. Tire o miolo antes de escrever.\n- **3º** os três pedaços "só em um": o conjunto inteiro menos os pedaços dele já preenchidos.\n- **4º** some as sete regiões.\n\nQuem começa por fora conta gente em dobro. Nos três exercícios a seguir, o jogo resolve quase tudo no primeiro, esconde mais passos no segundo, e deixa tudo com você no terceiro.'),
        gen('m1.ie3', 3),
        ex(mcq('m1-r-u4q4', 'm1.inclusao-exclusao', 'U4 · Questão 04 (aparece aqui porque é a mesma ideia)', 'Você cruza a lista de "Clientes Premium" com a de "Clientes que compraram este mês" e alguns aparecem nas duas. Como contar sem duplicar?', [
          'Somar diretamente as quantidades, pois o princípio aditivo se aplica havendo ou não interseção.',
          'Contar cada caso separadamente e subtrair as interseções, pois o princípio aditivo pressupõe casos mutuamente exclusivos.',
          'Multiplicar as quantidades, pois interseção implica combinações conjuntas.',
          'Somar só os casos sem interseção e ignorar os demais.',
          'Somar tudo e depois adicionar os elementos das interseções para compensar.',
        ], 1, 'Soma pura só vale quando os grupos não se cruzam ("mutuamente exclusivos"). Havendo cruzamento, desconta-se a interseção.')),
        ficha({
          titulo: 'Inclusão-exclusão: a ficha',
          porque: 'Quem está em dois grupos aparece duas vezes quando você só soma. É o que o `UNION` do SQL resolve ao "remover duplicatas".',
          ideia: 'Some os grupos e desconte quem foi contado em dobro. Com três, o miolo é somado 3 vezes e tirado 3 vezes, então volta 1 vez.',
          regra: '$$|A \\cup B| = |A| + |B| - |A \\cap B|$$',
          exemplo: '20 fazem Python, 15 fazem Java, 5 fazem os dois. Pelo menos um: 20 + 15 − 5 = 30.',
          armadilha: 'Num Venn com números, preencha de dentro para fora. E "em A e B" no enunciado inclui quem está nos três.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'm1-cart', titulo: 'Aula 4 · Pares, relações e todos os subconjuntos', tipo: 'licao', min: 10, resumo: 'Produto cartesiano, relação e conjunto das partes. De onde vem o 2ⁿ.',
      steps: [
        texto('**O problema.** A cantina da igreja vende 3 salgados, {coxinha, esfiha, pastel}, e 2 bebidas, {suco, refri}. Um combo é um salgado **com** uma bebida. Quantos combos diferentes existem?\n\nMonte todos:\n\n- coxinha com suco, coxinha com refri\n- esfiha com suco, esfiha com refri\n- pastel com suco, pastel com refri\n\nSão 6. Para **cada** salgado (3) há **todas** as bebidas (2): $3 \\times 2 = 6$.'),
        texto('**Par ordenado.** Cada combo é uma dupla em que a posição tem significado: primeiro o salgado, depois a bebida. Escreve-se com parênteses:\n\n$$(\\text{coxinha}, \\text{suco})$$\n\nIsso é um **par ordenado**. Diferente do conjunto, aqui **a ordem importa**: $(a, b)$ e $(b, a)$ são pares diferentes. Pense em coordenadas: a posição (2, 5) num mapa não é a posição (5, 2).\n\nO conjunto de **todos** os pares possíveis, pegando o primeiro elemento de A e o segundo de B, chama-se **produto cartesiano** e se escreve $A \\times B$ (lê-se "A cartesiano B").'),
        ex(cheque('m1-k08', 'm1.cartesiano', 'A = {1, 2} e B = {x, y, z}. Quantos pares tem $A \\times B$?', ['6', '5', '3'], 0, 'Para cada um dos 2 elementos de A há 3 de B: 2 × 3 = 6. Os pares são (1,x), (1,y), (1,z), (2,x), (2,y), (2,z).')),
        gen('m1.cart', 1),
        texto('**Relação: escolher alguns pares.** O produto cartesiano tem todos os pares que **poderiam** existir. No mundo real, só alguns existem de fato.\n\nExemplo: A = pessoas, B = instrumentos. $A \\times B$ tem toda combinação de pessoa com instrumento. Mas quem **toca** o quê é só uma parte disso:\n\n$$\\text{toca} = \\{(\\text{Ana}, \\text{violão}), (\\text{Ana}, \\text{teclado}), (\\text{Caio}, \\text{bateria})\\}$$\n\nUma **relação** entre A e B é isso: qualquer subconjunto de $A \\times B$, ou seja, uma escolha de quais pares "estão ligados".\n\nÉ daí que vem o nome **banco de dados relacional**: cada tabela é uma relação, e cada linha é um par (ou uma tupla maior) que existe de verdade. Guarde essa ideia: a próxima aula mostra que **função** é um tipo especial de relação.'),
        ex(cheque('m1-k09', 'm1.cartesiano', 'A tem 4 elementos e B tem 5. Uma relação entre A e B pode ter no máximo quantos pares?', ['20', '9', '5'], 0, 'A relação é um pedaço de A × B, que tem 4 × 5 = 20 pares. No máximo, a relação é o produto inteiro.')),
        texto('**Agora outra pergunta: quantos subconjuntos um conjunto tem?**\n\nVocê tem 3 microfones, {m1, m2, m3}, e precisa decidir quais ligar no culto. Cada escolha possível é um subconjunto. Quantas escolhas existem?\n\nVamos devagar, de um microfone em diante:\n\n- **1 microfone** {m1}: desligado ou ligado. Subconjuntos: ∅, {m1}. São **2**.\n- **2 microfones**: para cada escolha de antes, o m2 pode estar fora ou dentro. Dobrou: ∅, {m1}, {m2}, {m1, m2}. São **4**.\n- **3 microfones**: de novo, o m3 fora ou dentro para cada uma das 4. Dobrou: **8**.\n\nCada elemento novo **dobra** a quantidade, porque ele tem duas opções: entra ou não entra.'),
        texto('**De onde vem o $2^n$.** Dobrar uma vez para cada elemento é multiplicar por 2 várias vezes:\n\n$$\\underbrace{2 \\times 2 \\times \\dots \\times 2}_{n \\text{ vezes}} = 2^n$$\n\nO número pequeno em cima se chama **expoente** e diz quantas vezes o 2 aparece na multiplicação. $2^3 = 2 \\times 2 \\times 2 = 8$. (Não é $2 \\times 3$.)\n\nO conjunto de **todos os subconjuntos** de A chama-se **conjunto das partes**, escrito $P(A)$. Se A tem $n$ elementos:\n\n$$|P(A)| = 2^n$$\n\nEle sempre inclui o vazio (ninguém entra) e o próprio A (todo mundo entra).\n\nEsse $2^n$ vai reaparecer: é o número de linhas de uma tabela-verdade e o número de combinações de $n$ interruptores.'),
        gen('m1.partes', 2),
        texto('**Para que serve o conjunto das partes?** No estudo de caso do curso, cada usuário de um sistema recebe um **conjunto de permissões**. Se os recursos são $R = \\{r_1, r_2, r_3, r_4\\}$, as permissões de um usuário são um subconjunto de R: {r1, r2}, ou {r1, r3}, ou nada (∅). Ou seja, a permissão de cada usuário é **um elemento de $P(R)$**. Com 4 recursos existem $2^4 = 16$ perfis de permissão possíveis.'),
        ex(mcq('m1-r-cart', 'm1.cartesiano', 'U1 · Relações entre conjuntos e funções', 'Questão do curso (adianta a próxima aula). Qual afirmação caracteriza corretamente a relação entre uma função e o produto cartesiano do domínio A pelo contradomínio B?', [
          'Uma função é um subconjunto do produto cartesiano A × B onde cada elemento do domínio A está associado a exatamente um único elemento do contradomínio B.',
          'Uma função sempre relaciona todos os elementos do contradomínio B a exatamente um elemento do domínio A.',
          'O produto cartesiano A × B é formado apenas por pares ordenados correspondentes às imagens da função definida de A para B.',
          'Uma função pode associar um mesmo elemento do domínio A a múltiplos elementos diferentes do contradomínio B, desde que cubra todo o conjunto B.',
          'O domínio da função é um subconjunto do contradomínio B e, portanto, se confunde com a imagem da função.',
        ], 0, 'A × B tem todos os pares. Uma relação escolhe alguns. A função é uma relação com uma regra a mais: cada elemento de A aparece em exatamente um par.')),
        ficha({
          titulo: 'Pares, relações e partes: a ficha',
          porque: 'Produto cartesiano monta todas as combinações de duas listas; relação é a tabela do que existe de fato; conjunto das partes são todas as seleções possíveis.',
          ideia: '$A \\times B$ = todos os pares ordenados. Relação = um pedaço de $A \\times B$. $P(A)$ = todos os subconjuntos de A.',
          regra: '$$|A \\times B| = |A| \\cdot |B| \\qquad |P(A)| = 2^{n}$$',
          exemplo: 'A = {1, 2, 3}: $P(A)$ tem $2^3 = 8$ elementos: ∅, {1}, {2}, {3}, {1,2}, {1,3}, {2,3}, {1,2,3}.',
          armadilha: '$(a, b) \\neq (b, a)$. E $2^n$ não é $2 \\times n$.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 5
    {
      id: 'm1-func', titulo: 'Aula 5 · Funções', tipo: 'lab', min: 11, resumo: 'O que é função, domínio, contradomínio e imagem; injetora, sobrejetora, bijetora e inversa.',
      steps: [
        texto('**O problema.** O sistema da igreja guarda, para cada voluntário, o setor em que ele serve:\n\n- Ana → louvor\n- Bruno → som\n- Caio → som\n- Davi → recepção\n\nIsso é uma tabela de duas colunas. Mas ela tem uma propriedade especial: **cada pessoa aparece uma vez só**. Se eu perguntar "onde o Caio serve?", a resposta é uma só.\n\nUma relação com essa propriedade se chama **função**.'),
        texto('**A ideia de função: uma máquina.** Entra uma coisa, sai uma coisa. E a mesma entrada dá **sempre a mesma saída**.\n\nUma função precisa de três ingredientes:\n\n- O **domínio**: o conjunto das entradas permitidas. Aqui, A = {Ana, Bruno, Caio, Davi}.\n- O **contradomínio**: o conjunto onde as saídas podem cair. Aqui, B = {louvor, som, recepção, infantil}.\n- A **regra** que liga cada entrada à sua saída.\n\nEscreve-se $f : A \\to B$ ("f vai de A em B") e $f(\\text{Caio}) = \\text{som}$ ("f de Caio é som").\n\nA exigência é uma só, e vale decorar: **cada elemento do domínio tem exatamente uma saída**. Nem zero, nem duas.'),
        ex(cheque('m1-k10', 'm1.funcoes', 'No sistema aparece: "Edu → louvor" e também "Edu → som". Isso ainda é uma função?', ['Não: a mesma entrada (Edu) tem duas saídas', 'Sim: Edu só trabalha mais', 'Sim, desde que os setores existam'], 0, 'Função exige UMA saída por entrada. Como relação (tabela de quem serve onde) está ótimo; como função "pessoa → setor", quebrou.')),
        texto('**Contradomínio não é imagem.** No exemplo, ninguém serve no infantil. O setor existe (está no contradomínio), mas nenhuma seta chega nele.\n\nO conjunto das saídas **realmente atingidas** se chama **imagem**: {louvor, som, recepção}.\n\n- Contradomínio: onde as saídas **podem** cair.\n- Imagem: onde elas **de fato** caem. A imagem está sempre contida no contradomínio.\n\nRepare também: Bruno e Caio vão para o mesmo setor. **Isso é permitido.** Duas entradas podem dividir a mesma saída. O que não pode é uma entrada ter duas saídas.'),
        ex(mcq('m1-l2', 'm1.funcoes', undefined, 'O que faz uma relação ser uma função?', ['Cada elemento do domínio se liga a exatamente um elemento do contradomínio', 'Cada elemento do contradomínio é atingido por alguém', 'Nenhum elemento do contradomínio é atingido duas vezes'], 0, 'A regra da função olha para o **domínio**: toda entrada tem uma saída, e uma só. As outras duas frases são propriedades extras, que vêm agora.', { fixo: true })),
        { t: 'toy', toy: 'funcoes', modo: 'livre', intro: 'Aqui as setas são suas. Toque num elemento de A e depois num de B para criar uma seta; toque na seta para apagar.\n\nTente quebrar a função dos dois jeitos: deixe alguém de A sem seta; depois dê duas setas para a mesma entrada. Veja o que o contorno vermelho aponta.' },
        texto('**Três perguntas sobre uma função.** Depois de saber que é função, vêm duas perguntas extras, e as duas olham para o **lado das saídas**.\n\n**1. Alguma saída recebe mais de uma seta?** Se **não**, a função é **injetora**: entradas diferentes sempre dão saídas diferentes. Não há colisão. Exemplo do curso: cada cidadão com seu CPF. Duas pessoas não podem ter o mesmo número.\n\n**2. Alguma saída ficou sem seta?** Se **não**, a função é **sobrejetora**: todo o contradomínio é atingido (imagem = contradomínio). Exemplo do curso: distribuir projetos de modo que todo membro da equipe receba pelo menos um.\n\n**3. As duas coisas ao mesmo tempo?** Então é **bijetora**: cada saída tem exatamente uma entrada. Exemplo do curso: cada produto numa prateleira e cada prateleira com um produto.'),
        texto('**Por que a bijetora é especial: dá para voltar.** Se cada saída tem exatamente uma entrada, você pode inverter todas as setas e o resultado **continua sendo função**. Essa função de volta chama-se **inversa**, $f^{-1}$.\n\nÉ por isso que criptografia usa funções bijetoras: quem cifra precisa conseguir decifrar sem perder informação.\n\nSe a função não é injetora, a volta fica ambígua ("som" veio de Bruno ou de Caio?). Se não é sobrejetora, a volta tem saída sem dono (de onde veio "infantil"?). Nos dois casos, não há inversa.\n\nO curso cita ainda alguns nomes soltos: função **constante** (tudo vai para o mesmo valor), função **identidade** (cada elemento vai nele mesmo, $id(a) = a$), função **total** (todo o domínio tem saída, que é o que chamamos de função aqui) e **parcial** (algumas entradas ficam sem saída).'),
        { t: 'toy', toy: 'funcoes', modo: 'desafio', intro: 'Cinco desafios. Um deles é impossível de propósito: se você achar que não dá, diga.', desafios: ['f-inj', 'f-sob', 'f-bij', 'f-quebra', 'f-imp'] },
        gen('m1.classf', 3),
        ex(mcq('m1-r-inj', 'm1.funcoes', 'U1 · Complemento da teoria (leitura Scheinerman)', 'O que caracteriza uma função injetora?', ['Cada elemento do domínio mapeia para elementos distintos no contradomínio, sem repetições.', 'Cada elemento do domínio mapeia para pelo menos um elemento do contradomínio, cobrindo todo o contradomínio.', 'Cada elemento do domínio mapeia para exatamente um elemento idêntico no contradomínio.', 'Cada elemento do contradomínio pode ser mapeado por vários elementos do domínio.'], 0, 'Injetora = sem colisão. "Cobrindo todo o contradomínio" é sobrejetora.')),
        ex(mcq('m1-q2', 'm1.funcoes', 'U1 · Avaliando · Questão 2', 'Qual situação melhor exemplifica uma função injetora na gestão de sistemas de informação?', [
          'Cada funcionário possui um número único de CPF, e nenhum CPF se repete para funcionários diferentes.',
          'Cada setor pode ter vários funcionários, e cada funcionário pode atuar em diferentes setores.',
          'Todos os produtos são agrupados em categorias, porém algumas categorias podem estar sem produtos.',
          'Os custos de produção são distribuídos igualmente entre todos os setores.',
          'Cada cliente recebe uma senha que pode ser usada por múltiplos clientes ao mesmo tempo.',
        ], 0, 'Funcionários diferentes, CPFs diferentes: sem colisão.')),
        ficha({
          titulo: 'Funções: a ficha',
          porque: 'Chave primária, login, hash, endereço de prateleira: em todos você precisa saber se duas entradas podem dar a mesma saída e se toda saída é usada.',
          ideia: 'Função: cada entrada tem exatamente uma saída. Injetora: sem colisão. Sobrejetora: nenhuma saída sobrando. Bijetora: as duas; tem inversa.',
          regra: '$$\\text{injetora: } f(a_1) = f(a_2) \\Rightarrow a_1 = a_2 \\qquad \\text{sobrejetora: } \\mathrm{Im}(f) = B$$',
          exemplo: 'CPF por cidadão: injetora. Um projeto para cada membro, sem ninguém ocioso: sobrejetora. Produto ↔ prateleira: bijetora.',
          armadilha: '"Ser função" olha para o domínio. Injetora e sobrejetora olham para o contradomínio. Não misture.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 6
    {
      id: 'm1-comp', titulo: 'Aula 6 · Uma função depois da outra', tipo: 'licao', min: 9, resumo: 'Composição g∘f, funções com fórmula, e o caso das permissões do curso.',
      steps: [
        texto('**Funções com fórmula.** Até aqui as funções eram setas entre poucos elementos. Quando o domínio é de números, a regra costuma ser uma conta:\n\n$$f(x) = 2x + 1$$\n\nLê-se "f de x é duas vezes x mais um". O $x$ é só o nome da entrada. Para calcular $f(3)$, troque $x$ por 3: $2 \\cdot 3 + 1 = 7$.\n\nOutra função: $g(x) = x^2$ ("x ao quadrado", $x \\cdot x$). Então $g(3) = 9$.'),
        ex(cheque('m1-k11', 'm1.composicao', 'Se $f(x) = 2x + 1$, quanto é $f(5)$?', ['11', '26', '8'], 0, 'Troque x por 5: 2 · 5 + 1 = 11.')),
        texto('**O problema.** Um sistema processa um dado em duas etapas: primeiro aplica $f$ (dobra e soma 1), depois entrega o resultado para $g$ (eleva ao quadrado). O que sai quando entra o 2?\n\n- Etapa 1: $f(2) = 2 \\cdot 2 + 1 = 5$.\n- Etapa 2: $g(5) = 5^2 = 25$.\n\nEncadear funções assim se chama **composição**. Escreve-se $g \\circ f$ (lê-se "g bola f" ou "g composta com f"):\n\n$$(g \\circ f)(x) = g(f(x))$$\n\nA pegadinha está na leitura: **quem age primeiro é a função da direita**, a que está colada no $x$. Em $g(f(x))$, o $x$ entra em $f$; o que sai de $f$ entra em $g$.'),
        texto('**A ordem muda o resultado.** Faça ao contrário, $f \\circ g$, com a mesma entrada 2:\n\n- Primeiro $g(2) = 4$.\n- Depois $f(4) = 2 \\cdot 4 + 1 = 9$.\n\nDeu 9, não 25. Composição **não é comutativa**: $g \\circ f$ e $f \\circ g$ são funções diferentes.\n\nNa vida real também: "pôr a meia e depois o sapato" não é igual a "pôr o sapato e depois a meia".\n\nE atenção: compor **não é multiplicar**. $g(f(2))$ não é $g(2) \\cdot f(2)$.'),
        gen('m1.comp', 3),
        { t: 'toy', toy: 'funcoes', modo: 'desafio', intro: 'Agora com setas. Monte f (de A em B) e g (de B em C). As setas tracejadas mostram g∘f: o caminho completo.', desafios: ['f-comp'] },
        texto('**Caso do curso: permissões de acesso.** Cada usuário recebe um conjunto de recursos. A função é $f : U \\to P(R)$: a entrada é um usuário e a saída é um **subconjunto** de recursos (por isso o contradomínio é o conjunto das partes, da Aula 4).\n\nDados: $f(u_1) = \\{r_1, r_2\\}$, $f(u_2) = \\{r_1, r_3\\}$, $f(u_3) = \\emptyset$.\n\nA empresa cria uma regra: quem tem $r_1$ ganha também $r_4$. Em forma de função:\n\n- $g(S) = S \\cup \\{r_4\\}$, se $r_1 \\in S$\n- $g(S) = S$, caso contrário\n\nA permissão atualizada de cada usuário é a composição $h = g \\circ f$: primeiro pega as permissões ($f$), depois aplica a regra ($g$).\n\nRepare quanta coisa das aulas anteriores está aí: pertence ($\\in$), união ($\\cup$), vazio, partes, função e composição.'),
        ex(conj('m1-caso1', 'm1.composicao', 'U1 · Estudo de caso do tópico 4', 'No caso das permissões: quanto vale $g(f(u_1))$? Escreva os recursos (ex.: r1, r2).', ['r1', 'r2', 'r4'], '$f(u_1) = \\{r_1, r_2\\}$ contém $r_1$, então $g$ acrescenta $r_4$: $\\{r_1, r_2, r_4\\}$.', ['Primeiro calcule f(u1).', 'f(u1) = {r1, r2}. Tem r1 aí dentro?', 'Tem r1, então g acrescenta r4: {r1, r2, r4}.'], [{ valor: ['r1', 'r2'], causa: 'conta', msg: 'Você parou em f(u1). Falta aplicar g: como r1 está no conjunto, entra r4.' }])),
        ex(conj('m1-caso2', 'm1.composicao', 'U1 · Estudo de caso do tópico 4', 'E $g(f(u_3))$? (Se for vazio, deixe em branco e confira.)', [], '$f(u_3) = \\emptyset$ não contém $r_1$, então $g$ não mexe: continua $\\emptyset$.', ['f(u3) é o conjunto vazio.', 'A regra só acrescenta r4 se r1 estiver no conjunto.', 'Não há r1 em ∅, então g(∅) = ∅.'], [{ valor: ['r4'], causa: 'conceito', msg: 'r4 só entra para quem já tem r1. u3 não tem nada.' }])),
        texto('**Mais uma função do curso: crescimento exponencial.** A U1 usa este exemplo em Python:\n\n$$U(t) = U_0 \\cdot e^{k \\cdot t}$$\n\nEm palavras: o número de usuários depois de $t$ meses. $U_0$ é quantos havia no começo, $k$ é a taxa de crescimento, e $e$ é um número fixo, aproximadamente 2,718, que aparece sempre que algo cresce "sobre o que já cresceu" (como juros sobre juros).\n\nVocê não precisa calcular $e$ elevado a alguma coisa de cabeça: a prova dá o valor, ou o Python calcula com `math.exp`.'),
        ex(num('m1-exp', 'm1.funcoes', 'U1 · Exemplo de função no Colab', 'Com $U_0 = 1000$ usuários e $k = 0{,}05$ ao mês, quantos usuários depois de 12 meses? Use $e^{0{,}6} \\approx 1{,}822$.', 1822, '$U(12) = 1000 \\cdot e^{0{,}05 \\cdot 12} = 1000 \\cdot e^{0{,}6} \\approx 1000 \\cdot 1{,}822 = 1822$. O código do curso imprime 1822.12.', ['O expoente é k·t.', '0,05 × 12 = 0,6. Então U = 1000 · e^0,6.', '1000 × 1,822 = 1822.'], { tol: 1, armadilhas: [{ valor: 1600, causa: 'conceito', msg: 'Você fez crescimento simples (1000 + 5% × 12 meses). O exponencial cresce sobre o que já cresceu, por isso dá mais.' }] })),
        ficha({
          titulo: 'Composição: a ficha',
          porque: 'Programas são etapas encadeadas: a saída de uma função é a entrada da próxima (um pipeline de dados).',
          ideia: '$g \\circ f$ passa a entrada por $f$ e entrega o resultado para $g$. Lê-se da direita para a esquerda.',
          regra: '$$(g \\circ f)(x) = g(f(x))$$',
          exemplo: '$f(x) = 2x + 1$ e $g(x) = x^2$: $(g \\circ f)(2) = g(5) = 25$, mas $(f \\circ g)(2) = f(4) = 9$.',
          armadilha: 'Não é comutativa, e não é multiplicação.',
        }),
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'm1-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'Tudo da U1 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo aqui parecer novo, volte à aula daquele assunto.\n\n**Conjunto**: coleção sem ordem e sem repetição. $a \\in A$ (pertence), $B \\subseteq A$ (está contido), $\\emptyset$ (vazio, contido em todos), $U$ (universo), $|A|$ (quantidade). Pode ser listado, $\\{2, 4\\}$, ou descrito por propriedade, $\\{x \\mid x \\text{ é par}\\}$.\n\n**Operações**: união $\\cup$ (pelo menos um, OU), interseção $\\cap$ (os dois, E), diferença $-$ ou $\\setminus$ (num e não no outro; a ordem importa), complemento $\'$ (fora, dentro do universo). Em Python: `|`, `&`, `-`. Em SQL: `UNION`, `INTERSECT`, `EXCEPT`.\n\n**Venn**: três círculos formam 8 regiões; "apenas A" é $A - (B \\cup C)$.'),
        texto('**Inclusão-exclusão**: $|A \\cup B| = |A| + |B| - |A \\cap B|$. Com três: soma os três, tira as três duplas, devolve a tripla. Em Venn com números, de dentro para fora.\n\n**Produto cartesiano** $A \\times B$: todos os pares ordenados; $|A \\times B| = |A| \\cdot |B|$. **Relação**: qualquer subconjunto de $A \\times B$. **Conjunto das partes** $P(A)$: todos os subconjuntos; $|P(A)| = 2^n$.\n\n**Função** $f : A \\to B$: cada elemento do domínio com exatamente uma saída. Imagem = saídas atingidas. **Injetora**: sem colisão. **Sobrejetora**: imagem = contradomínio. **Bijetora**: as duas; tem inversa. Também: constante, identidade, total, parcial.\n\n**Composição**: $(g \\circ f)(x) = g(f(x))$; $f$ age primeiro; não é comutativa.'),
        ex(mcq('m1-q7', 'm1.funcoes', 'U1 · Relações entre conjuntos e funções', 'Qual propriedade diferencia uma função de uma relação qualquer entre dois conjuntos?', [
          'Cada elemento do domínio está associado a exatamente um elemento do contradomínio.',
          'Cada elemento do contradomínio deve estar associado a múltiplos elementos do domínio.',
          'Uma função pode associar um mesmo elemento do domínio a diferentes elementos do contradomínio sem restrições.',
          'Uma função contém todos os elementos do domínio e do contradomínio como pares, não importa o número de associações.',
        ], 0, 'Unicidade: uma entrada, uma saída. Relação qualquer não tem essa restrição.')),
        { t: 'feynman', prompt: 'Sem olhar: escreva de memória as quatro operações de conjuntos e uma frase para cada. Depois confira no resumo o que faltou.' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'm1-questoes', titulo: 'Questões reais da U1', tipo: 'questoes', min: 8, resumo: 'As questões da plataforma, com a fonte. As alternativas aparecem embaralhadas.',
      steps: [
        texto('Na plataforma, quase todas as corretas da U1 estão na letra A. Aqui as alternativas vêm **embaralhadas**, para você responder pelo conteúdo e não pela posição. Algumas questões do curso já apareceram dentro das aulas; estas são as que faltavam.'),
        ex(mcq('m1-q1', 'm1.operacoes', 'U1 · Avaliando · Questão 1', 'A = {1, 2, 3, 4} e B = {3, 4, 5, 6}. Qual conjunto é a diferença B \\ A?', ['{5, 6}', '{1, 2}', '{3, 4}', '{1, 2, 5, 6}', '{3, 4, 5, 6}'], 0, 'B \\ A = está em B e não em A = {5, 6}. {1, 2} é A \\ B (a ordem importa).', { porOpcao: [undefined, 'Isso é A \\ B. A pergunta é B \\ A.', 'Isso é a interseção.', 'Isso junta as duas diferenças.', 'Isso é o próprio B.'] })),
        ex(mcq('m1-q4', 'm1.operacoes', 'U1 · Avaliando · Questão 4', 'A = {C1, C2, C3, C4, C5, C6} (usam X) e B = {C4, C5, C7, C8} (usam Y). Qual operação dá os clientes que usam **apenas** o produto X?', ['Interseção A ∩ B', 'União A ∪ B', 'Diferença A \\ B', 'Diferença B \\ A', 'Conjunto vazio ∅'], 2, 'Apenas X = está em A e não em B = A \\ B = {C1, C2, C3, C6}.')),
        ex(mcq('m1-q5', 'm1.operacoes', 'U1 · Avaliando · Questão 5', 'Com os mesmos A e B: quais clientes estão na interseção, e para que serve essa segmentação?', [
          'C4 e C5; permite campanhas mais focadas em quem utiliza ambos os produtos.',
          'C1, C2 e C3; serve para ampliar o público de produtos exclusivos.',
          'C7 e C8; aponta clientes que não utilizam nenhum produto.',
          'C6, C7 e C8; identifica clientes que só usam o produto Y.',
          'Todos os clientes de A e B; não é relevante para a estratégia de vendas.',
        ], 0, 'A ∩ B = {C4, C5}: os únicos que aparecem nas duas listas.')),
        ex(mcq('m1-q8', 'm1.conjuntos', 'U1 · cards de abertura', 'Segundo o curso, como conjuntos e funções ajudam a organizar bancos de dados?', [
          'Permitem agrupar dados semelhantes (conjuntos) e criar regras claras para relacionar informações diferentes (funções), facilitando busca e análise.',
          'Substituem totalmente a necessidade de tabelas.',
          'Servem apenas para cálculos numéricos, sem relação com dados.',
          'Eliminam a necessidade de consultas.',
        ], 0, 'Tabelas são conjuntos de linhas; as ligações entre elas são relações e funções.', { heuristica: '"Totalmente", "apenas", "eliminam": absolutos são quase sempre distratores.' })),
        ex(mcq('m1-q9', 'm1.funcoes', 'U1 · resumo dos tipos de funções (PDF)', 'Segundo o resumo do curso, por que a criptografia simétrica usa função bijetora?', [
          'Porque a bijetora é invertível: permite decodificar a mensagem original sem perda de informação.',
          'Porque a bijetora leva todas as entradas para o mesmo valor.',
          'Porque a bijetora nunca cobre todo o contradomínio.',
          'Porque a bijetora aceita duas saídas para a mesma entrada.',
        ], 0, 'Bijetora = injetora + sobrejetora = tem inversa. "Todas para o mesmo valor" é função constante.')),
        ex(mcq('m1-q10', 'm1.operacoes', 'U1 · Estudo de caso 1 (SQL)', 'No SQL, qual operação de conjuntos identifica clientes que fizeram um pedido, mas **não** se inscreveram no boletim?', ['EXCEPT (diferença)', 'UNION (união)', 'INTERSECT (interseção)', 'Produto cartesiano'], 0, '"Fizeram pedido E NÃO se inscreveram" é diferença: clientes com pedido − clientes inscritos.')),
        ex(mcq('m1-q11', 'm1.conjuntos', 'U1 · Estudo de caso 2 (algoritmos)', 'Numa busca em grafo (DFS), para que o curso diz que se usa um conjunto (`set`)?', ['Para guardar os nós já visitados, garantindo que não sejam processados de novo', 'Para ordenar os nós por peso', 'Para repetir os nós o máximo possível', 'Para guardar a ordem exata de visita'], 0, 'Conjunto não tem repetição e responde rápido a "já está aqui?". Ordem ele não guarda. Isso volta na região de grafos.')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'm1-chefe', titulo: 'Chefão: segmentação de clientes', tipo: 'chefe', min: 10, resumo: 'Uma empresa de software, três produtos, uma campanha. Tudo da U1 em sequência.',
      steps: [
        texto('**A missão.** Você é o analista de uma empresa de software. O marketing quer três campanhas e precisa dos números certos, sem mandar e-mail em dobro para ninguém.\n\nListas de partida (são as do curso): **A** = clientes do produto X = {C1, C2, C3, C4, C5, C6} e **B** = clientes do produto Y = {C4, C5, C7, C8}.'),
        ex(conj('m1-b1', 'm1.operacoes', 'U1 · Exemplo 1: segmentação de clientes', 'Campanha "combo": só para quem usa **os dois** produtos. Quem recebe?', ['C4', 'C5'], 'A ∩ B = {C4, C5}. Em Python: `clientes_produto_x & clientes_produto_y`.', ['Quem aparece nas duas listas?', 'Percorra A e veja quem também está em B.', 'C4 e C5.'], [{ valor: ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8'], causa: 'conceito', msg: 'Isso é a união (pelo menos um). "Os dois" é interseção.' }])),
        ex(conj('m1-b2', 'm1.operacoes', 'U1 · Exemplo 1: segmentação de clientes', 'Campanha "conheça o Y": para quem usa **só** o X. Quem recebe?', ['C1', 'C2', 'C3', 'C6'], 'A − B = {C1, C2, C3, C6}.', ['É uma diferença. Qual das duas?', 'Pegue A e risque quem também está em B.', 'A − B = {C1, C2, C3, C6}.'], [{ valor: ['C7', 'C8'], causa: 'leitura', msg: 'Você fez B − A (só o Y). A campanha é para quem só tem o X.' }])),
        ex(num('m1-b3', 'm1.inclusao-exclusao', undefined, 'Aviso geral: um e-mail por cliente, para todos que usam **pelo menos um** produto. Quantos e-mails? (Faça pela fórmula, sem contar um por um.)', 8, '|A ∪ B| = 6 + 4 − 2 = 8.', ['|A| = 6, |B| = 4, |A ∩ B| = 2.', '6 + 4 conta C4 e C5 duas vezes.', '6 + 4 − 2 = 8.'], { armadilhas: [{ valor: 10, causa: 'conceito', msg: 'Você somou 6 + 4 e esqueceu de tirar os 2 que estão nas duas listas: C4 e C5 receberiam dois e-mails.' }] })),
        texto('Chegou um terceiro produto, o **Z**. Agora são três listas.'),
        { t: 'gen', gen: 'm1.ie3', n: 1 },
        texto('O sistema guarda, para cada cliente, o **plano** dele. Isso é uma função "cliente → plano". O gerente pergunta se dá para descobrir o cliente a partir do plano.'),
        ex(mcq('m1-b4', 'm1.funcoes', undefined, 'Clientes {C1, C2, C3, C4} e planos {básico, pro, premium}. A função é: C1 → básico, C2 → pro, C3 → pro, C4 → premium. Dá para voltar do plano para o cliente (existe inversa)?', ['Não: C2 e C3 têm o mesmo plano, então a função não é injetora', 'Sim: todos os planos são usados, então é bijetora', 'Não: porque não é função', 'Sim: toda função tem inversa'], 0, 'É função e é sobrejetora (os três planos aparecem), mas não é injetora: "pro" tem dois clientes. Sem ser bijetora, não há inversa.', { fixo: true })),
        { t: 'gen', gen: 'm1.comp', n: 1 },
        {
          t: 'escrita', fonte: 'treino para a A1 dissertativa',
          prompt: 'Escreva como numa prova dissertativa: uma pesquisa mostra que 40 usuários usam o app no celular, 25 no computador e 10 nos dois. Quantos usam pelo menos um? Mostre o raciocínio no formato "defino…, monto…, logo…".',
          modelo: 'Defino C como o conjunto dos usuários de celular e P como o dos usuários de computador. Pelo enunciado, |C| = 40, |P| = 25 e |C ∩ P| = 10. Quero |C ∪ P|. Se eu só somar 40 + 25, os 10 usuários que estão nos dois conjuntos entram duas vezes. Pelo princípio da inclusão-exclusão, |C ∪ P| = |C| + |P| − |C ∩ P| = 40 + 25 − 10 = 55. Logo, 55 usuários usam pelo menos um dos dois. Conferindo: só celular 30, só computador 15, os dois 10; 30 + 15 + 10 = 55.',
          rubrica: ['Dei nome aos conjuntos e disse o que cada um significa', 'Escrevi os dados na notação (|C| = 40 etc.)', 'Expliquei POR QUE não basta somar', 'Citei o nome da ferramenta (inclusão-exclusão) e mostrei a conta', 'Fechei com a resposta em frase completa', 'Conferi o resultado de outro jeito'],
        },
        { t: 'feynman', prompt: 'O que você diria para alguém que acha que "conjuntos e funções" não servem para nada em programação? Dê dois exemplos concretos.' },
      ],
    },
  ],
  cards: cards('mat', 'm1', [
    ['União, interseção, diferença: qual pergunta cada uma responde?', 'União: está em pelo menos um. Interseção: está nos dois. Diferença A − B: está em A e não em B.'],
    ['Fórmula da inclusão-exclusão para dois conjuntos', '|A ∪ B| = |A| + |B| − |A ∩ B|. O desconto tira quem foi contado em dobro.'],
    ['Inclusão-exclusão para três conjuntos', 'Soma os três, tira as três interseções duplas, devolve a tripla.'],
    ['Num Venn com números, por onde começar a preencher?', 'De dentro para fora: primeiro o miolo, depois as duplas, por último o "só".'],
    ['Quantos subconjuntos tem um conjunto de n elementos?', '2ⁿ: cada elemento entra ou não entra. Inclui ∅ e o próprio conjunto.'],
    ['|A × B| = ?', '|A| · |B|. São os pares ordenados (a, b); (a, b) ≠ (b, a).'],
    ['O que é uma relação entre A e B?', 'Qualquer subconjunto de A × B. Função é uma relação com unicidade.'],
    ['O que faz uma relação ser função?', 'Cada elemento do domínio tem exatamente uma saída (nem zero, nem duas).'],
    ['Injetora × sobrejetora × bijetora', 'Injetora: sem colisão. Sobrejetora: todo o contradomínio é atingido. Bijetora: as duas; só ela tem inversa.'],
    ['(g∘f)(x): quem age primeiro?', 'f. (g∘f)(x) = g(f(x)). Composição não é comutativa.'],
    ['A região "apenas A" num Venn de três conjuntos', 'A − (B ∪ C), que é o mesmo que A ∩ B\' ∩ C\'.'],
    ['Em Python, os operadores de conjunto', '| união, & interseção, - diferença. O tipo é set.'],
    ['Diferença entre ∈ e ⊆', '∈ liga um elemento a um conjunto. ⊆ liga um conjunto a outro conjunto.'],
    ['Contradomínio × imagem', 'Contradomínio: onde as saídas podem cair. Imagem: onde elas de fato caem.'],
  ]),
};
