// M2 · Lógica e álgebra booleana (U2 + U3), ensinado do zero: o mesmo conteúdo em duas notações.
// Fontes: fontes/matematica/U2.txt, U3.txt, PDFs da Unidade 3 e quiz da U8.
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, expr, ficha, gen, mcq, num, texto } from '../ajuda';

export const M2: Regiao = {
  id: 'm2', mundo: 'mat', nome: 'Lógica e álgebra booleana', unidades: 'U2 + U3', pronto: true,
  tese: 'Lógica (V/F, ∧ ∨ ¬) e álgebra booleana (1/0, · + \') são a mesma coisa escrita de dois jeitos. Todo if e todo chip rodam sobre isso.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'm2-prop', titulo: 'Aula 1 · Frases que a máquina entende', tipo: 'licao', min: 10, resumo: 'Do zero: o que é proposição, e os três conectivos básicos (NÃO, E, OU).',
      steps: [
        texto('**O problema.** Você quer que a mesa de som da igreja desligue sozinha os microfones quando ninguém está usando. Para isso, alguém precisa escrever a regra para a máquina.\n\nUma máquina não entende "mais ou menos", "talvez" ou "depende do dia". Ela só consegue trabalhar com afirmações que são **verdadeiras** ou **falsas**, sem meio-termo. A lógica é a matéria que estuda como escrever e combinar esse tipo de afirmação.'),
        texto('**Proposição.** É o nome de uma frase que **afirma** alguma coisa e que, por isso, pode ser julgada: ou é **verdadeira (V)** ou é **falsa (F)**.\n\n- "O microfone 1 está ligado." → dá para julgar. É proposição.\n- "3 é um número ímpar." → proposição (verdadeira).\n- "O Rio Amazonas fica na Europa." → proposição também! É **falsa**, mas dá para julgar.\n\nO que **não** é proposição:\n\n- Ordens: "Abra a porta."\n- Perguntas: "Que horas são?"\n- Desejos e exclamações: "Tomara que chova!"\n- **Sentenças abertas**: "x + 2 = 4". Enquanto ninguém disser quanto vale x, não dá para julgar.\n\nO teste não é "isso é verdade?". O teste é "**dá para dizer se é verdade ou mentira?**".'),
        ex(mcq('m2-l1', 'm2.proposicoes', 'U2 · cards de abertura', '"Lave o carro agora!" é uma proposição?', ['Não: é uma ordem, e ordens não têm valor lógico', 'Sim: toda frase é uma proposição', 'Sim, e é falsa'], 0, 'Frases imperativas expressam ordens; não dá para dizer que são verdadeiras ou falsas.', { fixo: true })),
        gen('m2.prop', 2),
        texto('**Letras no lugar de frases.** Para não reescrever a frase toda hora, cada proposição ganha uma letra minúscula:\n\n- $p$: "o microfone está ligado"\n- $q$: "tem alguém cantando"\n\nEssas são **proposições simples**: não dá para quebrar em pedaços menores. As regras de verdade aparecem quando você **combina** proposições simples com palavrinhas como "não", "e", "ou", "se… então". Essas palavrinhas se chamam **conectivos**, e o resultado é uma **proposição composta**.\n\nVamos ver um conectivo de cada vez. Para cada um, a pergunta é sempre a mesma: **quando a frase composta é verdadeira?**'),
        texto('**1. Negação (NÃO).** Símbolo: $\\lnot p$ (o curso também escreve $\\sim p$). Lê-se "não p".\n\nEla só inverte: se $p$ é V, $\\lnot p$ é F; se $p$ é F, $\\lnot p$ é V.\n\n$p$: "o microfone está ligado". $\\lnot p$: "o microfone **não** está ligado".\n\n**2. Conjunção (E).** Símbolo: $p \\land q$. Lê-se "p e q".\n\n"O microfone está ligado **e** tem alguém cantando." Para essa frase ser verdadeira, as **duas** partes precisam ser verdadeiras. Se qualquer uma falhar, a frase inteira é falsa.\n\nMacete do símbolo: $\\land$ parece um "A" sem o traço, de **A**ND ("e" em inglês).'),
        ex(cheque('m2-k01', 'm2.conectivos', '$p$ é V e $q$ é F. Quanto vale $p \\land q$?', ['F, porque o E exige as duas verdadeiras', 'V, porque pelo menos uma é verdadeira', 'Não dá para saber'], 0, 'O E só é V quando as duas partes são V. Aqui q falhou.')),
        texto('**3. Disjunção (OU).** Símbolo: $p \\lor q$. Lê-se "p ou q".\n\n"A porta está aberta **ou** a janela está aberta." Para um alarme, basta **uma** das duas. E se as duas estiverem abertas? O alarme toca do mesmo jeito.\n\nEsse é o "ou" da lógica, chamado **inclusivo**: é verdadeiro quando **pelo menos uma** parte é verdadeira (inclusive as duas). Só é falso quando as duas são falsas.\n\nNo dia a dia, "ou" às vezes quer dizer "um ou outro, não os dois" ("café ou chá?"). Esse é o "ou exclusivo", que tem símbolo próprio ($\\oplus$, o XOR) e aparece mais adiante. Na lógica, "ou" sem aviso é sempre o inclusivo.'),
        ex(cheque('m2-k02', 'm2.conectivos', '$p$ é V e $q$ é V. Quanto vale $p \\lor q$?', ['V: o OU da lógica aceita as duas verdadeiras', 'F: só pode uma', 'Depende'], 0, 'OU inclusivo: só é falso quando as duas partes são falsas.')),
        texto('**Você já viu isso.** Lembra das operações de conjuntos da região anterior?\n\n- Interseção $\\cap$ (está nos dois) é o **E** $\\land$.\n- União $\\cup$ (está em pelo menos um) é o **OU** $\\lor$.\n- Complemento (está fora) é o **NÃO** $\\lnot$.\n\nAté os símbolos se parecem: $\\cap$ e $\\land$ apontam para cima; $\\cup$ e $\\lor$ abrem para cima. Não é coincidência: é a mesma estrutura.'),
        ex(mcq('m2-q3', 'm2.conectivos', 'U2 · Avaliando · Exercício 1', 'Questão do curso. Um alarme deve tocar se a porta **não** estiver trancada. Qual operador inverte o valor lógico de uma proposição?', ['Conjunção (^)', 'Disjunção (v)', 'Negação (~)', 'Condicional (→)', 'Bicondicional (↔)'], 2, 'A negação transforma V em F e F em V.')),
        ex(mcq('m2-r-neg', 'm2.conectivos', 'U2 · cards de abertura', 'Qual é a negação de "Todo programador sabe lógica"?', ['Pelo menos um programador não sabe lógica.', 'Nenhum programador sabe lógica.', 'Todo programador não sabe lógica.', 'Algum programador sabe lógica.'], 0, 'Negar é dizer exatamente o que basta para a frase original ser falsa. Para derrubar um "todo", basta um contraexemplo. "Nenhum" é forte demais.')),
        ficha({
          titulo: 'Proposições e NÃO, E, OU: a ficha',
          porque: 'Um `if` só funciona com condição que dá verdadeiro ou falso. A lógica é o vocabulário para escrever regras sem ambiguidade.',
          ideia: 'Proposição: frase declarativa com um valor, V ou F. Conectivos combinam proposições.',
          regra: '$$\\begin{aligned} \\lnot p &: \\text{inverte} \\\\ p \\land q &: \\text{V só com as duas V} \\\\ p \\lor q &: \\text{F só com as duas F} \\end{aligned}$$',
          exemplo: '"3 é ímpar" (V). "O Amazonas fica na Europa" (F, mas é proposição). "Abra a porta" e "x + 2 = 4" não são.',
          armadilha: 'Proposição falsa continua sendo proposição. E o "ou" da lógica aceita os dois ao mesmo tempo.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'm2-cond', titulo: 'Aula 2 · "Se… então": a promessa', tipo: 'licao', min: 9, resumo: 'A condicional (a que mais cai), a bicondicional e a ordem dos conectivos.',
      steps: [
        texto('**O problema.** Seu pai promete: "**Se** você passar de ano, **então** eu te dou um violão."\n\nExistem quatro finais possíveis para essa história. Em qual (ou quais) deles seu pai **quebrou a promessa**?\n\n1. Você passou e ganhou o violão.\n2. Você passou e **não** ganhou.\n3. Você não passou e ganhou mesmo assim.\n4. Você não passou e não ganhou.'),
        ex(cheque('m2-k03', 'm2.condicional', 'Em qual final a promessa foi quebrada?', ['Só no 2: passou e não ganhou', 'No 2 e no 3', 'No 2, no 3 e no 4'], 0, 'No 3, ele foi generoso: a promessa não dizia nada sobre o que aconteceria se você não passasse. No 4, idem. Só no 2 ele prometeu e não cumpriu.')),
        texto('**Condicional.** A frase "se p, então q" se escreve $p \\to q$. A parte $p$ é a **condição** e $q$ é a **consequência**.\n\nElas funcionam como a promessa: a condicional só é **falsa** quando a condição acontece e a consequência não vem. Ou seja, só em **V → F**.\n\n- V → V: verdadeira (passou, ganhou)\n- **V → F: falsa** (passou, não ganhou)\n- F → V: verdadeira (não passou, ganhou assim mesmo)\n- F → F: verdadeira (não passou, não ganhou)\n\nA parte estranha são as duas últimas: quando a condição é falsa, a condicional é verdadeira **de qualquer jeito**. Pense assim: a promessa só é testada quando a condição acontece. Se não aconteceu, ninguém mentiu.'),
        texto('**Um erro no material.** Um card da U2 diz que a condicional "apresenta o valor falso quando o segundo valor lógico for falso". Isso está **errado**: em F → F o segundo é falso e a condicional é verdadeira. A tabela da própria unidade está certa: só V → F é falso.\n\nSe cair em prova, vale a tabela: **só V → F**.', 'erro', 'Card "Operadores lógicos" da U2. Conferido por código: p → q é falsa apenas com p = V e q = F.'),
        gen('m2.cond', 4),
        ex(mcq('m2-q5', 'm2.condicional', 'U2 · Avaliando · Exercício 3', 'Questão do curso. "Se o cliente comprar acima de R$ 500 (P), então ganha um cupom (Q)." Quando a condicional P → Q é falsa?', ['Quando P é verdadeiro e Q é falso', 'Quando P é falso e Q é verdadeiro', 'Quando ambas são falsas', 'Quando P e Q têm o mesmo valor lógico', 'Quando P é verdadeiro e Q também'], 0, 'O "contrato" só é quebrado quando o cliente compra e o cupom não sai.')),
        texto('**Bicondicional.** Às vezes a regra vale nos dois sentidos: "a porta abre **se e somente se** o crachá é válido". Crachá válido: abre. Crachá inválido: não abre. Nada de surpresas.\n\nEscreve-se $p \\leftrightarrow q$. É verdadeira quando os dois lados têm **o mesmo valor** (os dois V ou os dois F), e falsa quando são diferentes.\n\nÉ como duas promessas ao mesmo tempo: $p \\to q$ e $q \\to p$.'),
        ex(cheque('m2-k04', 'm2.conectivos', '$p$ é F e $q$ é F. Quanto vale $p \\leftrightarrow q$?', ['V: os dois lados têm o mesmo valor', 'F: os dois são falsos', 'Não dá para saber'], 0, 'A bicondicional pergunta "são iguais?". F e F são iguais, então é V.')),
        texto('**Quem vem primeiro?** Numa conta como $2 + 3 \\times 4$, você faz a multiplicação antes. Na lógica também há uma ordem, quando não existem parênteses:\n\n1. $\\lnot$ (negação)\n2. $\\land$ (e)\n3. $\\lor$ (ou)\n4. $\\to$ (se… então)\n5. $\\leftrightarrow$ (se e somente se)\n\nEntão $\\lnot p \\lor q \\land r$ quer dizer $(\\lnot p) \\lor (q \\land r)$.\n\nNa dúvida, **use parênteses**. Eles nunca atrapalham, e o que está dentro deles é sempre feito primeiro.'),
        ex(cheque('m2-k05', 'm2.conectivos', 'Com $p$ = F, $q$ = V, $r$ = F: quanto vale $p \\lor q \\land r$?', ['F: primeiro q ∧ r = F, depois F ∨ F = F', 'V: primeiro p ∨ q = V, depois V ∧ r…', 'V: tem um V no meio'], 0, 'O ∧ vem antes do ∨. q ∧ r = V ∧ F = F. Depois p ∨ F = F ∨ F = F.')),
        ficha({
          titulo: 'Condicional e bicondicional: a ficha',
          porque: 'Quase toda regra de negócio é "se acontecer isso, então faça aquilo". Saber exatamente quando ela é violada é o que permite testá-la.',
          ideia: '$p \\to q$ é uma promessa: só é quebrada quando p acontece e q não. $p \\leftrightarrow q$ pergunta se os dois lados são iguais.',
          regra: '$$p \\to q \\text{ é falsa só em } V \\to F$$\n\n$$\\lnot \\; > \\; \\land \\; > \\; \\lor \\; > \\; \\to \\; > \\; \\leftrightarrow$$',
          exemplo: '"Se comprar acima de R$ 500, ganha cupom." Não comprou e ganhou cupom: regra respeitada.',
          armadilha: 'Condição falsa deixa a condicional verdadeira. E $q \\to p$ (a recíproca) não é a mesma coisa que $p \\to q$.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB CHAVES
    {
      id: 'm2-chaves', titulo: 'Laboratório · Interruptores', tipo: 'lab', min: 6, resumo: 'Chaves, expressão, tabela e lâmpada reagindo juntas.',
      steps: [
        texto('Neste painel, cada proposição é uma **chave**: ligada quer dizer V, desligada quer dizer F. A **lâmpada** mostra o valor da frase composta: acesa é V.\n\nEmbaixo aparece uma tabela com todas as combinações de chaves; a linha em que você está fica destacada. Essa tabela é o assunto da próxima aula. Por enquanto, só brinque.'),
        { t: 'toy', toy: 'interruptores', modo: 'livre', preset: 'cond', intro: 'A expressão carregada é a condicional p → q. Ligue e desligue p e q e veja a lâmpada. Depois apague e digite a sua expressão (use o teclado de símbolos). Ligue "Prever antes" para o jogo perguntar o que vai acontecer antes de mostrar.' },
        { t: 'toy', toy: 'interruptores', modo: 'desafio', intro: 'Três desafios com expressões do curso.', desafios: ['i-cond', 'i-atalho', 'i-aegis'] },
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'm2-tabela', titulo: 'Aula 3 · Tabela-verdade', tipo: 'licao', min: 12, resumo: 'Testar todas as possibilidades, uma coluna de cada vez. Tautologia, contradição e contingência.',
      steps: [
        texto('**O problema.** Uma casa inteligente tem 3 sensores, cada um ligado ou desligado. Você escreveu a regra do alarme e quer ter **certeza** de que ela nunca se comporta errado. Quantas situações precisa testar?\n\nCada sensor tem 2 estados. Com 1 sensor, 2 situações. O segundo sensor dobra: 4. O terceiro dobra de novo: **8**.\n\nÉ o mesmo $2^n$ da região anterior (cada elemento "entra ou não entra"). Com $n$ proposições, existem $2^n$ combinações de V e F.'),
        gen('m2.linhas', 1),
        texto('**Tabela-verdade** é a lista dessas combinações, uma por linha, com o valor da frase composta calculado em cada uma. É o **teste exaustivo**: nenhuma situação fica de fora.\n\nComo montar, com duas proposições $p$ e $q$ (4 linhas):\n\n- Coluna de $p$: V, V, F, F (muda a cada 2 linhas).\n- Coluna de $q$: V, F, V, F (muda a cada linha).\n\nAssim as quatro combinações aparecem sem repetir: VV, VF, FV, FF. Com três proposições, a primeira coluna muda a cada 4 linhas, a segunda a cada 2, a terceira a cada 1.'),
        texto('**Exemplo passo a passo** (é do curso): $\\lnot(p \\lor \\lnot q)$.\n\nO segredo é **uma coluna de cada vez**, de dentro para fora:\n\n- **1ª coluna extra:** $\\lnot q$. Inverta a coluna de $q$: F, V, F, V.\n- **2ª:** $p \\lor \\lnot q$. Em cada linha, faça o OU entre $p$ e a coluna que acabou de calcular: V, V, F, V.\n- **3ª:** a negação de tudo. Inverta a coluna anterior: F, F, **V**, F.\n\nLinha por linha:\n\n- $p$=V, $q$=V: $\\lnot q$=F; V ∨ F = V; negando: **F**\n- $p$=V, $q$=F: $\\lnot q$=V; V ∨ V = V; negando: **F**\n- $p$=F, $q$=V: $\\lnot q$=F; F ∨ F = F; negando: **V**\n- $p$=F, $q$=F: $\\lnot q$=V; F ∨ V = V; negando: **F**\n\nQuase todo erro de tabela é tentar pular direto para a última coluna.'),
        ex(num('m2-r-tab', 'm2.tabela', 'U2 · Tabelas-verdade', 'Ao preencher a tabela-verdade de ~(p v ~q), quantos valores **V** aparecem na última coluna?', 1, 'p ∨ ¬q só é F em p = F, q = V. Negando, só essa linha vira V: **1**.', ['A tabela tem 4 linhas.', 'Descubra em quais linhas p ∨ ¬q é falsa: são essas que viram V.', 'Só em p = F, q = V. Resposta: 1.'], { armadilhas: [{ valor: 3, causa: 'conta', msg: 'Você contou os V de p ∨ ¬q. Falta a negação de fora, que inverte tudo.' }] })),
        texto('Agora você. Nos próximos exercícios, toque nas células para alternar entre V e F. Faça as colunas intermediárias com calma.'),
        gen('m2.tabela', 3),
        texto('**Três tipos de coluna final.** Depois de montar a tabela, olhe só para a última coluna:\n\n- Se deu **V em todas** as linhas, a frase é uma **tautologia**. Ela é verdadeira por causa da própria forma, não importa a situação. Exemplo: $p \\lor \\lnot p$ ("chove ou não chove").\n- Se deu **F em todas**, é uma **contradição**. Exemplo: $p \\land \\lnot p$ ("chove e não chove").\n- Se **mistura** V e F, é uma **contingência**: depende do caso. Quase toda regra útil é contingência.\n\nTautologia não quer dizer "frase verdadeira". Quer dizer "verdadeira em **todas** as linhas".'),
        gen('m2.classe', 2),
        texto('**Uma tautologia famosa: modus ponens.** É o raciocínio mais comum que existe:\n\n- "Se chove, a rua molha." ($p \\to q$)\n- "Está chovendo." ($p$)\n- "Logo, a rua está molhada." ($q$)\n\nEscrito como uma frase só: $[p \\land (p \\to q)] \\to q$. Se você montar a tabela, a última coluna dá V nas 4 linhas. É por ser tautologia que esse raciocínio é **sempre válido**, seja qual for o assunto.'),
        { t: 'toy', toy: 'interruptores', modo: 'desafio', intro: 'Preveja antes e depois confira passando por todas as linhas.', desafios: ['i-aegis5', 'i-mp'] },
        ex(mcq('m2-r-mp', 'm2.tautologia', 'U2 · Tautologia', 'A proposição [P ∧ (P → Q)] → Q (modus ponens) é uma tautologia?', ['Certo: é uma tautologia', 'Errado: não é uma tautologia'], 0, 'Dá V nas 4 linhas. O único jeito de falhar seria o lado esquerdo V e Q falso; mas com P verdadeiro e P → Q verdadeiro, Q tem que ser verdadeiro.', { fixo: true })),
        ficha({
          titulo: 'Tabela-verdade: a ficha',
          porque: 'É o teste exaustivo: você verifica todas as situações possíveis de uma regra. Em software, é testar todos os casos de um `if`.',
          ideia: 'Uma linha por combinação de V/F; uma coluna intermediária de cada vez, de dentro dos parênteses para fora.',
          regra: '$$n \\text{ proposições} \\Rightarrow 2^n \\text{ linhas}$$\n\n$$\\text{sempre V: tautologia} \\quad \\text{sempre F: contradição} \\quad \\text{mistura: contingência}$$',
          exemplo: '$\\lnot(p \\lor \\lnot q)$: colunas $\\lnot q$, depois $p \\lor \\lnot q$, depois a negação. Um único V, em p = F, q = V.',
          armadilha: 'Pular colunas intermediárias. E esquecer a negação de fora.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'm2-equiv', titulo: 'Aula 4 · Dizer a mesma coisa de outro jeito', tipo: 'licao', min: 10, resumo: 'Equivalência, as leis de De Morgan, a condicional sem seta e a contrapositiva.',
      steps: [
        texto('**O problema.** O sistema só libera o culto ao vivo quando "o servidor está ligado **e** respondendo". Alguém avisa: "**não é verdade** que o servidor está ligado e respondendo."\n\nO que isso quer dizer exatamente?\n\n- (a) O servidor está desligado **e** não está respondendo.\n- (b) O servidor está desligado **ou** não está respondendo.'),
        ex(cheque('m2-k06', 'm2.equivalencias', 'Qual das duas frases diz o mesmo que "não é verdade que está ligado E respondendo"?', ['(b): desligado OU não respondendo', '(a): desligado E não respondendo', 'As duas dizem o mesmo'], 0, 'Para "ligado E respondendo" ser falso, basta UMA das duas coisas falhar. Ele pode estar ligado e travado, por exemplo. Então é OU.')),
        texto('**Equivalência.** Duas frases são **equivalentes** quando têm o mesmo valor em **todas** as situações, isto é, a mesma coluna final na tabela-verdade. Escreve-se com $\\equiv$.\n\nO que você acabou de descobrir é a primeira **lei de De Morgan**:\n\n$$\\lnot(p \\land q) \\equiv \\lnot p \\lor \\lnot q$$\n\nE existe a gêmea, para o OU:\n\n$$\\lnot(p \\lor q) \\equiv \\lnot p \\land \\lnot q$$\n\n"Não é verdade que choveu ou ventou" = "não choveu **e** não ventou".\n\nA receita das duas: a negação entra no parêntese, **nega cada parte e troca o conectivo** (E vira OU, OU vira E).'),
        { t: 'toy', toy: 'interruptores', modo: 'desafio', intro: 'O painel agora compara duas expressões. Primeiro ache a linha em que a versão errada falha; depois conserte.', desafios: ['i-dm', 'i-dm2'] },
        texto('**Por que isso importa?** Porque equivalentes podem ser **trocadas** uma pela outra sem mudar o comportamento. É a base de simplificar um `if` gigante: você reescreve a condição de um jeito menor e tem a prova (a tabela) de que nada mudou.\n\nMais duas equivalências que o curso usa:\n\n**A condicional sem seta.** $p \\to q \\equiv \\lnot p \\lor q$. Confira com a promessa: ela só é quebrada em "passou e não ganhou". Então ela é cumprida quando "não passou **ou** ganhou".\n\n**A contrapositiva.** $p \\to q \\equiv \\lnot q \\to \\lnot p$. "Se chove, a rua molha" diz o mesmo que "se a rua não está molhada, não choveu".\n\nCuidado: a **recíproca** $q \\to p$ ("se a rua está molhada, choveu") **não** é equivalente. Pode ter sido um caminhão-pipa.'),
        gen('m2.equiv', 4),
        ex(mcq('m2-r-dm', 'm2.equivalencias', 'U2 · Estudo guiado (equivalências)', 'Qual é a equivalência correta de ~(P ∨ Q), e o que ela permite?', [
          '~P ∧ ~Q, permitindo substituir a negação da disjunção pela conjunção das negações, simplificando argumentos sem alterar sua validade.',
          '~P ∨ ~Q, o que possibilita transformar a disjunção eliminando a negação distribuída.',
          'P ∧ Q, pois a negação da disjunção implicaria a conjunção direta das proposições originais.',
          'P ∨ Q, pois a negação da disjunção não altera o operador lógico original.',
          '~(P ∧ Q), indicando que a equivalência se dá com a negação da conjunção.',
        ], 0, 'De Morgan: nega cada parte e troca ∨ por ∧. "Disjunção" é o nome do OU; "conjunção" é o nome do E.')),
        ficha({
          titulo: 'Equivalências: a ficha',
          porque: 'Duas expressões equivalentes fazem a mesma coisa; a menor gasta menos. É refatoração com prova.',
          ideia: 'Equivalentes = mesma coluna final. De Morgan: a negação atravessa o parêntese negando cada parte e trocando o conectivo.',
          regra: '$$\\lnot(p \\land q) \\equiv \\lnot p \\lor \\lnot q$$\n\n$$\\lnot(p \\lor q) \\equiv \\lnot p \\land \\lnot q$$\n\n$$p \\to q \\equiv \\lnot p \\lor q \\equiv \\lnot q \\to \\lnot p$$',
          exemplo: '"Não é verdade que choveu ou ventou" = "não choveu e não ventou".',
          armadilha: 'Negar um E não dá outro E. E a recíproca não é equivalente; a contrapositiva é.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 5
    {
      id: 'm2-bool', titulo: 'Aula 5 · De V/F para 1/0', tipo: 'licao', min: 9, resumo: 'A álgebra booleana é a mesma lógica com cara de conta. A tradução e a precedência.',
      steps: [
        texto('**A ideia de Boole.** Por volta de 1850, o matemático George Boole percebeu que dá para tratar raciocínio como **conta**. Em vez de V e F, use números:\n\n- Verdadeiro = **1**\n- Falso = **0**\n\nIsso casa com a eletrônica: um fio **com** tensão é 1, **sem** tensão é 0. Um computador inteiro é feito de bilhões desses "sim ou não". Cada um é um **bit**.\n\nA U3 do curso é exatamente a U2 reescrita assim. Nada de conteúdo novo por enquanto: só troca de roupa.'),
        texto('**O E vira multiplicação.** Veja a multiplicação comum com 0 e 1:\n\n- $1 \\cdot 1 = 1$\n- $1 \\cdot 0 = 0$\n- $0 \\cdot 1 = 0$\n- $0 \\cdot 0 = 0$\n\nSó dá 1 quando os dois são 1. É exatamente o **E**! Por isso, na álgebra booleana, $p \\land q$ se escreve $A \\cdot B$ (ou só $AB$, com as letras coladas).\n\n**O OU vira soma**, com uma única surpresa:\n\n- $0 + 0 = 0$\n- $0 + 1 = 1$\n- $1 + 0 = 1$\n- $1 + 1 = \\mathbf{1}$\n\nNão existe "2" aqui: só existem 0 e 1. "Verdadeiro ou verdadeiro" é verdadeiro. $p \\lor q$ se escreve $A + B$.\n\n**O NÃO vira um apóstrofo ou uma barra:** $\\lnot p$ se escreve $A\'$ ou $\\overline{A}$. O curso às vezes escreve também $\\sim A$. $0\' = 1$ e $1\' = 0$.'),
        ex(cheque('m2-k07', 'm2.traducao', 'Na álgebra booleana, quanto é $1 + 1$?', ['1', '2', '0'], 0, 'Só existem 0 e 1. O + é o OU: verdadeiro OU verdadeiro = verdadeiro = 1.')),
        ex(mcq('m2-l2', 'm2.traducao', undefined, 'Como fica $p \\lor (q \\land r)$ em notação booleana?', ['P + Q·R', 'P · (Q + R)', '(P + Q) · R', 'P + Q + R'], 0, '∨ vira + e ∧ vira ·. Guarde essa expressão: é a do Aegis-Grid, o caso final da disciplina.', { fixo: true })),
        texto('**A ordem das operações** é a da escola: primeiro parênteses, depois o **NÃO**, depois o **produto**, depois a **soma**.\n\n$$A + B \\cdot C = A + (B \\cdot C)$$\n\nQuanto vale $1 + 1 \\cdot 0$? Primeiro o produto: $1 \\cdot 0 = 0$. Depois a soma: $1 + 0 = 1$.\n\nE $(1 + 1) \\cdot 0$? Primeiro o parêntese: 1. Depois $1 \\cdot 0 = 0$. O parêntese mudou o resultado.\n\nExemplo do material (livro do Stallings): $D = A + (\\overline{B} \\cdot C)$. Lendo: D vale 1 se A for 1, **ou** se B for 0 **e** C for 1.'),
        gen('m2.bool', 3),
        ex(mcq('m2-q7', 'm2.traducao', 'U2 · Aplicações em computação', 'Questão do curso. A função f = A · ~B controla um sistema de segurança. Em quais condições f = 1?', ['Somente com A = 1 e B = 0.', 'Somente com A = 1 e B = 1.', 'Somente com A = 0 e B = 1.', 'Somente com A = 0 e B = 0.', 'Com A = 0 e B = 0, ou A = 1 e B = 1.'], 0, 'Um produto só dá 1 com todos os fatores em 1: A = 1 e ~B = 1, isto é, B = 0.')),
        texto('**Do português para a expressão.** A parte mais cobrada é traduzir uma regra escrita. Método:\n\n1. Dê uma letra a cada condição.\n2. Troque "e" por ·, "ou" por +, "não" por \'.\n3. Decida onde vão os **parênteses**: o que está "junto" na frase fica junto na expressão.\n\nExemplo do curso: "o alarme dispara caso a porta **ou** a janela estejam abertas **e** o sistema esteja ativado". O "sistema ativado" vale para as duas aberturas. Então: $(P + J) \\cdot S$.\n\nSem parênteses, $P + J \\cdot S$ seria $P + (J \\cdot S)$: a porta sozinha dispararia o alarme mesmo com o sistema desligado.'),
        ex(mcq('m2-q11', 'm2.traducao', 'U3 · Avaliando · Questão 5', 'O alarme dispara caso a porta OU a janela estejam abertas E o sistema esteja ativado. Qual expressão representa isso?', ['(Porta aberta OU Janela aberta) E Sistema ativado', 'Porta aberta E Janela aberta E Sistema ativado', '(Porta aberta E Janela aberta) OU Sistema ativado', 'Porta aberta OU (Janela aberta E Sistema ativado)', 'Sistema ativado E (Porta aberta NÃO OU Janela aberta)'], 0, 'O "E o sistema ativado" vale para as duas aberturas, então o OU fica entre parênteses.')),
        ficha({
          titulo: 'A tradução: a ficha',
          porque: 'Com conta, dá para simplificar no papel antes de gastar transistor. E é assim que as condições aparecem em código e em circuitos.',
          ideia: 'V = 1, F = 0, E = ·, OU = +, NÃO = \'. É a mesma lógica com outra escrita.',
          regra: "$$\\text{parênteses} \\;\\to\\; \\text{'} \\;\\to\\; \\cdot \\;\\to\\; +$$\n\n$$1 + 1 = 1 \\qquad A + B \\cdot C = A + (B \\cdot C)$$",
          exemplo: '$p \\lor (q \\land r)$ vira $P + (Q \\cdot R)$. "Porta ou janela, e sistema ativado" vira $(P + J) \\cdot S$.',
          armadilha: 'AB + C é (AB) + C, nunca A(B + C). Letras coladas são um produto.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 6
    {
      id: 'm2-leis', titulo: 'Aula 6 · As leis e a arte de enxugar', tipo: 'licao', min: 11, resumo: 'As leis da álgebra booleana, descobertas uma a uma, e como usá-las para simplificar.',
      steps: [
        texto('**Para que simplificar?** Cada operação de uma expressão vai virar um componente físico num chip (a próxima aula mostra). Menos operações = menos componentes = mais barato, mais rápido, menos energia. Essa frase é resposta de várias questões do curso.\n\nPara simplificar com segurança, usamos **leis**: equivalências que valem sempre. Você não precisa acreditar em nenhuma: dá para conferir cada uma testando com 0 e com 1.'),
        texto('**As leis fáceis.** Teste cada uma trocando $x$ por 0 e depois por 1:\n\n- **Identidade:** $x + 0 = x$ e $x \\cdot 1 = x$. (Somar zero ou multiplicar por um não muda nada, como na escola.)\n- **Anulação:** $x + 1 = 1$ e $x \\cdot 0 = 0$. (Se um lado do OU já é verdadeiro, o resultado é verdadeiro e pronto.)\n- **Idempotência:** $x + x = x$ e $x \\cdot x = x$. ("Chove ou chove" é só "chove".)\n- **Complemento:** $x + x\' = 1$ e $x \\cdot x\' = 0$. ("Chove ou não chove" é sempre verdade; "chove e não chove" nunca é.)\n- **Dupla negação:** $(x\')\' = x$.\n\nTambém valem a **comutativa** (a ordem não importa: $x + y = y + x$) e a **associativa** (o agrupamento não importa: $(x + y) + z = x + (y + z)$), para a soma e para o produto.'),
        ex(cheque('m2-k08', 'm2.simplificacao', 'Quanto vale $A + 1$, seja qual for o A?', ['1', 'A', '0'], 0, 'Lei da anulação: se um lado do OU é 1, o resultado é 1. Teste: 0 + 1 = 1 e 1 + 1 = 1.')),
        texto('**Distributiva: pôr em evidência.** Igual à escola:\n\n$$x(y + z) = xy + xz$$\n\nLida da direita para a esquerda, ela é "pôr o fator comum em evidência", e é a ferramenta principal de simplificação.\n\nExemplo que cai no curso: $S = A \\cdot B + A \\cdot B\'$.\n\n- O $A$ aparece nos dois termos. Em evidência: $A \\cdot (B + B\')$.\n- Pelo complemento, $B + B\' = 1$. Fica $A \\cdot 1$.\n- Pela identidade, $A \\cdot 1 = A$.\n\nResultado: $S = A$. O sensor B **não faz diferença nenhuma**. Quatro operações viraram zero.'),
        ex(mcq('m2-r-u8b', 'm2.simplificacao', 'U8 · quiz diagnóstico', 'A lógica de um alarme é S = (A · B) + (A · ~B). Qual é a forma simplificada?', ['S = B', 'S = A + B', 'S = A', 'S = A · B', 'S = 1 (sempre verdadeiro)'], 2, "Distributiva: A·(B + B'). Complemento: B + B' = 1. Identidade: A·1 = A.")),
        texto('**Duas leis que só existem aqui.**\n\n**A distributiva "estranha":** na álgebra booleana, a soma também distribui sobre o produto:\n\n$$x + yz = (x + y)(x + z)$$\n\nNa escola isso é falso ($2 + 3 \\cdot 4 \\neq 5 \\cdot 6$); com 0 e 1, funciona.\n\n**Absorção:**\n\n$$x + xy = x$$\n\nPense: se $x$ é 1, o resultado já é 1. Se $x$ é 0, $xy$ também é 0. O termo $xy$ nunca muda nada: é "absorvido".\n\nE **De Morgan**, que você já conhece, na roupa nova: $(xy)\' = x\' + y\'$ e $(x + y)\' = x\'y\'$.', 'alem', 'A absorção não está na lista de leis do texto da U3 (aparece só na tabela do Stallings, em imagem). Entra porque resolve muita simplificação.'),
        texto("**Um exemplo completo.** Simplifique $X + XY + X'Y$.\n\n- $X + XY = X$ (absorção). Sobra $X + X'Y$.\n- Distributiva estranha: $X + X'Y = (X + X')(X + Y)$.\n- Complemento: $X + X' = 1$. Fica $1 \\cdot (X + Y) = X + Y$.\n\nComo procurar, em ordem: (1) fator comum para pôr em evidência; (2) pares $x + x'$, que viram 1; (3) absorção.\n\nO curso cita também o **mapa de Karnaugh**: uma tabela desenhada de um jeito especial em que você simplifica circulando grupos de 1 vizinhos. É outra técnica para o mesmo objetivo; aqui basta saber que existe e para que serve."),
        gen('m2.simpl', 3),
        { t: 'toy', toy: 'bancada', modo: 'desafio', intro: 'Dois circuitos com peças sobrando. Você ainda não conhece as portas em detalhe (é a próxima fase), mas dá para fazer: o desafio é ligar a lâmpada de um jeito equivalente SEM nenhuma porta.', desafios: ['b-enxugar', 'b-absorcao'] },
        ex(mcq('m2-r-simp', 'm2.simplificacao', 'U3 · Efetivando · Quizz 1', 'Como a simplificação de expressões booleanas impacta o desenvolvimento de sistemas digitais?', [
          'Reduz o número de portas lógicas necessárias, o que diminui o custo e aumenta a velocidade de processamento dos circuitos.',
          'Aumenta o número de portas lógicas para garantir maior segurança e redundância.',
          'Aumenta a complexidade dos circuitos, tornando-os mais lentos e caros.',
          'Serve apenas para facilitar a leitura dos códigos, sem impacto prático no hardware.',
          'Não é relevante, pois as operações básicas são sempre as mesmas.',
        ], 0, 'Menos portas, menos custo, mais velocidade.', { heuristica: '"Apenas", "não é relevante": alternativas absolutas ou que negam a utilidade do tema costumam ser distratores.' })),
        ficha({
          titulo: 'As leis: a ficha',
          porque: 'São as ferramentas de simplificação. Cada lei é uma equivalência que você pode conferir por tabela-verdade.',
          ideia: 'Quase tudo é igual à álgebra da escola. As diferentes: $x + x = x$, $x + 1 = 1$, $x + x\' = 1$, a distributiva estranha e a absorção.',
          regra: "$$\\begin{aligned} \\text{identidade} &\\quad x+0=x,\\;\\; x\\cdot 1=x \\\\ \\text{anulação} &\\quad x+1=1,\\;\\; x\\cdot 0=0 \\\\ \\text{idempotência} &\\quad x+x=x,\\;\\; x\\cdot x=x \\\\ \\text{complemento} &\\quad x+x'=1,\\;\\; x\\cdot x'=0 \\\\ \\text{distributiva} &\\quad x(y+z)=xy+xz \\\\ \\text{a estranha} &\\quad x+yz=(x+y)(x+z) \\\\ \\text{absorção} &\\quad x+xy=x \\\\ \\text{De Morgan} &\\quad (xy)'=x'+y' \\\\ &\\quad (x+y)'=x'y' \\end{aligned}$$",
          exemplo: "$AB + AB' = A(B + B') = A \\cdot 1 = A$.",
          armadilha: 'Não existe "cancelar" ou "passar para o outro lado" como na álgebra comum. Só vale o que está na lista.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB PORTAS
    {
      id: 'm2-portas', titulo: 'Laboratório · Portas e bancada', tipo: 'lab', min: 12, resumo: 'Cada operação vira uma peça. As sete portas, a bancada livre e por que NAND é universal.',
      steps: [
        texto('**Da conta para o chip.** Uma **porta lógica** é um componente eletrônico pequeno que faz **uma** operação booleana. Entram fios com 0 ou 1; sai um fio com o resultado.\n\nAs três básicas são as operações que você já conhece:\n\n- **AND** (E): saída 1 só com as duas entradas em 1. É o $A \\cdot B$.\n- **OR** (OU): saída 0 só com as duas entradas em 0. É o $A + B$.\n- **NOT** (NÃO): uma entrada só; inverte. É o $A\'$.\n\nUm **circuito** é um desenho de portas ligadas por fios. Ler um circuito é ler uma expressão desenhada: $(A \\cdot B) + C\'$ é uma AND, uma NOT e uma OR juntando as duas.'),
        { t: 'toy', toy: 'bancada', modo: 'livre', intro: 'Sua bancada. Toque em "+ AND" para pôr uma porta; toque na bolinha de saída de uma peça e depois na bolinha de entrada de outra para ligar um fio; toque numa chave para ligá-la. O fio acende quando carrega 1. Embaixo, o jogo escreve a expressão e a tabela do que você montou.\n\nComece ligando duas chaves a uma AND e a AND à lâmpada.' },
        texto('**As portas derivadas.** São combinações tão usadas que ganharam peça própria:\n\n- **NAND** = NOT + AND: é a AND com a saída invertida, $(AB)\'$. Só dá 0 quando as duas entradas são 1.\n- **NOR** = NOT + OR: a OR invertida, $(A + B)\'$. Só dá 1 quando as duas entradas são 0.\n- **XOR** (ou exclusivo, $A \\oplus B$): dá 1 quando as entradas são **diferentes**. É o "café ou chá" da Aula 1.\n- **XNOR**: o XOR invertido; dá 1 quando as entradas são **iguais**.\n\nO XOR escrito com as básicas: $A \\oplus B = AB\' + A\'B$ ("A sim e B não, ou A não e B sim").'),
        ex(cheque('m2-k09', 'm2.portas', 'Uma porta NAND recebe 1 e 1. O que sai?', ['0: a AND daria 1, e a NAND inverte', '1', 'Depende da porta'], 0, 'NAND = AND seguida de NOT. 1·1 = 1; invertendo, 0.')),
        texto('**Confira na plataforma.** No texto extraído da U3, a tabela do XOR aparece com a legenda "Disjunção OR". Os valores mostrados (0, 1, 1, 0) são do **XOR**; o OR daria 0, 1, 1, 1. A diferença está na última linha: com as duas entradas em 1, o OR dá 1 e o XOR dá 0.', 'confira', 'Pode ser só uma legenda deslocada na extração do PDF. Vale olhar na plataforma. O XNOR não aparece no texto da U3 (além do material).'),
        texto('**NAND é universal.** Se você só pudesse fabricar **um** tipo de porta, daria para fazer um computador inteiro? Sim, se for a NAND (ou a NOR).\n\nCom NAND se monta um NOT; com NAND + NOT se monta uma AND; com De Morgan se monta uma OR. E com NOT, AND e OR se monta qualquer expressão. Por isso chips reais são feitos quase só de NAND: fabricar um único tipo de peça sai mais barato.\n\nOs dois últimos desafios abaixo fazem você descobrir como.'),
        { t: 'toy', toy: 'bancada', modo: 'desafio', intro: 'Cinco montagens. Se travar, peça a dica dentro do desafio.', desafios: ['b-and', 'b-alarme', 'b-xor', 'b-nand-not', 'b-nand-and'] },
        ex(mcq('m2-r-seq', 'm2.portas', 'U3 · Operações · Quizz 1', 'Qual sequência representa corretamente a expressão (A AND B) OR (NOT A)?', [
          'Aplicar a porta AND entre A e B; aplicar a porta NOT em A; conectar as saídas das portas AND e NOT a uma porta OR.',
          'Aplicar a porta OR entre A e B; aplicar a porta NOT em B; conectar as saídas das portas OR e NOT a uma porta AND.',
          'Aplicar a porta NOT em B; aplicar a porta AND entre A e NOT B; aplicar a porta OR entre os resultados.',
          'Aplicar a porta AND em A e NOT B; conectar a saída a uma porta NOR com B.',
          'Aplicar a porta OR em A e B; em seguida, aplicar a porta NOT na saída da OR.',
        ], 0, 'Leia a expressão de dentro para fora: os dois parênteses são feitos primeiro (AND e NOT), e a OR junta os resultados.')),
        ex(mcq('m2-r-xor', 'm2.portas', 'U3 · Aplicações · Quizz 2', 'F = (A AND NOT B) OR (NOT A AND B). Que operação clássica ela representa, e quanto vale com A = 1 e B = 0?', ['XOR, e o resultado é 1.', 'AND, e o resultado é 0.', 'OR, e o resultado é 1.', 'NAND, e o resultado é 0.', 'NOR, e o resultado é 1.'], 0, 'Acende quando exatamente uma entrada é 1: é o XOR. Com A = 1, B = 0: (1·1) + (0·0) = 1.')),
        ex(mcq('m2-q8', 'm2.portas', 'U3 · Aplicações · Quizz 1', 'Qual operação básica resulta em verdadeiro apenas quando ambos os operandos são verdadeiros?', ['Operação OR (disjunção)', 'Operação NOT (negação)', 'Operação AND (conjunção)', 'Lei da Complementação', 'Operação XOR (ou exclusivo)'], 2, 'AND: 1 só com as duas entradas em 1.')),
      ],
    },
    // ------------------------------------------------------------------ AULA 7
    {
      id: 'm2-sop', titulo: 'Aula 7 · Da tabela à expressão', tipo: 'licao', min: 9, resumo: 'Você só tem o comportamento desejado. Como escrever a expressão? Soma de produtos e produto de somas.',
      steps: [
        texto('**O problema ao contrário.** Até agora você tinha a expressão e montava a tabela. Na vida real costuma ser o inverso: o cliente diz **o que quer que aconteça** em cada situação (a tabela), e você precisa descobrir a expressão.\n\nExemplo: uma luz de escada com dois interruptores, A (embaixo) e B (em cima). A luz deve acender quando os interruptores estão em posições **diferentes**:\n\n- A=0, B=0: luz 0\n- A=0, B=1: luz **1**\n- A=1, B=0: luz **1**\n- A=1, B=1: luz 0'),
        texto('**A ideia: um termo "detector" para cada linha que acende.**\n\nOlhe a linha A=0, B=1. Quero um produto que dê 1 **só nessa linha**. Um produto só dá 1 quando todos os fatores são 1. O B já é 1. O A é 0, então uso $A\'$, que ali vale 1. O detector é $A\'B$.\n\nConfira: $A\'B$ dá 1 em A=0, B=1 e 0 em todas as outras. Perfeito.\n\nPara a linha A=1, B=0, o detector é $AB\'$.\n\nA luz acende quando **um ou outro** detector dispara. Então somo:\n\n$$L = A\'B + AB\'$$\n\nEsse método se chama **soma de produtos** (o curso também diz SOP). Receita: para cada linha com saída **1**, um produto de todas as variáveis; a variável que vale **0** naquela linha entra **negada**. Depois, some os produtos.'),
        ex(cheque('m2-k10', 'm2.circuitos', 'Na linha A=1, B=0, C=1 a saída é 1. Qual é o termo dessa linha na soma de produtos?', ["A·B'·C", "A'·B·C'", 'A + B\' + C'], 0, 'Quem vale 1 entra normal (A e C); quem vale 0 entra negado (B). E é um produto, não uma soma.')),
        gen('m2.sop', 3),
        texto("**O caminho pelo outro lado: produto de somas.** Em vez de detectar as linhas que dão 1, você pode **proibir** as linhas que dão 0.\n\nPara cada linha com saída **0**, escreva uma **soma** de todas as variáveis, negando as que valem **1** naquela linha. Depois multiplique as somas.\n\nNa luz de escada, as linhas com saída 0 são (0,0) e (1,1):\n\n- (0,0): $A + B$ (dá 0 só quando os dois são 0)\n- (1,1): $A' + B'$ (dá 0 só quando os dois são 1)\n\n$$L = (A + B)(A' + B')$$\n\nÉ a mesma função escrita de outro jeito. O curso chama de POS. Use soma de produtos quando há poucos 1 na tabela e produto de somas quando há poucos 0."),
        texto('**Depois, enxugar.** A expressão tirada direto da tabela sempre funciona, mas quase nunca é a menor. O fluxo completo de projeto que a U3 ensina é:\n\n**tabela → expressão (soma de produtos) → simplificação (leis ou Karnaugh) → circuito com portas.**'),
        { t: 'toy', toy: 'interruptores', modo: 'desafio', intro: 'Agora escreva você a expressão da luz de escada.', desafios: ['i-xor'] },
        ex(mcq('m2-q9', 'm2.simplificacao', 'U3 · Efetivando · Quizz 5', 'Como a álgebra booleana contribui para a simplificação e eficiência dos circuitos digitais?', [
          'Permite representar circuitos por expressões matemáticas que facilitam a análise e simplificação usando técnicas como mapas de Karnaugh, reduzindo componentes e aumentando a eficiência.',
          'Substitui completamente os circuitos digitais por circuitos analógicos.',
          'Torna os circuitos digitais capazes de trabalhar com sinais contínuos.',
          'Apenas serve para calcular tabelas-verdade, sem impacto na construção prática.',
        ], 0, 'Expressão → simplificação → menos componentes.', { heuristica: 'A correta põe a álgebra como meio para um fim prático; as erradas usam "completamente" e "apenas".' })),
        ficha({
          titulo: 'Soma de produtos e produto de somas: a ficha',
          porque: 'Às vezes o que se tem é o comportamento desejado (a tabela), não a fórmula. Esse método transforma qualquer tabela em circuito.',
          ideia: 'SOP: um produto por linha com saída 1 (variável em 0 entra negada), todos somados. POS: uma soma por linha com saída 0 (variável em 1 entra negada), todas multiplicadas.',
          regra: "$$\\text{linha } (A,B,C) = (0,1,1) \\text{ com saída 1} \\;\\Rightarrow\\; A'BC$$",
          exemplo: "XOR: saída 1 em (0,1) e (1,0). SOP: $A'B + AB'$. POS: $(A + B)(A' + B')$.",
          armadilha: 'A SOP direta da tabela funciona, mas raramente é a menor. Simplifique depois.',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 8
    {
      id: 'm2-circuitos', titulo: 'Aula 8 · Circuitos que o curso cobra', tipo: 'licao', min: 11, resumo: 'Multiplexador, decodificador 2→4 e o somador: lógica virando hardware de verdade.',
      steps: [
        texto('**Multiplexador: uma chave que escolhe.** Problema: um processador tem dois dados disponíveis, B e C, e precisa deixar passar **um deles**, conforme um sinal de controle A.\n\nA expressão que o curso usa é:\n\n$$S = A \\cdot B + A\' \\cdot C$$\n\nAntes de eu explicar, pense: o que sobra dessa expressão quando $A = 1$?'),
        ex(cheque('m2-k11', 'm2.circuitos', "Em $S = A \\cdot B + A' \\cdot C$, com $A = 1$, a saída S fica igual a:", ['B', 'C', '1'], 0, "Com A = 1: 1·B + 0·C = B + 0 = B. A entrada C é ignorada.")),
        texto("Com $A = 1$: $S = 1 \\cdot B + 0 \\cdot C = B$. Passa o B.\n\nCom $A = 0$: $S = 0 \\cdot B + 1 \\cdot C = C$. Passa o C.\n\nA entrada A funciona como **seletor**. Esse circuito se chama **multiplexador** (ou \"mux\"), e é a resposta de mais de uma questão da U3: a função $F = (A \\text{ AND } B) \\text{ OR } (\\text{NOT } A \\text{ AND } C)$ é ele."),
        { t: 'toy', toy: 'bancada', modo: 'desafio', intro: 'Monte o multiplexador e teste: com A ligado, a lâmpada deve copiar B; com A desligado, copiar C.', desafios: ['b-mux'] },
        texto('**Um erro no material.** Na autoavaliação da U3, Questão 1, uma alternativa diz que $AB + A\'C$ "pode ser simplificada para $(A + B)(A\' + C)$ pela lei distributiva". Parece técnico, mas **não é equivalente**.\n\nTeste com A = 1, B = 1, C = 0:\n\n- $AB + A\'C = 1 \\cdot 1 + 0 \\cdot 0 = 1$\n- $(A + B)(A\' + C) = (1)(0 + 0) = 0$\n\nResultados diferentes. A alternativa correta da questão é a do multiplexador. Lição geral: quando uma alternativa afirma uma equivalência, **teste uma linha**.', 'erro', 'Conferido por código: as duas expressões diferem em 4 das 8 linhas.'),
        ex(mcq('m2-r-q1', 'm2.circuitos', 'U3 · Avaliando · Questão 1', 'Dada F = (A AND B) OR (NOT A AND C), qual alternativa traz uma interpretação válida que facilita a implementação?', [
          'F pode ser interpretada como a operação XOR entre A e C, ignorando B.',
          'F é verdadeiro apenas se A e B forem verdadeiros simultaneamente, independentemente de C.',
          'F corresponde a uma função seletora (multiplexador) onde A atua como controle, selecionando entre B e C.',
          'F é uma simplificação da operação OR entre A, B e C, sem necessidade de negação.',
          'F pode ser simplificada para (A OR B) AND (NOT A OR C), mostrando sua equivalência pela lei distributiva.',
        ], 2, 'É o multiplexador. A alternativa da "lei distributiva" é falsa: teste A = 1, B = 1, C = 0.', { selo: 'erro', seloNota: 'A alternativa (A OR B) AND (NOT A OR C) NÃO é equivalente a F. Conferido por código.' })),
        texto('**Números em binário (o mínimo necessário).** Com fios que só valem 0 ou 1, números são escritos em **binário**. Com dois fios, $A_1$ e $A_0$, dá para escrever quatro números:\n\n- 00 = zero\n- 01 = um\n- 10 = dois\n- 11 = três\n\nO fio da esquerda ($A_1$) **vale 2**; o da direita ($A_0$) **vale 1**. O número é $A_1 \\cdot 2 + A_0$. Então 10 é $1 \\cdot 2 + 0 = 2$.\n\n**Decodificador 2→4.** Tem 2 entradas ($A_1$, $A_0$) e 4 saídas ($D_0$ a $D_3$). Ele lê o número binário da entrada e acende **só a saída com aquele número**. Serve, por exemplo, para escolher qual posição da memória acessar.\n\nCada saída é um "detector de linha", igual à Aula 7:\n\n$$D_0 = A_1\'A_0\' \\quad D_1 = A_1\'A_0 \\quad D_2 = A_1A_0\' \\quad D_3 = A_1A_0$$\n\nO **codificador** faz o caminho inverso: recebe qual linha está acesa e devolve o número.'),
        ex(mcq('m2-dec', 'm2.circuitos', 'U3 · Exemplo em Python: decodificador 2→4', 'Num decodificador 2→4, as entradas são A1 = 1 e A0 = 0. Qual saída fica em 1?', ['D0', 'D1', 'D2', 'D3'], 2, 'A1 vale 2 e A0 vale 1: 10 em binário = 2. Ativa D2. (O exemplo do PDF usa 01, que ativa D1.)', { fixo: true, porOpcao: [undefined, 'Você leu ao contrário: A1 vale 2, A0 vale 1. 10 = 2.'] })),
        texto('**Somar com portas.** Somar dois bits A e B:\n\n- 0 + 0 = 0\n- 0 + 1 = 1\n- 1 + 0 = 1\n- 1 + 1 = 2, que em binário é **10**: "escreve 0 e vai 1".\n\nSão duas saídas. O dígito da **soma** é 1 quando as entradas são diferentes: é o XOR, $A \\oplus B$. O **vai-um** é 1 só quando as duas são 1: é a AND, $A \\cdot B$.\n\nEsse circuito se chama **meio-somador**. Encadeando vários, o processador soma números de qualquer tamanho. É aqui que a lógica vira aritmética.', 'alem', 'O somador não está no texto do curso (só aparece citado num exemplo do simulador). Entra porque mostra para que serve o XOR.'),
        ex(mcq('m2-soma', 'm2.circuitos', undefined, 'No meio-somador, A = 1 e B = 1. Quanto valem a soma (A ⊕ B) e o vai-um (A·B)?', ['soma 0, vai-um 1', 'soma 1, vai-um 0', 'soma 1, vai-um 1', 'soma 0, vai-um 0'], 0, '1 + 1 = 10 em binário: escreve 0 e vai 1. XOR de iguais dá 0; AND de 1 e 1 dá 1.', { fixo: true, selo: 'alem' })),
        ex(mcq('m2-r-nand', 'm2.portas', 'U3 · Efetivando · Quizz 2', 'Para f = (A AND B) OR (NOT C) numa ALU (a parte do processador que faz contas), qual alternativa melhor representa a síntese adequada, pensando em custo e consumo?', [
          'Implementar diretamente f com uma OR que combina a saída de uma AND (A, B) e uma NOT em C, sem simplificação.',
          'Usar o teorema de De Morgan para transformar f em uma combinação de portas NAND e NOR, o que pode reduzir o número de transistores e aumentar a eficiência.',
          'Converter para a forma normal conjuntiva exclusiva, para usar só XOR e NOT.',
          'Substituir a OR por uma AND com inversores nas entradas, aumentando a modularidade, embora com maior consumo.',
          'Usar programação em Python para simular o circuito, pois isso substitui completamente a simplificação booleana.',
        ], 1, "Por De Morgan, AB + C' = ((AB)'·C)': duas portas NAND no lugar de três portas (AND, NOT, OR). É a alternativa que fala em reduzir transistores, o argumento da unidade.", { selo: 'confira', seloNota: "O gabarito oficial não está no material extraído. Pelo conteúdo, a resposta é a de De Morgan: conferi por código que NAND(NAND(A,B), C) = AB + C'. Vale confirmar na plataforma." })),
        ficha({
          titulo: 'Circuitos do curso: a ficha',
          porque: 'Escolher entre dados (mux), escolher um endereço (decodificador) e somar (somador) são as três coisas que um processador mais faz.',
          ideia: 'Mux: A escolhe entre B e C. Decodificador 2→4: acende a saída cujo número está na entrada. Meio-somador: soma = XOR, vai-um = AND.',
          regra: "$$S = AB + A'C \\qquad D_2 = A_1 A_0' \\qquad \\text{soma} = A \\oplus B,\\; \\text{vai-um} = AB$$",
          exemplo: 'Entradas 10 no decodificador: é o número 2, acende D2.',
          armadilha: "$A_1$ é o bit que vale 2. E $AB + A'C$ não é $(A + B)(A' + C)$.",
        }),
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'm2-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'U2 e U3 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**Lógica (U2).** Proposição: frase declarativa com um valor, V ou F (ordens, perguntas e sentenças abertas não são). Conectivos: $\\lnot$ inverte; $\\land$ só V com os dois V; $\\lor$ só F com os dois F; $\\to$ só F em V → F; $\\leftrightarrow$ V quando os lados são iguais. Ordem: $\\lnot, \\land, \\lor, \\to, \\leftrightarrow$.\n\nTabela-verdade: $2^n$ linhas, uma coluna de cada vez. Tautologia (sempre V), contradição (sempre F), contingência (mistura). Equivalentes = mesma coluna final. De Morgan; $p \\to q \\equiv \\lnot p \\lor q \\equiv \\lnot q \\to \\lnot p$; modus ponens é tautologia.\n\nEstudo de caso: $A = (B \\land C \\land R) \\lor E$, a regra de aprovação de projetos (é o chefão desta região).'),
        texto('**Álgebra booleana (U3).** V = 1, F = 0, E = ·, OU = +, NÃO = \'. Ordem: parênteses, \', ·, +. Surpresas: $1 + 1 = 1$ e $x + yz = (x + y)(x + z)$.\n\nLeis: identidade, anulação, idempotência, complemento, comutativa, associativa, distributiva, absorção, De Morgan. Simplificar = menos portas = menos custo e energia, mais velocidade.\n\nPortas: AND, OR, NOT, NAND, NOR, XOR ($AB\' + A\'B$), XNOR. NAND e NOR são universais.\n\nDa tabela à expressão: soma de produtos (linhas com 1) ou produto de somas (linhas com 0); depois simplificar (leis ou mapa de Karnaugh).\n\nCircuitos: multiplexador $AB + A\'C$; decodificador 2→4; codificador; meio-somador (XOR e AND).'),
        ex(mcq('m2-q1', 'm2.proposicoes', 'U2 · Proposições', 'Qual alternativa descreve corretamente o que é uma proposição?', [
          'Uma frase declarativa que pode ser classificada como verdadeira ou falsa, mas não admite valores intermediários.',
          'Uma pergunta que pode ser respondida com sim ou não.',
          'Uma sentença aberta que depende de variáveis para obter seu valor lógico.',
          'Qualquer frase que expresse opinião ou emoção.',
          'Uma ordem ou comando que determina uma ação.',
        ], 0, 'Declarativa + valor único (V ou F).')),
        { t: 'feynman', prompt: 'Explique com suas palavras por que a U2 e a U3 são "o mesmo conteúdo". O que muda de uma para a outra?' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'm2-questoes', titulo: 'Questões reais da U2 e da U3', tipo: 'questoes', min: 8, resumo: 'As questões da plataforma que ainda não apareceram nas aulas, embaralhadas, com a fonte.',
      steps: [
        ex(mcq('m2-q2', 'm2.tabela', 'U2 · Estudo guiado', 'Qual é o papel da tabela-verdade quando aplicada a proposições compostas com vários operadores?', [
          'Avalia exaustivamente todas as combinações possíveis de valores das proposições simples para determinar o valor final da composta, permitindo identificar tautologia, contradição ou contingência.',
          'Serve apenas para simplificar proposições em conjunções e disjunções, sem considerar negação ou implicação.',
          'Ignora as relações entre proposições simples e opera exclusivamente em nível algébrico.',
          'É utilizada para construir novas proposições independentes das originais.',
          'Restringe-se à análise de proposições simples, não sendo aplicável a proposições compostas.',
        ], 0, 'Tabela-verdade = teste exaustivo de todas as combinações.', { heuristica: 'A correta é a mais longa e qualificada; as erradas têm "apenas", "exclusivamente", "restringe-se".' })),
        ex(mcq('m2-q4', 'm2.tautologia', 'U2 · Avaliando · Exercício 2', 'O que é uma tautologia?', [
          'Uma proposição composta que é sempre verdadeira, independentemente dos valores lógicos das proposições simples.',
          'Uma proposição verdadeira somente quando as proposições simples forem verdadeiras.',
          'Uma proposição que pode ser verdadeira ou falsa dependendo do contexto.',
          'Uma proposição composta que é sempre falsa.',
          'Uma proposição que não pode ser avaliada por tabela-verdade.',
        ], 0, 'Sempre V = tautologia. "Sempre falsa" é contradição; "depende" é contingência.')),
        ex(mcq('m2-q6', 'm2.tabela', 'U2 · Avaliando · Exercício 4', 'Qual é a função principal da tabela-verdade?', [
          'Listar todas as regras de lógica formal sem avaliar proposições.',
          'Mapear todas as combinações possíveis de valores lógicos para determinar o valor final de uma proposição composta.',
          'Definir o significado linguístico das proposições simples.',
          'Armazenar apenas os valores verdadeiros das proposições simples.',
          'Substituir operadores lógicos por símbolos numéricos.',
        ], 1, 'Mapear exaustivamente as combinações de entrada.')),
        ex(mcq('m2-q10', 'm2.traducao', 'U3 · Avaliando · Questão 4', 'A porta automática só abre quando o sensor de presença detecta alguém **e** a segurança está desativada. Qual código representa isso?', [
          'if sensor_presenca and seguranca_desativada: abrir a porta.',
          'if sensor_presenca or seguranca_desativada: abrir a porta.',
          'if sensor_presenca and not seguranca_desativada: abrir a porta.',
          'if not sensor_presenca and not seguranca_desativada: abrir a porta.',
          'if not seguranca_desativada: abrir a porta.',
        ], 0, 'As duas condições precisam ser verdadeiras ao mesmo tempo: AND. Cuidado com a terceira: o nome da variável já é "desativada", então negar inverteria o sentido.', { porOpcao: [undefined, 'Com "or", a porta abriria só com a segurança desativada, sem ninguém na frente.', 'A variável já se chama "seguranca_desativada". Negá-la significa segurança ATIVADA.'] })),
        ex(mcq('m2-q12', 'm2.simplificacao', 'U3 · Avaliando · Questão 3', 'Qual é a principal vantagem de simplificar uma expressão booleana no projeto de circuitos?', [
          'Reduzir o número de componentes eletrônicos utilizados, aumentando a eficiência e a confiabilidade do circuito.',
          'Aumentar a complexidade do circuito para garantir maior segurança.',
          'Transformar os sinais analógicos em digitais.',
          'Garantir que todos os circuitos operem com sinais contínuos.',
          'Substituir a necessidade de programação em Python.',
        ], 0, 'Menos componentes, mais eficiência.')),
        ex(mcq('m2-q13', 'm2.condicional', 'U2 · Operadores lógicos (tabela da unidade)', 'Pela tabela-verdade da U2, qual é o valor de P → Q quando P é falso e Q é falso?', ['Verdadeiro', 'Falso', 'Indefinido'], 0, 'A condicional só é falsa em V → F. Com P falso, a promessa não foi testada. (Um card da mesma unidade diz o contrário; a tabela é que está certa.)', { selo: 'erro', seloNota: 'O card "Operadores lógicos" da U2 diz que a condicional é falsa "quando o segundo valor lógico for falso". A tabela da unidade mostra F → F = V.' })),
        ex(mcq('m2-q14', 'm2.portas', 'U3 · Portas lógicas', 'Por que as portas NAND e NOR são chamadas de "universais"?', ['Porque qualquer função lógica pode ser construída usando apenas uma delas', 'Porque funcionam com qualquer tensão elétrica', 'Porque são as únicas com duas entradas', 'Porque nunca precisam de simplificação'], 0, 'Com NAND (ou com NOR) se monta NOT, AND e OR; com esses três, qualquer expressão.')),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'm2-chefe', titulo: 'Chefão: o projeto e o alarme', tipo: 'chefe', min: 12, resumo: 'O estudo de caso da U2 e o exercício integrado S = (A·B) + M, do começo ao fim.',
      steps: [
        texto('**Parte 1: a regra de aprovação de projetos (estudo de caso da U2).**\n\nA empresa cansou de aprovar projeto no "achismo". As proposições são:\n\n- **B**: o projeto está dentro do orçamento\n- **C**: o cronograma é viável\n- **R**: os riscos são aceitáveis\n- **E**: o projeto tem retorno estratégico relevante\n\nRegra: o projeto é aceito (**A**) se atender **simultaneamente** aos três critérios operacionais **ou**, alternativamente, se tiver retorno estratégico.'),
        ex(expr('m2-b1', 'm2.traducao', 'U2 · Estudo de caso: lógica de projetos', 'Escreva a expressão lógica para A usando as letras B, C, R e E.', '(B∧C∧R)∨E', 'A = (B ∧ C ∧ R) ∨ E. "Simultaneamente" pede E entre os três; "ou, alternativamente" pede OU com o atalho.', ['"Simultaneamente" = todos ao mesmo tempo = E.', 'São dois caminhos: um grupo de três condições, e uma condição sozinha.', '(B ∧ C ∧ R) ∨ E'], { armadilhas: [{ valor: 'B∧C∧R∧E', causa: 'leitura', msg: 'Assim o projeto precisaria de TUDO, inclusive do retorno estratégico. O enunciado diz "ou, alternativamente".' }, { valor: 'B∨C∨R∨E', causa: 'leitura', msg: 'Assim bastaria um critério qualquer. O enunciado pede os três operacionais "simultaneamente".' }, { valor: 'B∧C∧(R∨E)', causa: 'conceito', msg: 'Os parênteses estão no lugar errado: E precisa ser alternativa ao grupo inteiro, não só a R.' }] })),
        ex(num('m2-b2', 'm2.tabela', 'U2 · Estudo de caso: lógica de projetos', 'São 4 proposições, então 16 combinações. Em quantas delas o projeto é aceito?', 9, 'Com E = 1 o projeto passa sempre: 8 combinações. Com E = 0, só passa com B = C = R = 1: mais 1. Total **9**.', ['Separe em dois casos: E = 1 e E = 0.', 'Com E = 1, quantas combinações de B, C, R existem?', '8 (com E = 1) + 1 (E = 0 e B = C = R = 1) = 9.'], { armadilhas: [{ valor: 8, causa: 'conta', msg: 'Faltou o caso sem retorno estratégico em que os três critérios operacionais são atendidos.' }, { valor: 2, causa: 'conceito', msg: 'São dois CAMINHOS, mas a pergunta é quantas das 16 linhas da tabela dão 1.' }] })),
        ex(mcq('m2-b3', 'm2.conectivos', 'U2 · Estudo de caso: lógica de projetos', 'Qual critério funciona como "atalho decisório"?', ['E (retorno estratégico): quando vale 1, a expressão inteira vale 1, qualquer que seja o resto', 'B (orçamento): sem ele nada é aprovado', 'R (riscos): ele decide sozinho', 'Nenhum: todos pesam igual'], 0, 'Na booleana: A = (qualquer valor) + 1 = 1. É a lei da anulação, x + 1 = 1.', { fixo: true })),
        { t: 'toy', toy: 'interruptores', modo: 'livre', preset: 'projeto', intro: 'Confira no painel: ligue só o E. Depois desligue o E e tente aprovar o projeto.' },
        texto('**Parte 2: o alarme (exercício "Aplicação integrada" da U2).**\n\nUm sistema liga os sensores A e B a um alarme S. O alarme dispara quando **A e B falham**, ou quando **o modo de segurança está ativo (M = 1)**. Modelo: $S = (A \\cdot B) + M$.\n\nO exercício pede: (a) a tabela-verdade; (b) dizer se dá para simplificar; (c) dizer se S é função de A, B e M; (d) modelar os estados num grafo (isso fica para a região de grafos).'),
        ex({ id: 'm2-b4', kind: 'tabela', topic: 'm2.tabela', fonte: 'U2 · Exercício: Aplicação integrada (a)', expr: '(A·B) + M', ordem: 'asc', notacao: 'bool', prompt: '(a) Monte a tabela-verdade de **S = (A·B) + M**. Toque nas células para alternar entre 0 e 1.', hints: ['São 3 variáveis: 8 linhas. Primeiro a coluna A·B.', 'A·B só dá 1 nas duas últimas linhas (A = 1 e B = 1).', 'S dá 1 quando M = 1 ou quando A·B = 1: linhas 001, 011, 101, 110, 111.'], explain: 'S = 1 em 5 das 8 linhas: as 4 com M = 1, mais A = 1, B = 1, M = 0. É a mesma forma do Aegis-Grid (P + QR), só com as letras trocadas.' }),
        ex(mcq('m2-b5', 'm2.simplificacao', 'U2 · Exercício: Aplicação integrada (b)', '(b) A função S = (A·B) + M pode ser simplificada?', ['Não: já está na forma mínima (um produto e uma soma, sem termo repetido nem complemento para cancelar)', 'Sim: vira S = M', 'Sim: vira S = A + B + M', 'Sim: vira S = A·B·M'], 0, 'Não há fator comum, nem par x + x\', nem absorção possível. Cada alternativa "simplificada" muda a tabela: confira a linha A = 1, B = 1, M = 0.', { fixo: true })),
        ex(mcq('m2-b6', 'm2.traducao', 'U2 · Exercício: Aplicação integrada (c)', '(c) S é uma função de A, B e M?', ['Sim: cada combinação (A, B, M) tem exatamente uma saída. É uma função de {0,1}³ em {0,1}', 'Não: há combinações diferentes com a mesma saída', 'Não: funções precisam de números reais'], 0, 'Volta à região anterior: função = cada entrada com exatamente uma saída. Ter saídas repetidas só significa que não é injetora (nem poderia: são 8 entradas para 2 saídas).', { fixo: true })),
        { t: 'toy', toy: 'bancada', modo: 'desafio', intro: 'Agora monte o circuito do alarme.', desafios: ['b-integrado'] },
        {
          t: 'escrita', fonte: 'treino para a A1 dissertativa',
          prompt: 'Como numa prova dissertativa: um sistema falha se o servidor central falha ou se as duas rotas críticas falham ao mesmo tempo. Defina as proposições, escreva a expressão lógica e a booleana, e diga em quantos cenários há falha. Formato "defino…, monto…, logo…".',
          modelo: 'Defino p: "o servidor central falha"; q: "a rota 1 falha"; r: "a rota 2 falha". A falha do sistema acontece quando p é verdadeira ou quando q e r são verdadeiras juntas, então monto p ∨ (q ∧ r). Em álgebra booleana, com 1 = falha: S = P + Q·R. São 3 variáveis, logo a tabela tem 2³ = 8 linhas. S = 1 nas quatro linhas em que P = 1 e também na linha P = 0, Q = 1, R = 1. Logo o sistema falha em 5 dos 8 cenários. A expressão mostra por que as rotas são redundantes: uma rota sozinha não derruba o sistema, só as duas juntas.',
          rubrica: ['Defini cada proposição com letra e frase', 'Escrevi a expressão lógica com os parênteses no lugar', 'Traduzi para a notação booleana', 'Justifiquei o número de linhas (2³ = 8)', 'Cheguei a 5 cenários e disse quais são', 'Interpretei o resultado (o que ele diz sobre o sistema)'],
        },
        { t: 'feynman', prompt: 'Explique para alguém que nunca viu: por que negar "A e B" dá "não A OU não B"? Use um exemplo do seu dia a dia.' },
      ],
    },
  ],
  cards: cards('mat', 'm2', [
    ['Quando p → q é falsa?', 'Só quando p é V e q é F. Nos outros três casos é verdadeira.'],
    ['Quantas linhas tem a tabela-verdade com n proposições?', '2ⁿ. Cada proposição dobra o número de linhas.'],
    ['Tautologia, contradição, contingência', 'Sempre V; sempre F; depende da linha.'],
    ['As duas leis de De Morgan', '¬(p ∧ q) ≡ ¬p ∨ ¬q e ¬(p ∨ q) ≡ ¬p ∧ ¬q. Nega cada parte e troca o conectivo.'],
    ['p → q escrito sem a seta', '¬p ∨ q. E a contrapositiva ¬q → ¬p também é equivalente.'],
    ['Modus ponens', 'De p → q e p, conclui-se q. A fórmula [p ∧ (p → q)] → q é tautologia.'],
    ['Tradução lógica → booleana', 'V = 1, F = 0, ∧ = ·, ∨ = +, ¬ = \'.'],
    ['Ordem das operações booleanas', 'Parênteses, depois \' (NÃO), depois · (E), depois + (OU).'],
    ['A distributiva "estranha"', 'x + yz = (x + y)(x + z). Só existe na álgebra booleana.'],
    ['Simplifique AB + AB\'', 'A(B + B\') = A·1 = A.'],
    ['XOR em função de AND, OR e NOT', 'A ⊕ B = AB\' + A\'B: dá 1 quando as entradas são diferentes.'],
    ['Por que NAND é "universal"?', 'Com NAND se monta NOT, AND e OR; logo, qualquer circuito. O mesmo vale para NOR.'],
    ['Soma de produtos (SOP)', 'Um termo para cada linha da tabela com saída 1; variável em 0 entra negada. Depois, simplifique.'],
    ['Multiplexador S = AB + A\'C', 'A é o seletor: com A = 1 passa B; com A = 0 passa C.'],
    ['Estudo de caso da U2: A = (B∧C∧R)∨E', 'Aceito em 9 das 16 combinações. E é o atalho decisório (x + 1 = 1).'],
    ['É proposição: "x + 2 = 4"?', 'Não. É sentença aberta; só vira proposição quando x recebe um valor.'],
    ['O "ou" da lógica é inclusivo ou exclusivo?', 'Inclusivo: p ∨ q é V quando pelo menos um é V, inclusive os dois. O exclusivo é o XOR (⊕).'],
    ['Absorção', 'x + xy = x. Se x é 1 o resultado já é 1; se x é 0, xy também é 0.'],
  ]),
};
