// M4 · Probabilidade (U5), ensinado do zero.
// Fontes: fontes/matematica/U5.txt, os quatro exemplos em Python da unidade e a lista de exercícios baseada em Sbrana (PDF).
import type { Regiao } from '../../engine/types';
import { cards, cheque, ex, ficha, gen, mcq, num, texto } from '../ajuda';

export const M4: Regiao = {
  id: 'm4', mundo: 'mat', nome: 'Probabilidade', unidades: 'U5', pronto: true,
  tese: 'Contagem com denominador: casos favoráveis sobre casos possíveis. Serve para medir risco.',
  fases: [
    // ------------------------------------------------------------------ AULA 1
    {
      id: 'm4-chance', titulo: 'Aula 1 · Medir a chance', tipo: 'licao', min: 11, resumo: 'Do zero: experimento, espaço amostral, evento e a conta "favoráveis sobre possíveis".',
      steps: [
        texto('**O problema.** O grupo de jovens vai sortear quem lava a louça do retiro com um dado: se sair 5 ou 6, é você. Qual a sua chance de se dar mal?\n\nVocê já sabe a resposta de cabeça: "2 em 6". Esta aula só dá nome às peças desse raciocínio, porque com os nomes dá para resolver problemas muito maiores.\n\n**Probabilidade** é a matemática de **medir a incerteza**: dar um número para "quão provável" é uma coisa que ainda não aconteceu.'),
        texto('**Três nomes.**\n\n**Experimento aleatório**: uma ação cujo resultado você não sabe antes. Lançar o dado, enviar um pacote pela rede, um usuário clicar ou não num botão.\n\n**Espaço amostral**: o **conjunto de todos os resultados possíveis**. O curso usa a letra grega $\\Omega$ (ômega) ou a letra $S$. Para o dado:\n\n$$\\Omega = \\{1, 2, 3, 4, 5, 6\\}$$\n\n**Evento**: um **subconjunto** do espaço amostral, isto é, os resultados que te interessam. "Sair 5 ou 6" é o evento $A = \\{5, 6\\}$.\n\nRepare: é a linguagem de conjuntos da primeira região. Probabilidade é conjuntos mais contagem.'),
        ex(mcq('m4-r-ex1', 'm4.classica', 'U5 · Exercício 1 (Sbrana)', 'Questão do curso. Um dado comum é lançado uma vez. Qual é o espaço amostral associado a esse experimento?', ['{1, 2, 3}', '{2, 4, 6}', '{1, 2, 3, 4, 5, 6}', '{0, 1, 2, 3, 4, 5, 6}', '{1, 3, 5}'], 2, 'Espaço amostral é o conjunto de TODOS os resultados possíveis: as seis faces. {2, 4, 6} seria o evento "sair par".')),
        texto('**A conta.** Quando todos os resultados têm a **mesma chance** (dado equilibrado, moeda honesta, sorteio justo), a probabilidade de um evento é:\n\n$$P(A) = \\frac{|A|}{|\\Omega|} = \\frac{\\text{casos favoráveis}}{\\text{casos possíveis}}$$\n\n($|A|$ é a quantidade de elementos de A, como na primeira região.)\n\nPara a louça: $P(A) = \\dfrac{2}{6} = \\dfrac{1}{3} \\approx 0{,}333$, ou 33,3%.\n\nIsso se chama **probabilidade clássica**. Fração, decimal e porcentagem são três jeitos de escrever o mesmo número.'),
        ex(cheque('m4-k01', 'm4.classica', 'Num baralho de 52 cartas, 13 são de copas (exemplo do curso). Qual a probabilidade de tirar uma carta de copas?', ['1/4', '1/13', '13'], 0, '13 favoráveis em 52 possíveis: 13/52 = 1/4 = 25%.')),
        texto('**O número sempre fica entre 0 e 1.**\n\n- $P = 0$: **impossível**. Sair 7 num dado comum. $P(\\emptyset) = 0$.\n- $P = 1$: **certo**. Sair um número de 1 a 6. $P(\\Omega) = 1$.\n- No meio: quanto mais perto de 1, mais provável.\n\nSe uma conta de probabilidade der 1,3 ou −0,2, a conta está errada. Sempre.\n\nEssas regras ($P \\ge 0$, $P(\\Omega) = 1$, e a soma para eventos que não se cruzam) têm nome: são os **axiomas de Kolmogorov**. Você só precisa reconhecer o nome e saber o que dizem.'),
        gen('m4.class', 3),
        texto('**E quando os resultados não têm a mesma chance?** Aí você estima pela **frequência**: faz (ou observa) o experimento muitas vezes e divide.\n\nExemplo do curso (em Python): de 1000 pacotes enviados, 50 se perderam. Probabilidade estimada de perda: $50 / 1000 = 0{,}05 = 5\\%$.\n\nA frequência e a teoria conversam: se você lançar um dado poucas vezes, o resultado pode ser bem torto. Lançando milhares de vezes, a frequência de cada face chega perto de 1/6. Isso se chama **lei dos grandes números**, e é o que justifica **simular** no computador (a técnica chamada **Monte Carlo**, que o curso cita).\n\nVeja acontecer.'),
        { t: 'toy', toy: 'simulador', modo: 'desafio', intro: 'Dois desafios na bancada de sorteio. Lance de 1 em 1 no começo, para ver como poucos lançamentos enganam; depois de 100 em 100.', desafios: ['s-dado', 's-evento'] },
        texto('**Uma questão do curso para discutir.** Uma urna tem 3 bolas vermelhas, 2 verdes e 1 azul. Qual é o espaço amostral de tirar uma bola?\n\nO gabarito do curso é {vermelha, verde, azul}: "considerando apenas as cores". É um espaço amostral válido. Mas **cuidado**: nele os resultados **não têm a mesma chance**. Não dá para dizer que P(vermelha) = 1/3.\n\nPara usar "favoráveis sobre possíveis", você precisa contar **bola por bola**: 6 bolas, 3 vermelhas, P(vermelha) = 3/6 = 1/2. É o espaço {R1, R2, R3, V1, V2, A1}, que aparece como outra alternativa da mesma questão.', 'confira', 'Exercício 3 da lista baseada em Sbrana. O gabarito oficial é a alternativa C (só as cores). As duas respostas são defensáveis; a diferença é que só a D é equiprovável. Se cair, marque a das cores, e lembre de contar bola por bola na hora de calcular.'),
        ex(mcq('m4-r-ex5', 'm4.classica', 'U5 · Exercício 5 (Sbrana)', 'Em uma urna há cinco bolas vermelhas, três azuis e duas verdes. Retira-se uma bola ao acaso. Qual é a probabilidade de ela ser azul?', ['0,1', '0,2', '0,3', '0,5', '0,8'], 2, 'Total: 5 + 3 + 2 = 10 bolas. Azuis: 3. P = 3/10 = 0,3.')),
        ficha({
          titulo: 'Medir a chance: a ficha',
          porque: 'Sistemas precisam decidir com informação incompleta: essa transação é fraude? esse e-mail é spam? o servidor aguenta? Probabilidade dá um número para a incerteza.',
          ideia: 'Espaço amostral Ω = todos os resultados. Evento = subconjunto de Ω. Se os resultados têm a mesma chance, P = favoráveis ÷ possíveis.',
          regra: '$$P(A) = \\frac{|A|}{|\\Omega|} \\qquad 0 \\le P(A) \\le 1 \\qquad P(\\Omega) = 1,\\; P(\\emptyset) = 0$$',
          exemplo: 'Dado, "maior que 4": A = {5, 6}, P = 2/6 = 1/3. Rede: 50 perdidos em 1000, P ≈ 5%.',
          armadilha: 'Usar "favoráveis sobre possíveis" quando os resultados não têm a mesma chance (a urna contada por cores).',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 2
    {
      id: 'm4-regras', titulo: 'Aula 2 · Não, ou, e, sabendo que', tipo: 'licao', min: 12, resumo: 'As regras para combinar probabilidades: complemento, adição, independência e condicional.',
      steps: [
        texto('**Quatro palavras.** Eventos se combinam com as mesmas palavras dos conjuntos e da lógica: **não**, **ou**, **e**. A probabilidade ganha mais uma: **sabendo que**. Cada uma tem a sua regra.\n\n**1. NÃO: o complemento.** A chance de um disco falhar no ano é 2%. A chance de **não** falhar é o resto: 98%.\n\n$$P(\\text{não } A) = 1 - P(A)$$\n\nParece bobo, mas é a regra mais útil de todas. Muitas vezes é difícil calcular o que você quer e fácil calcular o contrário.'),
        ex(cheque('m4-k02', 'm4.regras', 'A chance de um pacote se perder é 0,05. Qual a chance de ele chegar?', ['0,95', '0,05', '0,5'], 0, 'Chegar é o complemento de se perder: 1 − 0,05 = 0,95.')),
        texto('**2. OU: a regra da adição.** No dado, qual a chance de sair "par **ou** maior que 4"?\n\n- Par: {2, 4, 6}, 3 casos.\n- Maior que 4: {5, 6}, 2 casos.\n\nSomar daria 5 casos. Mas o **6** está nos dois grupos e seria contado duas vezes. Os casos de verdade são {2, 4, 5, 6}: 4 casos, P = 4/6.\n\nÉ a inclusão-exclusão que você já conhece, dividida pelo total:\n\n$$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$$\n\nSe os eventos **não podem acontecer juntos** (o curso diz **mutuamente exclusivos**, como "sair 1" e "sair 2"), a interseção é vazia e sobra só a soma: $P(A \\cup B) = P(A) + P(B)$.'),
        ex(cheque('m4-k03', 'm4.regras', 'P(A) = 0,5, P(B) = 0,4 e P(A ∩ B) = 0,2. Quanto é P(A ∪ B)?', ['0,7', '0,9', '0,2'], 0, '0,5 + 0,4 − 0,2 = 0,7. O 0,9 conta a interseção em dobro.')),
        texto('**3. E: independência.** Dois eventos são **independentes** quando um acontecer **não muda** a chance do outro. Dois lançamentos de moeda. Dois pacotes enviados por caminhos diferentes.\n\nPara eventos independentes, a chance de acontecerem **os dois** é o **produto**:\n\n$$P(A \\cap B) = P(A) \\cdot P(B)$$\n\nPor que multiplica? Pense na árvore da região passada: de cada 100 vezes, o primeiro dá certo em 90; **dessas 90**, o segundo dá certo em 90%, ou seja, 81. Então 81 em 100.\n\nExercício 11 do curso: um produto tem 0,1 de chance de ser defeituoso. Pegando dois (com reposição), a chance de **ambos** serem bons é $0{,}9 \\times 0{,}9 = 0{,}81$.'),
        ex(mcq('m4-r-ex11', 'm4.regras', 'U5 · Exercício 11 (Sbrana)', 'Sabendo-se que a probabilidade de um produto ser defeituoso é 0,1, qual é a probabilidade de, escolhendo-se dois produtos ao acaso (com reposição), ambos serem não defeituosos?', ['0,81', '0,80', '0,89', '0,90', '0,91'], 0, 'Não defeituoso: 1 − 0,1 = 0,9. Independentes: 0,9 × 0,9 = 0,81.', { porOpcao: [undefined, 'Você fez 1 − 0,1 − 0,1. Probabilidades de eventos independentes se multiplicam.', undefined, 'Essa é a chance de UM produto ser bom. São dois.'] })),
        texto('**O truque do "pelo menos um".** Um invasor tem 3 tentativas para acertar uma senha de 4 dígitos (exemplo em Python do curso). Qual a chance de acertar **pelo menos uma** vez?\n\nCalcular direto é chato (acerta na 1ª, ou erra e acerta na 2ª, ou…). O contrário de "pelo menos uma" é "**nenhuma**", que é fácil:\n\n- Chance de errar uma tentativa: $1 - \\dfrac{1}{10000} = 0{,}9999$.\n- Chance de errar as três (independentes): $0{,}9999^3$.\n- Chance de acertar pelo menos uma: $1 - 0{,}9999^3 \\approx 0{,}0003$, ou 0,03%.\n\n$$P(\\text{pelo menos um}) = 1 - P(\\text{nenhum})$$'),
        gen('m4.regras', 4),
        texto('**4. SABENDO QUE: a probabilidade condicional.** Às vezes você recebe uma informação que **encolhe o universo**.\n\nNo dado: qual a chance de ter saído 6? É 1/6. Agora alguém espiou e avisou: "saiu um número par". O universo deixou de ser {1, …, 6} e virou {2, 4, 6}. Nesse universo menor, a chance de ser 6 é **1/3**.\n\nEscreve-se $P(A \\mid B)$, e lê-se "probabilidade de A **dado** B" (ou "sabendo que B aconteceu"). A fórmula só diz "olhe para dentro de B":\n\n$$P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}$$\n\nNa prática, com uma tabela de contagens: divida o número de casos que estão em A **e** em B pelo total de casos de **B** (não pelo total geral).\n\nCom isso dá para dizer de novo o que é independência: A e B são independentes quando saber de B **não muda nada**, $P(A \\mid B) = P(A)$. Se muda, são **dependentes**.'),
        gen('m4.cond', 1),
        texto('**Juntando caminhos: a probabilidade total.** Exercício 10 do curso: numa escola, 60% dos alunos são meninas e 40% são meninos. Praticam esportes 70% das meninas e 50% dos meninos. Qual a chance de um aluno qualquer praticar esportes?\n\nSão dois caminhos para chegar em "pratica esportes" (desenhe a árvore):\n\n- É menina **e** pratica: $0{,}60 \\times 0{,}70 = 0{,}42$\n- É menino **e** pratica: $0{,}40 \\times 0{,}50 = 0{,}20$\n\nOs caminhos não se misturam (ninguém está nos dois), então **soma**: $0{,}42 + 0{,}20 = 0{,}62$.\n\nDentro de cada caminho, multiplica (E). Entre caminhos, soma (OU). É o PFC e o princípio aditivo, com probabilidades no lugar de contagens.\n\nO curso cita ainda o **Teorema de Bayes**, que usa a condicional para inverter a pergunta (de "P(positivo dado doente)" para "P(doente dado positivo)"). É a base dos filtros de spam (Naive Bayes). O material só cita; não cobra a conta.'),
        gen('m4.cond', 2),
        ex(mcq('m4-q1', 'm4.regras', 'U5 · Avaliando · Quizz 1', 'Qual afirmação melhor exemplifica a diferença entre eventos independentes e eventos dependentes?', [
          'Eventos independentes são aqueles cuja ocorrência de um não altera a probabilidade do outro, enquanto em eventos dependentes a ocorrência de um evento influencia a probabilidade do outro.',
          'Eventos independentes acontecem sempre ao mesmo tempo, e eventos dependentes nunca ocorrem simultaneamente.',
          'Eventos dependentes possuem probabilidades iguais para cada resultado, enquanto eventos independentes podem ter probabilidades diferentes.',
          'Em eventos independentes, a probabilidade conjunta é a soma das probabilidades individuais, enquanto em dependentes é o produto delas.',
          'Eventos independentes são sempre mutuamente exclusivos e eventos dependentes são excludentes somente quando ocorrem sequencialmente.',
        ], 0, 'Independente = um não muda a chance do outro. Cuidado com a última: independente NÃO é o mesmo que mutuamente exclusivo. Se dois eventos não podem acontecer juntos, saber de um muda tudo sobre o outro.')),
        ficha({
          titulo: 'As regras: a ficha',
          porque: 'Problemas reais combinam eventos: "o servidor A falha OU o B falha", "o pacote chega E é válido", "é fraude, SABENDO QUE veio de outro país".',
          ideia: 'NÃO: 1 menos. OU: soma e desconta a interseção. E (independentes): multiplica. SABENDO QUE: olha só para dentro do grupo informado.',
          regra: '$$P(A\') = 1 - P(A) \\qquad P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$$\n\n$$P(A \\cap B) = P(A) \\cdot P(B) \\;\\text{(independentes)} \\qquad P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}$$',
          exemplo: 'Dois produtos bons: 0,9 × 0,9 = 0,81. Esportes: 0,6·0,7 + 0,4·0,5 = 0,62.',
          armadilha: 'Independente não é mutuamente exclusivo. E "pelo menos um" se resolve por 1 − P(nenhum).',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 3
    {
      id: 'm4-binomial', titulo: 'Aula 3 · Variáveis e a binomial', tipo: 'licao', min: 12, resumo: 'Variável aleatória, discreta × contínua, valor esperado, e a distribuição de "quantos sucessos em n tentativas".',
      steps: [
        texto('**De resultados para números.** Lançar uma moeda dá "cara" ou "coroa". Para fazer contas, transformamos o resultado em número: X = 1 se der cara, X = 0 se der coroa.\n\nEsse X se chama **variável aleatória**: um número cujo valor depende do acaso. "Quantos pacotes se perderam hoje" é uma variável aleatória. "Quanto tempo o servidor demorou" também.\n\nElas vêm em dois tipos, e a diferença é cobrada:\n\n- **Discreta**: vem de **contar**. Valores separados: 0, 1, 2, 3… Usuários online, pacotes perdidos, erros num código.\n- **Contínua**: vem de **medir**. Qualquer valor dentro de um intervalo: 12,37 ms, 71,2 °C. Latência, tempo de resposta, uso de CPU, temperatura.\n\nO teste é uma pergunta: isso se **conta** ou se **mede**?'),
        gen('m4.tipo', 1),
        ex(mcq('m4-q2', 'm4.variaveis', 'U5 · Avaliando · Quizz 4', 'Questão do curso. Qual alternativa exemplifica corretamente a relação entre uma variável discreta e uma aplicação prática?', [
          'Número de pacotes de dados perdidos em uma rede, pois é uma contagem de eventos que ocorrem em quantidades inteiras.',
          'Utilização da CPU em porcentagem, pois essa variável contabiliza quantos processos estão ativos simultaneamente.',
          'Temperatura de um servidor medida em graus Celsius, pois varia discretamente conforme as condições do hardware.',
          'Latência da rede em milissegundos, pois é apenas o número de vezes que a rede falhou na conexão.',
        ], 0, 'Pacotes perdidos se contam: discreta. CPU, temperatura e latência se medem: contínuas.')),
        texto('**Distribuição e valor esperado.** A **distribuição de probabilidade** de uma variável é a tabela (ou o gráfico) que diz a chance de cada valor. Para uma variável discreta, as chances somam 1.\n\nExemplo: número de falhas de um servidor por dia.\n\n- P(X = 0) = 0,5\n- P(X = 1) = 0,3\n- P(X = 2) = 0,2\n\n"Em média, quantas falhas por dia?" Não é (0 + 1 + 2)/3, porque os valores não têm a mesma chance. Cada valor pesa conforme a sua probabilidade:\n\n$$E(X) = \\sum x_i \\cdot P(X = x_i) = 0 \\cdot 0{,}5 + 1 \\cdot 0{,}3 + 2 \\cdot 0{,}2 = 0{,}7$$\n\nIsso é o **valor esperado** (ou **esperança**), $E(X)$. O símbolo $\\sum$ (sigma maiúsculo) só quer dizer "some tudo". O valor esperado é a média que você veria em muitos dias, mesmo que em nenhum dia aconteçam "0,7 falhas".\n\nA **variância** mede o quanto os valores se espalham em volta dessa média; a raiz quadrada dela é o **desvio padrão**. Guarde os nomes: o desvio padrão é a estrela da próxima aula.'),
        gen('m4.esp', 2),
        texto('**O problema da binomial.** Lance uma moeda 3 vezes. Qual a chance de sair **exatamente 2 caras**? (É o exemplo do curso.)\n\nPelo jeito da Aula 1: o espaço amostral tem $2^3 = 8$ resultados, todos com a mesma chance:\n\nCCC, **CCK**, **CKC**, CKK, **KCC**, KCK, KKC, KKK  (C = cara, K = coroa)\n\nCom exatamente 2 caras: 3 deles. $P = 3/8 = 0{,}375$.\n\nComo saber que são 3 sem listar? É escolher **quais 2 dos 3 lançamentos** serão cara: $C(3, 2) = 3$. A contagem da região passada entrou aqui.'),
        ex(mcq('m4-q3', 'm4.binomial', 'U5 · Avaliando · Quizz 2', 'Para calcular a probabilidade de obter exatamente duas "caras" em três lançamentos de uma moeda honesta, qual técnica de contagem determina o número de casos favoráveis?', [
          'Combinação, pois seleciona subconjuntos sem considerar a ordem dos resultados.',
          'Permutação, pois a ordem dos resultados é fundamental para contar as possibilidades.',
          'Arranjo, porque a ordem dos elementos influencia diretamente no espaço amostral.',
          'Multiplicação direta simples, sem uso das técnicas fundamentais de contagem.',
          'Contagem de elementos repetidos, pois há resultados iguais que precisam ser diferenciados.',
        ], 0, 'Escolher quais 2 dos 3 lançamentos dão cara: C(3, 2) = 3. P = 3/8.')),
        texto('**E se a moeda não for honesta?** Uma rede transmite pacotes e cada um chega bem com chance $p = 0{,}8$. Em 3 pacotes, qual a chance de **exatamente 2** chegarem?\n\nAgora os 8 resultados **não** têm a mesma chance, então não dá para só contar. Mas dá para montar:\n\n- Um jeito específico, por exemplo "chega, chega, falha": $0{,}8 \\times 0{,}8 \\times 0{,}2 = 0{,}128$ (independentes: multiplica).\n- Quantos jeitos têm exatamente 2 chegadas? $C(3, 2) = 3$, e todos com a mesma chance 0,128.\n- Total: $3 \\times 0{,}128 = 0{,}384$.\n\nEsse padrão é a **distribuição binomial**:\n\n$$P(X = k) = C(n, k) \\cdot p^k \\cdot (1 - p)^{n - k}$$\n\nTrês pedaços: **quantos jeitos** × **chance dos k sucessos** × **chance dos n − k fracassos**.'),
        texto('**Quando é binomial?** O curso lista quatro condições, e elas caem em prova:\n\n1. Cada tentativa só tem **dois resultados** (sucesso ou fracasso).\n2. As tentativas são **independentes**.\n3. O número de tentativas $n$ é **fixo**.\n4. A chance de sucesso $p$ é **a mesma** em todas.\n\nCada tentativa dessas se chama **ensaio de Bernoulli**. Onde aparece em TI: pacotes transmitidos com ou sem erro, peças com ou sem defeito num lote, teste A/B (o usuário converteu ou não).\n\nA média da binomial é simples: $E(X) = n \\cdot p$. Em 10 transmissões com 80% de sucesso, esperam-se 8 sucessos.\n\nNos próximos exercícios o jogo mostra os passos no primeiro e vai escondendo.'),
        gen('m4.binom', 3),
        { t: 'toy', toy: 'simulador', modo: 'desafio', intro: 'Agora a binomial inteira de uma vez: cada barra é a chance de um número de sucessos.', desafios: ['s-moedas', 's-rede'] },
        ficha({
          titulo: 'Variáveis e binomial: a ficha',
          porque: 'Quantos pacotes vão falhar em 100? Quantas peças defeituosas num lote? Quantos usuários vão clicar? É sempre "quantos sucessos em n tentativas".',
          ideia: 'Discreta conta, contínua mede. Valor esperado é a média ponderada pelas chances. Binomial: jeitos × chance dos sucessos × chance dos fracassos.',
          regra: '$$E(X) = \\sum x_i \\, P(X = x_i) \\qquad P(X = k) = C(n,k)\\, p^k (1-p)^{n-k} \\qquad E = n p$$',
          exemplo: '2 caras em 3 moedas: C(3,2) · 0,5² · 0,5 = 3/8. Rede com p = 0,8 e n = 10: média 8.',
          armadilha: 'Esquecer o C(n, k): a chance de UMA ordem específica não é a chance de "exatamente k".',
        }),
      ],
    },
    // ------------------------------------------------------------------ AULA 4
    {
      id: 'm4-normal', titulo: 'Aula 4 · A curva em sino', tipo: 'licao', min: 11, resumo: 'A distribuição normal: média, desvio padrão, a regra 68-95-99,7 e por que ela aparece em todo lugar.',
      steps: [
        texto('**O problema.** Você mede o tempo de resposta de uma aplicação mil vezes. Quase nunca dá o mesmo número: 148 ms, 153, 171, 139… Como descrever isso?\n\nSe você fizer um gráfico de barras de "quantas vezes deu cada faixa de valor", vai aparecer uma forma conhecida: um **morro** no meio, caindo igual para os dois lados. Muita coisa perto da média, pouca coisa longe.\n\nEssa forma é a **distribuição normal** (também chamada **gaussiana**, ou **curva em sino**). Ela é o modelo padrão para variáveis **contínuas**.'),
        texto('**Só dois números descrevem a curva inteira.**\n\n- A **média**, $\\mu$ (letra grega "mi"): onde fica o **centro** do morro.\n- O **desvio padrão**, $\\sigma$ (letra grega "sigma"): a **largura** do morro. É a distância típica entre um valor e a média.\n\nNo exemplo do curso: $\\mu = 150$ ms e $\\sigma = 20$ ms. Um tempo "típico" fica a uns 20 ms da média, para mais ou para menos.\n\nCaracterísticas que o curso cobra: a curva é **simétrica** em torno da média; média, mediana e moda **coincidem**; a dispersão é dada pelo desvio padrão.'),
        ex(cheque('m4-k04', 'm4.normal', 'Duas aplicações têm média 150 ms. A primeira tem desvio padrão 5 ms; a segunda, 40 ms. Qual é mais previsível?', ['A primeira: os tempos ficam mais grudados na média', 'A segunda: desvio maior é melhor', 'São iguais, pois a média é a mesma'], 0, 'Desvio pequeno = morro estreito = valores perto da média. A segunda pode responder em 70 ms ou em 230 ms com facilidade.')),
        texto('**Probabilidade vira área.** Numa variável contínua, a chance de o tempo ser **exatamente** 150,000000… ms é **zero**: há infinitos valores possíveis. O que faz sentido é perguntar por **intervalos**: "qual a chance de ficar entre 130 e 170?".\n\nA resposta é a **área debaixo da curva** entre esses dois valores. A área total vale 1 (100%).\n\nA curva tem nome técnico: **função densidade de probabilidade** (a sigla em inglês, PDF, aparece nos códigos do curso). Calcular a área exige uma operação chamada integração; na prática, quem faz é o Python (`scipy.stats.norm`) ou uma regra pronta, que vem agora.'),
        texto('**A regra 68-95-99,7.** Em qualquer curva normal:\n\n- Entre $\\mu - 1\\sigma$ e $\\mu + 1\\sigma$ ficam cerca de **68%** dos valores.\n- Entre $\\mu - 2\\sigma$ e $\\mu + 2\\sigma$: cerca de **95%**.\n- Entre $\\mu - 3\\sigma$ e $\\mu + 3\\sigma$: cerca de **99,7%**.\n\nCom 150 ± 20 ms: 68% das respostas ficam entre 130 e 170; 95% entre 110 e 190; quase todas entre 90 e 210.\n\n**E fora da faixa?** Se 95% está dentro de ±2σ, sobram 5% fora. Como a curva é simétrica, metade em cada ponta: **2,5%** acima de 190 e 2,5% abaixo de 110.', 'alem', 'A regra 68-95-99,7 não está escrita no texto da U5 (a unidade mostra a curva e remete ao Python). Entra porque é o jeito de fazer conta com a normal sem computador, que é o que uma prova pode pedir.'),
        { t: 'toy', toy: 'simulador', modo: 'desafio', intro: 'Arraste os limites e leia a área. O número grande no meio da curva é a probabilidade.', desafios: ['s-68', 's-cauda'] },
        texto('**Medir em desvios: o escore z.** Para comparar valores de curvas diferentes, mede-se a distância até a média **em desvios padrão**:\n\n$$z = \\frac{x - \\mu}{\\sigma}$$\n\nUma resposta de 190 ms, com média 150 e desvio 20: $z = (190 - 150)/20 = 2$. Está 2 desvios acima da média, o que é raro (só 2,5% passam disso).\n\n$z$ negativo é abaixo da média. Um $z$ além de ±3 é quase certamente uma **anomalia**: é assim que sistemas de monitoramento detectam comportamento estranho.'),
        gen('m4.normal', 3),
        texto('**Por que a normal aparece em todo lugar?** A latência de uma rede é a **soma** de muitos atrasos pequenos e independentes: tráfego, carga do servidor, interferência…\n\nExiste um resultado famoso, o **Teorema Central do Limite**: quando você **soma muitos efeitos independentes**, o total tende a ter forma de sino, **não importa a forma de cada efeito**.\n\nUm dado sozinho não tem forma de sino: as seis faces empatam. Mas a média de 30 dados tem. Veja.'),
        { t: 'toy', toy: 'simulador', modo: 'desafio', intro: 'O Teorema Central do Limite acontecendo na sua frente.', desafios: ['s-tcl'] },
        ex(mcq('m4-q4', 'm4.normal', 'U5 · Aplicações · Quizz 2', 'A latência das respostas de uma rede costuma seguir uma distribuição aproximadamente normal. Qual alternativa explica melhor por quê?', [
          'Porque a latência é resultado da soma de diversos fatores independentes e aleatórios, que conforme o Teorema Central do Limite, tendem a formar uma distribuição normal.',
          'Porque a latência só pode assumir valores discretos e fixos, característicos de distribuições binomiais.',
          'Porque a latência depende exclusivamente de um único fator que segue uma distribuição uniforme.',
          'Porque a latência de rede sempre tem probabilidade constante ao longo do tempo, indicando uma distribuição uniforme contínua.',
          'Porque a latência é modelada por eventos com apenas dois resultados possíveis, como sucesso e fracasso, o que caracteriza uma distribuição binomial.',
        ], 0, 'Soma de muitos fatores independentes: Teorema Central do Limite.')),
        ficha({
          titulo: 'Normal: a ficha',
          porque: 'Tempos de resposta, latência, erros de medição: variáveis contínuas que se amontoam em torno de uma média. Saber a curva permite dizer o que é normal e o que é anomalia.',
          ideia: 'Sino simétrico, descrito por média (centro) e desvio padrão (largura). Probabilidade é área debaixo da curva.',
          regra: '$$\\mu \\pm 1\\sigma: 68\\% \\qquad \\mu \\pm 2\\sigma: 95\\% \\qquad \\mu \\pm 3\\sigma: 99{,}7\\% \\qquad z = \\frac{x - \\mu}{\\sigma}$$',
          exemplo: 'Resposta 150 ± 20 ms: 95% entre 110 e 190; acima de 190, só 2,5%.',
          armadilha: 'Esquecer de dividir por 2 ao pedir uma ponta só. E lembrar: a chance de um valor exato é zero.',
        }),
      ],
    },
    // ------------------------------------------------------------------ LAB
    {
      id: 'm4-lab', titulo: 'Laboratório · O simulador', tipo: 'lab', min: 8, resumo: 'As quatro bancadas à vontade, e a escolha entre binomial e normal.',
      steps: [
        texto('O simulador tem quatro bancadas: **Sorteio** (frequência × teoria), **Binomial**, **Normal** e **Médias** (o Teorema Central do Limite). Use os botões "E se…?" para ver casos estranhos: p muito pequeno, desvio dobrado.\n\nO curso lembra que simulação **não substitui** entender a teoria: uma simulação mal montada (por exemplo, supondo independência onde não há) dá resultado errado com cara de certo.'),
        { t: 'toy', toy: 'simulador', modo: 'livre', intro: 'Bancada livre. Sugestão: na Binomial, ponha n = 20 e p = 0,5 e repare que as barras já lembram um sino. Não é coincidência: é o Teorema Central do Limite de novo.' },
        ex(mcq('m4-q5', 'm4.classica', 'U5 · Avaliando · Quizz 3', 'Qual afirmação melhor representa a contribuição das simulações para a análise de eventos incertos?', [
          'As simulações substituem os cálculos teóricos, eliminando a necessidade de compreender as fórmulas matemáticas da probabilidade.',
          'As simulações permitem experimentar virtualmente repetições de eventos aleatórios, facilitando a visualização e compreensão dos resultados probabilísticos na prática.',
          'As simulações são úteis apenas para eventos simples e não conseguem modelar cenários complexos ou condicionais.',
          'O uso de ferramentas digitais nas simulações limita o aprendizado, pois torna a análise dependente exclusivamente dos softwares, dispensando validações.',
          'A probabilidade condicional não pode ser explorada por meio de simulações, pois envolve conceitos que só são resolvidos com cálculos analíticos rigorosos.',
        ], 1, 'Simular é repetir o experimento virtualmente para ver as frequências. Não substitui a teoria nem dispensa validação.', { heuristica: '"Substituem", "apenas", "exclusivamente", "não pode": os absolutos denunciam as erradas.' })),
        texto('**Binomial ou normal?** A pergunta de prova mais comum da unidade. Duas perguntas resolvem:\n\n- Estou **contando** sucessos em tentativas de sim ou não? **Binomial** (discreta).\n- Estou **medindo** uma grandeza que varia em torno de uma média? **Normal** (contínua).\n\nO curso cita ainda, sem desenvolver: **Poisson** (contagem de eventos raros num intervalo de tempo), **uniforme** (todos os valores com a mesma chance) e **exponencial** (tempo até o primeiro evento).'),
        ex(mcq('m4-q6', 'm4.binomial', 'U5 · Aplicações · Quizz 1', 'Para modelar o número de pacotes corrompidos em um conjunto de transmissões, qual distribuição é mais adequada, e por quê?', [
          'Distribuição binomial, pois ela modela eventos discretos com dois possíveis resultados e uma probabilidade constante de erro em cada pacote.',
          'Distribuição normal, porque as latências da rede seguem uma curva simétrica e contínua que pode representar erros em pacotes transmitidos.',
          'Distribuição uniforme, pois presume que todos os pacotes têm a mesma chance de serem corrompidos, distribuindo erros igualmente.',
          'Distribuição exponencial, pois ela é ideal para medir o tempo até a ocorrência do primeiro erro na transmissão.',
          'Distribuição de Poisson, porque ela é usada para eventos raros e pode contar os erros em intervalos de tempo contínuos.',
        ], 0, 'Conta-se quantos pacotes, de um conjunto fixo, deram erro; cada um é sim ou não com a mesma chance: binomial.')),
        gen('m4.tipo', 1),
      ],
    },
    // ------------------------------------------------------------------ RESUMO
    {
      id: 'm4-leitura', titulo: 'Resumo da região (para revisar)', tipo: 'leitura', min: 4, resumo: 'A U5 em uma página, para reler antes da prova. Só faz sentido depois das aulas.',
      steps: [
        texto('Esta página é para **revisão**. Se algo parecer novo, volte à aula daquele assunto.\n\n**Base**: espaço amostral $\\Omega$ (todos os resultados), evento (subconjunto). Clássica: $P(A) = |A| / |\\Omega|$, só com resultados de mesma chance. $0 \\le P \\le 1$; $P(\\Omega) = 1$; $P(\\emptyset) = 0$ (axiomas de Kolmogorov). Frequência chega perto da teoria com muitas repetições (simulação, Monte Carlo).\n\n**Regras**: complemento $1 - P(A)$; adição $P(A) + P(B) - P(A \\cap B)$ (sem o desconto se forem mutuamente exclusivos); independentes $P(A) \\cdot P(B)$; condicional $P(A \\mid B) = P(A \\cap B) / P(B)$; "pelo menos um" = 1 − P(nenhum); probabilidade total = soma dos caminhos. Bayes: só citado.'),
        texto('**Variáveis**: discreta (conta) × contínua (mede). Valor esperado $E(X) = \\sum x_i P(x_i)$; variância e desvio padrão medem o espalhamento.\n\n**Binomial** (discreta): $n$ tentativas independentes, dois resultados, $p$ constante. $P(X = k) = C(n,k)\\,p^k(1-p)^{n-k}$; média $np$. Exemplo do curso: n = 10, p = 0,8.\n\n**Normal** (contínua): sino simétrico; média $\\mu$, desvio $\\sigma$; probabilidade é área; 68-95-99,7; $z = (x - \\mu)/\\sigma$. Exemplo do curso: 150 ± 20 ms. Aparece por causa do Teorema Central do Limite (soma de muitos fatores independentes).\n\n**Outras, só citadas**: Poisson, uniforme, exponencial.'),
        ex(mcq('m4-q7', 'm4.normal', 'U5 · Avaliando · Quizz 5', 'Qual alternativa melhor explica a diferença central entre a distribuição binomial e a distribuição normal nos exemplos do curso?', [
          'A distribuição binomial é discreta e modela o número de sucessos em ensaios independentes com dois resultados possíveis, enquanto a distribuição normal é contínua e descreve fenômenos que tendem a se agrupar em torno de uma média.',
          'A distribuição normal é usada apenas para modelar eventos com dois resultados possíveis, e a binomial é ideal para tempos de resposta em aplicações de TI.',
          'Ambas distribuições são contínuas, mas a distribuição binomial possui simetria perfeita, enquanto a normal pode ser assimétrica dependendo dos dados.',
          'A distribuição binomial não pressupõe independência entre os ensaios, enquanto a normal exige variáveis independentes para funcionar adequadamente.',
          'A distribuição normal é usada exclusivamente para modelar falhas de hardware, enquanto a binomial é usada para latência e tempos de resposta de servidores.',
        ], 0, 'Binomial: discreta, conta sucessos. Normal: contínua, valores em torno de uma média.')),
        { t: 'feynman', prompt: 'Sem olhar: explique a diferença entre "eventos independentes" e "eventos mutuamente exclusivos", com um exemplo de cada.' },
      ],
    },
    // ------------------------------------------------------------------ QUESTÕES
    {
      id: 'm4-questoes', titulo: 'Questões reais da U5', tipo: 'questoes', min: 10, resumo: 'As questões da plataforma e da lista do Sbrana que ainda não apareceram nas aulas, com a fonte.',
      steps: [
        texto('A lista de exercícios do curso (baseada no livro do Sbrana) pula os exercícios 6 e 8: eles não estão no arquivo. Os demais estão aqui ou nas aulas.', 'confira', 'O PDF vai do exercício 5 para o 7 e do 7 para o 9. Nada a corrigir; só o aviso de que a lista está incompleta.'),
        ex(mcq('m4-r-ex2', 'm4.classica', 'U5 · Exercício 2 (Sbrana)', 'Considere o experimento de lançar uma moeda. Qual dos eventos a seguir é um subconjunto válido do espaço amostral?', ['{cara, coroa, lado}', '{cara, coroa}', '{cara, 2}', '{0, 1}', '{par, ímpar}'], 1, 'O espaço amostral da moeda é {cara, coroa}. Um evento precisa ser subconjunto dele; o próprio espaço inteiro é um subconjunto válido (o evento certo).')),
        ex(mcq('m4-r-ex3', 'm4.classica', 'U5 · Exercício 3 (Sbrana)', 'Retira-se uma bola de uma urna com três bolas vermelhas, duas verdes e uma azul. Qual é o espaço amostral, **segundo o gabarito do curso**?', ['{vermelha, verde}', '{1, 2, 3, 4, 5, 6}', '{vermelha, verde, azul}', '{R1, R2, R3, V1, V2, A1}', '{verde, azul}'], 2, 'O gabarito considera apenas as cores. Lembre da aula: esse espaço não é equiprovável (P(vermelha) = 3/6, não 1/3). Para calcular por "favoráveis sobre possíveis", conte bola por bola.', { selo: 'confira', seloNota: 'A alternativa {R1, R2, R3, V1, V2, A1} também é um espaço amostral correto, e é o único equiprovável. O gabarito oficial é o das cores.' })),
        ex(mcq('m4-r-ex4', 'm4.classica', 'U5 · Exercício 4 (Sbrana)', 'Um dado cúbico e equilibrado é lançado uma vez. Qual é a probabilidade de sair um número maior que quatro?', ['1/6', '1/3', '1/2', '2/3', '5/6'], 1, 'Favoráveis: {5, 6}, 2 casos em 6. P = 2/6 = 1/3.')),
        ex(mcq('m4-r-ex7', 'm4.classica', 'U5 · Exercício 7 (Sbrana)', 'Uma comissão de três pessoas será escolhida aleatoriamente dentre cinco candidatos. Quantas comissões distintas podem ser formadas?', ['5', '10', '20', '30', '60'], 1, 'Comissão: a ordem não importa. C(5, 3) = (5 · 4 · 3) ÷ 3! = 10. O 60 é o arranjo.')),
        ex(mcq('m4-r-ex9', 'm4.classica', 'U5 · Exercício 9 (Sbrana)', 'De um grupo de oito pessoas, deseja-se formar uma senha de três dígitos distintos escolhidos entre essas pessoas. De quantas maneiras distintas essa senha pode ser formada?', ['56', '112', '168', '336', '512'], 3, 'Escolher 3 de 8 com ordem: 8 · 7 · 6 = 336. O 56 é a combinação C(8, 3); o 512 é 8³ (permitiria repetir).', { selo: 'erro', seloNota: 'A resolução do curso chama isso de "permutação simples P(8,3)". O número 336 está certo, mas o nome certo é ARRANJO: A(8,3). Permutação usa todos os elementos (seria 8! = 40.320). O enunciado também é estranho ("dígitos escolhidos entre pessoas"); leia como "3 de 8, com ordem".' })),
        ex(mcq('m4-r-ex10', 'm4.condicional', 'U5 · Exercício 10 (Sbrana)', 'Em uma escola, 60% dos alunos são meninas e 40% são meninos. Sabe-se que 70% das meninas praticam esportes e 50% dos meninos também. Qual é a probabilidade de um aluno escolhido ao acaso praticar esportes?', ['0,58', '0,60', '0,62', '0,64', '0,66'], 2, 'Probabilidade total: 0,70 · 0,60 + 0,50 · 0,40 = 0,42 + 0,20 = 0,62.', { porOpcao: [undefined, 'Você fez a média simples de 70% e 50%. Há mais meninas que meninos: cada taxa pesa conforme o tamanho do grupo.'] })),
        ex(mcq('m4-q8', 'm4.variaveis', 'U5 · Cálculos · Quizz 1', 'Qual afirmativa melhor descreve a principal diferença prática entre variáveis discretas e contínuas na modelagem computacional?', [
          'Variáveis discretas assumem valores contáveis e possuem função de probabilidade; variáveis contínuas assumem qualquer valor em um intervalo e têm função densidade de probabilidade que exige integração para calcular probabilidades.',
          'Variáveis discretas podem assumir qualquer valor em um intervalo e usam distribuição acumulada; variáveis contínuas assumem apenas valores inteiros e usam função de massa de probabilidade.',
          'Variáveis discretas trabalham apenas com dados qualitativos; variáveis contínuas trabalham apenas com dados qualitativos também, mas em maior escala.',
          'Variáveis discretas possuem probabilidade zero para qualquer valor; variáveis contínuas têm probabilidade definida para cada valor específico.',
          'Variáveis discretas são utilizadas apenas em contextos estocásticos; variáveis contínuas só são usadas em problemas determinísticos.',
        ], 0, 'Discreta: valores contáveis, chance de cada valor. Contínua: intervalo, densidade, probabilidade por área (integração). A quarta alternativa inverte: é na contínua que um valor exato tem probabilidade zero.')),
        ex(mcq('m4-q9', 'm4.variaveis', 'U5 · Cálculos · Quizz 2', 'Qual situação exige a análise conjunta de uma variável discreta e uma contínua?', [
          'Modelar o tempo de resposta (em segundos) de um servidor (variável contínua) em função do número de requisições simultâneas processadas (variável discreta).',
          'Estimar apenas a quantidade total de dados armazenados em um banco de dados, considerando apenas variáveis contínuas.',
          'Analisar exclusivamente a probabilidade de falha de um componente onde a variável é contínua e pode assumir qualquer valor entre 0 e 1.',
          'Modelar o número de usuários conectados simultaneamente em uma rede como variável contínua para simplificar os cálculos.',
          'Estudar apenas as variáveis discretas em um sistema, pois variáveis contínuas não se aplicam em computação.',
        ], 0, 'Tempo (medido, contínuo) em função de requisições (contadas, discreta): é a única que junta os dois tipos.', { heuristica: '"Apenas", "exclusivamente": as erradas falam de um tipo só, e a pergunta pede os dois.' })),
        ex(num('m4-r-senha', 'm4.regras', 'U5 · Exemplo em Python: probabilidade em TIC', 'No código do curso, uma senha tem 4 dígitos numéricos (0000 a 9999) e o invasor tem 3 tentativas independentes. Qual a probabilidade de acertar em pelo menos uma? (Responda em decimal, com pelo menos 5 casas, ou em fração.)', 1 - (1 - 1 / 10000) ** 3, 'P = 1 − (1 − 1/10000)³ = 1 − 0,9999³ ≈ 0,00030 (o código imprime 0.000300). Na prática é quase 3/10000.', ['"Pelo menos uma" é 1 − P(nenhuma).', 'P(errar uma) = 0,9999. P(errar as três) = 0,9999³.', '1 − 0,99970003 ≈ 0,0003.'], { tol: 0.00002, armadilhas: [{ valor: 0.0001, causa: 'leitura', msg: 'Essa é a chance de acertar em UMA tentativa. São três.' }] })),
      ],
    },
    // ------------------------------------------------------------------ CHEFÃO
    {
      id: 'm4-chefe', titulo: 'Chefão: o relatório de confiabilidade', tipo: 'chefe', min: 12, resumo: 'Os quatro exemplos em Python da U5 viram um caso só: rede, discos, senha e tempo de resposta.',
      steps: [
        texto('**A missão.** Você assumiu a operação de um sistema e o gestor pede um relatório de riscos com números. Os dados são os dos exemplos em Python da unidade.\n\n**Parte 1: a rede.** De 1000 pacotes enviados ontem, 50 se perderam.'),
        ex(num('m4-b1', 'm4.classica', 'U5 · Exemplo em Python: probabilidade em TIC', 'Qual é a probabilidade estimada de um pacote se perder? (fração, decimal ou %)', 0.05, '50/1000 = 0,05 = 5%. É a probabilidade pela frequência.', ['Favoráveis (perdidos) sobre o total (enviados).', '50 ÷ 1000.', '0,05, ou 5%.'], { tol: 0.0006 })),
        ex(num('m4-b2', 'm4.regras', undefined, 'Com essa taxa, e supondo os envios independentes, qual a probabilidade de 2 pacotes seguidos chegarem os dois?', 0.9025, 'Chegar: 1 − 0,05 = 0,95. Os dois: 0,95 × 0,95 = 0,9025.', ['Primeiro a chance de UM chegar (complemento).', '0,95. Independentes: multiplica.', '0,95 × 0,95 = 0,9025.'], { tol: 0.0006, armadilhas: [{ valor: 0.9, causa: 'conceito', msg: 'Você fez 1 − 0,05 − 0,05. Probabilidades de eventos independentes se multiplicam: 0,95 × 0,95.' }, { valor: 0.0025, causa: 'leitura', msg: 'Essa é a chance de os dois se PERDEREM. A pergunta é os dois chegarem.' }] })),
        texto('**Parte 2: a transmissão em lote.** O sistema faz **10 transmissões**, cada uma com **80%** de chance de sucesso, independentes (é exatamente o exemplo da binomial do curso: n = 10, p = 0,8).'),
        ex(num('m4-b3', 'm4.binomial', 'U5 · Exemplo em Python: distribuição binomial', 'Em média, quantas das 10 transmissões dão certo?', 8, 'Média da binomial: n · p = 10 · 0,8 = 8. O código do curso simula e imprime uma média perto disso.', ['A média da binomial tem fórmula simples.', 'E(X) = n · p.', '10 × 0,8 = 8.'])),
        ex(num('m4-b4', 'm4.binomial', undefined, 'Qual a probabilidade de as 10 darem certo? Use $0{,}8^{10} \\approx 0{,}1074$.', 0.1074, 'P(X = 10) = C(10,10) · 0,8¹⁰ · 0,2⁰ = 1 · 0,1074 · 1 ≈ 0,1074. Só 10,7%: "80% de sucesso" em cada uma NÃO quer dizer que o lote todo costuma passar.', ['É a binomial com k = n.', 'C(10, 10) = 1 e 0,2⁰ = 1.', '0,8¹⁰ ≈ 0,1074.'], { tol: 0.0006, armadilhas: [{ valor: 0.8, causa: 'conceito', msg: 'Essa é a chance de UMA dar certo. Para as dez, multiplique 0,8 dez vezes.' }] })),
        { t: 'toy', toy: 'simulador', modo: 'livre', intro: 'Confira no simulador: aperte o cenário "Rede: 10 transmissões, 80% de sucesso" e toque na barra do 10. Depois toque na do 8 e compare.' },
        texto('**Parte 3: o tempo de resposta.** As medições seguem uma normal com média **150 ms** e desvio padrão **20 ms** (exemplo da normal do curso). O contrato com o cliente diz que respostas acima de **190 ms** são falha de serviço.'),
        ex(num('m4-b5', 'm4.normal', 'U5 · Exemplo em Python: distribuição normal', '190 ms está a quantos desvios padrão da média?', 2, 'z = (190 − 150) ÷ 20 = 2.', ['Distância até a média, dividida pelo desvio.', '190 − 150 = 40.', '40 ÷ 20 = 2.'], { armadilhas: [{ valor: 40, causa: 'conceito', msg: 'Essa é a distância em ms. Divida pelo desvio padrão (20).' }] })),
        ex(num('m4-b6', 'm4.normal', undefined, 'Pela regra 68-95-99,7, que fração das respostas viola o contrato (fica acima de 190 ms)? (fração, decimal ou %)', 0.025, 'Dentro de ±2σ: 95%. Fora: 5%, metade em cada ponta. Acima de 190: 2,5%. Em 1000 requisições, umas 25.', ['190 = média + 2 desvios.', 'Fora de ±2σ sobram 5%.', 'Só a ponta de cima: 2,5%.'], { tol: 0.006, armadilhas: [{ valor: 0.05, causa: 'conceito', msg: 'Esse é o total das duas pontas. Respostas rápidas demais (abaixo de 110) não violam o contrato: só a ponta de cima conta.' }, { valor: 0.95, causa: 'leitura', msg: 'Essa é a parte que CUMPRE o contrato dentro da faixa. A pergunta é quem viola.' }] })),
        ex(mcq('m4-b7', 'm4.binomial', undefined, 'O gestor pergunta: "em 1000 requisições, quantas violam o contrato?". Que tipo de variável é esse NÚMERO de violações, e que distribuição a descreve?', ['Discreta; binomial com n = 1000 e p = 0,025 (cada requisição viola ou não)', 'Contínua; normal com média 150', 'Discreta; uniforme', 'Contínua; binomial'], 0, 'O TEMPO de cada requisição é contínuo (normal). Mas o NÚMERO de requisições que violam é uma contagem de sim ou não: binomial. Média: 1000 · 0,025 = 25.', { fixo: true })),
        {
          t: 'escrita', fonte: 'treino para a A1 dissertativa',
          prompt: 'Como numa prova dissertativa: um lote tem 5 peças, e cada peça tem 10% de chance de ser defeituosa, de forma independente. Calcule a probabilidade de NENHUMA ser defeituosa e a de PELO MENOS UMA ser. Formato "defino…, monto…, logo…". Use 0,9⁵ ≈ 0,59.',
          modelo: 'Defino X como o número de peças defeituosas no lote. Cada peça é uma tentativa com dois resultados (defeituosa ou não), as peças são independentes, n = 5 é fixo e p = 0,1 é constante: X segue uma distribuição binomial. Monto a probabilidade de nenhuma ser defeituosa: P(X = 0) = C(5,0) · 0,1⁰ · 0,9⁵ = 1 · 1 · 0,59 ≈ 0,59. Para "pelo menos uma", uso o complemento, pois é o contrário de "nenhuma": P(X ≥ 1) = 1 − P(X = 0) = 1 − 0,59 = 0,41. Logo, há cerca de 59% de chance de o lote sair perfeito e 41% de ter ao menos uma peça defeituosa. O resultado mostra que uma taxa de defeito que parece pequena (10% por peça) deixa quase metade dos lotes com problema; em média são n · p = 0,5 peça defeituosa por lote.',
          rubrica: ['Defini a variável aleatória com palavras', 'Justifiquei por que é binomial (dois resultados, independência, n fixo, p constante)', 'Mostrei a conta de P(X = 0) com a fórmula', 'Usei o complemento para "pelo menos uma" e disse por quê', 'Dei as duas respostas em frase completa', 'Interpretei o resultado (o que ele diz sobre o lote)'],
        },
        { t: 'feynman', prompt: 'Explique para alguém da igreja, sem fórmula: por que a chance de dar certo dez vezes seguidas é bem menor do que a chance de dar certo uma vez?' },
      ],
    },
  ],
  cards: cards('mat', 'm4', [
    ['Espaço amostral e evento', 'Espaço amostral (Ω): conjunto de todos os resultados possíveis. Evento: um subconjunto dele.'],
    ['Probabilidade clássica', 'P(A) = casos favoráveis ÷ casos possíveis. Só vale quando todos os resultados têm a mesma chance.'],
    ['Entre que valores fica uma probabilidade?', 'De 0 (impossível) a 1 (certo). P(Ω) = 1, P(∅) = 0.'],
    ['Regra do complemento', 'P(não A) = 1 − P(A). "Pelo menos um" = 1 − P(nenhum).'],
    ['Regra da adição', 'P(A ∪ B) = P(A) + P(B) − P(A ∩ B). Sem o desconto se forem mutuamente exclusivos.'],
    ['Eventos independentes', 'Um não muda a chance do outro. P(A ∩ B) = P(A) · P(B). Não confundir com mutuamente exclusivos.'],
    ['Probabilidade condicional', 'P(A|B) = P(A ∩ B) ÷ P(B): olhe só para dentro de B.'],
    ['Variável discreta × contínua', 'Discreta conta (pacotes perdidos, usuários). Contínua mede (latência, temperatura, uso de CPU).'],
    ['Valor esperado', 'E(X) = soma de cada valor vezes a sua probabilidade. É a média de longo prazo.'],
    ['Fórmula da binomial', 'P(X = k) = C(n,k) · pᵏ · (1−p)ⁿ⁻ᵏ. Média: n·p.'],
    ['Quando usar a binomial?', 'Dois resultados por tentativa, tentativas independentes, n fixo, p constante.'],
    ['Regra 68-95-99,7', 'Na normal: ±1σ pega 68%, ±2σ pega 95%, ±3σ pega 99,7%.'],
    ['Escore z', 'z = (x − μ) ÷ σ: a quantos desvios padrão o valor está da média.'],
    ['Por que a latência de rede é quase normal?', 'É a soma de muitos fatores independentes: Teorema Central do Limite.'],
    ['Binomial ou normal?', 'Contando sucessos em tentativas de sim/não: binomial (discreta). Medindo algo em torno de uma média: normal (contínua).'],
    ['Probabilidade de um valor exato numa variável contínua', 'Zero. Só intervalos têm probabilidade (a área debaixo da curva).'],
  ]),
};
