// Erros e problemas encontrados no material do curso.
// Cada item marcado "conferido" tem um teste em src/tests/erros-material.test.ts que refaz a conta.
import type { Selo } from '../engine/types';

export type ErroMaterial = { id: string; mundo: 'mat' | 'exp'; onde: string; selo: Selo; oQue: string; certo: string; conferido: string };

export const ERROS_MATERIAL: ErroMaterial[] = [
  { id: 'e1', mundo: 'mat', onde: 'U1 · questão do diagrama de Venn', selo: 'erro', oQue: 'Pede os clientes que compraram apenas eletrônicos, mas nenhuma das cinco alternativas representa essa região.', certo: 'A − (B ∪ C), o mesmo que A ∩ B\' ∩ C\'.', conferido: 'As 8 regiões de cada alternativa foram comparadas por código: nenhuma coincide.' },
  { id: 'e2', mundo: 'mat', onde: 'U2 · card "Operadores lógicos"', selo: 'erro', oQue: 'Diz que a condicional "apresenta o valor falso quando o segundo valor lógico for falso".', certo: 'p → q só é falsa quando p é V e q é F. F → F é verdadeiro. A tabela da mesma unidade está certa.', conferido: 'Tabela-verdade calculada por código.' },
  { id: 'e3', mundo: 'mat', onde: 'U3 · tabela do XOR', selo: 'confira', oQue: 'No texto extraído, a tabela com saída 0, 1, 1, 0 aparece com a legenda "Disjunção OR".', certo: 'Essa tabela é do XOR. O OR daria 0, 1, 1, 1. Pode ser só uma legenda deslocada na extração do PDF.', conferido: 'As duas tabelas foram calculadas por código; a dúvida é só sobre a legenda na plataforma.' },
  { id: 'e4', mundo: 'mat', onde: 'U3 · Avaliando · Questão 1 (alternativa E)', selo: 'erro', oQue: 'Afirma que AB + A\'C "pode ser simplificada para (A + B)(A\' + C) pela lei distributiva".', certo: 'Não são equivalentes: diferem em 4 das 8 linhas (por exemplo A = 1, B = 1, C = 0). A correta é a do multiplexador.', conferido: 'Comparação linha a linha por código.' },
  { id: 'e5', mundo: 'mat', onde: 'U4 · anagramas de BALANÇA', selo: 'erro', oQue: 'Três alternativas (A, D e E) dão o mesmo valor, 840, e uma quarta usa a mesma fórmula com resultado 720.', certo: '7!/3! = 840. Se cair, marque a que mostra a fórmula 7!/3! com 840.', conferido: '7!/3! calculado por código.' },
  { id: 'e6', mundo: 'mat', onde: 'U4 · anagramas de ARARAS', selo: 'erro', oQue: 'A alternativa correta fala em "A (3 vezes) e N (2 vezes)". Não existe N em ARARAS.', certo: 'As letras são A (3), R (2) e S (1). O valor 60 está certo: 6!/(3!·2!).', conferido: 'Contagem das letras e do valor por código.' },
  { id: 'e7', mundo: 'mat', onde: 'U8 · quadro-síntese e U5 · exercício 9 (Sbrana)', selo: 'erro', oQue: 'O quadro define "Permutações: arranjos onde a ordem importa". O exercício 9 chama de "permutação simples P(8,3)" a escolha ordenada de 3 entre 8.', certo: 'Escolher e ordenar 3 de 8 é arranjo: A(8,3) = 8·7·6 = 336. Permutação usa todos os elementos. O número 336 está certo; o nome é que está trocado.', conferido: 'Lido nos PDFs (imagem). A(8,3) = 336 calculado por código.' },
  { id: 'e8', mundo: 'mat', onde: 'U5 · exercício 3 (Sbrana), urna de cores', selo: 'confira', oQue: 'Dá {vermelha, verde, azul} como o espaço amostral de uma urna com 3 vermelhas, 2 verdes e 1 azul.', certo: 'É um espaço amostral válido, mas não é equiprovável: P(vermelha) = 3/6, não 1/3. A alternativa D (R1, R2, R3, V1, V2, A1) também é defensável e é a que permite usar "favoráveis/possíveis".', conferido: 'Lido no PDF. Classificado como ambíguo, não como erro.' },
  { id: 'e9', mundo: 'mat', onde: 'U6 · gabarito do problema de Telecom', selo: 'erro', oQue: 'Acha y ≈ 6,36, arredonda para 6, tira x = 5 da equação das horas e afirma que o plano "nem estourará o orçamento de R$ 25 mil".', certo: 'x = 5 e y = 6 custam 3·5 + 2·6 = 27 mil. A solução exata é x = 45/11 ≈ 4,09 e y = 70/11 ≈ 6,36; não existe solução inteira que use exatamente os recursos. O par (4, 6) cabe nos limites (38 h, 24 mil).', conferido: 'Lido no PDF. Sistema resolvido com frações exatas por código.' },
  { id: 'e10', mundo: 'mat', onde: 'U6 · padrão de resposta dos 4 servidores', selo: 'erro', oQue: 'Dá x ≈ (4,74; 4,21; 3,42; 2,50) como solução de norma mínima.', certo: 'Esses valores dão CPU 19,61, memória 25,79 e energia 23,29, e não 20, 25 e 30. A solução de norma mínima é ≈ (4,344; 2,104; 4,071; 5,137). O texto também diz que a pseudo-inversa "minimiza a norma dos resíduos"; aqui, com infinitas soluções, ela escolhe a solução de menor norma.', conferido: 'Lido no PDF. A·x calculado por código para os dois vetores.' },
  { id: 'e11', mundo: 'mat', onde: 'U6 · estudo de caso da metalmecânica', selo: 'alem', oQue: 'A solução única é x1 = −30, x2 = −180, x3 = 940: produção negativa.', certo: 'Não é erro do material: o próprio gabarito conclui que a solução é inviável. É a lição "modelo × realidade": um sistema pode ser SPD e a resposta não servir.', conferido: 'Determinante (−1) e solução calculados por código.' },
  { id: 'e12', mundo: 'mat', onde: 'U8 · respostas da atividade avaliativa (Aegis-Grid)', selo: 'erro', oQue: 'O texto diz que "o sistema falha em quatro cenários".', certo: 'A tabela do próprio gabarito mostra cinco linhas com S = 1: as quatro com P = 1 e a linha P = 0, Q = 1, R = 1.', conferido: 'Tabela de P + QR calculada por código: 5 de 8.' },
  { id: 'e13', mundo: 'mat', onde: 'U8 · introdução', selo: 'erro', oQue: 'Fala em "formas, medidas, ângulos e relações trigonométricas" e pede para aplicar "conceitos geométricos e trigonométricos".', certo: 'Geometria e trigonometria não fazem parte da disciplina; o trecho veio de outra matéria. Ignore.', conferido: 'Leitura do texto.' },
  { id: 'e14', mundo: 'mat', onde: 'U7 · exemplo de DFS', selo: 'alem', oQue: 'Mostra a ordem A, B, D, E, C como "a" ordem do DFS.', certo: 'A ordem depende de como os vizinhos estão listados. Com vizinhos em ordem alfabética sai A, B, D, C, E. As duas são DFS válidos.', conferido: 'As duas ordens foram geradas por código.' },
  { id: 'e15', mundo: 'mat', onde: 'U4 · Avaliando · Questão 01 (senhas)', selo: 'confira', oQue: 'No texto extraído, as alternativas aparecem cortadas, começando por "000".', certo: '26 × 10 × 4 × 26 × 16 = 432.640 senhas, pelo princípio multiplicativo.', conferido: 'Produto calculado por código. Veja o enunciado completo na plataforma.' },
  { id: 'e16', mundo: 'mat', onde: 'U4 · exemplos de fatorial', selo: 'confira', oQue: 'Aparece "2! = 2 · 1 = 23".', certo: '2! = 2. Provavelmente um número de nota de rodapé colado na extração.', conferido: 'Fatorial calculado por código.' },
  { id: 'e21', mundo: 'mat', onde: 'U4 · anagramas de COMPUTADOR', selo: 'erro', oQue: 'O enunciado diz que COMPUTADOR é "formada por 10 letras distintas" e espera 10! = 3.628.800.', certo: 'A letra O aparece duas vezes (C-O-M-P-U-T-A-D-O-R). O número real de anagramas é 10!/2! = 1.814.400, que é a alternativa B. Na prova, se o enunciado afirmar "letras distintas", siga o enunciado (10!), mas saiba que a premissa está errada.', conferido: 'Contagem das letras e do valor por código.' },
  { id: 'e17', mundo: 'mat', onde: 'U8 · quiz diagnóstico (matrizes)', selo: 'confira', oQue: 'Alternativas corrompidas: "B=B.A" e "Independentemente de A e A".', certo: 'A que faz sentido: o produto de duas matrizes n×n tem ordem n×n. As outras falham: o produto não é comutativo, não existe "cancelar" matriz, e nem toda matriz é inversível.', conferido: 'Leitura do texto.' },
  { id: 'e18', mundo: 'mat', onde: 'U5 · exercícios Sbrana', selo: 'confira', oQue: 'O PDF pula do exercício 5 para o 7 e do 7 para o 9: os exercícios 6 e 8 não estão no arquivo.', certo: 'Nada a corrigir; só fica o aviso de que a lista está incompleta.', conferido: 'Leitura do PDF.' },
  { id: 'e19', mundo: 'exp', onde: 'U2 · referências bibliográficas', selo: 'erro', oQue: 'Atribui "Transformação Digital: repensando o seu negócio para a era digital" a Martha Gabriel (Alta Books, 2018).', certo: 'Esse livro é de David L. Rogers (Autêntica, 2017), como aparece nas outras unidades. O de Gabriel é "Você, eu e os robôs" (2021).', conferido: 'Comparação entre as listas de referências das 8 unidades.' },
  { id: 'e20', mundo: 'exp', onde: 'U2 · duas questões com alternativas corrompidas', selo: 'confira', oQue: 'Há alternativas com dois textos colados um por cima do outro ("Digitaliza doUtiliza tecnologias…").', certo: 'Ignore o trecho quebrado e procure a alternativa limpa: digitalização é etapa inicial; transformação digital muda modelo de negócio, processos, cultura e criação de valor.', conferido: 'Leitura do texto.' },
];
